/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2015 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int FIRInstanceIDParseCurrentLibraryVersion();
// int __usercall __FIRInstanceIDParseCurrentLibraryVersion_block_invoke@<eax>(__int64 a1@<rax>);
int FIRInstanceIDCurrentLibraryVersion();
__int64 FIRInstanceIDCurrentLibraryVersionMajor();
__int64 FIRInstanceIDCurrentLibraryVersionMinor();
__int64 FIRInstanceIDCurrentLibraryVersionPatch();
bool FIRInstanceIDCurrentLibraryVersionIsBeta();
// int __fastcall dispatch_once(_QWORD, _QWORD); weak
// void *objc_msgSend(void *, const char *, ...); idb
// int __fastcall objc_retainAutoreleaseReturnValue(_QWORD); weak
// int __fastcall objc_retainAutoreleasedReturnValue(_QWORD); weak

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN loc_1; // weak
char a_[2] = "."; // weak
__CFString cfstr__ = { &__CFConstantStringClassReference, 1992LL, ".", 1LL }; // weak
__int64 (__fastcall *paStringwithutf8)() = &aStringwithutf8; // weak
void *__block_literal_global = &_NSConcreteGlobalBlock; // weak
__int64 FIRInstanceIDParseCurrentLibraryVersion_allVersions; // weak
__int64 FIRInstanceIDParseCurrentLibraryVersion_onceToken; // weak
int majorVersion; // weak
int minorVersion; // weak
int patchVersion; // weak
int betaVersion; // weak
__int64 libraryVersion; // weak
// extern _UNKNOWN OBJC_CLASS___NSMutableString; weak
// extern int (__fastcall *objc_release)(_QWORD); weak


//----- (0000000000000000) ----------------------------------------------------
int FIRInstanceIDParseCurrentLibraryVersion()
{
  int result; // eax@2

  if ( FIRInstanceIDParseCurrentLibraryVersion_onceToken != -1 )
    result = dispatch_once(&FIRInstanceIDParseCurrentLibraryVersion_onceToken, &__block_literal_global);
  return result;
}
// 480: using guessed type void *__block_literal_global;
// 2600: using guessed type __int64 FIRInstanceIDParseCurrentLibraryVersion_onceToken;
// 2638: using guessed type int __fastcall dispatch_once(_QWORD, _QWORD);

//----- (0000000000000024) ----------------------------------------------------
int __usercall __FIRInstanceIDParseCurrentLibraryVersion_block_invoke@<eax>(__int64 a1@<rax>)
{
  void *v1; // rax@1
  void *v2; // rax@1
  void *v3; // rbx@1
  void *v4; // rax@1
  __int64 v5; // rax@1
  __int64 v6; // rdi@1
  const char *v7; // r14@2
  void *v8; // rax@2
  void *v9; // rax@2
  void *v10; // rbx@2
  const char *v11; // r13@2
  void *v12; // rax@2
  void *v13; // rax@2
  void *v14; // rbx@2
  void *v15; // rax@2
  void *v16; // rax@2
  void *v17; // r15@2
  void *v18; // rax@2
  void *v19; // rax@2
  void *v20; // r13@2
  const char *v21; // rbx@2
  void *v22; // rax@3
  void *v23; // rax@3
  void *v24; // rbx@3
  const char *v25; // r15@3
  void *v26; // rax@3
  void *v27; // rax@3
  void *v28; // rbx@3
  const char *v29; // r15@4
  void *v30; // rax@5
  void *v31; // rax@5
  void *v32; // rbx@5
  void *v33; // rax@7
  __int64 v34; // rdi@7
  void *v36; // [sp+0h] [bp-30h]@2

  v1 = objc_msgSend(&OBJC_CLASS___NSMutableString, (const char *)paStringwithutf8, &a_[8], a1);
  LODWORD(v2) = objc_retainAutoreleasedReturnValue(v1);
  v3 = v2;
  v4 = objc_msgSend(v2, (const char *)*(&paStringwithutf8 + 1), &cfstr__);
  LODWORD(v5) = objc_retainAutoreleasedReturnValue(v4);
  v6 = FIRInstanceIDParseCurrentLibraryVersion_allVersions;
  FIRInstanceIDParseCurrentLibraryVersion_allVersions = v5;
  objc_release(v6);
  if ( objc_msgSend((void *)FIRInstanceIDParseCurrentLibraryVersion_allVersions, (const char *)*(&paStringwithutf8 + 2)) == (char *)&loc_1 + 2 )
  {
    v7 = (const char *)*(&paStringwithutf8 + 3);
    v8 = objc_msgSend(
           (void *)FIRInstanceIDParseCurrentLibraryVersion_allVersions,
           (const char *)*(&paStringwithutf8 + 3),
           0LL,
           v3);
    LODWORD(v9) = objc_retainAutoreleasedReturnValue(v8);
    v10 = v9;
    v11 = (const char *)*(&paStringwithutf8 + 4);
    majorVersion = (unsigned __int64)objc_msgSend(v9, (const char *)*(&paStringwithutf8 + 4));
    objc_release(v10);
    v12 = objc_msgSend((void *)FIRInstanceIDParseCurrentLibraryVersion_allVersions, v7, 1LL);
    LODWORD(v13) = objc_retainAutoreleasedReturnValue(v12);
    v14 = v13;
    minorVersion = (unsigned __int64)objc_msgSend(v13, v11);
    objc_release(v14);
    v15 = objc_msgSend((void *)FIRInstanceIDParseCurrentLibraryVersion_allVersions, v7, 2LL);
    LODWORD(v16) = objc_retainAutoreleasedReturnValue(v15);
    v17 = v16;
    v18 = objc_msgSend(v16, (const char *)*(&paStringwithutf8 + 1), &cfstr__ + 1);
    LODWORD(v19) = objc_retainAutoreleasedReturnValue(v18);
    v20 = v19;
    v21 = (const char *)*(&paStringwithutf8 + 2);
    objc_release(v17);
    if ( objc_msgSend(v20, v21) == (char *)&loc_1 + 1 )
    {
      v22 = objc_msgSend(v20, (const char *)*(&paStringwithutf8 + 3), 0LL);
      LODWORD(v23) = objc_retainAutoreleasedReturnValue(v22);
      v24 = v23;
      v25 = (const char *)*(&paStringwithutf8 + 4);
      patchVersion = (unsigned __int64)objc_msgSend(v23, (const char *)*(&paStringwithutf8 + 4));
      objc_release(v24);
      v26 = objc_msgSend(v20, (const char *)*(&paStringwithutf8 + 3), 1LL);
      LODWORD(v27) = objc_retainAutoreleasedReturnValue(v26);
      v28 = v27;
      betaVersion = (unsigned __int64)objc_msgSend(v27, v25);
      objc_release(v28);
    }
    else
    {
      v29 = (const char *)*(&paStringwithutf8 + 4);
      if ( objc_msgSend(v20, v21) == &loc_1 )
      {
        v30 = objc_msgSend(v20, (const char *)*(&paStringwithutf8 + 3), 0LL);
        LODWORD(v31) = objc_retainAutoreleasedReturnValue(v30);
        v32 = v31;
        patchVersion = (unsigned __int64)objc_msgSend(v31, v29);
        objc_release(v32);
      }
    }
    objc_release(v20);
    v3 = v36;
  }
  v33 = objc_msgSend(v3, (const char *)*(&paStringwithutf8 + 5));
  v34 = libraryVersion;
  libraryVersion = (__int64)v33;
  objc_release(v34);
  return objc_release(v3);
}
// 380: using guessed type __CFString cfstr__;
// 430: using guessed type __int64 (__fastcall *paStringwithutf8)();
// 25F8: using guessed type __int64 FIRInstanceIDParseCurrentLibraryVersion_allVersions;
// 2608: using guessed type int majorVersion;
// 260C: using guessed type int minorVersion;
// 2610: using guessed type int patchVersion;
// 2614: using guessed type int betaVersion;
// 2618: using guessed type __int64 libraryVersion;
// 2648: using guessed type int (__fastcall *objc_release)(_QWORD);
// 2658: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000289) ----------------------------------------------------
int FIRInstanceIDCurrentLibraryVersion()
{
  if ( FIRInstanceIDParseCurrentLibraryVersion_onceToken != -1 )
    dispatch_once(&FIRInstanceIDParseCurrentLibraryVersion_onceToken, &__block_literal_global);
  return objc_retainAutoreleaseReturnValue(libraryVersion);
}
// 480: using guessed type void *__block_literal_global;
// 2600: using guessed type __int64 FIRInstanceIDParseCurrentLibraryVersion_onceToken;
// 2618: using guessed type __int64 libraryVersion;
// 2638: using guessed type int __fastcall dispatch_once(_QWORD, _QWORD);
// 2650: using guessed type int __fastcall objc_retainAutoreleaseReturnValue(_QWORD);

//----- (00000000000002B9) ----------------------------------------------------
__int64 FIRInstanceIDCurrentLibraryVersionMajor()
{
  if ( FIRInstanceIDParseCurrentLibraryVersion_onceToken != -1 )
    dispatch_once(&FIRInstanceIDParseCurrentLibraryVersion_onceToken, &__block_literal_global);
  return (unsigned int)majorVersion;
}
// 480: using guessed type void *__block_literal_global;
// 2600: using guessed type __int64 FIRInstanceIDParseCurrentLibraryVersion_onceToken;
// 2608: using guessed type int majorVersion;
// 2638: using guessed type int __fastcall dispatch_once(_QWORD, _QWORD);

//----- (00000000000002E4) ----------------------------------------------------
__int64 FIRInstanceIDCurrentLibraryVersionMinor()
{
  if ( FIRInstanceIDParseCurrentLibraryVersion_onceToken != -1 )
    dispatch_once(&FIRInstanceIDParseCurrentLibraryVersion_onceToken, &__block_literal_global);
  return (unsigned int)minorVersion;
}
// 480: using guessed type void *__block_literal_global;
// 2600: using guessed type __int64 FIRInstanceIDParseCurrentLibraryVersion_onceToken;
// 260C: using guessed type int minorVersion;
// 2638: using guessed type int __fastcall dispatch_once(_QWORD, _QWORD);

//----- (000000000000030F) ----------------------------------------------------
__int64 FIRInstanceIDCurrentLibraryVersionPatch()
{
  if ( FIRInstanceIDParseCurrentLibraryVersion_onceToken != -1 )
    dispatch_once(&FIRInstanceIDParseCurrentLibraryVersion_onceToken, &__block_literal_global);
  return (unsigned int)patchVersion;
}
// 480: using guessed type void *__block_literal_global;
// 2600: using guessed type __int64 FIRInstanceIDParseCurrentLibraryVersion_onceToken;
// 2610: using guessed type int patchVersion;
// 2638: using guessed type int __fastcall dispatch_once(_QWORD, _QWORD);

//----- (000000000000033A) ----------------------------------------------------
bool FIRInstanceIDCurrentLibraryVersionIsBeta()
{
  if ( FIRInstanceIDParseCurrentLibraryVersion_onceToken != -1 )
    dispatch_once(&FIRInstanceIDParseCurrentLibraryVersion_onceToken, &__block_literal_global);
  return betaVersion > 0;
}
// 480: using guessed type void *__block_literal_global;
// 2600: using guessed type __int64 FIRInstanceIDParseCurrentLibraryVersion_onceToken;
// 2614: using guessed type int betaVersion;
// 2638: using guessed type int __fastcall dispatch_once(_QWORD, _QWORD);

// ALL OK, 7 function(s) have been successfully decompiled
