/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2015 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void *__fastcall -[FIRInstanceIDTokenFetchOperation initWithAuthorizedEntity:scope:options:checkinPreferences:keyPair:](void *a1, __int64 a2, __int64 a3, __int64 a4, __int64 a5, __int64 a6, __int64 a7);
void __cdecl -[FIRInstanceIDTokenFetchOperation performTokenOperation](struct FIRInstanceIDTokenFetchOperation *self, SEL);
// int __usercall __57__FIRInstanceIDTokenFetchOperation_performTokenOperation__block_invoke@<eax>(__int64 a1@<rax>, __int64 a2@<rdx>, __int64 a3@<rcx>, __int64 a4@<rdi>, __int64 a5@<rsi>);
int __fastcall __copy_helper_block_(__int64 a1, __int64 a2);
int __fastcall __destroy_helper_block_(__int64 a1);
void __cdecl -[FIRInstanceIDTokenFetchOperation handleResponseWithData:response:error:](struct FIRInstanceIDTokenFetchOperation *self, SEL, id, id, id);
// int __usercall __74__FIRInstanceIDTokenFetchOperation_handleResponseWithData_response_error___block_invoke@<eax>(__int64 a1@<rax>, __int64 a2@<rdi>);
int __fastcall __copy_helper_block__107(__int64 a1, __int64 a2);
int __fastcall __destroy_helper_block__108(__int64 a1);
id __cdecl -[FIRInstanceIDTokenFetchOperation parseFetchTokenResponse:](struct FIRInstanceIDTokenFetchOperation *self, SEL, id);
void __cdecl -[FIRInstanceIDTokenFetchOperation parseToken:withRequestID:](struct FIRInstanceIDTokenFetchOperation *self, SEL, id, uint64_t);
// int __fastcall FIRInstanceIDAPNSTupleStringForTokenAndServerType(_QWORD, _QWORD); weak
// int __fastcall FIRInstanceIDQueryFromQueryItems(_QWORD); weak
// int __fastcall FIRInstanceIDRegisterServer(_QWORD); weak
// int __fastcall FIRInstanceIDSharedLogger(_QWORD); weak
// int __fastcall dispatch_after(_QWORD, _QWORD, _QWORD); weak
// dispatch_time_t __cdecl dispatch_time(dispatch_time_t when, int64_t delta);
// int __fastcall objc_autoreleaseReturnValue(_QWORD); weak
// int __fastcall objc_copyWeak(_QWORD, _QWORD); weak
// int __fastcall objc_destroyWeak(_QWORD); weak
// int __fastcall objc_enumerationMutation(_QWORD); weak
// int __fastcall objc_initWeak(_QWORD, _QWORD); weak
// int __fastcall objc_loadWeakRetained(_QWORD); weak
// void *objc_msgSend(void *, const char *, ...); idb
// void *objc_msgSendSuper2(void *, const char *, ...); idb
// int __fastcall objc_release(_QWORD); weak
// int __fastcall objc_retain(_QWORD); weak
// int __fastcall objc_retainAutoreleasedReturnValue(_QWORD); weak
// int __fastcall objc_retainBlock(_QWORD, _QWORD); weak

//-------------------------------------------------------------------------
// Data declarations

void *classRef_FIRInstanceIDTokenFetchOperation = &OBJC_CLASS___FIRInstanceIDTokenFetchOperation; // weak
char *selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ = "initWithAction:forAuthorizedEntity:scope:options:checkinPreferences:keyPair:"; // weak
void *classRef_FIRInstanceIDTokenOperation = &OBJC_CLASS___FIRInstanceIDTokenOperation; // weak
char aInfo[5] = "info"; // weak
__CFString cfstr_Info = { &__CFConstantStringClassReference, 1992LL, "info", 4LL }; // weak
_UNKNOWN __block_descriptor_tmp; // weak
_UNKNOWN __block_descriptor_tmp_110; // weak
int phoneRegistrationErrorRetryCount; // weak
// extern _UNKNOWN KFIRInstanceIDTokenMismatchNotification; weak
// extern void *_NSConcreteStackBlock[32];
// extern _UNKNOWN __stack_chk_guard; weak
// extern _UNKNOWN _dispatch_main_q; weak
// extern _UNKNOWN kFIRInstanceIDIdentityInvalidatedNotification; weak
// extern _UNKNOWN kFIRInstanceIDTokenOptionsAPNSIsSandboxKey; weak
// extern _UNKNOWN kFIRInstanceIDTokenOptionsAPNSKey; weak
// extern _UNKNOWN kFIRInstanceIDTokenOptionsFirebaseAppIDKey; weak
// extern _UNKNOWN kFIRInstanceID_CMD_RST; weak
// extern _UNKNOWN kFIRInstanceID_CMD_SYNC; weak


//----- (0000000000000000) ----------------------------------------------------
void *__fastcall -[FIRInstanceIDTokenFetchOperation initWithAuthorizedEntity:scope:options:checkinPreferences:keyPair:](void *a1, __int64 a2, __int64 a3, __int64 a4, __int64 a5, __int64 a6, __int64 a7)
{
  __int64 v7; // r12@1
  __int64 v8; // r13@1
  __int64 v9; // rbx@1
  __int64 v10; // rax@1
  __int64 v11; // rax@1
  __int64 v12; // r15@1
  __int64 v13; // rax@1
  __int64 v14; // r13@1
  __int64 v15; // rax@1
  __int64 v16; // rbx@1
  __int64 v17; // r12@1
  void *v19; // [sp+8h] [bp-48h]@1
  void *v20; // [sp+10h] [bp-40h]@1
  __int64 v21; // [sp+18h] [bp-38h]@1
  void *v22; // [sp+20h] [bp-30h]@1

  v7 = a6;
  v8 = a5;
  v9 = a4;
  v22 = a1;
  LODWORD(v10) = objc_retain(a3);
  v21 = v10;
  LODWORD(v11) = objc_retain(v9);
  v12 = v11;
  LODWORD(v13) = objc_retain(v8);
  v14 = v13;
  LODWORD(v15) = objc_retain(v7);
  v16 = v15;
  v19 = a1;
  v20 = classRef_FIRInstanceIDTokenFetchOperation;
  v17 = v21;
  v22 = objc_msgSendSuper2(
          &v19,
          selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_,
          0LL,
          v21,
          v12,
          v14,
          v15,
          a7);
  objc_release(v16);
  objc_release(v14);
  objc_release(v12);
  objc_release(v17);
  return v22;
}
// 1418: using guessed type void *classRef_FIRInstanceIDTokenFetchOperation;
// 1908: using guessed type char *selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_;
// 85F8: using guessed type int __fastcall objc_release(_QWORD);
// 8600: using guessed type int __fastcall objc_retain(_QWORD);

//----- (00000000000000BC) ----------------------------------------------------
// FIRInstanceIDTokenFetchOperation - (void)performTokenOperation
void __cdecl -[FIRInstanceIDTokenFetchOperation performTokenOperation](struct FIRInstanceIDTokenFetchOperation *self, SEL a2)
{
  void *v2; // rax@1
  void *v3; // rax@1
  void *v4; // rax@1
  __int64 v5; // rax@1
  __int64 v6; // rbx@1
  void *v7; // rax@1
  __int64 v8; // rax@1
  __int64 v9; // r15@1
  void *v10; // rax@1
  const char *v11; // rsi@1
  void *v12; // rax@1
  void *v13; // rax@1
  void *v14; // r15@1
  void *v15; // rax@1
  void *v16; // rax@1
  void *v17; // r13@1
  void *v18; // rax@1
  __int64 v19; // rax@1
  __int64 v20; // rbx@1
  const char *v21; // rsi@1
  void *v22; // rax@1
  void *v23; // rax@1
  void *v24; // rbx@1
  void *v25; // rax@1
  __int64 v26; // rax@1
  __int64 v27; // r15@1
  void *v28; // r14@1
  __int64 v29; // rax@1
  __int64 v30; // rax@1
  __int64 v31; // rbx@1
  __int64 v32; // rax@1
  __int64 v33; // rsi@1
  __int64 v34; // rax@1
  void *v35; // rax@1
  void *v36; // r14@1
  __int64 v37; // r15@1
  __int64 v38; // rax@1
  __int64 v39; // rax@1
  __int64 v40; // r13@1
  __int64 v41; // rax@1
  __int64 v42; // rax@1
  __int64 v43; // rbx@1
  __int64 v44; // r15@1
  __int64 v45; // rax@1
  __int64 v46; // rax@1
  __int64 v47; // r14@1
  __int64 v48; // rax@1
  __int64 v49; // rax@1
  __int64 v50; // rbx@1
  __int64 v51; // rax@1
  __int64 v52; // rax@1
  __int64 v53; // r14@1
  __int64 v54; // rax@1
  __int64 v55; // rax@1
  __int64 v56; // rbx@1
  __int64 v57; // rax@1
  __int64 v58; // rax@1
  __int64 v59; // rbx@1
  __int64 v60; // r15@1
  __int64 v61; // rsi@1
  __int64 v62; // rax@1
  __int64 v63; // rax@1
  __int64 v64; // r13@1
  __int64 v65; // rax@1
  __int64 v66; // rax@1
  __int64 v67; // rbx@1
  __int64 v68; // rax@1
  void *v69; // rax@1
  void *v70; // r15@1
  const char *v71; // r12@1
  __int64 v72; // rax@1
  const char *v73; // rcx@1
  __int64 v74; // rdi@1
  const char *v75; // r13@1
  __int64 v76; // rbx@1
  void *v77; // rax@2
  unsigned __int8 v78; // al@3
  __int64 v79; // rax@3
  __int64 v80; // rax@3
  __int64 v81; // r15@3
  void *v82; // rax@3
  __int64 v83; // rax@3
  __int64 v84; // r14@3
  void *v85; // rax@4
  void *v86; // rax@4
  void *v87; // rbx@4
  __int64 v88; // r14@4
  void *v89; // rax@4
  void *v90; // rax@4
  void *v91; // r13@4
  void *v92; // rax@4
  void *v93; // rax@5
  __int64 v94; // rax@5
  __int64 v95; // rbx@5
  __int64 v96; // rax@6
  void *v97; // rax@6
  __int64 v98; // r13@6
  void *v99; // rax@6
  __int64 v100; // rax@6
  __int64 v101; // rbx@6
  __int64 v102; // rax@6
  __int64 v103; // rdi@6
  void *v104; // rax@6
  void *v105; // r15@6
  __int64 v106; // rax@6
  __int64 v107; // rax@6
  __int64 v108; // rbx@6
  const char *v109; // rsi@6
  struct FIRInstanceIDTokenFetchOperation *v110; // rbx@6
  __int64 v111; // rax@6
  __int64 v112; // r15@6
  const char *v113; // r12@6
  void *v114; // rax@6
  __int64 v115; // rax@6
  __int64 v116; // r14@6
  void *v117; // rax@7
  __int64 v118; // rax@7
  __int64 v119; // rbx@7
  __int64 v120; // r14@7
  void (__fastcall *v121)(__int64); // rbx@7
  void *v122; // rax@8
  struct FIRInstanceIDTokenFetchOperation *v123; // r14@8
  void *v124; // rax@8
  void *v125; // r12@8
  void *v126; // rax@8
  __int64 v127; // rax@8
  __int64 v128; // rbx@8
  void *v129; // rax@8
  void *v130; // rax@8
  void *v131; // rbx@8
  void *v132; // rdi@8
  __int64 v133; // r12@9
  void *v134; // [sp+8h] [bp-A8h]@6
  signed int v135; // [sp+10h] [bp-A0h]@6
  int v136; // [sp+14h] [bp-9Ch]@6
  int (__usercall *v137)@<eax>(__int64@<rax>, __int64@<rdx>, __int64@<rcx>, __int64@<rdi>, __int64@<rsi>); // [sp+18h] [bp-98h]@6
  void *v138; // [sp+20h] [bp-90h]@6
  char v139; // [sp+28h] [bp-88h]@6
  __int64 v140; // [sp+30h] [bp-80h]@1
  __int64 v141; // [sp+38h] [bp-78h]@4
  __int64 v142; // [sp+40h] [bp-70h]@6
  char v143; // [sp+48h] [bp-68h]@6
  __int64 v144; // [sp+50h] [bp-60h]@1
  __int64 v145; // [sp+58h] [bp-58h]@1
  __int64 v146; // [sp+60h] [bp-50h]@1
  struct FIRInstanceIDTokenFetchOperation *v147; // [sp+68h] [bp-48h]@1
  void *v148; // [sp+70h] [bp-40h]@1
  void *v149; // [sp+78h] [bp-38h]@1
  void *v150; // [sp+80h] [bp-30h]@1

  v2 = objc_msgSend(self, *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 1));
  v3 = objc_msgSend(v2, *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 2));
  objc_msgSend(self, *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 3), v3);
  v4 = objc_msgSend(self, *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 4));
  LODWORD(v5) = objc_retainAutoreleasedReturnValue(v4);
  v6 = v5;
  v7 = objc_msgSend(
         classRef_FIRInstanceIDTokenOperation,
         *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 5),
         v5);
  LODWORD(v8) = objc_retainAutoreleasedReturnValue(v7);
  v9 = v8;
  objc_release(v6);
  v10 = objc_msgSend(self, *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 1));
  v11 = *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 6);
  v145 = v9;
  v12 = objc_msgSend(v10, v11, v9);
  LODWORD(v13) = objc_retainAutoreleasedReturnValue(v12);
  v14 = v13;
  v15 = objc_msgSend(self, *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 4));
  LODWORD(v16) = objc_retainAutoreleasedReturnValue(v15);
  v17 = v16;
  v18 = objc_msgSend(v16, *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 7));
  LODWORD(v19) = objc_retainAutoreleasedReturnValue(v18);
  v20 = v19;
  objc_release(v17);
  v21 = *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 8);
  v148 = v14;
  v140 = v20;
  objc_msgSend(v14, v21, v20, &cfstr_Info);
  v22 = objc_msgSend(self, *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 4));
  LODWORD(v23) = objc_retainAutoreleasedReturnValue(v22);
  v24 = v23;
  v25 = objc_msgSend(v23, *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 9));
  LODWORD(v26) = objc_retainAutoreleasedReturnValue(v25);
  v27 = v26;
  objc_release(v24);
  v28 = objc_msgSend(self, *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 1));
  LODWORD(v29) = ((int (__fastcall *)(struct FIRInstanceIDTokenFetchOperation *, _QWORD))objc_msgSend)(
                   self,
                   *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 10));
  LODWORD(v30) = objc_retainAutoreleasedReturnValue(v29);
  v31 = v30;
  LODWORD(v32) = ((int (__fastcall *)(struct FIRInstanceIDTokenFetchOperation *, _QWORD))objc_msgSend)(
                   self,
                   *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 11));
  v33 = (__int64)*(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 12);
  v146 = v27;
  LODWORD(v34) = ((int (__fastcall *)(void *, __int64, __int64, __int64, __int64))objc_msgSend)(v28, v33, v27, v31, v32);
  LODWORD(v35) = objc_retainAutoreleasedReturnValue(v34);
  v36 = v35;
  v150 = v35;
  objc_release(v31);
  v37 = (__int64)*(&classRef_FIRInstanceIDTokenOperation + 1);
  LODWORD(v38) = ((int (__fastcall *)(_QWORD, _QWORD))objc_msgSend)(
                   self,
                   *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 13));
  LODWORD(v39) = objc_retainAutoreleasedReturnValue(v38);
  v40 = v39;
  LODWORD(v41) = ((int (__fastcall *)(__int64, _QWORD, __CFString *, __int64))objc_msgSend)(
                   v37,
                   *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 14),
                   &cfstr_Info + 1,
                   v39);
  LODWORD(v42) = objc_retainAutoreleasedReturnValue(v41);
  v43 = v42;
  ((void (__fastcall *)(void *, _QWORD, __int64))objc_msgSend)(
    v36,
    *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 15),
    v42);
  objc_release(v43);
  objc_release(v40);
  v44 = (__int64)*(&classRef_FIRInstanceIDTokenOperation + 1);
  LODWORD(v45) = ((int (__fastcall *)(_QWORD, _QWORD))objc_msgSend)(
                   self,
                   *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 13));
  LODWORD(v46) = objc_retainAutoreleasedReturnValue(v45);
  v47 = v46;
  LODWORD(v48) = ((int (__fastcall *)(__int64, _QWORD, __CFString *, __int64))objc_msgSend)(
                   v44,
                   *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 14),
                   &cfstr_Info + 2,
                   v46);
  LODWORD(v49) = objc_retainAutoreleasedReturnValue(v48);
  v50 = v49;
  ((void (__fastcall *)(void *, _QWORD, __int64))objc_msgSend)(
    v150,
    *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 15),
    v49);
  objc_release(v50);
  objc_release(v47);
  LODWORD(v51) = ((int (__fastcall *)(_QWORD, _QWORD))objc_msgSend)(
                   self,
                   *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 16));
  LODWORD(v52) = objc_retainAutoreleasedReturnValue(v51);
  v53 = v52;
  LODWORD(v54) = ((int (__fastcall *)(struct FIRInstanceIDTokenFetchOperation *, _QWORD, __int64))objc_msgSend)(
                   self,
                   *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 17),
                   v52);
  LODWORD(v55) = objc_retainAutoreleasedReturnValue(v54);
  v56 = v55;
  ((void (__fastcall *)(void *, _QWORD, __int64))objc_msgSend)(
    v150,
    *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 18),
    v55);
  objc_release(v56);
  objc_release(v53);
  LODWORD(v57) = ((int (__fastcall *)(_QWORD, _QWORD))objc_msgSend)(
                   self,
                   *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 19));
  LODWORD(v58) = objc_retainAutoreleasedReturnValue(v57);
  v59 = v58;
  v60 = (__int64)*(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 20);
  v61 = (__int64)*(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 20);
  v149 = (void *)*kFIRInstanceIDTokenOptionsAPNSKey;
  LODWORD(v62) = ((int (__fastcall *)(__int64, __int64))objc_msgSend)(v58, v61);
  LODWORD(v63) = objc_retainAutoreleasedReturnValue(v62);
  v64 = v63;
  objc_release(v59);
  v147 = self;
  LODWORD(v65) = ((int (__fastcall *)(_QWORD, _QWORD))objc_msgSend)(
                   self,
                   *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 19));
  LODWORD(v66) = objc_retainAutoreleasedReturnValue(v65);
  v67 = v66;
  LODWORD(v68) = ((int (__fastcall *)(__int64, __int64, _QWORD))objc_msgSend)(
                   v66,
                   v60,
                   *kFIRInstanceIDTokenOptionsAPNSIsSandboxKey);
  LODWORD(v69) = objc_retainAutoreleasedReturnValue(v68);
  v70 = v69;
  objc_release(v67);
  v71 = *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 1);
  LODWORD(v72) = ((int (__fastcall *)(_QWORD))objc_msgSend)(*(&classRef_FIRInstanceIDTokenOperation + 2));
  v73 = *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 21);
  v144 = v64;
  v74 = v64;
  v75 = v73;
  v76 = (__int64)v70;
  if ( (unsigned __int8)((int (__fastcall *)(__int64, const char *, __int64))objc_msgSend)(v74, v73, v72) )
  {
    v77 = objc_msgSend(*(&classRef_FIRInstanceIDTokenOperation + 3), v71);
    if ( (unsigned __int8)objc_msgSend(v70, v75, v77) )
    {
      v78 = (unsigned __int64)objc_msgSend(
                                v70,
                                *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_
                                + 22));
      LODWORD(v79) = FIRInstanceIDAPNSTupleStringForTokenAndServerType(v144, v78);
      LODWORD(v80) = objc_retainAutoreleasedReturnValue(v79);
      v81 = v80;
      v82 = objc_msgSend(
              *(&classRef_FIRInstanceIDTokenOperation + 1),
              *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 14),
              v149,
              v80);
      LODWORD(v83) = objc_retainAutoreleasedReturnValue(v82);
      v84 = v83;
      objc_msgSend(
        v150,
        *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 15),
        v83);
      objc_release(v84);
      v71 = *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 1);
      objc_release(v81);
    }
  }
  v141 = v76;
  v85 = objc_msgSend(v147, *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 19));
  LODWORD(v86) = objc_retainAutoreleasedReturnValue(v85);
  v87 = v86;
  v88 = *kFIRInstanceIDTokenOptionsFirebaseAppIDKey;
  v89 = objc_msgSend(
          v86,
          *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 20),
          *kFIRInstanceIDTokenOptionsFirebaseAppIDKey);
  LODWORD(v90) = objc_retainAutoreleasedReturnValue(v89);
  v91 = v90;
  objc_release(v87);
  v92 = objc_msgSend(*(&classRef_FIRInstanceIDTokenOperation + 4), v71);
  v149 = v91;
  if ( (unsigned __int8)objc_msgSend(
                          v91,
                          *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 21),
                          v92) )
  {
    v93 = objc_msgSend(
            *(&classRef_FIRInstanceIDTokenOperation + 1),
            *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 14),
            v88,
            v149);
    LODWORD(v94) = objc_retainAutoreleasedReturnValue(v93);
    v95 = v94;
    objc_msgSend(
      v150,
      *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 15),
      v94);
    objc_release(v95);
  }
  LODWORD(v96) = FIRInstanceIDQueryFromQueryItems(v150);
  LODWORD(v97) = objc_retainAutoreleasedReturnValue(v96);
  v98 = (__int64)v97;
  v99 = objc_msgSend(
          v97,
          *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 23),
          4LL);
  LODWORD(v100) = objc_retainAutoreleasedReturnValue(v99);
  v101 = v100;
  objc_msgSend(v148, *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 24), v100);
  objc_release(v101);
  LODWORD(v102) = FIRInstanceIDSharedLogger(v101);
  v103 = v102;
  LODWORD(v104) = objc_retainAutoreleasedReturnValue(v102);
  v105 = v104;
  LODWORD(v106) = FIRInstanceIDRegisterServer(v103);
  LODWORD(v107) = objc_retainAutoreleasedReturnValue(v106);
  v108 = v107;
  v109 = *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 25);
  v142 = v98;
  objc_msgSend(v105, v109, &aInfo[22], 20000LL, &cfstr_Info + 3, v107, v98);
  objc_release(v108);
  objc_release(v105);
  v110 = v147;
  objc_initWeak(&v143, v147);
  v134 = _NSConcreteStackBlock[0];
  v135 = -1040187392;
  v136 = 0;
  v137 = __57__FIRInstanceIDTokenFetchOperation_performTokenOperation__block_invoke;
  v138 = &__block_descriptor_tmp;
  objc_copyWeak(&v139, &v143);
  LODWORD(v111) = objc_retainBlock(&v134, &v143);
  v112 = v111;
  v113 = *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 27);
  v114 = objc_msgSend(
           v110,
           *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 27));
  LODWORD(v115) = objc_retainAutoreleasedReturnValue(v114);
  v116 = v115;
  objc_release(v115);
  if ( v116 )
  {
    v117 = objc_msgSend(v147, v113);
    LODWORD(v118) = objc_retainAutoreleasedReturnValue(v117);
    v119 = v118;
    (*(void (__fastcall **)(__int64, void *, __int64))(v118 + 16))(v118, v148, v112);
    objc_release(v119);
    v120 = v145;
    v121 = (void (__fastcall *)(__int64))objc_release;
  }
  else
  {
    v122 = objc_msgSend(
             classRef_FIRInstanceIDTokenOperation,
             *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 28));
    v123 = v147;
    LODWORD(v124) = objc_retainAutoreleasedReturnValue(v122);
    v125 = v124;
    v126 = objc_msgSend(
             v124,
             *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 29),
             v148,
             v112);
    LODWORD(v127) = objc_retainAutoreleasedReturnValue(v126);
    v128 = v127;
    objc_msgSend(
      v123,
      *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 30),
      v127);
    objc_release(v128);
    v129 = objc_msgSend(
             v123,
             *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 31));
    LODWORD(v130) = objc_retainAutoreleasedReturnValue(v129);
    v131 = v130;
    objc_msgSend(v130, *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 32));
    v132 = v131;
    v121 = (void (__fastcall *)(__int64))objc_release;
    objc_release(v132);
    objc_release(v125);
    v120 = v145;
  }
  v133 = v146;
  v121(v112);
  objc_destroyWeak(&v139);
  objc_destroyWeak(&v143);
  v121(v142);
  v121(v149);
  v121(v141);
  v121(v144);
  v121(v150);
  v121(v133);
  v121(v140);
  v121(v148);
  v121(v120);
}
// 1908: using guessed type char *selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_;
// 1AD8: using guessed type void *classRef_FIRInstanceIDTokenOperation;
// 1D10: using guessed type __CFString cfstr_Info;
// 84C0: using guessed type int __fastcall FIRInstanceIDAPNSTupleStringForTokenAndServerType(_QWORD, _QWORD);
// 84C8: using guessed type int __fastcall FIRInstanceIDQueryFromQueryItems(_QWORD);
// 84D0: using guessed type int __fastcall FIRInstanceIDRegisterServer(_QWORD);
// 84D8: using guessed type int __fastcall FIRInstanceIDSharedLogger(_QWORD);
// 85C0: using guessed type int __fastcall objc_copyWeak(_QWORD, _QWORD);
// 85C8: using guessed type int __fastcall objc_destroyWeak(_QWORD);
// 85D8: using guessed type int __fastcall objc_initWeak(_QWORD, _QWORD);
// 85F8: using guessed type int __fastcall objc_release(_QWORD);
// 8608: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);
// 8610: using guessed type int __fastcall objc_retainBlock(_QWORD, _QWORD);

//----- (0000000000000858) ----------------------------------------------------
int __usercall __57__FIRInstanceIDTokenFetchOperation_performTokenOperation__block_invoke@<eax>(__int64 a1@<rax>, __int64 a2@<rdx>, __int64 a3@<rcx>, __int64 a4@<rdi>, __int64 a5@<rsi>)
{
  __int64 v5; // ST00_8@1
  __int64 v6; // r14@1
  __int64 v7; // r12@1
  __int64 v8; // rax@1
  __int64 v9; // r15@1
  __int64 v10; // rax@1
  __int64 v11; // r12@1
  __int64 v12; // rax@1
  __int64 v13; // r14@1
  void *v14; // rax@1
  void *v15; // r13@1

  v5 = a1;
  v6 = a3;
  v7 = a2;
  LODWORD(v8) = objc_retain(a5);
  v9 = v8;
  LODWORD(v10) = objc_retain(v7);
  v11 = v10;
  LODWORD(v12) = objc_retain(v6);
  v13 = v12;
  LODWORD(v14) = objc_loadWeakRetained(a4 + 32);
  v15 = v14;
  objc_msgSend(
    v14,
    *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 26),
    v9,
    v11,
    v13,
    v5);
  objc_release(v13);
  objc_release(v11);
  objc_release(v9);
  return objc_release(v15);
}
// 1908: using guessed type char *selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_;
// 85E0: using guessed type int __fastcall objc_loadWeakRetained(_QWORD);
// 85F8: using guessed type int __fastcall objc_release(_QWORD);
// 8600: using guessed type int __fastcall objc_retain(_QWORD);

//----- (00000000000008E5) ----------------------------------------------------
int __fastcall __copy_helper_block_(__int64 a1, __int64 a2)
{
  return objc_copyWeak(a1 + 32, a2 + 32);
}
// 85C0: using guessed type int __fastcall objc_copyWeak(_QWORD, _QWORD);

//----- (00000000000008F7) ----------------------------------------------------
int __fastcall __destroy_helper_block_(__int64 a1)
{
  return objc_destroyWeak(a1 + 32);
}
// 85C8: using guessed type int __fastcall objc_destroyWeak(_QWORD);

//----- (0000000000000905) ----------------------------------------------------
// FIRInstanceIDTokenFetchOperation - (void)handleResponseWithData:(id) response:(id) error:(id) 
void __cdecl -[FIRInstanceIDTokenFetchOperation handleResponseWithData:response:error:](struct FIRInstanceIDTokenFetchOperation *self, SEL a2, id a3, id a4, id a5)
{
  id v5; // rbx@1
  struct FIRInstanceIDTokenFetchOperation *v6; // r12@1
  __int64 v7; // rax@1
  __int64 v8; // r13@1
  void *v9; // rax@1
  void *v10; // r14@1
  __int64 v11; // rax@2
  void *v12; // rax@2
  void *v13; // rbx@2
  void *v14; // rax@2
  void (*v15)(void *, const char *, ...); // r15@3
  void *v16; // rax@3
  void *v17; // rbx@3
  const char *v18; // rsi@4
  void *v19; // rax@4
  void *v20; // rax@4
  const char *v21; // rsi@4
  void *v22; // rax@4
  void *v23; // rax@4
  void *v24; // rbx@4
  void *v25; // r13@4
  void *v26; // rax@5
  __int64 v27; // rax@5
  __int64 v28; // rbx@5
  void *v29; // rax@5
  __int64 v30; // rdi@5
  void *v31; // rax@6
  void *v32; // rax@6
  __int64 v33; // r15@6
  void *v34; // rbx@6
  void *v35; // rdi@6
  void *v36; // rax@7
  void *v37; // rax@7
  void *v38; // rbx@7
  void *v39; // rdi@7
  void *v40; // rax@7
  void *v41; // rax@8
  void *v42; // rax@8
  void *v43; // r13@8
  signed int v44; // ebx@10
  dispatch_time_t v45; // r15@10
  __int64 v46; // rax@12
  void *v47; // rax@12
  void *v48; // rbx@12
  void *v49; // rax@12
  __int64 v50; // rax@12
  __int64 v51; // rbx@12
  void *v52; // [sp+8h] [bp-78h]@10
  signed int v53; // [sp+10h] [bp-70h]@10
  int v54; // [sp+14h] [bp-6Ch]@10
  int (__usercall *v55)@<eax>(__int64@<rax>, __int64@<rdi>); // [sp+18h] [bp-68h]@10
  void *v56; // [sp+20h] [bp-60h]@10
  char v57; // [sp+28h] [bp-58h]@10
  char v58; // [sp+30h] [bp-50h]@10
  __int64 v59; // [sp+38h] [bp-48h]@7
  __int64 v60; // [sp+40h] [bp-40h]@4
  __int64 v61; // [sp+48h] [bp-38h]@4
  void *v62; // [sp+50h] [bp-30h]@4

  v5 = a5;
  v6 = self;
  LODWORD(v7) = objc_retain(a3);
  v8 = v7;
  LODWORD(v9) = objc_retain(v5);
  v10 = v9;
  if ( !v9 )
  {
    v15 = (void (*)(void *, const char *, ...))objc_msgSend;
    v16 = objc_msgSend(
            *(&classRef_FIRInstanceIDTokenOperation + 4),
            *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 35));
    v17 = objc_msgSend(
            v16,
            *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 36),
            v8,
            4LL);
    if ( !objc_msgSend(
            v17,
            *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 37)) )
    {
      v31 = objc_msgSend(
              *(&classRef_FIRInstanceIDTokenOperation + 5),
              *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 38),
              0LL);
      LODWORD(v32) = objc_retainAutoreleasedReturnValue(v31);
      v33 = (__int64)v17;
      v34 = v32;
      objc_msgSend(
        self,
        *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 34),
        1LL,
        0LL,
        v32);
      v35 = v34;
LABEL_15:
      objc_release(v35);
      objc_release(v33);
      goto LABEL_16;
    }
    v60 = v8;
    v18 = *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 39);
    v61 = (__int64)v17;
    v19 = objc_msgSend(self, v18, v17);
    LODWORD(v20) = objc_retainAutoreleasedReturnValue(v19);
    v21 = *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 20);
    v62 = v20;
    v22 = objc_msgSend(v20, v21, &cfstr_Info + 5);
    LODWORD(v23) = objc_retainAutoreleasedReturnValue(v22);
    v24 = v23;
    v25 = objc_msgSend(
            v23,
            *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 37));
    objc_release(v24);
    if ( v25 )
    {
      v26 = objc_msgSend(
              v62,
              *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 20),
              &cfstr_Info + 5);
      LODWORD(v27) = objc_retainAutoreleasedReturnValue(v26);
      v28 = v27;
      v29 = objc_msgSend(
              self,
              *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 11));
      objc_msgSend(
        self,
        *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 43),
        v28,
        v29);
      v30 = v28;
LABEL_14:
      objc_release(v30);
      v8 = v60;
      v33 = v61;
      v35 = v62;
      goto LABEL_15;
    }
    v36 = objc_msgSend(
            v62,
            *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 20),
            &cfstr_Info + 6);
    LODWORD(v37) = objc_retainAutoreleasedReturnValue(v36);
    v38 = v37;
    v39 = v37;
    v40 = objc_msgSend(
            v37,
            *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 37));
    v59 = (__int64)v38;
    if ( v40 )
    {
      v41 = objc_msgSend(
              v38,
              *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 40),
              &cfstr_Info + 7);
      LODWORD(v42) = objc_retainAutoreleasedReturnValue(v41);
      v43 = v42;
      if ( (unsigned __int8)objc_msgSend(
                              v42,
                              *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 41),
                              &cfstr_Info + 8)
        && phoneRegistrationErrorRetryCount <= 9 )
      {
        v44 = 1 << phoneRegistrationErrorRetryCount;
        objc_initWeak(&v58, v6);
        v45 = dispatch_time(0LL, 1000000000LL * v44);
        v52 = _NSConcreteStackBlock[0];
        v53 = -1040187392;
        v54 = 0;
        v55 = __74__FIRInstanceIDTokenFetchOperation_handleResponseWithData_response_error___block_invoke;
        v56 = &__block_descriptor_tmp_110;
        objc_copyWeak(&v57, &v58);
        dispatch_after(v45, _dispatch_main_q, &v52);
        objc_destroyWeak(&v57);
        objc_destroyWeak(&v58);
        objc_release(v43);
LABEL_13:
        v30 = v59;
        goto LABEL_14;
      }
      v39 = v43;
      objc_release(v43);
      v15 = (void (*)(void *, const char *, ...))objc_msgSend;
    }
    LODWORD(v46) = FIRInstanceIDSharedLogger(v39);
    LODWORD(v47) = objc_retainAutoreleasedReturnValue(v46);
    v48 = v47;
    v15(
      v47,
      *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 25),
      &aInfo[162],
      20002LL,
      &cfstr_Info + 9);
    objc_release(v48);
    v49 = ((void *(*)(void *, const char *, ...))v15)(
            *(&classRef_FIRInstanceIDTokenOperation + 5),
            *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 38),
            0LL);
    LODWORD(v50) = objc_retainAutoreleasedReturnValue(v49);
    v51 = v50;
    v15(v6, *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 34), 1LL, 0LL, v50);
    objc_release(v51);
    goto LABEL_13;
  }
  LODWORD(v11) = FIRInstanceIDSharedLogger(v5);
  LODWORD(v12) = objc_retainAutoreleasedReturnValue(v11);
  v13 = v12;
  v14 = objc_msgSend(v10, *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 33));
  objc_msgSend(
    v13,
    *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 25),
    &aInfo[162],
    20001LL,
    &cfstr_Info + 4,
    v14);
  objc_release(v13);
  objc_msgSend(
    self,
    *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 34),
    1LL,
    0LL,
    v10);
LABEL_16:
  objc_release(v10);
  objc_release(v8);
}
// 1908: using guessed type char *selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_;
// 1AD8: using guessed type void *classRef_FIRInstanceIDTokenOperation;
// 1D10: using guessed type __CFString cfstr_Info;
// 84B8: using guessed type int phoneRegistrationErrorRetryCount;
// 84D8: using guessed type int __fastcall FIRInstanceIDSharedLogger(_QWORD);
// 8578: using guessed type int __fastcall dispatch_after(_QWORD, _QWORD, _QWORD);
// 85C0: using guessed type int __fastcall objc_copyWeak(_QWORD, _QWORD);
// 85C8: using guessed type int __fastcall objc_destroyWeak(_QWORD);
// 85D8: using guessed type int __fastcall objc_initWeak(_QWORD, _QWORD);
// 85F8: using guessed type int __fastcall objc_release(_QWORD);
// 8600: using guessed type int __fastcall objc_retain(_QWORD);
// 8608: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000CD2) ----------------------------------------------------
int __usercall __74__FIRInstanceIDTokenFetchOperation_handleResponseWithData_response_error___block_invoke@<eax>(__int64 a1@<rax>, __int64 a2@<rdi>)
{
  __int64 v2; // ST00_8@1
  void *v3; // rax@1
  void *v4; // rbx@1

  v2 = a1;
  LODWORD(v3) = objc_loadWeakRetained(a2 + 32);
  v4 = v3;
  ++phoneRegistrationErrorRetryCount;
  objc_msgSend(v3, *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 42), v2);
  return objc_release(v4);
}
// 1908: using guessed type char *selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_;
// 84B8: using guessed type int phoneRegistrationErrorRetryCount;
// 85E0: using guessed type int __fastcall objc_loadWeakRetained(_QWORD);
// 85F8: using guessed type int __fastcall objc_release(_QWORD);

//----- (0000000000000D09) ----------------------------------------------------
int __fastcall __copy_helper_block__107(__int64 a1, __int64 a2)
{
  return objc_copyWeak(a1 + 32, a2 + 32);
}
// 85C0: using guessed type int __fastcall objc_copyWeak(_QWORD, _QWORD);

//----- (0000000000000D1B) ----------------------------------------------------
int __fastcall __destroy_helper_block__108(__int64 a1)
{
  return objc_destroyWeak(a1 + 32);
}
// 85C8: using guessed type int __fastcall objc_destroyWeak(_QWORD);

//----- (0000000000000D29) ----------------------------------------------------
// FIRInstanceIDTokenFetchOperation - (id)parseFetchTokenResponse:(id) 
id __cdecl -[FIRInstanceIDTokenFetchOperation parseFetchTokenResponse:](struct FIRInstanceIDTokenFetchOperation *self, SEL a2, id a3)
{
  void *v3; // rax@1
  __int64 v4; // rax@1
  __int64 v5; // r14@1
  void *v6; // rax@1
  void *v7; // rax@1
  void *v8; // rax@1
  const char *v9; // rsi@1
  __int64 v10; // rbx@2
  unsigned __int64 v11; // r14@3
  void *v12; // rax@6
  void *v13; // rax@6
  void *v14; // r13@6
  const char *v15; // r12@7
  void *v16; // rax@7
  __int64 v17; // rax@7
  __int64 v18; // rbx@7
  void *v19; // rax@7
  __int64 v20; // rax@7
  __int64 v21; // r12@7
  __int64 v22; // rdi@7
  void *v23; // rbx@10
  id result; // rax@10
  __int128 v25; // [sp+0h] [bp-130h]@1
  __int128 v26; // [sp+10h] [bp-120h]@1
  __int128 v27; // [sp+20h] [bp-110h]@1
  __int128 v28; // [sp+30h] [bp-100h]@1
  const char *v29; // [sp+48h] [bp-E8h]@3
  const char *v30; // [sp+50h] [bp-E0h]@3
  const char *v31; // [sp+58h] [bp-D8h]@3
  __int64 v32; // [sp+60h] [bp-D0h]@2
  void *v33; // [sp+68h] [bp-C8h]@1
  void *v34; // [sp+70h] [bp-C0h]@1
  void *v35; // [sp+78h] [bp-B8h]@1
  char v36; // [sp+80h] [bp-B0h]@1
  __int64 v37; // [sp+100h] [bp-30h]@1

  v37 = *__stack_chk_guard;
  v3 = objc_msgSend(
         a3,
         *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 40),
         &cfstr_Info + 10);
  LODWORD(v4) = objc_retainAutoreleasedReturnValue(v3);
  v5 = v4;
  v6 = objc_msgSend(
         *(&classRef_FIRInstanceIDTokenOperation + 6),
         *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 44));
  LODWORD(v7) = objc_retainAutoreleasedReturnValue(v6);
  v34 = v7;
  v28 = 0LL;
  v27 = 0LL;
  v26 = 0LL;
  v25 = 0LL;
  LODWORD(v8) = objc_retain(v5);
  v9 = *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 45);
  v35 = v8;
  v33 = objc_msgSend(v8, v9, &v25, &v36, 16LL, (_QWORD)v25);
  if ( v33 )
  {
    v10 = *(_QWORD *)v26;
    v32 = *(_QWORD *)v26;
    do
    {
      v29 = *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 46);
      v30 = *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 47);
      v31 = *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 48);
      v11 = 0LL;
      do
      {
        if ( *(_QWORD *)v26 != v10 )
          objc_enumerationMutation(v35);
        v12 = objc_msgSend(
                *(void **)(*((_QWORD *)&v25 + 1) + 8 * v11),
                *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 40),
                &cfstr_Info + 11,
                (_QWORD)v25);
        LODWORD(v13) = objc_retainAutoreleasedReturnValue(v12);
        v14 = v13;
        if ( (unsigned __int64)objc_msgSend(v13, v29, (_QWORD)v25) >= 2 )
        {
          v15 = v30;
          v16 = objc_msgSend(v14, v30, 0LL, (_QWORD)v25);
          LODWORD(v17) = objc_retainAutoreleasedReturnValue(v16);
          v18 = v17;
          v19 = objc_msgSend(v14, v15, 1LL, (_QWORD)v25);
          LODWORD(v20) = objc_retainAutoreleasedReturnValue(v19);
          v21 = v20;
          objc_msgSend(v34, v31, v20, v18, (_QWORD)v25);
          objc_release(v21);
          v22 = v18;
          v10 = v32;
          objc_release(v22);
        }
        objc_release(v14);
        ++v11;
      }
      while ( v11 < (unsigned __int64)v33 );
      v33 = objc_msgSend(
              v35,
              *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 45),
              &v25,
              &v36,
              16LL,
              (_QWORD)v25);
    }
    while ( v33 );
  }
  v23 = v35;
  objc_release(v35);
  objc_release(v23);
  result = (id)*__stack_chk_guard;
  if ( *__stack_chk_guard == v37 )
    LODWORD(result) = objc_autoreleaseReturnValue(v34);
  return result;
}
// 1908: using guessed type char *selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_;
// 1AD8: using guessed type void *classRef_FIRInstanceIDTokenOperation;
// 1D10: using guessed type __CFString cfstr_Info;
// 85B8: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 85D0: using guessed type int __fastcall objc_enumerationMutation(_QWORD);
// 85F8: using guessed type int __fastcall objc_release(_QWORD);
// 8600: using guessed type int __fastcall objc_retain(_QWORD);
// 8608: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000F7F) ----------------------------------------------------
// FIRInstanceIDTokenFetchOperation - (void)parseToken:(id) withRequestID:(uint64_t) 
void __cdecl -[FIRInstanceIDTokenFetchOperation parseToken:withRequestID:](struct FIRInstanceIDTokenFetchOperation *self, SEL a2, id a3, uint64_t a4)
{
  uint64_t v4; // r15@1
  struct FIRInstanceIDTokenFetchOperation *v5; // r12@1
  void *v6; // rax@1
  void *v7; // rbx@1
  void *v8; // rax@2
  void *v9; // rax@2
  void *v10; // r12@2
  void *v11; // rax@2
  __int64 v12; // rax@2
  __int64 v13; // rbx@2
  int v14; // er14@2
  __int64 v15; // rax@3
  void *v16; // rax@3
  void *v17; // rbx@3
  void *v18; // r14@5
  void *v19; // rax@5
  __int64 v20; // rax@5
  __int64 v21; // rbx@5
  void *v22; // rax@6
  void *v23; // rax@6
  void *v24; // rbx@6
  const char *v25; // r14@6
  void *v26; // r13@7
  void *v27; // rax@7
  void *v28; // rax@7
  void *v29; // r15@7
  void *v30; // rax@8
  void *v31; // rax@8
  void *v32; // rax@8
  void *v33; // r14@11
  void *v34; // rax@11
  __int64 v35; // rax@11
  __int64 v36; // rbx@11
  bool v37; // zf@11
  void *v38; // rax@12
  void *v39; // rax@12
  void *v40; // rbx@12
  void *v41; // rax@13
  void *v42; // rax@13
  void *v43; // rax@14
  void *v44; // rax@14
  void *v45; // r14@14
  void *v46; // [sp+10h] [bp-30h]@1

  v4 = a4;
  v5 = self;
  LODWORD(v6) = objc_retain(a3);
  v7 = v6;
  v46 = v6;
  if ( (unsigned __int8)objc_msgSend(
                          v6,
                          *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 49),
                          &cfstr_Info + 12) )
  {
    v8 = objc_msgSend(
           v7,
           *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 40),
           &cfstr_Info + 12);
    LODWORD(v9) = objc_retainAutoreleasedReturnValue(v8);
    v10 = v9;
    v11 = objc_msgSend(
            v9,
            *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 47),
            1LL);
    LODWORD(v12) = objc_retainAutoreleasedReturnValue(v11);
    v13 = v12;
    v14 = (unsigned __int64)objc_msgSend(
                              &cfstr_Info + 13,
                              *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 50),
                              v12);
    objc_release(v13);
    if ( !(_BYTE)v14 )
    {
      LODWORD(v15) = FIRInstanceIDSharedLogger(v13);
      LODWORD(v16) = objc_retainAutoreleasedReturnValue(v15);
      v17 = v16;
      objc_msgSend(
        v16,
        *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 51),
        &aInfo[387],
        20003LL,
        &cfstr_Info + 14,
        v46);
      objc_release(v17);
    }
    if ( (unsigned __int64)objc_msgSend(
                             v10,
                             *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 46)) < 5 )
    {
      v26 = 0LL;
    }
    else
    {
      v18 = (void *)*kFIRInstanceID_CMD_SYNC;
      v19 = objc_msgSend(
              v10,
              *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 47),
              3LL);
      LODWORD(v20) = objc_retainAutoreleasedReturnValue(v19);
      v21 = v20;
      LODWORD(v18) = (unsigned __int64)objc_msgSend(
                                         v18,
                                         *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_
                                         + 50),
                                         v20);
      objc_release(v21);
      if ( (_BYTE)v18 )
      {
        v22 = objc_msgSend(
                *(&classRef_FIRInstanceIDTokenOperation + 7),
                *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 52));
        LODWORD(v23) = objc_retainAutoreleasedReturnValue(v22);
        v24 = v23;
        objc_msgSend(
          v23,
          *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 53),
          *KFIRInstanceIDTokenMismatchNotification,
          0LL);
        objc_release(v24);
        v25 = *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 49);
      }
      else
      {
        v33 = (void *)*kFIRInstanceID_CMD_RST;
        v34 = objc_msgSend(
                v10,
                *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 47),
                3LL);
        LODWORD(v35) = objc_retainAutoreleasedReturnValue(v34);
        v36 = v35;
        LOBYTE(v33) = (unsigned __int64)objc_msgSend(
                                          v33,
                                          *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_
                                          + 50),
                                          v35);
        objc_release(v36);
        v37 = (_BYTE)v33 == 0;
        v25 = *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 49);
        if ( !v37 )
        {
          v38 = objc_msgSend(
                  *(&classRef_FIRInstanceIDTokenOperation + 7),
                  *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 52));
          LODWORD(v39) = objc_retainAutoreleasedReturnValue(v38);
          v40 = v39;
          objc_msgSend(
            v39,
            *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 53),
            *kFIRInstanceIDIdentityInvalidatedNotification,
            0LL);
          objc_release(v40);
        }
      }
      v41 = objc_msgSend(
              v10,
              *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 54));
      LODWORD(v42) = objc_retainAutoreleasedReturnValue(v41);
      v26 = v42;
      if ( (unsigned __int8)objc_msgSend(v42, v25, &cfstr_Info + 7) )
      {
        v43 = objc_msgSend(
                v26,
                *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 55),
                1LL);
        LODWORD(v44) = objc_retainAutoreleasedReturnValue(v43);
        v45 = v44;
        objc_release(v26);
        v26 = v45;
      }
    }
    objc_release(v10);
    v5 = self;
  }
  else
  {
    v26 = 0LL;
    v27 = objc_msgSend(
            *(&classRef_FIRInstanceIDTokenOperation + 4),
            *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 56),
            &cfstr_Info + 15,
            v4);
    LODWORD(v28) = objc_retainAutoreleasedReturnValue(v27);
    v29 = v28;
    if ( (unsigned __int8)objc_msgSend(
                            v7,
                            *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 49),
                            v28) )
    {
      v30 = objc_msgSend(
              v29,
              *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 37));
      v31 = objc_msgSend(
              v7,
              *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 57),
              0LL,
              v30,
              &cfstr_Info + 16);
      LODWORD(v32) = objc_retainAutoreleasedReturnValue(v31);
      v26 = v32;
    }
    objc_release(v29);
  }
  objc_msgSend(
    v5,
    *(&selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_ + 34),
    0LL,
    v26,
    0LL);
  objc_release(v26);
  objc_release(v46);
}
// 1908: using guessed type char *selRef_initWithAction_forAuthorizedEntity_scope_options_checkinPreferences_keyPair_;
// 1AD8: using guessed type void *classRef_FIRInstanceIDTokenOperation;
// 1D10: using guessed type __CFString cfstr_Info;
// 84D8: using guessed type int __fastcall FIRInstanceIDSharedLogger(_QWORD);
// 85F8: using guessed type int __fastcall objc_release(_QWORD);
// 8600: using guessed type int __fastcall objc_retain(_QWORD);
// 8608: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

// ALL OK, 11 function(s) have been successfully decompiled
