/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2015 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int __fastcall _FIRInstanceIDCheckinPreferences_Internal__preferencesFromKeychainContents__(void *a1, __int64 a2, __int64 a3);
void *__fastcall _FIRInstanceIDCheckinPreferences_Internal__initWithDeviceID_secretToken__(__int64 a1, __int64 a2, __int64 a3, __int64 a4);
void *__fastcall _FIRInstanceIDCheckinPreferences_Internal__reset_(void *a1);
__int64 __fastcall _FIRInstanceIDCheckinPreferences_Internal__updateWithCheckinPlistContents__(void *a1, __int64 a2, __int64 a3);
// int __usercall _FIRInstanceIDCheckinPreferences_Internal__checkinKeychainContent_@<eax>(__int64 a1@<rax>, void *a2@<rdi>);
void *__fastcall _FIRInstanceIDCheckinPreferences_Internal__checkinDeviceIDFromKeychainContent__(void *a1, __int64 a2, __int64 a3);
void *__fastcall _FIRInstanceIDCheckinPreferences_Internal__checkinSecretFromKeychainContent__(void *a1, __int64 a2, __int64 a3);
int __fastcall _FIRInstanceIDCheckinPreferences_Internal__checkinKeychainContent_forIndex__(__int64 a1, __int64 a2, void *a3, unsigned int a4);
// int __fastcall objc_autoreleaseReturnValue(_QWORD); weak
// int __fastcall objc_enumerationMutation(_QWORD); weak
// void *objc_msgSend(void *, const char *, ...); idb
// void *objc_msgSendSuper2(void *, const char *, ...); idb
// int __fastcall objc_retainAutoreleasedReturnValue(_QWORD); weak

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN loc_1; // weak
__CFString stru_808 = { &__CFConstantStringClassReference, 1992LL, "|", 1LL }; // weak
__int64 (__fastcall *paCheckindevicei)() = &aCheckindevicei; // weak
void *off_B68 = &OBJC_CLASS___FIRInstanceIDCheckinPreferences; // weak
// extern _UNKNOWN OBJC_CLASS___FIRInstanceIDCheckinPreferences; weak
// extern _UNKNOWN __stack_chk_guard; weak
// extern _UNKNOWN kFIRInstanceIDDeviceDataVersionKey; weak
// extern _UNKNOWN kFIRInstanceIDDigestStringKey; weak
// extern _UNKNOWN kFIRInstanceIDGServicesDictionaryKey; weak
// extern _UNKNOWN kFIRInstanceIDLastCheckinTimeKey; weak
// extern _UNKNOWN kFIRInstanceIDVersionInfoStringKey; weak
// extern int (__fastcall *objc_release)(_QWORD); weak
// extern int (__fastcall *objc_retain)(_QWORD); weak


//----- (0000000000000000) ----------------------------------------------------
int __fastcall _FIRInstanceIDCheckinPreferences_Internal__preferencesFromKeychainContents__(void *a1, __int64 a2, __int64 a3)
{
  __int64 v3; // rax@1
  __int64 v4; // rbx@1
  void *v5; // rax@1
  void *v6; // rax@1
  void *v7; // r14@1
  void *v8; // r15@1
  void *v9; // rax@1
  void *v10; // r15@1
  const char *v11; // rbx@1
  void *v12; // rax@3
  void *v13; // r12@3

  LODWORD(v3) = objc_retain(a3);
  v4 = v3;
  v5 = objc_msgSend(a1, (const char *)paCheckindevicei, v3);
  LODWORD(v6) = objc_retainAutoreleasedReturnValue(v5);
  v7 = v6;
  v8 = objc_msgSend(a1, (const char *)*(&paCheckindevicei + 1), v4);
  objc_release(v4);
  LODWORD(v9) = objc_retainAutoreleasedReturnValue(v8);
  v10 = v9;
  v11 = (const char *)*(&paCheckindevicei + 2);
  if ( objc_msgSend(v7, (const char *)*(&paCheckindevicei + 2)) && objc_msgSend(v10, v11) )
  {
    v12 = objc_msgSend(&OBJC_CLASS___FIRInstanceIDCheckinPreferences, (const char *)*(&paCheckindevicei + 3));
    v13 = objc_msgSend(v12, (const char *)*(&paCheckindevicei + 4), v7, v10);
  }
  else
  {
    v13 = 0LL;
  }
  objc_release(v10);
  objc_release(v7);
  return objc_autoreleaseReturnValue(v13);
}
// A98: using guessed type __int64 (__fastcall *paCheckindevicei)();
// 3BF0: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 3C10: using guessed type int (__fastcall *objc_release)(_QWORD);
// 3C18: using guessed type int (__fastcall *objc_retain)(_QWORD);
// 3C20: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (00000000000000D9) ----------------------------------------------------
void *__fastcall _FIRInstanceIDCheckinPreferences_Internal__initWithDeviceID_secretToken__(__int64 a1, __int64 a2, __int64 a3, __int64 a4)
{
  __int64 v4; // rbx@1
  void *v5; // rax@1
  void *v6; // r14@1
  void *v7; // rax@1
  void *v8; // r15@1
  void *v9; // r13@1
  void *v10; // rbx@2
  void *v11; // rbx@2
  __int64 v13; // [sp+0h] [bp-40h]@1
  void *v14; // [sp+8h] [bp-38h]@1
  void *v15; // [sp+10h] [bp-30h]@2

  v4 = a4;
  LODWORD(v5) = objc_retain(a3);
  v6 = v5;
  LODWORD(v7) = objc_retain(v4);
  v8 = v7;
  v13 = a1;
  v14 = &OBJC_CLASS___FIRInstanceIDCheckinPreferences;
  v9 = objc_msgSendSuper2(
         &v13,
         (const char *)*(&paCheckindevicei + 5),
         a1,
         &OBJC_CLASS___FIRInstanceIDCheckinPreferences);
  if ( v9 )
  {
    v10 = objc_msgSend(v6, (const char *)*(&paCheckindevicei + 6), v13, v14);
    objc_msgSend(v9, (const char *)*(&paCheckindevicei + 7), v10, v13, v14);
    v15 = v6;
    objc_release(v10);
    v11 = objc_msgSend(v8, (const char *)*(&paCheckindevicei + 6), v13, v14);
    objc_msgSend(v9, (const char *)*(&paCheckindevicei + 8), v11, v13, v14);
    objc_release(v11);
    v6 = v15;
  }
  objc_release(v8);
  objc_release(v6);
  return v9;
}
// A98: using guessed type __int64 (__fastcall *paCheckindevicei)();
// 3C10: using guessed type int (__fastcall *objc_release)(_QWORD);
// 3C18: using guessed type int (__fastcall *objc_retain)(_QWORD);

//----- (00000000000001B4) ----------------------------------------------------
void *__fastcall _FIRInstanceIDCheckinPreferences_Internal__reset_(void *a1)
{
  objc_msgSend(a1, (const char *)*(&paCheckindevicei + 7), 0LL);
  objc_msgSend(a1, (const char *)*(&paCheckindevicei + 8), 0LL);
  objc_msgSend(a1, (const char *)*(&paCheckindevicei + 9), 0LL);
  objc_msgSend(a1, (const char *)*(&paCheckindevicei + 10), 0LL);
  objc_msgSend(a1, (const char *)*(&paCheckindevicei + 11), 0LL);
  objc_msgSend(a1, (const char *)*(&paCheckindevicei + 12), 0LL);
  return objc_msgSend(a1, (const char *)*(&paCheckindevicei + 13), 0LL);
}
// A98: using guessed type __int64 (__fastcall *paCheckindevicei)();

//----- (0000000000000231) ----------------------------------------------------
__int64 __fastcall _FIRInstanceIDCheckinPreferences_Internal__updateWithCheckinPlistContents__(void *a1, __int64 a2, __int64 a3)
{
  void *v3; // rax@1
  const char *v4; // rsi@1
  const char *v5; // r12@3
  unsigned __int64 v6; // r14@3
  void *v7; // rax@5
  void *v8; // rax@5
  void *v9; // rbx@5
  void *v10; // rax@5
  void *v11; // rax@7
  void *v12; // rax@7
  void *v13; // r15@7
  void *v14; // rbx@7
  void *v15; // rdi@7
  const char *v16; // rsi@7
  void *v17; // rax@9
  void *v18; // rax@9
  __int64 v19; // r15@12
  void *v20; // rax@13
  void *v21; // rax@13
  void *v22; // rax@15
  void *v23; // rax@15
  __int128 v25; // [sp+0h] [bp-180h]@1
  __int128 v26; // [sp+10h] [bp-170h]@1
  __int128 v27; // [sp+20h] [bp-160h]@1
  __int128 v28; // [sp+30h] [bp-150h]@1
  __int64 v29; // [sp+40h] [bp-140h]@2
  void *v30; // [sp+48h] [bp-138h]@2
  const char *v31; // [sp+50h] [bp-130h]@3
  void *v32; // [sp+58h] [bp-128h]@2
  const char *v33; // [sp+60h] [bp-120h]@3
  void *v34; // [sp+68h] [bp-118h]@2
  const char *v35; // [sp+70h] [bp-110h]@3
  const char *v36; // [sp+78h] [bp-108h]@3
  void *v37; // [sp+80h] [bp-100h]@2
  const char *v38; // [sp+88h] [bp-F8h]@3
  const char *v39; // [sp+90h] [bp-F0h]@3
  void *v40; // [sp+98h] [bp-E8h]@2
  const char *v41; // [sp+A0h] [bp-E0h]@3
  void *v42; // [sp+A8h] [bp-D8h]@1
  const char *v43; // [sp+B0h] [bp-D0h]@3
  const char *v44; // [sp+B8h] [bp-C8h]@3
  void *v45; // [sp+C0h] [bp-C0h]@1
  void *v46; // [sp+C8h] [bp-B8h]@1
  char v47; // [sp+D0h] [bp-B0h]@1
  __int64 v48; // [sp+150h] [bp-30h]@1

  v45 = a1;
  v48 = *__stack_chk_guard;
  LODWORD(v3) = objc_retain(a3);
  v28 = 0LL;
  v27 = 0LL;
  v26 = 0LL;
  v25 = 0LL;
  v4 = (const char *)*(&paCheckindevicei + 14);
  v46 = v3;
  v42 = objc_msgSend(v3, v4, &v25, &v47, 0LL, 0LL);
  if ( v42 )
  {
    v29 = *(_QWORD *)v26;
    v30 = (void *)*kFIRInstanceIDDigestStringKey;
    v32 = (void *)*kFIRInstanceIDVersionInfoStringKey;
    v34 = (void *)*kFIRInstanceIDLastCheckinTimeKey;
    v37 = (void *)*kFIRInstanceIDGServicesDictionaryKey;
    v40 = (void *)*kFIRInstanceIDDeviceDataVersionKey;
    do
    {
      v5 = (const char *)*(&paCheckindevicei + 15);
      v44 = (const char *)*(&paCheckindevicei + 16);
      v43 = (const char *)*(&paCheckindevicei + 6);
      v31 = (const char *)*(&paCheckindevicei + 9);
      v33 = (const char *)*(&paCheckindevicei + 10);
      v35 = (const char *)*(&paCheckindevicei + 17);
      v36 = (const char *)*(&paCheckindevicei + 13);
      v38 = (const char *)*(&paCheckindevicei + 18);
      v39 = (const char *)*(&paCheckindevicei + 11);
      v41 = (const char *)*(&paCheckindevicei + 12);
      v6 = 0LL;
      do
      {
        if ( *(_QWORD *)v26 != v29 )
          objc_enumerationMutation(v46);
        v19 = *(_QWORD *)(*((_QWORD *)&v25 + 1) + 8 * v6);
        if ( (unsigned __int8)objc_msgSend(v30, v5, *(_QWORD *)(*((_QWORD *)&v25 + 1) + 8 * v6), (_QWORD)v25) )
        {
          v20 = objc_msgSend(v46, v44, v19, (_QWORD)v25, *((_QWORD *)&v25 + 1));
          LODWORD(v21) = objc_retainAutoreleasedReturnValue(v20);
          v13 = v21;
          v14 = objc_msgSend(v21, v43, (_QWORD)v25, *((_QWORD *)&v25 + 1));
          v15 = v45;
          v16 = v31;
        }
        else if ( (unsigned __int8)objc_msgSend(v32, v5, v19, (_QWORD)v25, *((_QWORD *)&v25 + 1)) )
        {
          v22 = objc_msgSend(v46, v44, v19, (_QWORD)v25, *((_QWORD *)&v25 + 1));
          LODWORD(v23) = objc_retainAutoreleasedReturnValue(v22);
          v13 = v23;
          v14 = objc_msgSend(v23, v43, (_QWORD)v25, *((_QWORD *)&v25 + 1));
          v15 = v45;
          v16 = v33;
        }
        else
        {
          if ( (unsigned __int8)objc_msgSend(v34, v5, v19, (_QWORD)v25, *((_QWORD *)&v25 + 1)) )
          {
            v7 = objc_msgSend(v46, v44, v19, (_QWORD)v25, *((_QWORD *)&v25 + 1));
            LODWORD(v8) = objc_retainAutoreleasedReturnValue(v7);
            v9 = v8;
            v10 = objc_msgSend(v8, v35, (_QWORD)v25, *((_QWORD *)&v25 + 1));
            objc_msgSend(v45, v36, v10, (_QWORD)v25, *((_QWORD *)&v25 + 1));
            objc_release(v9);
            goto LABEL_17;
          }
          if ( (unsigned __int8)objc_msgSend(v37, v5, v19, (_QWORD)v25, *((_QWORD *)&v25 + 1)) )
          {
            v11 = objc_msgSend(v46, v44, v19, (_QWORD)v25, *((_QWORD *)&v25 + 1));
            LODWORD(v12) = objc_retainAutoreleasedReturnValue(v11);
            v13 = v12;
            v14 = objc_msgSend(v12, v38, (_QWORD)v25, *((_QWORD *)&v25 + 1));
            v15 = v45;
            v16 = v39;
          }
          else
          {
            if ( !(unsigned __int8)objc_msgSend(v40, v5, v19, (_QWORD)v25, *((_QWORD *)&v25 + 1)) )
              goto LABEL_17;
            v17 = objc_msgSend(v46, v44, v19, (_QWORD)v25, *((_QWORD *)&v25 + 1));
            LODWORD(v18) = objc_retainAutoreleasedReturnValue(v17);
            v13 = v18;
            v14 = objc_msgSend(v18, v43, (_QWORD)v25, *((_QWORD *)&v25 + 1));
            v15 = v45;
            v16 = v41;
          }
        }
        objc_msgSend(v15, v16, v14, (_QWORD)v25, *((_QWORD *)&v25 + 1));
        objc_release(v14);
        objc_release(v13);
LABEL_17:
        ++v6;
      }
      while ( v6 < (unsigned __int64)v42 );
      v42 = objc_msgSend(
              v46,
              (const char *)*(&paCheckindevicei + 14),
              &v25,
              &v47,
              16LL,
              (_QWORD)v25,
              *((_QWORD *)&v25 + 1));
    }
    while ( v42 );
  }
  objc_release(v46);
  return *__stack_chk_guard;
}
// A98: using guessed type __int64 (__fastcall *paCheckindevicei)();
// 3BF8: using guessed type int __fastcall objc_enumerationMutation(_QWORD);
// 3C10: using guessed type int (__fastcall *objc_release)(_QWORD);
// 3C18: using guessed type int (__fastcall *objc_retain)(_QWORD);
// 3C20: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000625) ----------------------------------------------------
int __usercall _FIRInstanceIDCheckinPreferences_Internal__checkinKeychainContent_@<eax>(__int64 a1@<rax>, void *a2@<rdi>)
{
  void *v2; // rax@1
  void *v3; // rax@1
  void *v4; // rbx@1
  const char *v5; // r13@1
  void *v6; // rax@2
  void *v7; // rax@2
  void *v8; // r15@2
  void *v9; // r13@2
  void *v10; // r14@3
  void *v11; // rax@3
  __int64 v12; // rax@3
  __int64 v13; // r13@3
  void *v14; // rax@3
  __int64 v15; // rax@3
  __int64 v16; // r15@3
  void *v17; // rax@3
  __int64 v18; // rax@3
  __int64 v19; // rbx@3

  v2 = objc_msgSend(a2, (const char *)*(&paCheckindevicei + 19), a1);
  LODWORD(v3) = objc_retainAutoreleasedReturnValue(v2);
  v4 = v3;
  v5 = (const char *)*(&paCheckindevicei + 2);
  if ( !objc_msgSend(v3, (const char *)*(&paCheckindevicei + 2)) )
  {
    objc_release(v4);
    goto LABEL_5;
  }
  v6 = objc_msgSend(a2, (const char *)*(&paCheckindevicei + 20));
  LODWORD(v7) = objc_retainAutoreleasedReturnValue(v6);
  v8 = v7;
  v9 = objc_msgSend(v7, v5);
  objc_release(v8);
  objc_release(v4);
  if ( !v9 )
  {
LABEL_5:
    v19 = 0LL;
    return objc_autoreleaseReturnValue(v19);
  }
  v10 = *(&off_B68 + 1);
  v11 = objc_msgSend(a2, (const char *)*(&paCheckindevicei + 19));
  LODWORD(v12) = objc_retainAutoreleasedReturnValue(v11);
  v13 = v12;
  v14 = objc_msgSend(a2, (const char *)*(&paCheckindevicei + 20));
  LODWORD(v15) = objc_retainAutoreleasedReturnValue(v14);
  v16 = v15;
  v17 = objc_msgSend(v10, (const char *)*(&paCheckindevicei + 21), &stru_808 + 1, v13, &stru_808, v15);
  LODWORD(v18) = objc_retainAutoreleasedReturnValue(v17);
  v19 = v18;
  objc_release(v16);
  objc_release(v13);
  return objc_autoreleaseReturnValue(v19);
}
// 808: using guessed type __CFString stru_808;
// A98: using guessed type __int64 (__fastcall *paCheckindevicei)();
// B68: using guessed type void *off_B68;
// 3BF0: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 3C10: using guessed type int (__fastcall *objc_release)(_QWORD);
// 3C20: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000750) ----------------------------------------------------
void *__fastcall _FIRInstanceIDCheckinPreferences_Internal__checkinDeviceIDFromKeychainContent__(void *a1, __int64 a2, __int64 a3)
{
  return objc_msgSend(a1, (const char *)*(&paCheckindevicei + 22), a3);
}
// A98: using guessed type __int64 (__fastcall *paCheckindevicei)();

//----- (0000000000000764) ----------------------------------------------------
void *__fastcall _FIRInstanceIDCheckinPreferences_Internal__checkinSecretFromKeychainContent__(void *a1, __int64 a2, __int64 a3)
{
  return objc_msgSend(a1, (const char *)*(&paCheckindevicei + 22), a3);
}
// A98: using guessed type __int64 (__fastcall *paCheckindevicei)();

//----- (000000000000077B) ----------------------------------------------------
int __fastcall _FIRInstanceIDCheckinPreferences_Internal__checkinKeychainContent_forIndex__(__int64 a1, __int64 a2, void *a3, unsigned int a4)
{
  unsigned int v4; // ebx@1
  void *v5; // rax@1
  void *v6; // rax@1
  void *v7; // r14@1
  void *v8; // rax@3
  __int64 v9; // rax@3
  __int64 v10; // rbx@3

  v4 = a4;
  v5 = objc_msgSend(a3, (const char *)*(&paCheckindevicei + 23), &stru_808);
  LODWORD(v6) = objc_retainAutoreleasedReturnValue(v5);
  v7 = v6;
  if ( v4 > 1 || objc_msgSend(v6, (const char *)*(&paCheckindevicei + 24)) != (char *)&loc_1 + 1 )
  {
    v10 = 0LL;
  }
  else
  {
    v8 = objc_msgSend(v7, (const char *)*(&paCheckindevicei + 25), (signed int)v4);
    LODWORD(v9) = objc_retainAutoreleasedReturnValue(v8);
    v10 = v9;
  }
  objc_release(v7);
  return objc_autoreleaseReturnValue(v10);
}
// 808: using guessed type __CFString stru_808;
// A98: using guessed type __int64 (__fastcall *paCheckindevicei)();
// 3BF0: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 3C10: using guessed type int (__fastcall *objc_release)(_QWORD);
// 3C20: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

// ALL OK, 8 function(s) have been successfully decompiled
