/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2015 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int __fastcall FIRInstanceIDRegisterServerForType(int a1);
__CFString *FIRInstanceIDRegisterServer();
__int64 __fastcall FIRInstanceIDCurrentTimestampInSeconds(double a1);
__int64 __fastcall FIRInstanceIDCurrentTimestampInMilliseconds(double a1);
// int __usercall FIRInstanceIDCurrentAppVersion@<eax>(__int64 a1@<rax>);
// int __usercall FIRInstanceIDAppIdentifier@<eax>(__int64 a1@<rax>);
int FIRInstanceIDDeviceModel();
int FIRInstanceIDOperatingSystemVersion();
bool __fastcall FIRInstanceIDIsValidGCMScope(void *a1);
void *__fastcall FIRInstanceIDIsValidDefaultScope(void *a1);
int __fastcall FIRInstanceIDStringForAPNSDeviceToken(__int64 a1);
int __fastcall FIRInstanceIDAPNSTupleStringForTokenAndServerType(__int64 a1, char a2);
// int __usercall FIRInstanceIDCurrentGCMVersion@<eax>(__int64 a1@<rax>);
// int __usercall FIRInstanceIDCurrentLocale@<eax>(__int64 a1@<rax>);
// int __usercall __FIRInstanceIDRetrieveEnvironmentInfoFromFirebaseCore_block_invoke@<eax>(__int64 a1@<rax>);
// int __fastcall FIRInstanceIDSharedLogger(_QWORD); weak
// int __fastcall NSClassFromString(_QWORD); weak
// int __fastcall NSLog(_QWORD); weak
// int __fastcall NSSelectorFromString(_QWORD); weak
// int __fastcall dispatch_once(_QWORD, _QWORD); weak
// int __fastcall objc_autoreleaseReturnValue(_QWORD); weak
// void *objc_msgSend(void *, const char *, ...); idb
// int __fastcall objc_retainAutorelease(_QWORD); weak
// int __fastcall objc_retainAutoreleaseReturnValue(_QWORD); weak
// int __fastcall objc_retainAutoreleasedReturnValue(_QWORD); weak

//-------------------------------------------------------------------------
// Data declarations

char aS_[3] = "s_"; // weak
__CFString cfstr_S_ = { &__CFConstantStringClassReference, 1992LL, "s_", 2LL }; // weak
void *off_C70 = &OBJC_CLASS___NSDate; // weak
__int64 (__fastcall *paDate)() = &aDate; // weak
void *__block_literal_global = &_NSConcreteGlobalBlock; // weak
__int64 hardwareDeviceModel; // weak
__int64 operatingSystemVersion; // weak
__int64 FIRInstanceIDRetrieveEnvironmentInfoFromFirebaseCore_onceToken; // weak
// extern _UNKNOWN OBJC_CLASS___NSDate; weak
// extern _UNKNOWN kFIRInstanceIDDefaultTokenScope; weak
// extern _UNKNOWN kFIRInstanceIDScopeFirebaseMessaging; weak
// extern int (__fastcall *objc_release)(_QWORD); weak
// extern int (__fastcall *objc_retain)(_QWORD); weak


//----- (0000000000000000) ----------------------------------------------------
int __fastcall FIRInstanceIDRegisterServerForType(int a1)
{
  __CFString *v1; // rbx@3

  if ( a1 == 1 )
  {
    v1 = &cfstr_S_ + 6;
  }
  else
  {
    if ( a1 )
    {
      NSLog(&cfstr_S_ + 7);
      BUG();
    }
    v1 = &cfstr_S_ + 5;
  }
  objc_retain(v1);
  return objc_autoreleaseReturnValue(v1);
}
// A10: using guessed type __CFString cfstr_S_;
// 4A80: using guessed type int __fastcall NSLog(_QWORD);
// 4AE0: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 4AF8: using guessed type int (__fastcall *objc_retain)(_QWORD);

//----- (0000000000000046) ----------------------------------------------------
__CFString *FIRInstanceIDRegisterServer()
{
  objc_retainAutorelease(&cfstr_S_ + 5);
  objc_retainAutorelease(&cfstr_S_ + 5);
  return &cfstr_S_ + 5;
}
// A10: using guessed type __CFString cfstr_S_;
// 4B00: using guessed type int __fastcall objc_retainAutorelease(_QWORD);

//----- (000000000000006D) ----------------------------------------------------
__int64 __fastcall FIRInstanceIDCurrentTimestampInSeconds(double a1)
{
  void *v1; // rax@1
  void *v2; // rax@1
  void *v3; // rbx@1

  v1 = objc_msgSend(&OBJC_CLASS___NSDate, (const char *)paDate);
  LODWORD(v2) = objc_retainAutoreleasedReturnValue(v1);
  v3 = v2;
  objc_msgSend(v2, (const char *)*(&paDate + 1));
  objc_release(v3);
  return (unsigned int)(signed int)floor(a1);
}
// DE8: using guessed type __int64 (__fastcall *paDate)();
// 4AF0: using guessed type int (__fastcall *objc_release)(_QWORD);
// 4B10: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (00000000000000BA) ----------------------------------------------------
__int64 __fastcall FIRInstanceIDCurrentTimestampInMilliseconds(double a1)
{
  return (unsigned int)(signed int)floor((double)(signed int)FIRInstanceIDCurrentTimestampInSeconds(a1) * 1000.0);
}

//----- (00000000000000D7) ----------------------------------------------------
int __usercall FIRInstanceIDCurrentAppVersion@<eax>(__int64 a1@<rax>)
{
  void *v1; // rax@1
  void *v2; // rax@1
  void *v3; // r15@1
  void *v4; // rax@1
  void *v5; // rax@1
  void *v6; // rbx@1
  void *v7; // rax@1
  void *v8; // rax@1
  void *v9; // r14@1
  __CFString *v10; // rax@2
  __CFString *v11; // rbx@2

  v1 = objc_msgSend(*(&off_C70 + 1), (const char *)*(&paDate + 2), a1);
  LODWORD(v2) = objc_retainAutoreleasedReturnValue(v1);
  v3 = v2;
  v4 = objc_msgSend(v2, (const char *)*(&paDate + 3));
  LODWORD(v5) = objc_retainAutoreleasedReturnValue(v4);
  v6 = v5;
  v7 = objc_msgSend(v5, (const char *)*(&paDate + 4), &cfstr_S_ + 8);
  LODWORD(v8) = objc_retainAutoreleasedReturnValue(v7);
  v9 = v8;
  objc_release(v6);
  objc_release(v3);
  if ( objc_msgSend(v9, (const char *)*(&paDate + 5)) )
  {
    LODWORD(v10) = objc_retain(v9);
    v11 = v10;
  }
  else
  {
    v11 = &cfstr_S_ + 9;
    objc_retain(&cfstr_S_ + 9);
  }
  objc_release(v9);
  return objc_autoreleaseReturnValue(v11);
}
// A10: using guessed type __CFString cfstr_S_;
// C70: using guessed type void *off_C70;
// DE8: using guessed type __int64 (__fastcall *paDate)();
// 4AE0: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 4AF0: using guessed type int (__fastcall *objc_release)(_QWORD);
// 4AF8: using guessed type int (__fastcall *objc_retain)(_QWORD);
// 4B10: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (00000000000001A1) ----------------------------------------------------
int __usercall FIRInstanceIDAppIdentifier@<eax>(__int64 a1@<rax>)
{
  void *v1; // rax@1
  void *v2; // rax@1
  void *v3; // rbx@1
  void *v4; // rax@1
  void *v5; // rax@1
  void *v6; // r14@1
  __CFString *v7; // rax@2
  __CFString *v8; // rbx@2
  __int64 v9; // rax@3
  void *v10; // rax@3
  void *v11; // rbx@3

  v1 = objc_msgSend(*(&off_C70 + 1), (const char *)*(&paDate + 2), a1);
  LODWORD(v2) = objc_retainAutoreleasedReturnValue(v1);
  v3 = v2;
  v4 = objc_msgSend(v2, (const char *)*(&paDate + 6));
  LODWORD(v5) = objc_retainAutoreleasedReturnValue(v4);
  v6 = v5;
  objc_release(v3);
  if ( objc_msgSend(v6, (const char *)*(&paDate + 5)) )
  {
    LODWORD(v7) = objc_retain(v6);
    v8 = v7;
  }
  else
  {
    LODWORD(v9) = FIRInstanceIDSharedLogger(v6);
    LODWORD(v10) = objc_retainAutoreleasedReturnValue(v9);
    v11 = v10;
    objc_msgSend(v10, (const char *)*(&paDate + 7), &aS_[208], 18000LL, &cfstr_S_ + 10, v6);
    objc_release(v11);
    v8 = &cfstr_S_ + 9;
    objc_retain(&cfstr_S_ + 9);
  }
  objc_release(v6);
  return objc_autoreleaseReturnValue(v8);
}
// A10: using guessed type __CFString cfstr_S_;
// C70: using guessed type void *off_C70;
// DE8: using guessed type __int64 (__fastcall *paDate)();
// 4A70: using guessed type int __fastcall FIRInstanceIDSharedLogger(_QWORD);
// 4AE0: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 4AF0: using guessed type int (__fastcall *objc_release)(_QWORD);
// 4AF8: using guessed type int (__fastcall *objc_retain)(_QWORD);
// 4B10: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (000000000000027B) ----------------------------------------------------
int FIRInstanceIDDeviceModel()
{
  if ( FIRInstanceIDRetrieveEnvironmentInfoFromFirebaseCore_onceToken != -1 )
    dispatch_once(&FIRInstanceIDRetrieveEnvironmentInfoFromFirebaseCore_onceToken, &__block_literal_global);
  return objc_retainAutoreleaseReturnValue(hardwareDeviceModel);
}
// EB0: using guessed type void *__block_literal_global;
// 4A58: using guessed type __int64 hardwareDeviceModel;
// 4A68: using guessed type __int64 FIRInstanceIDRetrieveEnvironmentInfoFromFirebaseCore_onceToken;
// 4AC8: using guessed type int __fastcall dispatch_once(_QWORD, _QWORD);
// 4B08: using guessed type int __fastcall objc_retainAutoreleaseReturnValue(_QWORD);

//----- (00000000000002AB) ----------------------------------------------------
int FIRInstanceIDOperatingSystemVersion()
{
  if ( FIRInstanceIDRetrieveEnvironmentInfoFromFirebaseCore_onceToken != -1 )
    dispatch_once(&FIRInstanceIDRetrieveEnvironmentInfoFromFirebaseCore_onceToken, &__block_literal_global);
  return objc_retainAutoreleaseReturnValue(operatingSystemVersion);
}
// EB0: using guessed type void *__block_literal_global;
// 4A60: using guessed type __int64 operatingSystemVersion;
// 4A68: using guessed type __int64 FIRInstanceIDRetrieveEnvironmentInfoFromFirebaseCore_onceToken;
// 4AC8: using guessed type int __fastcall dispatch_once(_QWORD, _QWORD);
// 4B08: using guessed type int __fastcall objc_retainAutoreleaseReturnValue(_QWORD);

//----- (00000000000002DB) ----------------------------------------------------
bool __fastcall FIRInstanceIDIsValidGCMScope(void *a1)
{
  return objc_msgSend(a1, (const char *)*(&paDate + 8), *kFIRInstanceIDScopeFirebaseMessaging, 1LL) == 0LL;
}
// DE8: using guessed type __int64 (__fastcall *paDate)();

//----- (0000000000000303) ----------------------------------------------------
void *__fastcall FIRInstanceIDIsValidDefaultScope(void *a1)
{
  return objc_msgSend(a1, (const char *)*(&paDate + 9), *kFIRInstanceIDDefaultTokenScope);
}
// DE8: using guessed type __int64 (__fastcall *paDate)();

//----- (000000000000031F) ----------------------------------------------------
int __fastcall FIRInstanceIDStringForAPNSDeviceToken(__int64 a1)
{
  __int64 v1; // rax@1
  __int64 v2; // rbx@1
  void *v3; // rax@1
  void *v4; // rax@1
  void *v5; // rax@1
  void *v6; // rbx@1
  const char *v7; // r13@2
  const char *v8; // r15@2
  signed __int64 v9; // r14@2
  _BYTE *v11; // [sp+8h] [bp-38h]@1
  void *v12; // [sp+10h] [bp-30h]@1

  LODWORD(v1) = objc_retain(a1);
  v2 = v1;
  v3 = objc_msgSend(*(&off_C70 + 2), (const char *)*(&paDate + 10));
  LODWORD(v4) = objc_retainAutoreleasedReturnValue(v3);
  v12 = v4;
  LODWORD(v5) = objc_retainAutorelease(v2);
  v6 = v5;
  v11 = objc_msgSend(v5, (const char *)*(&paDate + 11));
  if ( (signed int)objc_msgSend(v6, (const char *)*(&paDate + 5)) > 0 )
  {
    v7 = (const char *)*(&paDate + 12);
    v8 = (const char *)*(&paDate + 5);
    v9 = 0LL;
    do
      objc_msgSend(v12, v7, &cfstr_S_ + 11, v11[v9++]);
    while ( v9 < (signed int)objc_msgSend(v6, v8) );
  }
  objc_release(v6);
  return objc_autoreleaseReturnValue(v12);
}
// A10: using guessed type __CFString cfstr_S_;
// C70: using guessed type void *off_C70;
// DE8: using guessed type __int64 (__fastcall *paDate)();
// 4AE0: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 4AF0: using guessed type int (__fastcall *objc_release)(_QWORD);
// 4AF8: using guessed type int (__fastcall *objc_retain)(_QWORD);
// 4B00: using guessed type int __fastcall objc_retainAutorelease(_QWORD);
// 4B10: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (00000000000003F2) ----------------------------------------------------
int __fastcall FIRInstanceIDAPNSTupleStringForTokenAndServerType(__int64 a1, char a2)
{
  __CFString *v2; // rbx@1
  __int64 v3; // rax@3
  __int64 v4; // r14@3
  __int64 v5; // rax@3
  __int64 v6; // r15@3
  __int64 v7; // rax@3
  __int64 v8; // rbx@3
  __int64 v9; // rax@3
  __int64 v10; // r14@3
  void *v11; // rbx@3
  __int64 v12; // rax@3
  __int64 v13; // rbx@3

  v2 = &cfstr_S_ + 1;
  if ( a2 )
    v2 = &cfstr_S_;
  LODWORD(v3) = objc_retain(a1);
  v4 = v3;
  LODWORD(v5) = objc_retain(v2);
  v6 = v5;
  LODWORD(v7) = FIRInstanceIDStringForAPNSDeviceToken(v4);
  v8 = v7;
  objc_release(v4);
  LODWORD(v9) = objc_retainAutoreleasedReturnValue(v8);
  v10 = v9;
  v11 = objc_msgSend(*(&off_C70 + 3), (const char *)*(&paDate + 13), &cfstr_S_ + 12, v6, v9);
  objc_release(v6);
  LODWORD(v12) = objc_retainAutoreleasedReturnValue(v11);
  v13 = v12;
  objc_release(v10);
  return objc_autoreleaseReturnValue(v13);
}
// A10: using guessed type __CFString cfstr_S_;
// C70: using guessed type void *off_C70;
// DE8: using guessed type __int64 (__fastcall *paDate)();
// 4AE0: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 4AF0: using guessed type int (__fastcall *objc_release)(_QWORD);
// 4AF8: using guessed type int (__fastcall *objc_retain)(_QWORD);
// 4B10: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000498) ----------------------------------------------------
int __usercall FIRInstanceIDCurrentGCMVersion@<eax>(__int64 a1@<rax>)
{
  __int64 v1; // ST00_8@1
  void *v2; // rax@1
  void *v3; // r14@1
  __int64 v4; // rax@1
  __int64 v5; // rbx@1
  void *v6; // rax@2
  void *v7; // rax@2
  void *v8; // rbx@2
  void *v9; // rax@2

  v1 = a1;
  LODWORD(v2) = NSClassFromString(&cfstr_S_ + 2);
  v3 = v2;
  LODWORD(v4) = NSSelectorFromString(&cfstr_S_ + 3);
  v5 = v4;
  if ( !(unsigned __int8)objc_msgSend(v3, (const char *)*(&paDate + 14), v4, v1) )
    goto LABEL_4;
  v6 = objc_msgSend(v3, (const char *)*(&paDate + 15), v5);
  LODWORD(v7) = objc_retainAutoreleasedReturnValue(v6);
  v8 = v7;
  v9 = objc_msgSend(*(&off_C70 + 3), (const char *)*(&paDate + 16));
  if ( !(unsigned __int8)objc_msgSend(v8, (const char *)*(&paDate + 17), v9) )
  {
    objc_release(v8);
LABEL_4:
    v8 = 0LL;
  }
  return objc_autoreleaseReturnValue(v8);
}
// A10: using guessed type __CFString cfstr_S_;
// C70: using guessed type void *off_C70;
// DE8: using guessed type __int64 (__fastcall *paDate)();
// 4A78: using guessed type int __fastcall NSClassFromString(_QWORD);
// 4A88: using guessed type int __fastcall NSSelectorFromString(_QWORD);
// 4AE0: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 4AF0: using guessed type int (__fastcall *objc_release)(_QWORD);
// 4B10: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (000000000000053B) ----------------------------------------------------
int __usercall FIRInstanceIDCurrentLocale@<eax>(__int64 a1@<rax>)
{
  __int64 v1; // ST00_8@1
  void *v2; // rax@1
  void *v3; // r14@1
  __int64 v4; // rax@1
  __int64 v5; // rbx@1
  void *v6; // rax@2
  void *v7; // rax@2
  void *v8; // r14@2
  void *v9; // rax@2
  void *v10; // rax@4
  void *v11; // rax@4
  void *v12; // rbx@4
  void *v13; // rax@4
  void *v14; // rax@4

  v1 = a1;
  LODWORD(v2) = NSClassFromString(&cfstr_S_ + 2);
  v3 = v2;
  LODWORD(v4) = NSSelectorFromString(&cfstr_S_ + 4);
  v5 = v4;
  if ( !(unsigned __int8)objc_msgSend(v3, (const char *)*(&paDate + 14), v4, v1) )
    goto LABEL_4;
  v6 = objc_msgSend(v3, (const char *)*(&paDate + 15), v5);
  LODWORD(v7) = objc_retainAutoreleasedReturnValue(v6);
  v8 = v7;
  v9 = objc_msgSend(*(&off_C70 + 3), (const char *)*(&paDate + 16));
  if ( !(unsigned __int8)objc_msgSend(v8, (const char *)*(&paDate + 17), v9) )
  {
    objc_release(v8);
LABEL_4:
    v10 = objc_msgSend(*(&off_C70 + 4), (const char *)*(&paDate + 18));
    LODWORD(v11) = objc_retainAutoreleasedReturnValue(v10);
    v12 = v11;
    v13 = objc_msgSend(v11, (const char *)*(&paDate + 19));
    LODWORD(v14) = objc_retainAutoreleasedReturnValue(v13);
    v8 = v14;
    objc_release(v12);
  }
  return objc_autoreleaseReturnValue(v8);
}
// A10: using guessed type __CFString cfstr_S_;
// C70: using guessed type void *off_C70;
// DE8: using guessed type __int64 (__fastcall *paDate)();
// 4A78: using guessed type int __fastcall NSClassFromString(_QWORD);
// 4A88: using guessed type int __fastcall NSSelectorFromString(_QWORD);
// 4AE0: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 4AF0: using guessed type int (__fastcall *objc_release)(_QWORD);
// 4B10: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000620) ----------------------------------------------------
int __usercall __FIRInstanceIDRetrieveEnvironmentInfoFromFirebaseCore_block_invoke@<eax>(__int64 a1@<rax>)
{
  void *v1; // rax@1
  void *v2; // r15@1
  __int64 v3; // rax@2
  __int64 v4; // rbx@2
  const char *v5; // r14@2
  void *v6; // rax@3
  __int64 v7; // rax@3
  __int64 v8; // rdi@3
  __int64 v9; // rax@4
  void *v10; // rax@4
  void *v11; // rbx@4
  const char *v12; // rsi@4
  char *v13; // rdx@4
  __CFString *v14; // r8@4
  signed __int64 v15; // rcx@4
  __int64 v16; // rax@5
  void *v17; // rax@5
  __int64 v18; // rbx@5
  __int64 v19; // rax@6
  __int64 v20; // rbx@6
  void *v21; // rax@7
  __int64 v22; // rax@7
  __int64 v23; // rdi@7
  __int64 v24; // rax@8
  void *v25; // rax@8
  __int64 v27; // [sp-8h] [bp-20h]@1

  v27 = a1;
  LODWORD(v1) = NSClassFromString(&cfstr_S_ + 13);
  v2 = v1;
  if ( !v1 )
  {
    LODWORD(v9) = FIRInstanceIDSharedLogger(&cfstr_S_ + 13);
    LODWORD(v10) = objc_retainAutoreleasedReturnValue(v9);
    v11 = v10;
    v12 = (const char *)*(&paDate + 7);
    v13 = &aS_[315];
    v14 = &cfstr_S_ + 14;
    v15 = 18001LL;
LABEL_9:
    objc_msgSend(v11, v12, v13, v15, v14, v27);
    v23 = (__int64)v11;
    return objc_release(v23);
  }
  LODWORD(v3) = NSSelectorFromString(&cfstr_S_ + 15);
  v4 = v3;
  v5 = (const char *)*(&paDate + 14);
  if ( (unsigned __int8)objc_msgSend(v2, (const char *)*(&paDate + 14), v3, v27) )
  {
    v6 = objc_msgSend(v2, (const char *)*(&paDate + 15), v4);
    LODWORD(v7) = objc_retainAutoreleasedReturnValue(v6);
    v8 = hardwareDeviceModel;
    hardwareDeviceModel = v7;
  }
  else
  {
    LODWORD(v16) = FIRInstanceIDSharedLogger(v2);
    LODWORD(v17) = objc_retainAutoreleasedReturnValue(v16);
    v18 = (__int64)v17;
    objc_msgSend(v17, (const char *)*(&paDate + 20), &aS_[315], 18002LL, &cfstr_S_ + 16);
    v8 = v18;
  }
  objc_release(v8);
  LODWORD(v19) = NSSelectorFromString(&cfstr_S_ + 17);
  v20 = v19;
  if ( !(unsigned __int8)objc_msgSend(v2, v5, v19) )
  {
    LODWORD(v24) = FIRInstanceIDSharedLogger(v2);
    LODWORD(v25) = objc_retainAutoreleasedReturnValue(v24);
    v11 = v25;
    v12 = (const char *)*(&paDate + 20);
    v13 = &aS_[315];
    v14 = &cfstr_S_ + 18;
    v15 = 18003LL;
    goto LABEL_9;
  }
  v21 = objc_msgSend(v2, (const char *)*(&paDate + 15), v20);
  LODWORD(v22) = objc_retainAutoreleasedReturnValue(v21);
  v23 = operatingSystemVersion;
  operatingSystemVersion = v22;
  return objc_release(v23);
}
// A10: using guessed type __CFString cfstr_S_;
// DE8: using guessed type __int64 (__fastcall *paDate)();
// 4A58: using guessed type __int64 hardwareDeviceModel;
// 4A60: using guessed type __int64 operatingSystemVersion;
// 4A70: using guessed type int __fastcall FIRInstanceIDSharedLogger(_QWORD);
// 4A78: using guessed type int __fastcall NSClassFromString(_QWORD);
// 4A88: using guessed type int __fastcall NSSelectorFromString(_QWORD);
// 4AF0: using guessed type int (__fastcall *objc_release)(_QWORD);
// 4B10: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

// ALL OK, 15 function(s) have been successfully decompiled
