/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2015 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void *__fastcall -[FIRInstanceIDCheckinService init](__int64 a1);
void __cdecl -[FIRInstanceIDCheckinService dealloc](struct FIRInstanceIDCheckinService *self, SEL);
void __cdecl -[FIRInstanceIDCheckinService checkinWithExistingCheckin:completion:](struct FIRInstanceIDCheckinService *self, SEL, id, id);
__int64 __fastcall __69__FIRInstanceIDCheckinService_checkinWithExistingCheckin_completion___block_invoke(__int64 a1, __int64 a2, __int64 a3, __int64 a4);
void __fastcall __copy_helper_block_(__int64 a1, __int64 a2);
int __fastcall __destroy_helper_block_(__int64 a1);
void __cdecl -[FIRInstanceIDCheckinService stopFetching](struct FIRInstanceIDCheckinService *self, SEL);
id __cdecl -[FIRInstanceIDCheckinService checkinParametersWithExistingCheckin:](struct FIRInstanceIDCheckinService *self, SEL, id);
void __cdecl +[FIRInstanceIDCheckinService setCheckinTestBlock:](struct FIRInstanceIDCheckinService *self, SEL, id);
id __cdecl -[FIRInstanceIDCheckinService session](struct FIRInstanceIDCheckinService *self, SEL);
void __cdecl -[FIRInstanceIDCheckinService setSession:](struct FIRInstanceIDCheckinService *self, SEL, id);
void __cdecl -[FIRInstanceIDCheckinService .cxx_destruct](struct FIRInstanceIDCheckinService *self, SEL);
// int __fastcall FIRInstanceIDCurrentLocale(_QWORD); weak
// int __fastcall FIRInstanceIDCurrentTimestampInMilliseconds(_QWORD); weak
// int __fastcall FIRInstanceIDDeviceModel(_QWORD, _QWORD); weak
// int __fastcall FIRInstanceIDOperatingSystemVersion(_QWORD); weak
// int __fastcall FIRInstanceIDSharedLogger(_QWORD); weak
// void __cdecl _Block_object_assign(void *, const void *, const int);
// u_int32_t arc4random(void);
// int __fastcall objc_autoreleaseReturnValue(_QWORD); weak
// int __fastcall objc_enumerationMutation(_QWORD); weak
// void *objc_msgSend(void *, const char *, ...); idb
// void *objc_msgSendSuper2(void *, const char *, ...); idb
// int __fastcall objc_release(_QWORD); weak
// int __fastcall objc_retain(_QWORD); weak
// int __fastcall objc_retainAutoreleasedReturnValue(_QWORD); weak
// int __fastcall objc_retainBlock(_QWORD); weak
// int __fastcall objc_storeStrong(_QWORD, _QWORD); weak

//-------------------------------------------------------------------------
// Data declarations

char aHttpsDevicePro[51] = "https://device-provisioning.googleapis.com/checkin"; // weak
__CFString cfstr_HttpsDevicePro =
{
  &__CFConstantStringClassReference,
  1992LL,
  "https://device-provisioning.googleapis.com/checkin",
  50LL
}; // weak
_UNKNOWN __block_descriptor_tmp; // weak
void *classRef_FIRInstanceIDCheckinService = &OBJC_CLASS___FIRInstanceIDCheckinService; // weak
char *selRef_init = "init"; // weak
void *classRef_NSURLSessionConfiguration = &OBJC_CLASS___NSURLSessionConfiguration; // weak
__int64 testBlock; // weak
// extern void *_NSConcreteStackBlock[32];
// extern _UNKNOWN __stack_chk_guard; weak


//----- (0000000000000000) ----------------------------------------------------
void *__fastcall -[FIRInstanceIDCheckinService init](__int64 a1)
{
  void *v1; // rbx@1
  void *v2; // rax@2
  void *v3; // rax@2
  void *v4; // r14@2
  void *v5; // rax@2
  __int64 v6; // rax@2
  __int64 v7; // rdi@2
  __int64 v9; // [sp+8h] [bp-38h]@1
  void *v10; // [sp+10h] [bp-30h]@1

  v9 = a1;
  v10 = classRef_FIRInstanceIDCheckinService;
  v1 = objc_msgSendSuper2(&v9, selRef_init);
  if ( v1 )
  {
    v2 = objc_msgSend(classRef_NSURLSessionConfiguration, *(&selRef_init + 1));
    LODWORD(v3) = objc_retainAutoreleasedReturnValue(v2);
    v4 = v3;
    objc_msgSend(v3, *(&selRef_init + 2), COERCE_DOUBLE(4633641066610819072LL));
    objc_msgSend(v4, *(&selRef_init + 3), 1LL);
    v5 = objc_msgSend(*(&classRef_NSURLSessionConfiguration + 1), *(&selRef_init + 4), v4);
    LODWORD(v6) = objc_retainAutoreleasedReturnValue(v5);
    v7 = *((_QWORD *)v1 + 1);
    *((_QWORD *)v1 + 1) = v6;
    objc_release(v7);
    objc_msgSend(*((void **)v1 + 1), *(&selRef_init + 5), &cfstr_HttpsDevicePro + 8);
    objc_release(v4);
  }
  return v1;
}
// 1720: using guessed type __CFString cfstr_HttpsDevicePro;
// 1D40: using guessed type void *classRef_FIRInstanceIDCheckinService;
// 2148: using guessed type char *selRef_init;
// 22B0: using guessed type void *classRef_NSURLSessionConfiguration;
// 9070: using guessed type int __fastcall objc_release(_QWORD);
// 9080: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (00000000000000EA) ----------------------------------------------------
// FIRInstanceIDCheckinService - (void)dealloc
void __cdecl -[FIRInstanceIDCheckinService dealloc](struct FIRInstanceIDCheckinService *self, SEL a2)
{
  struct FIRInstanceIDCheckinService *v2; // r14@1
  __int64 v3; // rdi@1
  void *v4; // rax@1
  void *v5; // rax@1
  void *v6; // rbx@1
  struct FIRInstanceIDCheckinService *v7; // [sp+0h] [bp-30h]@1
  void *v8; // [sp+8h] [bp-28h]@1

  v2 = self;
  v3 = testBlock;
  testBlock = 0LL;
  objc_release(v3);
  v4 = objc_msgSend(v2, *(&selRef_init + 6));
  LODWORD(v5) = objc_retainAutoreleasedReturnValue(v4);
  v6 = v5;
  objc_msgSend(v5, *(&selRef_init + 7));
  objc_release(v6);
  v7 = v2;
  v8 = classRef_FIRInstanceIDCheckinService;
  objc_msgSendSuper2(&v7, *(&selRef_init + 8), v2, classRef_FIRInstanceIDCheckinService);
}
// 1D40: using guessed type void *classRef_FIRInstanceIDCheckinService;
// 2148: using guessed type char *selRef_init;
// 8F70: using guessed type __int64 testBlock;
// 9070: using guessed type int __fastcall objc_release(_QWORD);
// 9080: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000175) ----------------------------------------------------
// FIRInstanceIDCheckinService - (void)checkinWithExistingCheckin:(id) completion:(id) 
void __cdecl -[FIRInstanceIDCheckinService checkinWithExistingCheckin:completion:](struct FIRInstanceIDCheckinService *self, SEL a2, id a3, id a4)
{
  id v4; // r14@1
  struct FIRInstanceIDCheckinService *v5; // r13@1
  __int64 v6; // rax@1
  __int64 v7; // r12@1
  __int64 v8; // rax@1
  void *v9; // rax@1
  __int64 v10; // rax@1
  void *v11; // rdi@1
  const char *v12; // rsi@1
  void *v13; // rax@1
  void *v14; // rax@1
  void *v15; // r15@1
  const char *v16; // rsi@1
  void *v17; // rbx@1
  struct FIRInstanceIDCheckinService *v18; // rax@1
  struct FIRInstanceIDCheckinService *v19; // r12@1
  void *v20; // rax@1
  __int64 v21; // rax@1
  __int64 v22; // rbx@1
  const char *v23; // rsi@1
  __int64 v24; // rax@1
  __int64 v25; // rax@1
  __int64 v26; // r13@1
  __int64 v27; // rax@2
  void *v28; // rax@2
  void *v29; // rbx@2
  void *v30; // rax@3
  void *v31; // rax@3
  void *v32; // rbx@3
  void *v33; // rax@3
  void *v34; // rax@3
  void *v35; // r12@3
  void *v36; // rdi@3
  void *v37; // [sp+0h] [bp-70h]@1
  signed int v38; // [sp+8h] [bp-68h]@1
  int v39; // [sp+Ch] [bp-64h]@1
  __int64 (__fastcall *v40)(__int64, __int64, __int64, __int64); // [sp+10h] [bp-60h]@1
  void *v41; // [sp+18h] [bp-58h]@1
  __int64 v42; // [sp+20h] [bp-50h]@1
  __int64 v43; // [sp+28h] [bp-48h]@1
  __int64 v44; // [sp+30h] [bp-40h]@1
  __int64 v45; // [sp+38h] [bp-38h]@1
  struct FIRInstanceIDCheckinService *v46; // [sp+40h] [bp-30h]@1

  v4 = a4;
  v5 = self;
  LODWORD(v6) = objc_retain(a3);
  v7 = v6;
  LODWORD(v8) = objc_retain(v4);
  v45 = v8;
  v9 = objc_msgSend(*(&classRef_NSURLSessionConfiguration + 2), *(&selRef_init + 9), &cfstr_HttpsDevicePro);
  LODWORD(v10) = objc_retainAutoreleasedReturnValue(v9);
  v11 = *(&classRef_NSURLSessionConfiguration + 3);
  v12 = *(&selRef_init + 10);
  v43 = v10;
  v13 = objc_msgSend(v11, v12, v10);
  LODWORD(v14) = objc_retainAutoreleasedReturnValue(v13);
  v15 = v14;
  objc_msgSend(v14, *(&selRef_init + 11), &cfstr_HttpsDevicePro + 9, &cfstr_HttpsDevicePro + 10);
  v16 = *(&selRef_init + 12);
  v46 = v5;
  v17 = objc_msgSend(v5, v16, v7);
  objc_release(v7);
  LODWORD(v18) = objc_retainAutoreleasedReturnValue(v17);
  v19 = v18;
  v20 = objc_msgSend(*(&classRef_NSURLSessionConfiguration + 4), *(&selRef_init + 13), v18, 0LL, 0LL);
  LODWORD(v21) = objc_retainAutoreleasedReturnValue(v20);
  v22 = v21;
  objc_msgSend(v15, *(&selRef_init + 14), &cfstr_HttpsDevicePro + 11);
  v23 = *(&selRef_init + 15);
  v44 = v22;
  objc_msgSend(v15, v23, v22);
  v37 = _NSConcreteStackBlock[0];
  v38 = -1040187392;
  v39 = 0;
  v40 = __69__FIRInstanceIDCheckinService_checkinWithExistingCheckin_completion___block_invoke;
  v41 = &__block_descriptor_tmp;
  LODWORD(v24) = objc_retain(v45);
  v45 = v24;
  v42 = v24;
  LODWORD(v25) = objc_retainBlock(&v37);
  v26 = v25;
  if ( testBlock )
  {
    LODWORD(v27) = FIRInstanceIDSharedLogger(&v37);
    LODWORD(v28) = objc_retainAutoreleasedReturnValue(v27);
    v29 = v28;
    objc_msgSend(
      v28,
      *(&selRef_init + 17),
      &aHttpsDevicePro[753],
      7005LL,
      &cfstr_HttpsDevicePro + 26,
      v37,
      *(_QWORD *)&v38,
      v40,
      v41,
      v42,
      v43,
      v44,
      v45);
    objc_release(v29);
    (*(void (__fastcall **)(__int64, void *, __int64))(testBlock + 16))(testBlock, v15, v26);
  }
  else
  {
    v30 = objc_msgSend(v46, *(&selRef_init + 6), v37, *(_QWORD *)&v38, v40, v41, v42, v43, v44, v45);
    LODWORD(v31) = objc_retainAutoreleasedReturnValue(v30);
    v32 = v31;
    v33 = objc_msgSend(v31, *(&selRef_init + 32), v15, v26, v37, *(_QWORD *)&v38, v40, v41);
    LODWORD(v34) = objc_retainAutoreleasedReturnValue(v33);
    v46 = v19;
    v35 = v34;
    objc_release(v32);
    objc_msgSend(v35, *(&selRef_init + 33), v37, *(_QWORD *)&v38, v40, v41);
    v36 = v35;
    v19 = v46;
    objc_release(v36);
  }
  objc_release(v26);
  objc_release(v42);
  objc_release(v44);
  objc_release(v19);
  objc_release(v15);
  objc_release(v43);
  objc_release(v45);
}
// 1720: using guessed type __CFString cfstr_HttpsDevicePro;
// 2148: using guessed type char *selRef_init;
// 22B0: using guessed type void *classRef_NSURLSessionConfiguration;
// 8F70: using guessed type __int64 testBlock;
// 8FA0: using guessed type int __fastcall FIRInstanceIDSharedLogger(_QWORD);
// 9070: using guessed type int __fastcall objc_release(_QWORD);
// 9078: using guessed type int __fastcall objc_retain(_QWORD);
// 9080: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);
// 9088: using guessed type int __fastcall objc_retainBlock(_QWORD);

//----- (00000000000003C4) ----------------------------------------------------
__int64 __fastcall __69__FIRInstanceIDCheckinService_checkinWithExistingCheckin_completion___block_invoke(__int64 a1, __int64 a2, __int64 a3, __int64 a4)
{
  __int64 v4; // rbx@1
  __int64 v5; // rax@1
  __int64 v6; // r15@1
  void *v7; // rax@1
  void *v8; // r13@1
  __int64 v9; // rax@2
  void *v10; // rax@2
  void *v11; // rbx@2
  void *v12; // rax@2
  void *v13; // rdi@3
  const char *v14; // rsi@3
  void *v15; // rax@3
  void *v16; // rax@3
  void *v17; // rbx@3
  __int64 v18; // rdi@3
  void *v19; // rax@3
  void *v20; // r14@3
  __int64 v21; // rax@4
  void *v22; // rax@4
  void *v23; // r12@4
  void *v24; // rax@4
  void *v25; // r15@4
  __int64 v26; // rbx@4
  void *v27; // rax@5
  void *v28; // rax@5
  void *v29; // r14@5
  void *v30; // rax@5
  void *v31; // rax@5
  void *v32; // rax@5
  void *v33; // rax@5
  void *v34; // rbx@5
  void *v35; // rax@5
  __int64 v36; // rax@5
  __int64 v37; // r14@5
  const char *v38; // r12@6
  __int64 v39; // rax@6
  __int64 v40; // rax@6
  __int64 v41; // rbx@6
  __int64 v42; // rax@6
  __int64 v43; // r15@6
  __int64 v44; // rax@6
  __int64 v45; // r14@6
  __int64 v46; // rax@7
  void *v47; // rax@7
  void *v48; // r15@7
  void *v49; // rax@8
  __int64 v50; // rax@8
  __int64 v51; // rbx@8
  void (__fastcall *v52)(__int64); // rbx@8
  void *v53; // r13@10
  void *v54; // rax@10
  __CFString *v55; // rax@10
  __CFString *v56; // rbx@10
  __CFString *v57; // r15@10
  __CFString *v58; // rdi@10
  __int64 v59; // rax@12
  void *v60; // rax@12
  __CFString *v61; // rax@12
  __CFString *v62; // rbx@12
  __CFString *v63; // rdi@12
  __int64 v64; // rax@14
  __int64 v65; // r14@14
  __int64 v66; // rax@14
  void *v67; // rax@14
  void *v68; // rbx@14
  void *v69; // rax@14
  __CFString *v70; // rax@14
  __CFString *v71; // r14@14
  const char *v72; // rbx@16
  __int64 v73; // rax@16
  void *v74; // rax@16
  void *v75; // rax@16
  void *v76; // rdi@16
  void *(*v77)(void *, const char *, ...); // r13@16
  void *v78; // rax@16
  __int64 v79; // rax@16
  __int64 v80; // rsi@16
  const char *v81; // rax@16
  unsigned __int64 v82; // r14@18
  void *v83; // r12@21
  __int64 v84; // rax@21
  __int64 v85; // rax@21
  __int64 v86; // r15@21
  __int64 v87; // rax@22
  __int64 v88; // rax@22
  __int64 v89; // r13@22
  bool v90; // zf@22
  void *v91; // rax@23
  __int64 v92; // rax@23
  __int64 v93; // r15@23
  void *v94; // rax@23
  __int64 v95; // rax@23
  __int64 v96; // rbx@23
  const char *v97; // rax@25
  __int64 v98; // rax@26
  __int64 v99; // rax@26
  __int64 v100; // rbx@26
  __int64 v101; // rax@26
  __int64 v102; // rax@26
  void *(*v103)(void *, const char *, ...); // r14@26
  __int64 v104; // r13@26
  __int64 v105; // rax@26
  __int64 v106; // rax@26
  __int64 v107; // r15@26
  __int64 v108; // r14@26
  __int64 v109; // rdi@26
  __int128 v111; // [sp+0h] [bp-1D0h]@16
  __int128 v112; // [sp+10h] [bp-1C0h]@16
  __int128 v113; // [sp+20h] [bp-1B0h]@16
  __int128 v114; // [sp+30h] [bp-1A0h]@16
  __int64 v115; // [sp+48h] [bp-188h]@3
  __int64 v116; // [sp+50h] [bp-180h]@17
  const char *v117; // [sp+58h] [bp-178h]@18
  __int64 v118; // [sp+60h] [bp-170h]@3
  __int64 v119; // [sp+68h] [bp-168h]@5
  void *v120; // [sp+70h] [bp-160h]@10
  __int64 v121; // [sp+78h] [bp-158h]@6
  __int64 v122; // [sp+80h] [bp-150h]@12
  __int64 v123; // [sp+88h] [bp-148h]@14
  __int64 v124; // [sp+90h] [bp-140h]@16
  __int64 v125; // [sp+98h] [bp-138h]@16
  void *v126; // [sp+A0h] [bp-130h]@16
  __int64 v127; // [sp+A8h] [bp-128h]@3
  __int64 v128; // [sp+B0h] [bp-120h]@7
  void *v129; // [sp+B8h] [bp-118h]@3
  void *v130; // [sp+C0h] [bp-110h]@5
  const char *v131; // [sp+C8h] [bp-108h]@7
  char v132; // [sp+D0h] [bp-100h]@26
  __CFString *v133; // [sp+E0h] [bp-F0h]@26
  __int64 v134; // [sp+E8h] [bp-E8h]@26
  __int64 v135; // [sp+F8h] [bp-D8h]@26
  __int64 v136; // [sp+100h] [bp-D0h]@26
  __int64 v137; // [sp+108h] [bp-C8h]@26
  void *v138; // [sp+110h] [bp-C0h]@26
  __int64 v139; // [sp+118h] [bp-B8h]@26
  char v140; // [sp+120h] [bp-B0h]@16
  __int64 v141; // [sp+1A0h] [bp-30h]@1

  v4 = a4;
  v141 = *__stack_chk_guard;
  LODWORD(v5) = objc_retain(a2);
  v6 = v5;
  LODWORD(v7) = objc_retain(v4);
  v8 = v7;
  if ( v7 )
  {
    LODWORD(v9) = FIRInstanceIDSharedLogger(v4);
    LODWORD(v10) = objc_retainAutoreleasedReturnValue(v9);
    v11 = v10;
    v12 = objc_msgSend(v8, *(&selRef_init + 16));
    objc_msgSend(v11, *(&selRef_init + 17), &aHttpsDevicePro[309], 7000LL, &cfstr_HttpsDevicePro + 12, v12);
    objc_release(v11);
    (*(void (__fastcall **)(_QWORD, _QWORD, void *))(*(_QWORD *)(a1 + 32) + 16LL))(*(_QWORD *)(a1 + 32), 0LL, v8);
  }
  else
  {
    v127 = a1;
    v13 = *(&classRef_NSURLSessionConfiguration + 4);
    v115 = 0LL;
    v14 = *(&selRef_init + 18);
    v118 = v6;
    v15 = objc_msgSend(v13, v14, v6, 0LL, &v115);
    LODWORD(v16) = objc_retainAutoreleasedReturnValue(v15);
    v17 = v16;
    v18 = v115;
    LODWORD(v19) = objc_retain(v115);
    v20 = v19;
    v129 = v17;
    if ( v19 )
    {
      LODWORD(v21) = FIRInstanceIDSharedLogger(v18);
      LODWORD(v22) = objc_retainAutoreleasedReturnValue(v21);
      v23 = v22;
      v24 = objc_msgSend(v20, *(&selRef_init + 16));
      objc_msgSend(v23, *(&selRef_init + 17), &aHttpsDevicePro[309], 7001LL, &cfstr_HttpsDevicePro + 13, v24);
      v25 = v129;
      objc_release(v23);
      (*(void (__fastcall **)(_QWORD, _QWORD, void *))(*(_QWORD *)(v127 + 32) + 16LL))(*(_QWORD *)(v127 + 32), 0LL, v20);
      v26 = (__int64)v20;
    }
    else
    {
      v119 = 0LL;
      v27 = objc_msgSend(v17, *(&selRef_init + 19), &cfstr_HttpsDevicePro + 14);
      LODWORD(v28) = objc_retainAutoreleasedReturnValue(v27);
      v29 = v28;
      v30 = objc_msgSend(v28, *(&selRef_init + 20));
      LODWORD(v31) = objc_retainAutoreleasedReturnValue(v30);
      v130 = v31;
      objc_release(v29);
      v32 = objc_msgSend(v17, *(&selRef_init + 19), &cfstr_HttpsDevicePro + 15);
      LODWORD(v33) = objc_retainAutoreleasedReturnValue(v32);
      v34 = v33;
      v35 = objc_msgSend(v33, *(&selRef_init + 20));
      LODWORD(v36) = objc_retainAutoreleasedReturnValue(v35);
      v37 = v36;
      objc_release(v34);
      if ( objc_msgSend(v130, *(&selRef_init + 21)) )
      {
        v121 = v37;
        v38 = *(&selRef_init + 19);
        LODWORD(v39) = ((int (__fastcall *)(void *, _QWORD, __CFString *))objc_msgSend)(
                         v129,
                         *(&selRef_init + 19),
                         &cfstr_HttpsDevicePro + 16);
        LODWORD(v40) = objc_retainAutoreleasedReturnValue(v39);
        v41 = v40;
        LODWORD(v42) = ((int (__fastcall *)(__int64, _QWORD))objc_msgSend)(v40, *(&selRef_init + 23));
        v43 = v42;
        objc_release(v41);
        LODWORD(v44) = FIRInstanceIDCurrentTimestampInMilliseconds(v41);
        v45 = v44;
        if ( v43 <= v44 )
        {
          v131 = *(&selRef_init + 17);
          v128 = v43;
        }
        else
        {
          LODWORD(v46) = ((int (*)(void))FIRInstanceIDSharedLogger)();
          LODWORD(v47) = objc_retainAutoreleasedReturnValue(v46);
          v48 = v47;
          v131 = *(&selRef_init + 17);
          objc_msgSend(v47, v131, &aHttpsDevicePro[309], 7002LL, &cfstr_HttpsDevicePro + 17);
          objc_release(v48);
          v128 = v45;
        }
        v120 = v8;
        v53 = v129;
        v54 = objc_msgSend(v129, v38, &cfstr_HttpsDevicePro + 18);
        LODWORD(v55) = objc_retainAutoreleasedReturnValue(v54);
        v56 = v55;
        v57 = &cfstr_HttpsDevicePro + 19;
        v58 = &cfstr_HttpsDevicePro + 19;
        if ( v55 )
          v58 = v55;
        LODWORD(v59) = objc_retain(v58);
        v122 = v59;
        objc_release(v56);
        v60 = objc_msgSend(v53, *(&selRef_init + 19), &cfstr_HttpsDevicePro + 20);
        LODWORD(v61) = objc_retainAutoreleasedReturnValue(v60);
        v62 = v61;
        v63 = &cfstr_HttpsDevicePro + 19;
        if ( v61 )
          v63 = v61;
        LODWORD(v64) = objc_retain(v63);
        v65 = v64;
        objc_release(v62);
        LODWORD(v66) = FIRInstanceIDSharedLogger(v62);
        LODWORD(v67) = objc_retainAutoreleasedReturnValue(v66);
        v68 = v67;
        v123 = v65;
        objc_msgSend(v67, v131, &aHttpsDevicePro[309], 7003LL, &cfstr_HttpsDevicePro + 21, v130, v65, v128);
        objc_release(v68);
        v69 = objc_msgSend(v53, *(&selRef_init + 19), &cfstr_HttpsDevicePro + 22);
        LODWORD(v70) = objc_retainAutoreleasedReturnValue(v69);
        v71 = v70;
        if ( v70 )
          v57 = v70;
        v72 = *(&selRef_init + 19);
        LODWORD(v73) = objc_retain(v57);
        v124 = v73;
        objc_release(v71);
        v74 = objc_msgSend(*(&classRef_NSURLSessionConfiguration + 6), *(&selRef_init + 24));
        LODWORD(v75) = objc_retainAutoreleasedReturnValue(v74);
        v126 = v75;
        v76 = v53;
        v77 = objc_msgSend;
        v78 = objc_msgSend(v76, v72, &cfstr_HttpsDevicePro + 23);
        LODWORD(v79) = objc_retainAutoreleasedReturnValue(v78);
        v114 = 0LL;
        v113 = 0LL;
        v112 = 0LL;
        v111 = 0LL;
        v80 = (__int64)*(&selRef_init + 25);
        v125 = v79;
        LODWORD(v81) = ((int (__fastcall *)(__int64, __int64, __int128 *, char *, signed __int64))objc_msgSend)(
                         v79,
                         v80,
                         &v111,
                         &v140,
                         16LL);
        v131 = v81;
        if ( v81 )
        {
          v116 = *(_QWORD *)v112;
          do
          {
            v117 = *(&selRef_init + 26);
            v82 = 0LL;
            do
            {
              if ( *(_QWORD *)v112 != v116 )
                objc_enumerationMutation(v125);
              v83 = *(void **)(*((_QWORD *)&v111 + 1) + 8 * v82);
              LODWORD(v84) = ((int (__fastcall *)(_QWORD, const char *, __CFString *))v77)(
                               *(_QWORD *)(*((_QWORD *)&v111 + 1) + 8 * v82),
                               v72,
                               &cfstr_HttpsDevicePro + 24);
              LODWORD(v85) = objc_retainAutoreleasedReturnValue(v84);
              v86 = v85;
              if ( v85 )
              {
                LODWORD(v87) = ((int (__fastcall *)(void *, const char *, __CFString *))v77)(
                                 v83,
                                 v72,
                                 &cfstr_HttpsDevicePro + 25);
                LODWORD(v88) = objc_retainAutoreleasedReturnValue(v87);
                v89 = v88;
                objc_release(v88);
                objc_release(v86);
                v72 = *(&selRef_init + 19);
                v90 = v89 == 0;
                v77 = objc_msgSend;
                if ( !v90 )
                {
                  v91 = objc_msgSend(v83, *(&selRef_init + 19), &cfstr_HttpsDevicePro + 24, (_QWORD)v111);
                  LODWORD(v92) = objc_retainAutoreleasedReturnValue(v91);
                  v93 = v92;
                  v94 = objc_msgSend(v83, v72, &cfstr_HttpsDevicePro + 25, (_QWORD)v111);
                  LODWORD(v95) = objc_retainAutoreleasedReturnValue(v94);
                  v96 = v95;
                  objc_msgSend(v126, v117, v95, v93, (_QWORD)v111);
                  objc_release(v96);
                  objc_release(v93);
                  v72 = *(&selRef_init + 19);
                }
              }
              ++v82;
            }
            while ( v82 < (unsigned __int64)v131 );
            LODWORD(v97) = ((int (__fastcall *)(__int64, _QWORD, __int128 *, char *, signed __int64))v77)(
                             v125,
                             *(&selRef_init + 25),
                             &v111,
                             &v140,
                             16LL);
            v131 = v97;
          }
          while ( v97 );
        }
        LODWORD(v98) = ((int (__fastcall *)(_QWORD, _QWORD))v77)(
                         *(&classRef_NSURLSessionConfiguration + 7),
                         *(&selRef_init + 27));
        LODWORD(v99) = ((int (__fastcall *)(__int64, _QWORD, void *, __int64))v77)(
                         v98,
                         *(&selRef_init + 28),
                         v130,
                         v121);
        v100 = v99;
        v135 = v123;
        _mm_store_si128(
          (__m128i *)&v132,
          _mm_unpacklo_epi64(
            (__m128i)(unsigned __int64)(&cfstr_HttpsDevicePro + 3),
            (__m128i)(unsigned __int64)(&cfstr_HttpsDevicePro + 5)));
        v136 = v124;
        v133 = &cfstr_HttpsDevicePro + 4;
        LODWORD(v101) = ((int (__fastcall *)(_QWORD, _QWORD, __int64))v77)(
                          *(&classRef_NSURLSessionConfiguration + 8),
                          *(&selRef_init + 29),
                          v128);
        LODWORD(v102) = objc_retainAutoreleasedReturnValue(v101);
        v103 = v77;
        v104 = v102;
        v137 = v102;
        v138 = v126;
        _mm_storeu_si128(
          (__m128i *)&v134,
          _mm_unpacklo_epi64(
            (__m128i)(unsigned __int64)(&cfstr_HttpsDevicePro + 6),
            (__m128i)(unsigned __int64)(&cfstr_HttpsDevicePro + 7)));
        v139 = v122;
        LODWORD(v105) = ((int (__fastcall *)(_QWORD, _QWORD, __int64 *, char *, signed __int64))v103)(
                          *(&classRef_NSURLSessionConfiguration + 9),
                          *(&selRef_init + 30),
                          &v135,
                          &v132,
                          5LL);
        LODWORD(v106) = objc_retainAutoreleasedReturnValue(v105);
        v107 = v106;
        objc_release(v104);
        ((void (__fastcall *)(__int64, _QWORD, __int64))v103)(v100, *(&selRef_init + 31), v107);
        v108 = v100;
        (*(void (__fastcall **)(_QWORD, __int64, _QWORD))(*(_QWORD *)(v127 + 32) + 16LL))(
          *(_QWORD *)(v127 + 32),
          v100,
          0LL);
        v52 = (void (__fastcall *)(__int64))objc_release;
        objc_release(v107);
        v109 = v108;
        v37 = v121;
        objc_release(v109);
        objc_release(v125);
        objc_release(v126);
        objc_release(v124);
        objc_release(v123);
        objc_release(v122);
        v8 = v120;
      }
      else
      {
        v49 = objc_msgSend(*(&classRef_NSURLSessionConfiguration + 5), *(&selRef_init + 22), 7LL);
        LODWORD(v50) = objc_retainAutoreleasedReturnValue(v49);
        v51 = v50;
        (*(void (__fastcall **)(_QWORD, _QWORD, __int64))(*(_QWORD *)(v127 + 32) + 16LL))(
          *(_QWORD *)(v127 + 32),
          0LL,
          v50);
        objc_release(v51);
        v52 = (void (__fastcall *)(__int64))objc_release;
      }
      v52(v37);
      v52(v130);
      v25 = v129;
      v26 = v119;
    }
    objc_release(v25);
    objc_release(v26);
    v6 = v118;
  }
  objc_release(v8);
  objc_release(v6);
  return *__stack_chk_guard;
}
// 1720: using guessed type __CFString cfstr_HttpsDevicePro;
// 2148: using guessed type char *selRef_init;
// 22B0: using guessed type void *classRef_NSURLSessionConfiguration;
// 8F88: using guessed type int __fastcall FIRInstanceIDCurrentTimestampInMilliseconds(_QWORD);
// 8FA0: using guessed type int __fastcall FIRInstanceIDSharedLogger(_QWORD);
// 9058: using guessed type int __fastcall objc_enumerationMutation(_QWORD);
// 9070: using guessed type int __fastcall objc_release(_QWORD);
// 9078: using guessed type int __fastcall objc_retain(_QWORD);
// 9080: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000C1A) ----------------------------------------------------
void __fastcall __copy_helper_block_(__int64 a1, __int64 a2)
{
  _Block_object_assign((void *)(a1 + 32), *(const void **)(a2 + 32), 7);
}

//----- (0000000000000C31) ----------------------------------------------------
int __fastcall __destroy_helper_block_(__int64 a1)
{
  return objc_release(*(_QWORD *)(a1 + 32));
}
// 9070: using guessed type int __fastcall objc_release(_QWORD);

//----- (0000000000000C40) ----------------------------------------------------
// FIRInstanceIDCheckinService - (void)stopFetching
void __cdecl -[FIRInstanceIDCheckinService stopFetching](struct FIRInstanceIDCheckinService *self, SEL a2)
{
  void *v2; // rax@1
  void *v3; // rax@1
  void *v4; // rbx@1

  v2 = objc_msgSend(self, *(&selRef_init + 6));
  LODWORD(v3) = objc_retainAutoreleasedReturnValue(v2);
  v4 = v3;
  objc_msgSend(v3, *(&selRef_init + 7));
  objc_release(v4);
}
// 2148: using guessed type char *selRef_init;
// 9070: using guessed type int __fastcall objc_release(_QWORD);
// 9080: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000C7D) ----------------------------------------------------
// FIRInstanceIDCheckinService - (id)checkinParametersWithExistingCheckin:(id) 
id __cdecl -[FIRInstanceIDCheckinService checkinParametersWithExistingCheckin:](struct FIRInstanceIDCheckinService *self, SEL a2, id a3)
{
  id v3; // r12@1
  id v4; // rdi@1
  __int64 v5; // rax@1
  __int64 v6; // rax@1
  __int64 v7; // rdi@1
  __int64 v8; // rax@1
  __int64 v9; // r13@1
  __int64 v10; // rax@1
  __int64 v11; // rax@1
  void *v12; // rax@1
  void *v13; // rdi@1
  __int64 v14; // rax@1
  __int64 v15; // r15@1
  __int64 v16; // rax@1
  __int64 v17; // rax@1
  __int64 v18; // rax@1
  __int64 v19; // rax@1
  __int64 v20; // rbx@1
  __int64 v21; // rax@1
  __int64 v22; // rax@1
  __int64 v23; // rax@1
  __int64 v24; // r14@1
  __int64 v25; // rax@1
  __int64 v26; // rax@1
  __int64 v27; // r13@1
  __int64 v28; // rax@1
  __int64 v29; // rax@1
  __int64 v30; // rax@1
  __int64 v31; // rax@1
  __int64 v32; // rax@1
  __int64 v33; // rax@1
  __int64 v34; // rax@1
  __int64 v35; // rax@1
  __int64 v36; // rax@1
  __int64 v37; // rax@1
  __int64 v38; // rax@1
  __int64 v39; // rax@1
  __int64 v40; // rax@1
  __int64 v41; // rax@1
  id v42; // rbx@1
  __int64 v43; // rax@1
  __int64 v44; // rax@1
  __CFString *v45; // rcx@1
  __int64 v46; // rax@3
  __int64 v47; // rax@3
  __int64 v48; // r14@3
  __int64 v49; // rax@3
  __int64 v50; // rax@3
  __int64 v51; // rax@3
  __int64 v52; // rax@3
  __int64 v53; // rax@3
  __int64 v54; // r14@3
  __int64 v55; // r15@3
  __int64 v56; // rax@3
  __int64 v57; // rbx@3
  __int64 v58; // rax@3
  __int64 v59; // r13@3
  __int64 v60; // rax@3
  __int64 v61; // rax@3
  __int64 v62; // rax@3
  __int64 v63; // rbx@3
  __int64 v64; // rax@3
  __int64 v65; // rax@3
  __int64 v66; // r12@3
  __int64 v67; // rdi@3
  __int64 v68; // rax@3
  __int64 v69; // rax@3
  __int64 v70; // rbx@3
  id result; // rax@3
  char v72; // [sp+0h] [bp-1C0h]@1
  __int64 v73; // [sp+10h] [bp-1B0h]@1
  __int64 v74; // [sp+18h] [bp-1A8h]@1
  __int64 v75; // [sp+20h] [bp-1A0h]@1
  __int64 v76; // [sp+28h] [bp-198h]@1
  __int64 v77; // [sp+30h] [bp-190h]@1
  __int64 v78; // [sp+38h] [bp-188h]@1
  __int64 v79; // [sp+40h] [bp-180h]@1
  __int64 v80; // [sp+48h] [bp-178h]@1
  __int64 v81; // [sp+50h] [bp-170h]@1
  __int64 v82; // [sp+58h] [bp-168h]@1
  id v83; // [sp+60h] [bp-160h]@1
  __int64 v84; // [sp+68h] [bp-158h]@1
  __int64 v85; // [sp+70h] [bp-150h]@1
  __int64 v86; // [sp+78h] [bp-148h]@3
  __int64 v87; // [sp+80h] [bp-140h]@3
  __int64 v88; // [sp+88h] [bp-138h]@1
  __int64 v89; // [sp+90h] [bp-130h]@1
  __int64 v90; // [sp+98h] [bp-128h]@1
  __int64 v91; // [sp+A0h] [bp-120h]@1
  __int64 v92; // [sp+A8h] [bp-118h]@1
  __CFString *v93; // [sp+B0h] [bp-110h]@1
  __CFString *v94; // [sp+B8h] [bp-108h]@1
  __CFString *v95; // [sp+C0h] [bp-100h]@1
  __CFString *v96; // [sp+C8h] [bp-F8h]@1
  __int64 v97; // [sp+D0h] [bp-F0h]@1
  __int64 v98; // [sp+D8h] [bp-E8h]@1
  __int64 v99; // [sp+E0h] [bp-E0h]@1
  __int64 v100; // [sp+E8h] [bp-D8h]@1
  __CFString *v101; // [sp+F0h] [bp-D0h]@1
  __CFString *v102; // [sp+F8h] [bp-C8h]@1
  __CFString *v103; // [sp+100h] [bp-C0h]@1
  __int64 v104; // [sp+108h] [bp-B8h]@1
  __CFString *v105; // [sp+118h] [bp-A8h]@1
  __int64 v106; // [sp+120h] [bp-A0h]@3
  __CFString *v107; // [sp+130h] [bp-90h]@3
  __CFString *v108; // [sp+138h] [bp-88h]@3
  __int64 v109; // [sp+140h] [bp-80h]@1
  __int64 v110; // [sp+148h] [bp-78h]@1
  __int64 v111; // [sp+150h] [bp-70h]@1
  __int64 v112; // [sp+158h] [bp-68h]@1
  __int64 v113; // [sp+160h] [bp-60h]@1
  __CFString *v114; // [sp+168h] [bp-58h]@3
  __int64 v115; // [sp+170h] [bp-50h]@3
  __int64 v116; // [sp+178h] [bp-48h]@3
  __int64 v117; // [sp+180h] [bp-40h]@3
  __int64 v118; // [sp+188h] [bp-38h]@3
  __int64 v119; // [sp+190h] [bp-30h]@1

  v3 = a3;
  v119 = *__stack_chk_guard;
  v4 = a3;
  v83 = a3;
  LODWORD(v5) = objc_retain(a3);
  v76 = v5;
  LODWORD(v6) = FIRInstanceIDDeviceModel(v4, a2);
  v7 = v6;
  LODWORD(v8) = objc_retainAutoreleasedReturnValue(v6);
  v9 = v8;
  v74 = v8;
  LODWORD(v10) = FIRInstanceIDOperatingSystemVersion(v7);
  LODWORD(v11) = objc_retainAutoreleasedReturnValue(v10);
  v73 = v11;
  v12 = objc_msgSend(*(&classRef_NSURLSessionConfiguration + 10), *(&selRef_init + 34), &cfstr_HttpsDevicePro + 27);
  v13 = v12;
  LODWORD(v14) = objc_retainAutoreleasedReturnValue(v12);
  v15 = v14;
  v75 = v14;
  LODWORD(v16) = FIRInstanceIDCurrentLocale(v13);
  LODWORD(v17) = objc_retainAutoreleasedReturnValue(v16);
  v88 = v17;
  LODWORD(v90) = arc4random();
  LODWORD(v18) = ((int (__fastcall *)(_QWORD, _QWORD))objc_msgSend)(
                   *(&classRef_NSURLSessionConfiguration + 11),
                   *(&selRef_init + 35));
  LODWORD(v19) = objc_retainAutoreleasedReturnValue(v18);
  v20 = v19;
  LODWORD(v21) = ((int (__fastcall *)(__int64, _QWORD))objc_msgSend)(v19, *(&selRef_init + 36));
  LODWORD(v22) = objc_retainAutoreleasedReturnValue(v21);
  v89 = v22;
  objc_release(v20);
  LODWORD(v23) = ((int (__fastcall *)(id, _QWORD))objc_msgSend)(v3, *(&selRef_init + 37));
  v24 = v23;
  v101 = &cfstr_HttpsDevicePro + 28;
  v93 = &cfstr_HttpsDevicePro + 29;
  v91 = v9;
  _mm_store_si128(
    (__m128i *)&v72,
    _mm_unpacklo_epi64(
      (__m128i)(unsigned __int64)(&cfstr_HttpsDevicePro + 30),
      (__m128i)(unsigned __int64)(&cfstr_HttpsDevicePro + 31)));
  v92 = v15;
  LODWORD(v25) = ((int (__fastcall *)(_QWORD, _QWORD, __int64 *, char *, signed __int64))objc_msgSend)(
                   *(&classRef_NSURLSessionConfiguration + 9),
                   *(&selRef_init + 30),
                   &v91,
                   &v72,
                   2LL);
  LODWORD(v26) = objc_retainAutoreleasedReturnValue(v25);
  v77 = v26;
  v97 = v26;
  v94 = &cfstr_HttpsDevicePro + 32;
  v27 = (__int64)*(&selRef_init + 38);
  LODWORD(v28) = ((int (__fastcall *)(_QWORD, _QWORD, signed __int64))objc_msgSend)(
                   *(&classRef_NSURLSessionConfiguration + 8),
                   *(&selRef_init + 38),
                   2LL);
  LODWORD(v29) = objc_retainAutoreleasedReturnValue(v28);
  v78 = v29;
  v98 = v29;
  v95 = &cfstr_HttpsDevicePro + 33;
  LODWORD(v30) = ((int (__fastcall *)(_QWORD, _QWORD, _QWORD))objc_msgSend)(
                   *(&classRef_NSURLSessionConfiguration + 8),
                   *(&selRef_init + 39),
                   0LL);
  LODWORD(v31) = objc_retainAutoreleasedReturnValue(v30);
  v79 = v31;
  v99 = v31;
  v96 = &cfstr_HttpsDevicePro + 34;
  LODWORD(v32) = ((int (__fastcall *)(_QWORD, _QWORD, __int64))objc_msgSend)(
                   *(&classRef_NSURLSessionConfiguration + 8),
                   *(&selRef_init + 29),
                   v24);
  LODWORD(v33) = objc_retainAutoreleasedReturnValue(v32);
  v80 = v33;
  v100 = v33;
  LODWORD(v34) = ((int (__fastcall *)(_QWORD, _QWORD, __int64 *, __CFString **, signed __int64))objc_msgSend)(
                   *(&classRef_NSURLSessionConfiguration + 9),
                   *(&selRef_init + 30),
                   &v97,
                   &v93,
                   4LL);
  LODWORD(v35) = objc_retainAutoreleasedReturnValue(v34);
  v81 = v35;
  v109 = v35;
  v102 = &cfstr_HttpsDevicePro + 35;
  LODWORD(v36) = ((int (__fastcall *)(_QWORD, __int64, _QWORD))objc_msgSend)(
                   *(&classRef_NSURLSessionConfiguration + 8),
                   v27,
                   0LL);
  LODWORD(v37) = objc_retainAutoreleasedReturnValue(v36);
  v82 = v37;
  v110 = v37;
  v103 = &cfstr_HttpsDevicePro + 36;
  LODWORD(v38) = ((int (__fastcall *)(_QWORD, _QWORD, _QWORD))objc_msgSend)(
                   *(&classRef_NSURLSessionConfiguration + 8),
                   *(&selRef_init + 40),
                   (unsigned int)v90);
  LODWORD(v39) = objc_retainAutoreleasedReturnValue(v38);
  v90 = v39;
  v111 = v39;
  v112 = v88;
  _mm_storeu_si128(
    (__m128i *)&v104,
    _mm_unpacklo_epi64(
      (__m128i)(unsigned __int64)(&cfstr_HttpsDevicePro + 37),
      (__m128i)(unsigned __int64)(&cfstr_HttpsDevicePro + 38)));
  LODWORD(v40) = ((int (__fastcall *)(_QWORD, __int64, signed __int64))objc_msgSend)(
                   *(&classRef_NSURLSessionConfiguration + 8),
                   v27,
                   2LL);
  LODWORD(v41) = objc_retainAutoreleasedReturnValue(v40);
  v84 = v41;
  v113 = v41;
  v105 = &cfstr_HttpsDevicePro + 20;
  v42 = v83;
  LODWORD(v43) = ((int (__fastcall *)(id, _QWORD))objc_msgSend)(v83, *(&selRef_init + 41));
  LODWORD(v44) = objc_retainAutoreleasedReturnValue(v43);
  v85 = v44;
  v45 = &cfstr_HttpsDevicePro + 19;
  if ( v44 )
    v45 = (__CFString *)v44;
  v114 = v45;
  v115 = v89;
  _mm_storeu_si128(
    (__m128i *)&v106,
    _mm_unpacklo_epi64(
      (__m128i)(unsigned __int64)(&cfstr_HttpsDevicePro + 39),
      (__m128i)(unsigned __int64)(&cfstr_HttpsDevicePro + 40)));
  LODWORD(v46) = ((int (__fastcall *)(_QWORD, _QWORD, _QWORD))objc_msgSend)(
                   *(&classRef_NSURLSessionConfiguration + 8),
                   *(&selRef_init + 39),
                   0LL);
  LODWORD(v47) = objc_retainAutoreleasedReturnValue(v46);
  v86 = v47;
  v116 = v47;
  v107 = &cfstr_HttpsDevicePro + 41;
  v48 = (__int64)*(&classRef_NSURLSessionConfiguration + 8);
  LODWORD(v49) = ((int (__fastcall *)(_QWORD, _QWORD))objc_msgSend)(v42, *(&selRef_init + 42));
  LODWORD(v50) = objc_retainAutoreleasedReturnValue(v49);
  v87 = v50;
  LODWORD(v51) = ((int (__fastcall *)(__int64, _QWORD))objc_msgSend)(v50, *(&selRef_init + 23));
  LODWORD(v52) = ((int (__fastcall *)(__int64, _QWORD, __int64))objc_msgSend)(v48, *(&selRef_init + 29), v51);
  LODWORD(v53) = objc_retainAutoreleasedReturnValue(v52);
  v54 = v53;
  v117 = v53;
  v108 = &cfstr_HttpsDevicePro + 15;
  v55 = (__int64)*(&classRef_NSURLSessionConfiguration + 8);
  LODWORD(v56) = ((int (__fastcall *)(_QWORD, _QWORD))objc_msgSend)(v42, *(&selRef_init + 43));
  v57 = v56;
  objc_release(v76);
  LODWORD(v58) = objc_retainAutoreleasedReturnValue(v57);
  v59 = v58;
  LODWORD(v60) = ((int (__fastcall *)(__int64, _QWORD))objc_msgSend)(v58, *(&selRef_init + 23));
  LODWORD(v61) = ((int (__fastcall *)(__int64, _QWORD, __int64))objc_msgSend)(v55, *(&selRef_init + 29), v60);
  LODWORD(v62) = objc_retainAutoreleasedReturnValue(v61);
  v63 = v62;
  v118 = v62;
  LODWORD(v64) = ((int (__fastcall *)(_QWORD, _QWORD, __int64 *, __CFString **, signed __int64))objc_msgSend)(
                   *(&classRef_NSURLSessionConfiguration + 9),
                   *(&selRef_init + 30),
                   &v109,
                   &v101,
                   10LL);
  LODWORD(v65) = objc_retainAutoreleasedReturnValue(v64);
  v66 = v65;
  objc_release(v63);
  objc_release(v59);
  objc_release(v54);
  objc_release(v87);
  objc_release(v86);
  objc_release(v85);
  objc_release(v84);
  objc_release(v90);
  objc_release(v82);
  objc_release(v81);
  objc_release(v80);
  objc_release(v79);
  objc_release(v78);
  v67 = v77;
  objc_release(v77);
  LODWORD(v68) = FIRInstanceIDSharedLogger(v67);
  LODWORD(v69) = objc_retainAutoreleasedReturnValue(v68);
  v70 = v69;
  ((void (__fastcall *)(__int64, _QWORD, char *, signed __int64, __CFString *, __int64))objc_msgSend)(
    v69,
    *(&selRef_init + 17),
    &aHttpsDevicePro[1005],
    7006LL,
    &cfstr_HttpsDevicePro + 42,
    v66);
  objc_release(v70);
  objc_release(v89);
  objc_release(v88);
  objc_release(v75);
  ((void (*)(void))objc_release)();
  objc_release(v74);
  result = (id)*__stack_chk_guard;
  if ( *__stack_chk_guard == v119 )
    LODWORD(result) = objc_autoreleaseReturnValue(v66);
  return result;
}
// 1720: using guessed type __CFString cfstr_HttpsDevicePro;
// 2148: using guessed type char *selRef_init;
// 22B0: using guessed type void *classRef_NSURLSessionConfiguration;
// 8F80: using guessed type int __fastcall FIRInstanceIDCurrentLocale(_QWORD);
// 8F90: using guessed type int __fastcall FIRInstanceIDDeviceModel(_QWORD, _QWORD);
// 8F98: using guessed type int __fastcall FIRInstanceIDOperatingSystemVersion(_QWORD);
// 8FA0: using guessed type int __fastcall FIRInstanceIDSharedLogger(_QWORD);
// 9050: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 9070: using guessed type int __fastcall objc_release(_QWORD);
// 9078: using guessed type int __fastcall objc_retain(_QWORD);
// 9080: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000001244) ----------------------------------------------------
// FIRInstanceIDCheckinService + (void)setCheckinTestBlock:(id) 
void __cdecl +[FIRInstanceIDCheckinService setCheckinTestBlock:](struct FIRInstanceIDCheckinService *self, SEL a2, id a3)
{
  void *v3; // rax@1
  __int64 v4; // rdi@1

  v3 = objc_msgSend(a3, *(&selRef_init + 44));
  v4 = testBlock;
  testBlock = (__int64)v3;
  objc_release(v4);
}
// 2148: using guessed type char *selRef_init;
// 8F70: using guessed type __int64 testBlock;
// 9070: using guessed type int __fastcall objc_release(_QWORD);

//----- (000000000000126D) ----------------------------------------------------
// FIRInstanceIDCheckinService - (id)session
id __cdecl -[FIRInstanceIDCheckinService session](struct FIRInstanceIDCheckinService *self, SEL a2)
{
  return (id)self->_session;
}

//----- (000000000000127E) ----------------------------------------------------
// FIRInstanceIDCheckinService - (void)setSession:(id) 
void __cdecl -[FIRInstanceIDCheckinService setSession:](struct FIRInstanceIDCheckinService *self, SEL a2, id a3)
{
  objc_storeStrong(&self->_session, a3);
}
// 9090: using guessed type int __fastcall objc_storeStrong(_QWORD, _QWORD);

//----- (0000000000001292) ----------------------------------------------------
// FIRInstanceIDCheckinService - (void).cxx_destruct
void __cdecl -[FIRInstanceIDCheckinService .cxx_destruct](struct FIRInstanceIDCheckinService *self, SEL a2)
{
  objc_storeStrong(&self->_session, 0LL);
}
// 9090: using guessed type int __fastcall objc_storeStrong(_QWORD, _QWORD);

// ALL OK, 12 function(s) have been successfully decompiled
