/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2015 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

_QWORD *__fastcall -[FIRInstanceIDAPNSInfo initWithDeviceToken:isSandbox:](__int64 a1, __int64 a2, __int64 a3, char a4);
id __cdecl -[FIRInstanceIDAPNSInfo initWithTokenOptionsDictionary:](struct FIRInstanceIDAPNSInfo *self, SEL, id);
id __cdecl -[FIRInstanceIDAPNSInfo initWithCoder:](struct FIRInstanceIDAPNSInfo *self, SEL, id);
void __cdecl -[FIRInstanceIDAPNSInfo encodeWithCoder:](struct FIRInstanceIDAPNSInfo *self, SEL, id);
bool __cdecl -[FIRInstanceIDAPNSInfo isEqualToAPNSInfo:](struct FIRInstanceIDAPNSInfo *self, SEL, id);
id __cdecl -[FIRInstanceIDAPNSInfo deviceToken](struct FIRInstanceIDAPNSInfo *self, SEL);
bool __cdecl -[FIRInstanceIDAPNSInfo isSandbox](struct FIRInstanceIDAPNSInfo *self, SEL);
void __cdecl -[FIRInstanceIDAPNSInfo .cxx_destruct](struct FIRInstanceIDAPNSInfo *self, SEL);
// void *objc_msgSend(void *, const char *, ...); idb
// void *objc_msgSendSuper2(void *, const char *, ...); idb
// int __fastcall objc_retainAutoreleasedReturnValue(_QWORD); weak
// int __fastcall objc_storeStrong(_QWORD); weak

//-------------------------------------------------------------------------
// Data declarations

void *classRef_FIRInstanceIDAPNSInfo = &OBJC_CLASS___FIRInstanceIDAPNSInfo; // weak
char *selRef_init = "init"; // weak
void *classRef_NSData = &OBJC_CLASS___NSData; // weak
// extern _UNKNOWN kFIRInstanceIDTokenOptionsAPNSIsSandboxKey; weak
// extern _UNKNOWN kFIRInstanceIDTokenOptionsAPNSKey; weak
// extern int (__fastcall *objc_release)(_QWORD); weak
// extern int (__fastcall *objc_retain)(_QWORD); weak


//----- (0000000000000000) ----------------------------------------------------
_QWORD *__fastcall -[FIRInstanceIDAPNSInfo initWithDeviceToken:isSandbox:](__int64 a1, __int64 a2, __int64 a3, char a4)
{
  char v4; // r14@1
  void *v5; // rax@1
  void *v6; // r15@1
  _QWORD *v7; // rbx@1
  void *v8; // rax@2
  __int64 v9; // rdi@2
  __int64 v11; // [sp+8h] [bp-28h]@1
  void *v12; // [sp+10h] [bp-20h]@1

  v4 = a4;
  LODWORD(v5) = objc_retain(a3);
  v6 = v5;
  v11 = a1;
  v12 = classRef_FIRInstanceIDAPNSInfo;
  v7 = objc_msgSendSuper2(&v11, selRef_init);
  if ( v7 )
  {
    v8 = objc_msgSend(v6, *(&selRef_init + 1));
    v9 = v7[2];
    v7[2] = v8;
    objc_release(v9);
    *((_BYTE *)v7 + 8) = v4;
  }
  objc_release(v6);
  return v7;
}
// 590: using guessed type void *classRef_FIRInstanceIDAPNSInfo;
// 6F0: using guessed type char *selRef_init;
// 3B70: using guessed type int (__fastcall *objc_release)(_QWORD);
// 3B78: using guessed type int (__fastcall *objc_retain)(_QWORD);

//----- (000000000000008C) ----------------------------------------------------
// FIRInstanceIDAPNSInfo - (id)initWithTokenOptionsDictionary:(id) 
id __cdecl -[FIRInstanceIDAPNSInfo initWithTokenOptionsDictionary:](struct FIRInstanceIDAPNSInfo *self, SEL a2, id a3)
{
  void *v3; // rax@1
  void *v4; // r13@1
  void *v5; // rax@1
  __int64 v6; // r14@1
  void *v7; // rax@1
  void *v8; // rbx@1
  void *v9; // rax@1
  const char *v10; // r12@1
  void *v11; // rax@2
  void *v12; // rax@2
  void *v13; // r14@2
  void *v14; // rax@2
  char *v15; // rax@3
  char *v16; // rbx@3
  struct FIRInstanceIDAPNSInfo *v17; // rax@5
  struct FIRInstanceIDAPNSInfo *v18; // r12@5
  struct objc_object *v19; // r15@5
  struct FIRInstanceIDAPNSInfo *v21; // [sp+8h] [bp-58h]@3
  void *v22; // [sp+10h] [bp-50h]@3
  __int64 v23; // [sp+18h] [bp-48h]@2
  void *v24; // [sp+20h] [bp-40h]@2
  void *v25; // [sp+28h] [bp-38h]@2
  struct FIRInstanceIDAPNSInfo *v26; // [sp+30h] [bp-30h]@1

  v26 = self;
  LODWORD(v3) = objc_retain(a3);
  v4 = v3;
  v5 = objc_msgSend(v3, *(&selRef_init + 2), *kFIRInstanceIDTokenOptionsAPNSKey);
  v6 = (__int64)v5;
  LODWORD(v7) = objc_retainAutoreleasedReturnValue(v5);
  v8 = v7;
  v9 = objc_msgSend(classRef_NSData, *(&selRef_init + 3));
  v10 = *(&selRef_init + 4);
  if ( (unsigned __int8)objc_msgSend(v8, *(&selRef_init + 4), v9) )
  {
    v23 = v6;
    v25 = v8;
    v11 = objc_msgSend(v4, *(&selRef_init + 2), *kFIRInstanceIDTokenOptionsAPNSIsSandboxKey);
    LODWORD(v12) = objc_retainAutoreleasedReturnValue(v11);
    v13 = v12;
    v14 = objc_msgSend(*(&classRef_NSData + 1), *(&selRef_init + 3));
    v24 = v13;
    if ( (unsigned __int8)objc_msgSend(v13, v10, v14) )
    {
      v21 = v26;
      v22 = classRef_FIRInstanceIDAPNSInfo;
      v15 = (char *)objc_msgSendSuper2(&v21, selRef_init);
      v16 = v15;
      if ( v15 )
      {
        objc_storeStrong(v15 + 16);
        v16[8] = (unsigned __int64)objc_msgSend(v24, *(&selRef_init + 5));
      }
      LODWORD(v17) = objc_retain(v16);
      v18 = v17;
      v19 = (struct objc_object *)v17;
    }
    else
    {
      v19 = 0LL;
      v18 = v26;
    }
    v8 = v25;
    objc_release(v24);
  }
  else
  {
    v19 = 0LL;
    v18 = v26;
  }
  objc_release(v8);
  objc_release(v4);
  objc_release(v18);
  return v19;
}
// 590: using guessed type void *classRef_FIRInstanceIDAPNSInfo;
// 6F0: using guessed type char *selRef_init;
// 778: using guessed type void *classRef_NSData;
// 3B70: using guessed type int (__fastcall *objc_release)(_QWORD);
// 3B78: using guessed type int (__fastcall *objc_retain)(_QWORD);
// 3B80: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);
// 3B88: using guessed type int __fastcall objc_storeStrong(_QWORD);

//----- (0000000000000206) ----------------------------------------------------
// FIRInstanceIDAPNSInfo - (id)initWithCoder:(id) 
id __cdecl -[FIRInstanceIDAPNSInfo initWithCoder:](struct FIRInstanceIDAPNSInfo *self, SEL a2, id a3)
{
  __int64 v3; // rax@0
  __int64 v4; // ST00_8@1
  struct FIRInstanceIDAPNSInfo *v5; // r15@1
  void *v6; // rax@1
  void *v7; // r14@1
  void *v8; // rax@1
  void *v9; // rax@1
  void *v10; // r12@1
  void *v11; // rax@1
  unsigned __int8 v12; // al@2
  void *v13; // rax@2
  struct FIRInstanceIDAPNSInfo *v14; // rax@2
  struct objc_object *v15; // r13@2

  v4 = v3;
  v5 = self;
  LODWORD(v6) = objc_retain(a3);
  v7 = v6;
  v8 = objc_msgSend(v6, *(&selRef_init + 6), CFSTR(""), v4);
  LODWORD(v9) = objc_retainAutoreleasedReturnValue(v8);
  v10 = v9;
  v11 = objc_msgSend(classRef_NSData, *(&selRef_init + 3));
  if ( (unsigned __int8)objc_msgSend(v10, *(&selRef_init + 4), v11) )
  {
    v12 = (unsigned __int64)objc_msgSend(v7, *(&selRef_init + 7), CFSTR("") + 1);
    v13 = objc_msgSend(self, *(&selRef_init + 8), v10, v12);
    LODWORD(v14) = objc_retainAutoreleasedReturnValue(v13);
    v5 = v14;
    v15 = (struct objc_object *)v14;
  }
  else
  {
    v15 = 0LL;
  }
  objc_release(v10);
  objc_release(v7);
  objc_release(v5);
  return v15;
}
// 4F0: using guessed type __CFString cfstr_Device_token;
// 6F0: using guessed type char *selRef_init;
// 778: using guessed type void *classRef_NSData;
// 3B70: using guessed type int (__fastcall *objc_release)(_QWORD);
// 3B78: using guessed type int (__fastcall *objc_retain)(_QWORD);
// 3B80: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (00000000000002CB) ----------------------------------------------------
// FIRInstanceIDAPNSInfo - (void)encodeWithCoder:(id) 
void __cdecl -[FIRInstanceIDAPNSInfo encodeWithCoder:](struct FIRInstanceIDAPNSInfo *self, SEL a2, id a3)
{
  id v3; // r13@1
  const char *v4; // r12@1
  __int64 v5; // rax@1
  void *v6; // rax@1
  __int64 v7; // rax@1
  __int64 v8; // rbx@1
  unsigned __int8 v9; // al@1
  __int64 v10; // ST00_8@1

  v3 = a3;
  v4 = *(&selRef_init + 9);
  LODWORD(v5) = objc_retain(a3);
  v6 = objc_msgSend(self, v4, v5);
  LODWORD(v7) = objc_retainAutoreleasedReturnValue(v6);
  v8 = v7;
  objc_msgSend(v3, *(&selRef_init + 10), v7, CFSTR(""));
  objc_release(v8);
  v9 = (unsigned __int64)objc_msgSend(self, *(&selRef_init + 11));
  objc_msgSend(v3, *(&selRef_init + 12), v9, CFSTR("") + 1);
  objc_release(v10);
}
// 4F0: using guessed type __CFString cfstr_Device_token;
// 6F0: using guessed type char *selRef_init;
// 3B70: using guessed type int (__fastcall *objc_release)(_QWORD);
// 3B78: using guessed type int (__fastcall *objc_retain)(_QWORD);
// 3B80: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (000000000000036D) ----------------------------------------------------
// FIRInstanceIDAPNSInfo - (bool)isEqualToAPNSInfo:(id) 
bool __cdecl -[FIRInstanceIDAPNSInfo isEqualToAPNSInfo:](struct FIRInstanceIDAPNSInfo *self, SEL a2, id a3)
{
  void *v3; // rax@1
  void *v4; // r13@1
  char v5; // bl@1
  const char *v6; // r12@2
  void *v7; // rax@2
  void *v8; // rax@2
  void *v9; // r15@2
  void *v10; // rax@2
  __int64 v11; // rax@2
  __int64 v12; // r12@2
  int v13; // er14@3
  struct FIRInstanceIDAPNSInfo *v15; // [sp+8h] [bp-38h]@1
  void *v16; // [sp+10h] [bp-30h]@1

  LODWORD(v3) = objc_retain(a3);
  v4 = v3;
  v15 = self;
  v16 = classRef_FIRInstanceIDAPNSInfo;
  v5 = 1;
  if ( !(unsigned __int8)objc_msgSendSuper2(&v15, *(&selRef_init + 13), v3) )
  {
    v6 = *(&selRef_init + 9);
    v7 = objc_msgSend(self, *(&selRef_init + 9));
    LODWORD(v8) = objc_retainAutoreleasedReturnValue(v7);
    v9 = v8;
    v10 = objc_msgSend(v4, v6);
    LODWORD(v11) = objc_retainAutoreleasedReturnValue(v10);
    v12 = v11;
    if ( (unsigned __int8)objc_msgSend(v9, *(&selRef_init + 14), v11) )
    {
      v13 = (unsigned __int64)objc_msgSend(self, *(&selRef_init + 11));
      v5 = v13 ^ (unsigned __int64)objc_msgSend(v4, *(&selRef_init + 11)) ^ 1;
    }
    else
    {
      v5 = 0;
    }
    objc_release(v12);
    objc_release(v9);
  }
  objc_release(v4);
  return v5;
}
// 590: using guessed type void *classRef_FIRInstanceIDAPNSInfo;
// 6F0: using guessed type char *selRef_init;
// 3B70: using guessed type int (__fastcall *objc_release)(_QWORD);
// 3B78: using guessed type int (__fastcall *objc_retain)(_QWORD);
// 3B80: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (000000000000045A) ----------------------------------------------------
// FIRInstanceIDAPNSInfo - (id)deviceToken
id __cdecl -[FIRInstanceIDAPNSInfo deviceToken](struct FIRInstanceIDAPNSInfo *self, SEL a2)
{
  return (id)self->_deviceToken;
}

//----- (000000000000046B) ----------------------------------------------------
// FIRInstanceIDAPNSInfo - (bool)isSandbox
bool __cdecl -[FIRInstanceIDAPNSInfo isSandbox](struct FIRInstanceIDAPNSInfo *self, SEL a2)
{
  return self->_sandbox;
}

//----- (000000000000047B) ----------------------------------------------------
// FIRInstanceIDAPNSInfo - (void).cxx_destruct
void __cdecl -[FIRInstanceIDAPNSInfo .cxx_destruct](struct FIRInstanceIDAPNSInfo *self, SEL a2)
{
  objc_storeStrong(&self->_deviceToken);
}
// 3B88: using guessed type int __fastcall objc_storeStrong(_QWORD);

// ALL OK, 8 function(s) have been successfully decompiled
