/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2015 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int __fastcall _FIRInstanceID_FIRApp__load_(__int64 a1);
int __fastcall _FIRInstanceID_FIRApp__didReceiveConfigureSDKNotification__(__int64 a1, __int64 a2, void *a3);
// int __usercall _FIRInstanceID_FIRApp__configureInstanceIDWithOptions_app__@<eax>(__int64 a1@<rax>, __int64 a2@<rdx>, __int64 a3@<rcx>, void *a4@<rdi>);
int __fastcall _FIRInstanceID_FIRApp__configureErrorWithReason__(__int64 a1, __int64 a2, __int64 a3);
// int __usercall _FIRInstanceID_FIRApp__exitWithReason_forFirebaseApp__@<eax>(__int64 a1@<rax>, __int64 a2@<rdx>, __int64 a3@<rcx>, void *a4@<rdi>);
int __fastcall _FIRInstanceID_FIRApp__sendLogsForFirebaseApp_withError__(__int64 a1, __int64 a2, __int64 a3, __int64 a4);
// int FIRInstanceIDCurrentLibraryVersion(void); weak
// int FIRInstanceIDSharedLogger(void); weak
// int __fastcall NSClassFromString(_QWORD); weak
// int __fastcall NSSelectorFromString(_QWORD); weak
// int __fastcall objc_autoreleaseReturnValue(_QWORD); weak
// void *objc_msgSend(void *, const char *, ...); idb
// int __fastcall objc_retain(_QWORD); weak
// int __fastcall objc_retainAutoreleasedReturnValue(_QWORD); weak

//-------------------------------------------------------------------------
// Data declarations

char aFirappreadytoc[38] = "FIRAppReadyToConfigureSDKNotification"; // weak
__CFString cfstr_Firappreadytoc =
{
  &__CFConstantStringClassReference,
  1992LL,
  "FIRAppReadyToConfigureSDKNotification",
  37LL
}; // weak
void *off_CE8 = &OBJC_CLASS___NSNotificationCenter; // weak
__int64 (__fastcall *paDefaultcenter)() = &aDefaultcenter; // weak
// extern _UNKNOWN NSLocalizedDescriptionKey; weak
// extern _UNKNOWN NSLocalizedFailureReasonErrorKey; weak
// extern _UNKNOWN OBJC_CLASS___NSNotificationCenter; weak
// extern _UNKNOWN __stack_chk_guard; weak
// extern int (__fastcall *objc_release)(_QWORD); weak


//----- (0000000000000000) ----------------------------------------------------
int __fastcall _FIRInstanceID_FIRApp__load_(__int64 a1)
{
  void *v1; // rax@1
  void *v2; // rax@1
  void *v3; // rbx@1
  __int64 v4; // r15@1
  __int64 v5; // rax@1

  v1 = objc_msgSend(&OBJC_CLASS___NSNotificationCenter, (const char *)paDefaultcenter);
  LODWORD(v2) = objc_retainAutoreleasedReturnValue(v1);
  v3 = v2;
  v4 = (__int64)*(&paDefaultcenter + 1);
  LODWORD(v5) = NSClassFromString(&cfstr_Firappreadytoc + 5);
  objc_msgSend(v3, (const char *)*(&paDefaultcenter + 2), a1, v4, &cfstr_Firappreadytoc, v5);
  return objc_release(v3);
}
// A88: using guessed type __CFString cfstr_Firappreadytoc;
// FC8: using guessed type __int64 (__fastcall *paDefaultcenter)();
// 4C40: using guessed type int __fastcall NSClassFromString(_QWORD);
// 4CC0: using guessed type int (__fastcall *objc_release)(_QWORD);
// 4CD0: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000072) ----------------------------------------------------
int __fastcall _FIRInstanceID_FIRApp__didReceiveConfigureSDKNotification__(__int64 a1, __int64 a2, void *a3)
{
  void *v3; // rax@1
  void *v4; // rax@1
  void *v5; // rbx@1
  const char *v6; // r14@1
  void *v7; // rax@1
  void *v8; // rax@1
  void *v9; // r15@1
  void *v10; // rax@3
  __int64 v11; // rax@3
  __int64 v12; // r14@3
  __int64 v13; // rax@3
  __int64 v14; // r13@3
  void *v15; // rax@3
  void *v16; // rbx@3
  void *v17; // rax@4
  void *v18; // rax@4
  void *v19; // r13@4
  __int64 v20; // rbx@5
  void *v21; // rax@6
  __int64 v22; // rax@6
  __int64 v23; // r14@6
  void *v24; // rax@6
  void *v25; // rax@6
  void *v26; // rbx@6
  void *v27; // rax@7
  __int64 v28; // rax@7
  __int64 v29; // rbx@7
  __int64 v30; // rdi@7
  __int64 v31; // rax@8
  void *v32; // rax@8
  void *v33; // r14@8
  void *v35; // [sp+0h] [bp-40h]@3
  void *v36; // [sp+8h] [bp-38h]@3
  __int64 v37; // [sp+10h] [bp-30h]@5

  v3 = objc_msgSend(a3, (const char *)*(&paDefaultcenter + 3));
  LODWORD(v4) = objc_retainAutoreleasedReturnValue(v3);
  v5 = v4;
  v6 = (const char *)*(&paDefaultcenter + 4);
  v7 = objc_msgSend(v4, (const char *)*(&paDefaultcenter + 4), &cfstr_Firappreadytoc + 1);
  LODWORD(v8) = objc_retainAutoreleasedReturnValue(v7);
  v9 = v8;
  if ( v8 && !(unsigned __int8)objc_msgSend(v8, (const char *)*(&paDefaultcenter + 5)) )
  {
    LODWORD(v31) = FIRInstanceIDSharedLogger();
    LODWORD(v32) = objc_retainAutoreleasedReturnValue(v31);
    v33 = v32;
    objc_msgSend(v32, (const char *)*(&paDefaultcenter + 6), &aFirappreadytoc[116], 1002LL, &cfstr_Firappreadytoc + 6);
    objc_release(v33);
  }
  else
  {
    v10 = objc_msgSend(v5, v6, &cfstr_Firappreadytoc + 2, v5, a1);
    LODWORD(v11) = objc_retainAutoreleasedReturnValue(v10);
    v12 = v11;
    LODWORD(v13) = NSSelectorFromString(&cfstr_Firappreadytoc + 7);
    v14 = v13;
    LODWORD(v15) = NSClassFromString(&cfstr_Firappreadytoc + 5);
    v16 = v15;
    if ( (unsigned __int8)objc_msgSend(v15, (const char *)*(&paDefaultcenter + 7), v14)
      && (v17 = objc_msgSend(v16, (const char *)*(&paDefaultcenter + 8), v14, v12),
          LODWORD(v18) = objc_retainAutoreleasedReturnValue(v17),
          (v19 = v18) != 0LL) )
    {
      v37 = v12;
      v20 = (__int64)*(&paDefaultcenter + 11);
      if ( (unsigned __int8)objc_msgSend(v18, (const char *)*(&paDefaultcenter + 7), *(&paDefaultcenter + 11)) )
      {
        v21 = objc_msgSend(v19, (const char *)*(&paDefaultcenter + 12), v20);
        LODWORD(v22) = objc_retainAutoreleasedReturnValue(v21);
        v23 = v22;
        v24 = objc_msgSend(*(&off_CE8 + 2), (const char *)*(&paDefaultcenter + 13));
        LODWORD(v25) = objc_retainAutoreleasedReturnValue(v24);
        v26 = v25;
        objc_msgSend(v25, (const char *)*(&paDefaultcenter + 14), v23, v19);
        objc_release(v26);
        objc_release(v23);
        objc_release(v19);
      }
      else
      {
        objc_msgSend(v36, (const char *)*(&paDefaultcenter + 10), &cfstr_Firappreadytoc + 9, v19);
        objc_release(v19);
      }
      v30 = v37;
    }
    else
    {
      v27 = objc_msgSend(*(&off_CE8 + 1), (const char *)*(&paDefaultcenter + 9), &cfstr_Firappreadytoc + 8, v12);
      LODWORD(v28) = objc_retainAutoreleasedReturnValue(v27);
      v29 = v28;
      objc_msgSend(v36, (const char *)*(&paDefaultcenter + 10), v28, 0LL);
      objc_release(v29);
      v30 = v12;
    }
    objc_release(v30);
    v5 = v35;
  }
  objc_release(v9);
  return objc_release(v5);
}
// A88: using guessed type __CFString cfstr_Firappreadytoc;
// CE8: using guessed type void *off_CE8;
// FC8: using guessed type __int64 (__fastcall *paDefaultcenter)();
// 4C38: using guessed type int FIRInstanceIDSharedLogger(void);
// 4C40: using guessed type int __fastcall NSClassFromString(_QWORD);
// 4C58: using guessed type int __fastcall NSSelectorFromString(_QWORD);
// 4CC0: using guessed type int (__fastcall *objc_release)(_QWORD);
// 4CD0: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (00000000000002D3) ----------------------------------------------------
int __usercall _FIRInstanceID_FIRApp__configureInstanceIDWithOptions_app__@<eax>(__int64 a1@<rax>, __int64 a2@<rdx>, __int64 a3@<rcx>, void *a4@<rdi>)
{
  __int64 v4; // ST00_8@1
  __int64 v5; // rbx@1
  void *v6; // rax@1
  void *v7; // r12@1
  __int64 v8; // rax@1
  __int64 v9; // r13@1
  __int64 v10; // rax@1
  __int64 v11; // rbx@1
  void *v12; // rax@3
  void *v13; // rax@3
  void *v14; // r14@3
  __int64 v15; // rax@4
  __int64 v16; // r13@4
  void *v17; // rax@5
  __int64 v18; // rax@7
  void *v19; // rax@7
  void *v20; // r15@7
  __int64 v22; // [sp+0h] [bp-30h]@4

  v4 = a1;
  v5 = a3;
  LODWORD(v6) = objc_retain(a2);
  v7 = v6;
  LODWORD(v8) = objc_retain(v5);
  v9 = v8;
  LODWORD(v10) = NSSelectorFromString(&cfstr_Firappreadytoc + 10);
  v11 = v10;
  if ( !(unsigned __int8)objc_msgSend(v7, (const char *)*(&paDefaultcenter + 7), v10, v4) )
    objc_msgSend(*(&off_CE8 + 2), (const char *)*(&paDefaultcenter + 10), &cfstr_Firappreadytoc + 11, v9);
  v12 = objc_msgSend(v7, (const char *)*(&paDefaultcenter + 12), v11);
  LODWORD(v13) = objc_retainAutoreleasedReturnValue(v12);
  v14 = v13;
  if ( objc_msgSend(v13, (const char *)*(&paDefaultcenter + 15)) )
  {
    objc_msgSend(a4, (const char *)*(&paDefaultcenter + 17), v14, v9);
    LODWORD(v15) = NSSelectorFromString(&cfstr_Firappreadytoc + 14);
    v16 = v15;
    if ( (unsigned __int8)objc_msgSend(v7, (const char *)*(&paDefaultcenter + 7), v15) )
    {
      v17 = objc_msgSend(v7, (const char *)*(&paDefaultcenter + 12), v16);
      objc_msgSend(a4, (const char *)*(&paDefaultcenter + 18), v17);
    }
    objc_msgSend(a4, (const char *)*(&paDefaultcenter + 19));
    v9 = v22;
  }
  else
  {
    LODWORD(v18) = FIRInstanceIDSharedLogger();
    LODWORD(v19) = objc_retainAutoreleasedReturnValue(v18);
    v20 = v19;
    objc_msgSend(v19, (const char *)*(&paDefaultcenter + 16), &aFirappreadytoc[387], 1000LL, &cfstr_Firappreadytoc + 12);
    objc_release(v20);
    objc_msgSend(*(&off_CE8 + 2), (const char *)*(&paDefaultcenter + 10), &cfstr_Firappreadytoc + 13, v9);
  }
  objc_release(v14);
  objc_release(v9);
  return objc_release(v7);
}
// A88: using guessed type __CFString cfstr_Firappreadytoc;
// CE8: using guessed type void *off_CE8;
// FC8: using guessed type __int64 (__fastcall *paDefaultcenter)();
// 4C38: using guessed type int FIRInstanceIDSharedLogger(void);
// 4C58: using guessed type int __fastcall NSSelectorFromString(_QWORD);
// 4CC0: using guessed type int (__fastcall *objc_release)(_QWORD);
// 4CC8: using guessed type int __fastcall objc_retain(_QWORD);
// 4CD0: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (000000000000045D) ----------------------------------------------------
int __fastcall _FIRInstanceID_FIRApp__configureErrorWithReason__(__int64 a1, __int64 a2, __int64 a3)
{
  __CFString *v3; // rax@1
  __CFString *v4; // r15@1
  void *v5; // rax@1
  __int64 v6; // rax@1
  __int64 v7; // r14@1
  void *v8; // rax@3
  __int64 v9; // rax@3
  __int64 v10; // rbx@3
  void *v11; // rax@3
  __int64 v12; // rax@3
  __int64 v13; // r12@3
  __int64 v14; // rax@3
  __int64 v16; // [sp+0h] [bp-50h]@3
  __int64 v17; // [sp+8h] [bp-48h]@3
  __int64 v18; // [sp+10h] [bp-40h]@3
  __CFString *v19; // [sp+18h] [bp-38h]@3
  __int64 v20; // [sp+20h] [bp-30h]@1

  v20 = *__stack_chk_guard;
  LODWORD(v3) = objc_retain(a3);
  v4 = v3;
  v5 = objc_msgSend(
         *(&off_CE8 + 1),
         (const char *)*(&paDefaultcenter + 9),
         &cfstr_Firappreadytoc + 15,
         &cfstr_Firappreadytoc + 4);
  LODWORD(v6) = objc_retainAutoreleasedReturnValue(v5);
  v7 = v6;
  if ( !objc_msgSend(v4, (const char *)*(&paDefaultcenter + 15)) )
  {
    objc_retain(&cfstr_Firappreadytoc + 16);
    objc_release(v4);
    v4 = &cfstr_Firappreadytoc + 16;
  }
  v16 = *NSLocalizedDescriptionKey;
  v18 = v7;
  v17 = *NSLocalizedFailureReasonErrorKey;
  v19 = v4;
  v8 = objc_msgSend(*(&off_CE8 + 3), (const char *)*(&paDefaultcenter + 20), &v18, v16, v17, v7, v4);
  LODWORD(v9) = objc_retainAutoreleasedReturnValue(v8);
  v10 = v9;
  v11 = objc_msgSend(
          *(&off_CE8 + 4),
          (const char *)*(&paDefaultcenter + 21),
          &cfstr_Firappreadytoc + 3,
          -121LL,
          v9,
          v16,
          v17,
          v18,
          v19);
  LODWORD(v12) = objc_retainAutoreleasedReturnValue(v11);
  v13 = v12;
  objc_release(v10);
  objc_release(v7);
  objc_release(v4);
  v14 = *__stack_chk_guard;
  if ( *__stack_chk_guard == v20 )
    LODWORD(v14) = objc_autoreleaseReturnValue(v13);
  return v14;
}
// A88: using guessed type __CFString cfstr_Firappreadytoc;
// CE8: using guessed type void *off_CE8;
// FC8: using guessed type __int64 (__fastcall *paDefaultcenter)();
// 4CB0: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 4CC0: using guessed type int (__fastcall *objc_release)(_QWORD);
// 4CC8: using guessed type int __fastcall objc_retain(_QWORD);
// 4CD0: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (00000000000005A6) ----------------------------------------------------
int __usercall _FIRInstanceID_FIRApp__exitWithReason_forFirebaseApp__@<eax>(__int64 a1@<rax>, __int64 a2@<rdx>, __int64 a3@<rcx>, void *a4@<rdi>)
{
  __int64 v4; // rbx@1
  __int64 v5; // rax@1
  __int64 v6; // r15@1
  __int64 v7; // rax@2
  __int64 v8; // r13@2
  void *v9; // rax@2
  __int64 v10; // rax@2
  __int64 v11; // rbx@2
  __int64 v13; // [sp-8h] [bp-30h]@1

  v13 = a1;
  v4 = a3;
  LODWORD(v5) = objc_retain(a2);
  v6 = v5;
  if ( v4 )
  {
    LODWORD(v7) = objc_retain(v4);
    v8 = v7;
    v9 = objc_msgSend(a4, (const char *)*(&paDefaultcenter + 22), v6, v13);
    LODWORD(v10) = objc_retainAutoreleasedReturnValue(v9);
    v11 = v10;
    objc_msgSend(a4, (const char *)*(&paDefaultcenter + 23), v8, v10);
    objc_release(v8);
    objc_release(v11);
  }
  objc_msgSend(
    *(&off_CE8 + 5),
    (const char *)*(&paDefaultcenter + 24),
    &cfstr_Firappreadytoc + 3,
    &cfstr_Firappreadytoc + 17,
    v6,
    v13);
  return objc_release(v6);
}
// A88: using guessed type __CFString cfstr_Firappreadytoc;
// CE8: using guessed type void *off_CE8;
// FC8: using guessed type __int64 (__fastcall *paDefaultcenter)();
// 4CC0: using guessed type int (__fastcall *objc_release)(_QWORD);
// 4CC8: using guessed type int __fastcall objc_retain(_QWORD);
// 4CD0: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (000000000000065D) ----------------------------------------------------
int __fastcall _FIRInstanceID_FIRApp__sendLogsForFirebaseApp_withError__(__int64 a1, __int64 a2, __int64 a3, __int64 a4)
{
  __int64 v4; // rbx@1
  void *v5; // rax@1
  void *v6; // r15@1
  __int64 v7; // rax@1
  __int64 v8; // rbx@1
  __int64 v9; // rax@1
  __int64 v10; // r12@1
  void *v11; // rax@2
  __int64 v12; // rax@2
  void *v13; // rax@2
  void *v14; // rax@2
  void *v15; // r13@2
  __int64 v16; // rbx@2
  __int64 v17; // rax@2
  __int64 v18; // rax@2
  __int64 v20; // [sp+8h] [bp-48h]@2
  __CFString *v21; // [sp+10h] [bp-40h]@2
  __int64 v22; // [sp+18h] [bp-38h]@2
  __int64 v23; // [sp+20h] [bp-30h]@1

  v4 = a4;
  LODWORD(v5) = objc_retain(a3);
  v6 = v5;
  LODWORD(v7) = objc_retain(v4);
  v8 = v7;
  v23 = v7;
  LODWORD(v9) = NSSelectorFromString(&cfstr_Firappreadytoc + 18);
  v10 = v9;
  if ( (unsigned __int8)objc_msgSend(v6, (const char *)*(&paDefaultcenter + 7), v9) )
  {
    v11 = objc_msgSend(v6, (const char *)*(&paDefaultcenter + 25), v10);
    LODWORD(v12) = objc_retainAutoreleasedReturnValue(v11);
    v22 = v12;
    v13 = objc_msgSend(*(&off_CE8 + 6), (const char *)*(&paDefaultcenter + 26), v12);
    LODWORD(v14) = objc_retainAutoreleasedReturnValue(v13);
    v15 = v14;
    objc_msgSend(v14, (const char *)*(&paDefaultcenter + 27), v10);
    ((void (__fastcall *)(void *, _QWORD, void *))objc_msgSend)(v15, *(&paDefaultcenter + 28), v6);
    objc_retain(&cfstr_Firappreadytoc + 4);
    v21 = &cfstr_Firappreadytoc + 4;
    v16 = (__int64)*(&paDefaultcenter + 29);
    ((void (__fastcall *)(void *, _QWORD, __CFString **, signed __int64))objc_msgSend)(
      v15,
      *(&paDefaultcenter + 29),
      &v21,
      2LL);
    LODWORD(v17) = FIRInstanceIDCurrentLibraryVersion();
    LODWORD(v18) = objc_retainAutoreleasedReturnValue(v17);
    v20 = v18;
    ((void (__fastcall *)(void *, __int64, __int64 *, signed __int64))objc_msgSend)(v15, v16, &v20, 3LL);
    ((void (__fastcall *)(void *, __int64, __int64 *, signed __int64))objc_msgSend)(v15, v16, &v23, 4LL);
    ((void (__fastcall *)(void *, _QWORD))objc_msgSend)(v15, *(&paDefaultcenter + 30));
    objc_release(v20);
    objc_release(v21);
    objc_release(v15);
    objc_release(v22);
    v8 = v23;
  }
  objc_release(v8);
  return objc_release(v6);
}
// A88: using guessed type __CFString cfstr_Firappreadytoc;
// CE8: using guessed type void *off_CE8;
// FC8: using guessed type __int64 (__fastcall *paDefaultcenter)();
// 4C30: using guessed type int FIRInstanceIDCurrentLibraryVersion(void);
// 4C58: using guessed type int __fastcall NSSelectorFromString(_QWORD);
// 4CC0: using guessed type int (__fastcall *objc_release)(_QWORD);
// 4CC8: using guessed type int __fastcall objc_retain(_QWORD);
// 4CD0: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

// ALL OK, 6 function(s) have been successfully decompiled
