/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2015 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

// __int64 __usercall -[FIRInstanceIDKeyPair init]@<rax>(__int64 a1@<rax>, void *a2@<rdi>);
id __cdecl -[FIRInstanceIDKeyPair initWithPrivateKey:publicKey:publicKeyData:privateKeyData:](struct FIRInstanceIDKeyPair *self, SEL, struct __SecKey *, struct __SecKey *, id, id);
void __cdecl -[FIRInstanceIDKeyPair dealloc](struct FIRInstanceIDKeyPair *self, SEL);
id __cdecl +[FIRInstanceIDKeyPair generateRSA2048KeyPairWithPrivateTag:publicTag:error:](struct FIRInstanceIDKeyPair *self, SEL, id, id, id *);
id __cdecl +[FIRInstanceIDKeyPair keyPairForPrivateKeyTag:publicKeyTag:error:](struct FIRInstanceIDKeyPair *self, SEL, id, id, id *);
id __cdecl +[FIRInstanceIDKeyPair queryDictWithTag:addReturnAttr:withTypeData:](struct FIRInstanceIDKeyPair *self, SEL, id, bool, bool);
id __cdecl +[FIRInstanceIDKeyPair keyDataWithTag:](struct FIRInstanceIDKeyPair *self, SEL, id);
struct __SecKey *__cdecl +[FIRInstanceIDKeyPair cachedKeyRefWithTag:](struct FIRInstanceIDKeyPair *self, SEL, id);
bool __cdecl +[FIRInstanceIDKeyPair deleteKeyPairWithPrivateTag:publicTag:error:](struct FIRInstanceIDKeyPair *self, SEL, id, id, id *);
bool __cdecl -[FIRInstanceIDKeyPair isValid](struct FIRInstanceIDKeyPair *self, SEL);
struct __SecKey *__cdecl -[FIRInstanceIDKeyPair publicKey](struct FIRInstanceIDKeyPair *self, SEL);
struct __SecKey *__cdecl -[FIRInstanceIDKeyPair privateKey](struct FIRInstanceIDKeyPair *self, SEL);
id __cdecl +[FIRInstanceIDKeyPair appIdentityWithKeyPair:](struct FIRInstanceIDKeyPair *self, SEL, id);
id __cdecl -[FIRInstanceIDKeyPair publicKeyData](struct FIRInstanceIDKeyPair *self, SEL);
void __cdecl -[FIRInstanceIDKeyPair setPublicKeyData:](struct FIRInstanceIDKeyPair *self, SEL, id);
id __cdecl -[FIRInstanceIDKeyPair privateKeyData](struct FIRInstanceIDKeyPair *self, SEL);
void __cdecl -[FIRInstanceIDKeyPair setPrivateKeyData:](struct FIRInstanceIDKeyPair *self, SEL, id);
void __cdecl -[FIRInstanceIDKeyPair .cxx_destruct](struct FIRInstanceIDKeyPair *self, SEL);
// int __fastcall CFRelease(_QWORD, _QWORD); weak
// int __fastcall FIRInstanceIDSHA1(_QWORD); weak
// int FIRInstanceIDSharedLogger(void); weak
// int __fastcall FIRInstanceIDWebSafeBase64(_QWORD); weak
// int __fastcall SecItemCopyMatching(_QWORD, _QWORD); weak
// int __fastcall SecItemDelete(_QWORD); weak
// int __fastcall SecItemUpdate(_QWORD, _QWORD); weak
// int __fastcall SecKeyGeneratePair(_QWORD); weak
// int __fastcall objc_autorelease(_QWORD); weak
// int __fastcall objc_autoreleaseReturnValue(_QWORD); weak
// void *objc_msgSend(void *, const char *, ...); idb
// void *objc_msgSendSuper2(void *, const char *, ...); idb
// int __fastcall objc_release(_QWORD); weak
// int __fastcall objc_retain(_QWORD, _QWORD); weak
// int __fastcall objc_retainAutorelease(_QWORD); weak
// int __fastcall objc_retainAutoreleasedReturnValue(_QWORD); weak
// int __fastcall objc_storeStrong(_QWORD, _QWORD); weak

//-------------------------------------------------------------------------
// Data declarations

char *selRef_class = "class"; // weak
void *classRef_FIRInstanceIDKeyPair_0 = &OBJC_CLASS___FIRInstanceIDKeyPair; // weak
void *classRef_NSNumber = &OBJC_CLASS___NSNumber; // weak
char aFirinstanceidk[78] = "+[FIRInstanceIDKeyPair generateRSA2048KeyPairWithPrivateTag:publicTag:error:]"; // weak
__CFString cfstr_CouldNotUpdate =
{
  &__CFConstantStringClassReference,
  1992LL,
  "Could not update attributes of the key pair to be accessible after first unlock. Public Key update status: %d, Private Keyupdate status: %d",
  139LL
}; // weak
// extern _UNKNOWN __stack_chk_guard; weak
// extern _UNKNOWN kFIRInstanceIDDomain; weak
// extern _UNKNOWN kSecAttrAccessible; weak
// extern _UNKNOWN kSecAttrAccessibleAlwaysThisDeviceOnly; weak
// extern _UNKNOWN kSecAttrApplicationTag; weak
// extern _UNKNOWN kSecAttrIsPermanent; weak
// extern _UNKNOWN kSecAttrKeySizeInBits; weak
// extern _UNKNOWN kSecAttrKeyType; weak
// extern _UNKNOWN kSecAttrKeyTypeRSA; weak
// extern _UNKNOWN kSecClass; weak
// extern _UNKNOWN kSecClassKey; weak
// extern _UNKNOWN kSecPrivateKeyAttrs; weak
// extern _UNKNOWN kSecPublicKeyAttrs; weak
// extern _UNKNOWN kSecReturnData; weak
// extern _UNKNOWN kSecReturnRef; weak


//----- (0000000000000000) ----------------------------------------------------
__int64 __usercall -[FIRInstanceIDKeyPair init]@<rax>(__int64 a1@<rax>, void *a2@<rdi>)
{
  objc_msgSend(a2, selRef_class, a1);
  objc_release(a2);
  return 0LL;
}
// 1268: using guessed type char *selRef_class;
// 7428: using guessed type int __fastcall objc_release(_QWORD);

//----- (0000000000000028) ----------------------------------------------------
// FIRInstanceIDKeyPair - (id)initWithPrivateKey:(struct __SecKey *) publicKey:(struct __SecKey *) publicKeyData:(id) privateKeyData:(id) 
id __cdecl -[FIRInstanceIDKeyPair initWithPrivateKey:publicKey:publicKeyData:privateKeyData:](struct FIRInstanceIDKeyPair *self, SEL a2, struct __SecKey *a3, struct __SecKey *a4, id a5, id a6)
{
  id v6; // r15@1
  id v7; // r13@1
  struct __SecKey *v8; // r14@1
  __int64 v9; // rax@1
  __int64 v10; // rax@1
  __int64 v11; // r12@1
  struct objc_object *v12; // rax@1
  struct objc_object *v13; // rbx@1
  struct FIRInstanceIDKeyPair *v15; // [sp+8h] [bp-48h]@1
  void *v16; // [sp+10h] [bp-40h]@1
  __int64 v17; // [sp+18h] [bp-38h]@1
  struct __SecKey *v18; // [sp+20h] [bp-30h]@1

  v6 = a6;
  v7 = a5;
  v18 = a4;
  v8 = a3;
  LODWORD(v9) = objc_retain(a5, a2);
  v17 = v9;
  LODWORD(v10) = objc_retain(v6, a2);
  v11 = v10;
  v15 = self;
  v16 = classRef_FIRInstanceIDKeyPair_0;
  v12 = (struct objc_object *)objc_msgSendSuper2(&v15, *(&selRef_class + 1));
  v13 = v12;
  if ( v12 )
  {
    v12[1].isa = (Class)v8;
    v12[2].isa = (Class)v18;
    objc_storeStrong(&v12[3], v7);
    objc_storeStrong(&v13[4], v6);
  }
  objc_release(v11);
  objc_release(v17);
  return v13;
}
// 1268: using guessed type char *selRef_class;
// 1388: using guessed type void *classRef_FIRInstanceIDKeyPair_0;
// 7428: using guessed type int __fastcall objc_release(_QWORD);
// 7430: using guessed type int __fastcall objc_retain(_QWORD, _QWORD);
// 7448: using guessed type int __fastcall objc_storeStrong(_QWORD, _QWORD);

//----- (00000000000000ED) ----------------------------------------------------
// FIRInstanceIDKeyPair - (void)dealloc
void __cdecl -[FIRInstanceIDKeyPair dealloc](struct FIRInstanceIDKeyPair *self, SEL a2)
{
  struct FIRInstanceIDKeyPair *v2; // rbx@1
  struct FIRInstanceIDKeyPair::__SecKey *v3; // rdi@1
  struct FIRInstanceIDKeyPair::__SecKey *v4; // rdi@3
  struct FIRInstanceIDKeyPair *v5; // [sp+8h] [bp-18h]@5
  void *v6; // [sp+10h] [bp-10h]@5

  v2 = self;
  v3 = self->_privateKey;
  if ( v3 )
    CFRelease(v3, a2);
  v4 = v2->_publicKey;
  if ( v4 )
    CFRelease(v4, a2);
  v5 = v2;
  v6 = classRef_FIRInstanceIDKeyPair_0;
  objc_msgSendSuper2(&v5, *(&selRef_class + 2));
}
// 1268: using guessed type char *selRef_class;
// 1388: using guessed type void *classRef_FIRInstanceIDKeyPair_0;
// 7300: using guessed type int __fastcall CFRelease(_QWORD, _QWORD);

//----- (0000000000000148) ----------------------------------------------------
// FIRInstanceIDKeyPair + (id)generateRSA2048KeyPairWithPrivateTag:(id) publicTag:(id) error:(id *) 
id __cdecl +[FIRInstanceIDKeyPair generateRSA2048KeyPairWithPrivateTag:publicTag:error:](struct FIRInstanceIDKeyPair *self, SEL a2, id a3, id a4, id *a5)
{
  id v5; // r15@1
  id *v6; // rax@1
  id *v7; // rbx@1
  void *v8; // rax@1
  const char *v9; // r14@1
  void *v10; // rax@1
  __int64 v11; // rax@1
  void *v12; // rax@1
  __int64 v13; // rax@1
  __int64 v14; // r14@1
  __int64 v15; // r13@1
  void *v16; // rax@1
  __int64 v17; // rax@1
  __int64 v18; // rbx@1
  __int64 v19; // r15@1
  void *v20; // rax@1
  __int64 v21; // rax@1
  void *v22; // rax@1
  __int64 v23; // rax@1
  __int64 v24; // r14@1
  __int64 v25; // rax@1
  id *v26; // rax@1
  id *v27; // r15@1
  __int64 v28; // rax@1
  __int64 v29; // rax@1
  __int64 v30; // rbx@1
  const char *v31; // r15@1
  __int64 v32; // rax@1
  id *v33; // rax@1
  id *v34; // r13@1
  int v35; // eax@1
  void *v36; // rax@4
  __int64 v37; // rax@4
  __int64 v38; // r14@4
  struct FIRInstanceIDKeyPair *v39; // rbx@4
  __int64 v40; // r13@4
  void *v41; // rax@4
  __int64 v42; // rax@4
  __int64 v43; // r12@4
  void *v44; // rax@4
  __int64 v45; // rax@4
  __int64 v46; // rbx@4
  int v47; // er12@4
  int v48; // ebx@4
  __int64 v49; // rax@5
  void *v50; // rax@5
  void *v51; // r13@5
  void *v52; // rdi@5
  const char *v53; // r12@6
  struct FIRInstanceIDKeyPair *v54; // rbx@6
  void *v55; // rax@6
  __int64 v56; // rax@6
  __int64 v57; // r13@6
  void *v58; // rax@6
  __int64 v59; // rax@6
  __int64 v60; // rbx@6
  void *v61; // rax@6
  void (__fastcall *v62)(id *); // r15@6
  __int64 v63; // r14@6
  __int64 v64; // r12@6
  __int64 v65; // rbx@6
  id *v66; // rbx@7
  void *v67; // rdi@8
  __int64 v68; // rdx@8
  const char *v69; // rsi@8
  void *v70; // rax@8
  __int64 v71; // rax@8
  struct objc_object *v72; // rax@8
  id result; // rax@11
  __int64 v74; // [sp+0h] [bp-130h]@0
  id *v75; // [sp+8h] [bp-128h]@1
  __int64 v76; // [sp+10h] [bp-120h]@4
  __int64 v77; // [sp+18h] [bp-118h]@4
  __int64 v78; // [sp+20h] [bp-110h]@4
  __int64 v79; // [sp+28h] [bp-108h]@1
  __int64 v80; // [sp+30h] [bp-100h]@1
  id *v81; // [sp+38h] [bp-F8h]@1
  id *v82; // [sp+40h] [bp-F0h]@1
  __int64 v83; // [sp+48h] [bp-E8h]@1
  id *v84; // [sp+50h] [bp-E0h]@1
  __int64 v85; // [sp+58h] [bp-D8h]@1
  void *v86; // [sp+60h] [bp-D0h]@1
  struct FIRInstanceIDKeyPair *v87; // [sp+68h] [bp-C8h]@1
  __int64 v88; // [sp+70h] [bp-C0h]@4
  __int64 v89; // [sp+78h] [bp-B8h]@4
  __int64 v90; // [sp+80h] [bp-B0h]@1
  __int64 v91; // [sp+88h] [bp-A8h]@1
  __int64 v92; // [sp+90h] [bp-A0h]@1
  __int64 v93; // [sp+98h] [bp-98h]@1
  __int64 v94; // [sp+A0h] [bp-90h]@1
  __int64 v95; // [sp+A8h] [bp-88h]@1
  __int64 v96; // [sp+B0h] [bp-80h]@1
  id *v97; // [sp+B8h] [bp-78h]@1
  __int64 v98; // [sp+C0h] [bp-70h]@1
  __int64 v99; // [sp+C8h] [bp-68h]@1
  __int64 v100; // [sp+D0h] [bp-60h]@1
  __int64 v101; // [sp+D8h] [bp-58h]@1
  __int64 v102; // [sp+E0h] [bp-50h]@1
  __int64 v103; // [sp+E8h] [bp-48h]@1
  __int64 v104; // [sp+F0h] [bp-40h]@1
  __int64 v105; // [sp+F8h] [bp-38h]@1
  __int64 v106; // [sp+100h] [bp-30h]@1

  v84 = a5;
  v5 = a4;
  v87 = self;
  v106 = *__stack_chk_guard;
  LODWORD(v6) = objc_retain(a3, a2);
  v7 = v6;
  LODWORD(v8) = objc_retain(v5, a2);
  v9 = *(&selRef_class + 3);
  v86 = v8;
  v10 = objc_msgSend(v8, v9, 4LL);
  LODWORD(v11) = objc_retainAutoreleasedReturnValue(v10);
  v85 = v11;
  v82 = v7;
  v12 = objc_msgSend(v7, v9, 4LL);
  LODWORD(v13) = objc_retainAutoreleasedReturnValue(v12);
  v14 = v13;
  v102 = *kSecAttrIsPermanent;
  v15 = v102;
  v16 = objc_msgSend(classRef_NSNumber, *(&selRef_class + 4), 1LL);
  LODWORD(v17) = objc_retainAutoreleasedReturnValue(v16);
  v18 = v17;
  v104 = v17;
  v103 = *kSecAttrApplicationTag;
  v19 = v103;
  v83 = v14;
  v105 = v14;
  v20 = objc_msgSend(*(&classRef_NSNumber + 1), *(&selRef_class + 5), &v104, &v102);
  LODWORD(v21) = objc_retainAutoreleasedReturnValue(v20);
  v81 = (id *)v21;
  objc_release(v18);
  v98 = v15;
  v22 = objc_msgSend(classRef_NSNumber, *(&selRef_class + 4), 1LL);
  LODWORD(v23) = objc_retainAutoreleasedReturnValue(v22);
  v24 = v23;
  v100 = v23;
  v99 = v19;
  v101 = v85;
  LODWORD(v25) = ((int (__fastcall *)(_QWORD, _QWORD, __int64 *, __int64 *, signed __int64))objc_msgSend)(
                   *(&classRef_NSNumber + 1),
                   *(&selRef_class + 5),
                   &v100,
                   &v98,
                   2LL);
  LODWORD(v26) = objc_retainAutoreleasedReturnValue(v25);
  v27 = v26;
  objc_release(v24);
  v90 = *kSecAttrKeyType;
  v94 = *kSecAttrKeyTypeRSA;
  v91 = *kSecAttrKeySizeInBits;
  LODWORD(v28) = ((int (__fastcall *)(void *, _QWORD, signed __int64))objc_msgSend)(
                   classRef_NSNumber,
                   *(&selRef_class + 6),
                   2048LL);
  LODWORD(v29) = objc_retainAutoreleasedReturnValue(v28);
  v30 = v29;
  v95 = v29;
  v92 = *kSecPrivateKeyAttrs;
  v96 = (__int64)v81;
  v93 = *kSecPublicKeyAttrs;
  v75 = v27;
  v97 = v27;
  v31 = *(&selRef_class + 5);
  LODWORD(v32) = ((int (__fastcall *)(_QWORD, _QWORD, __int64 *, __int64 *, signed __int64))objc_msgSend)(
                   *(&classRef_NSNumber + 1),
                   *(&selRef_class + 5),
                   &v94,
                   &v90,
                   4LL);
  LODWORD(v33) = objc_retainAutoreleasedReturnValue(v32);
  v34 = v33;
  objc_release(v30);
  v79 = 0LL;
  v80 = 0LL;
  v35 = SecKeyGeneratePair(v34);
  if ( !v35 && v80 && v79 )
  {
    v84 = v34;
    v88 = *kSecAttrAccessible;
    v89 = *kSecAttrAccessibleAlwaysThisDeviceOnly;
    v36 = objc_msgSend(*(&classRef_NSNumber + 1), v31, &v89);
    LODWORD(v37) = objc_retainAutoreleasedReturnValue(v36);
    v38 = v37;
    v39 = v87;
    v40 = (__int64)v86;
    v41 = objc_msgSend(v87, *(&selRef_class + 8), v86, 0LL, 0LL);
    LODWORD(v42) = objc_retainAutoreleasedReturnValue(v41);
    v43 = v42;
    v44 = objc_msgSend(v39, *(&selRef_class + 8), v82, 0LL);
    LODWORD(v45) = objc_retainAutoreleasedReturnValue(v44);
    v46 = v45;
    v77 = v43;
    v47 = SecItemUpdate(v43, v38);
    v78 = v46;
    v76 = v38;
    v48 = SecItemUpdate(v46, v38);
    if ( v47 | v48 )
    {
      LODWORD(v49) = FIRInstanceIDSharedLogger();
      LODWORD(v50) = objc_retainAutoreleasedReturnValue(v49);
      v51 = v50;
      LODWORD(v74) = v48;
      objc_msgSend(
        v50,
        *(&selRef_class + 9),
        "+[FIRInstanceIDKeyPair generateRSA2048KeyPairWithPrivateTag:publicTag:error:]",
        9003LL,
        &cfstr_CouldNotUpdate,
        (unsigned int)v47,
        v74,
        v75,
        v38,
        v77,
        v78);
      v52 = v51;
      v40 = (__int64)v86;
      objc_release(v52);
    }
    v53 = *(&selRef_class + 10);
    v54 = v87;
    v55 = objc_msgSend(v87, *(&selRef_class + 10), v40);
    LODWORD(v56) = objc_retainAutoreleasedReturnValue(v55);
    v57 = v56;
    v58 = objc_msgSend(v54, v53);
    LODWORD(v59) = objc_retainAutoreleasedReturnValue(v58);
    v60 = v59;
    v61 = objc_msgSend(*(&classRef_NSNumber + 3), *(&selRef_class + 11));
    v87 = (struct FIRInstanceIDKeyPair *)objc_msgSend(v61, *(&selRef_class + 12), v79, v80, v57, v60);
    v62 = (void (__fastcall *)(id *))objc_release;
    objc_release(v60);
    v63 = (__int64)v86;
    objc_release(v57);
    objc_release(v78);
    objc_release(v77);
    objc_release(v76);
    v64 = v85;
    v65 = v83;
    v34 = v84;
  }
  else
  {
    v62 = (void (__fastcall *)(id *))objc_release;
    v66 = v84;
    if ( v84 )
    {
      v67 = *(&classRef_NSNumber + 2);
      v68 = *kFIRInstanceIDDomain;
      v69 = *(&selRef_class + 7);
      v87 = 0LL;
      v70 = objc_msgSend(v67, v69, v68, v35, 0LL);
      LODWORD(v71) = objc_retainAutoreleasedReturnValue(v70);
      LODWORD(v72) = objc_autorelease(v71);
      *v66 = v72;
    }
    else
    {
      v87 = 0LL;
    }
    v63 = (__int64)v86;
    v65 = v83;
    v64 = v85;
  }
  v62(v34);
  v62(v75);
  v62(v81);
  v62((id *)v65);
  v62((id *)v64);
  v62((id *)v63);
  v62(v82);
  result = (id)*__stack_chk_guard;
  if ( *__stack_chk_guard == v106 )
    LODWORD(result) = objc_autoreleaseReturnValue(v87);
  return result;
}
// 1268: using guessed type char *selRef_class;
// 13B0: using guessed type void *classRef_NSNumber;
// 1648: using guessed type __CFString cfstr_CouldNotUpdate;
// 7310: using guessed type int FIRInstanceIDSharedLogger(void);
// 7368: using guessed type int __fastcall SecItemUpdate(_QWORD, _QWORD);
// 7370: using guessed type int __fastcall SecKeyGeneratePair(_QWORD);
// 7408: using guessed type int __fastcall objc_autorelease(_QWORD);
// 7410: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 7428: using guessed type int __fastcall objc_release(_QWORD);
// 7430: using guessed type int __fastcall objc_retain(_QWORD, _QWORD);
// 7440: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (00000000000006BC) ----------------------------------------------------
// FIRInstanceIDKeyPair + (id)keyPairForPrivateKeyTag:(id) publicKeyTag:(id) error:(id *) 
id __cdecl +[FIRInstanceIDKeyPair keyPairForPrivateKeyTag:publicKeyTag:error:](struct FIRInstanceIDKeyPair *self, SEL a2, id a3, id a4, id *a5)
{
  id *v5; // r12@1
  id v6; // rbx@1
  void *v7; // rax@1
  void *v8; // r15@1
  void *v9; // rax@1
  void *v10; // r14@1
  const char *v11; // rbx@1
  void *v12; // rbx@3
  void *v13; // rax@3
  __int64 v14; // r15@5
  void *v15; // ST10_8@5
  void *v16; // rax@5
  __int64 v17; // rax@5
  __int64 v18; // r12@5
  __int64 v19; // rsi@5
  __int64 v20; // rax@5
  __int64 v21; // rax@5
  __int64 v22; // rbx@5
  __int64 v23; // rax@5
  __int64 v24; // rax@5
  __int64 v25; // r13@5
  void *v26; // rax@7
  __int64 v27; // rax@7
  struct objc_object *v28; // rax@7
  void *v29; // rax@10
  __int64 v30; // rax@10
  struct objc_object *v31; // rax@10
  __int64 v32; // rax@11
  void *v33; // rax@11
  void *v34; // r12@11
  id result; // rax@12
  void *v36; // [sp+8h] [bp-48h]@3
  void *v37; // [sp+18h] [bp-38h]@3

  v5 = a5;
  v6 = a4;
  LODWORD(v7) = objc_retain(a3, a2);
  v8 = v7;
  LODWORD(v9) = objc_retain(v6, a2);
  v10 = v9;
  v11 = *(&selRef_class + 13);
  if ( objc_msgSend(v8, *(&selRef_class + 13)) && objc_msgSend(v10, v11) )
  {
    v37 = v8;
    v12 = objc_msgSend(self, *(&selRef_class + 15));
    v13 = objc_msgSend(self, *(&selRef_class + 15), v10);
    v36 = v12;
    if ( v12 && v13 )
    {
      v14 = (__int64)*(&selRef_class + 10);
      v15 = v13;
      v16 = objc_msgSend(self, *(&selRef_class + 10), v10);
      LODWORD(v17) = objc_retainAutoreleasedReturnValue(v16);
      v18 = v17;
      v19 = v14;
      v8 = v37;
      LODWORD(v20) = ((int (__fastcall *)(struct FIRInstanceIDKeyPair *, __int64, void *))objc_msgSend)(self, v19, v37);
      LODWORD(v21) = objc_retainAutoreleasedReturnValue(v20);
      v22 = v21;
      LODWORD(v23) = ((int (__fastcall *)(_QWORD, _QWORD))objc_msgSend)(
                       *(&classRef_NSNumber + 3),
                       *(&selRef_class + 11));
      LODWORD(v24) = ((int (__fastcall *)(__int64, _QWORD, void *, void *, __int64, __int64))objc_msgSend)(
                       v23,
                       *(&selRef_class + 12),
                       v36,
                       v15,
                       v18,
                       v22);
      v25 = v24;
      objc_release(v22);
      objc_release(v18);
    }
    else
    {
      if ( v5 )
      {
        v29 = objc_msgSend(*(&classRef_NSNumber + 2), *(&selRef_class + 14), 2001LL);
        LODWORD(v30) = objc_retainAutoreleasedReturnValue(v29);
        LODWORD(v31) = objc_autorelease(v30);
        *v5 = v31;
      }
      LODWORD(v32) = FIRInstanceIDSharedLogger();
      LODWORD(v33) = objc_retainAutoreleasedReturnValue(v32);
      v34 = v33;
      v25 = 0LL;
      objc_msgSend(v33, *(&selRef_class + 16), &aFirinstanceidk[218], 9000LL, &cfstr_CouldNotUpdate + 1, v8);
      objc_release(v34);
    }
  }
  else
  {
    if ( v5 )
    {
      v26 = objc_msgSend(*(&classRef_NSNumber + 2), *(&selRef_class + 14), 2002LL);
      LODWORD(v27) = objc_retainAutoreleasedReturnValue(v26);
      LODWORD(v28) = objc_autorelease(v27);
      *v5 = v28;
    }
    v25 = 0LL;
  }
  objc_release(v10);
  objc_release(v8);
  LODWORD(result) = objc_autoreleaseReturnValue(v25);
  return result;
}
// 1268: using guessed type char *selRef_class;
// 13B0: using guessed type void *classRef_NSNumber;
// 1648: using guessed type __CFString cfstr_CouldNotUpdate;
// 7310: using guessed type int FIRInstanceIDSharedLogger(void);
// 7408: using guessed type int __fastcall objc_autorelease(_QWORD);
// 7410: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 7428: using guessed type int __fastcall objc_release(_QWORD);
// 7430: using guessed type int __fastcall objc_retain(_QWORD, _QWORD);
// 7440: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (00000000000008DB) ----------------------------------------------------
// FIRInstanceIDKeyPair + (id)queryDictWithTag:(id) addReturnAttr:(bool) withTypeData:(bool) 
id __cdecl +[FIRInstanceIDKeyPair queryDictWithTag:addReturnAttr:withTypeData:](struct FIRInstanceIDKeyPair *self, SEL a2, id a3, bool a4, bool a5)
{
  bool v5; // ST10_1@1
  id v6; // r14@1
  void *v7; // rbx@1
  const char *v8; // r15@1
  __int64 v9; // rax@1
  __int64 v10; // r12@1
  void *v11; // rax@1
  void *v12; // rax@1
  void *v13; // r15@1
  void *v14; // rbx@1
  __int64 v15; // rax@1
  __int64 v16; // r14@1
  const char *v17; // r12@1
  __int64 *v18; // rax@3
  __int64 v19; // ST10_8@5
  void *v20; // rax@5
  __int64 v21; // rax@5
  __int64 v22; // rbx@5
  id result; // rax@6
  bool v24; // [sp+Ch] [bp-34h]@1

  v24 = a5;
  v5 = a4;
  v6 = a3;
  v7 = *(&classRef_NSNumber + 4);
  v8 = *(&selRef_class + 17);
  LODWORD(v9) = objc_retain(a3, a2);
  v10 = v9;
  v11 = objc_msgSend(v7, v8);
  LODWORD(v12) = objc_retainAutoreleasedReturnValue(v11);
  v13 = v12;
  v14 = objc_msgSend(v6, *(&selRef_class + 3), 4LL);
  objc_release(v10);
  LODWORD(v15) = objc_retainAutoreleasedReturnValue(v14);
  v16 = v15;
  v17 = *(&selRef_class + 18);
  objc_msgSend(v13, *(&selRef_class + 18), *kSecClassKey, *kSecClass);
  objc_msgSend(v13, v17, v16, *kSecAttrApplicationTag);
  objc_msgSend(v13, v17, *kSecAttrKeyTypeRSA, *kSecAttrKeyType);
  if ( v5 )
  {
    if ( v24 )
      v18 = (__int64 *)kSecReturnData;
    else
      v18 = (__int64 *)kSecReturnRef;
    v19 = *v18;
    v20 = objc_msgSend(classRef_NSNumber, *(&selRef_class + 4), 1LL);
    LODWORD(v21) = objc_retainAutoreleasedReturnValue(v20);
    v22 = v21;
    objc_msgSend(v13, v17, v21);
    objc_release(v22);
  }
  objc_release(v16);
  LODWORD(result) = objc_autoreleaseReturnValue(v13);
  return result;
}
// 1268: using guessed type char *selRef_class;
// 13B0: using guessed type void *classRef_NSNumber;
// 7410: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 7428: using guessed type int __fastcall objc_release(_QWORD);
// 7430: using guessed type int __fastcall objc_retain(_QWORD, _QWORD);
// 7440: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000A29) ----------------------------------------------------
// FIRInstanceIDKeyPair + (id)keyDataWithTag:(id) 
id __cdecl +[FIRInstanceIDKeyPair keyDataWithTag:](struct FIRInstanceIDKeyPair *self, SEL a2, id a3)
{
  __int64 v3; // rax@0
  void *v4; // rax@1
  void *v5; // r15@1
  void *v6; // rax@2
  __int64 v7; // rax@2
  __int64 v8; // r14@2
  __int64 v9; // rbx@5
  __int64 v10; // rax@7
  id result; // rax@9
  __int64 v12; // [sp+0h] [bp-20h]@1

  v12 = v3;
  LODWORD(v4) = objc_retain(a3, a2);
  v5 = v4;
  if ( objc_msgSend(v4, *(&selRef_class + 13), v12) )
  {
    v6 = objc_msgSend(self, *(&selRef_class + 8), v5, 1LL, 1LL, v12);
    LODWORD(v7) = objc_retainAutoreleasedReturnValue(v6);
    v8 = v7;
    v12 = 0LL;
    if ( SecItemCopyMatching(v7, &v12) )
    {
      if ( v12 )
        CFRelease(v12, &v12);
      v9 = 0LL;
    }
    else
    {
      LODWORD(v10) = objc_retain(v12, &v12);
      v9 = v10;
    }
    objc_release(v8);
  }
  else
  {
    v9 = 0LL;
  }
  objc_release(v5);
  LODWORD(result) = objc_autoreleaseReturnValue(v9);
  return result;
}
// 1268: using guessed type char *selRef_class;
// 7300: using guessed type int __fastcall CFRelease(_QWORD, _QWORD);
// 7358: using guessed type int __fastcall SecItemCopyMatching(_QWORD, _QWORD);
// 7410: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 7428: using guessed type int __fastcall objc_release(_QWORD);
// 7430: using guessed type int __fastcall objc_retain(_QWORD, _QWORD);
// 7440: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000ADC) ----------------------------------------------------
// FIRInstanceIDKeyPair + (struct __SecKey *)cachedKeyRefWithTag:(id) 
struct __SecKey *__cdecl +[FIRInstanceIDKeyPair cachedKeyRefWithTag:](struct FIRInstanceIDKeyPair *self, SEL a2, id a3)
{
  void *v3; // rax@1
  void *v4; // r14@1
  struct __SecKey *v5; // rbx@2
  void *v6; // rax@2
  __int64 v7; // rax@2
  __int64 v8; // r15@2
  struct __SecKey *v10; // [sp+8h] [bp-28h]@2

  LODWORD(v3) = objc_retain(a3, a2);
  v4 = v3;
  if ( objc_msgSend(v3, *(&selRef_class + 13)) )
  {
    v5 = 0LL;
    v6 = objc_msgSend(self, *(&selRef_class + 8), v4, 1LL, 0LL);
    LODWORD(v7) = objc_retainAutoreleasedReturnValue(v6);
    v8 = v7;
    v10 = 0LL;
    if ( !SecItemCopyMatching(v7, &v10) )
      v5 = v10;
    objc_release(v8);
  }
  else
  {
    v5 = 0LL;
  }
  objc_release(v4);
  return v5;
}
// 1268: using guessed type char *selRef_class;
// 7358: using guessed type int __fastcall SecItemCopyMatching(_QWORD, _QWORD);
// 7428: using guessed type int __fastcall objc_release(_QWORD);
// 7430: using guessed type int __fastcall objc_retain(_QWORD, _QWORD);
// 7440: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000B77) ----------------------------------------------------
// FIRInstanceIDKeyPair + (bool)deleteKeyPairWithPrivateTag:(id) publicTag:(id) error:(id *) 
bool __cdecl +[FIRInstanceIDKeyPair deleteKeyPairWithPrivateTag:publicTag:error:](struct FIRInstanceIDKeyPair *self, SEL a2, id a3, id a4, id *a5)
{
  id *v5; // ST00_8@1
  id v6; // r14@1
  __int64 v7; // rax@1
  __int64 v8; // r15@1
  const char *v9; // r13@1
  void *v10; // rax@1
  __int64 v11; // rax@1
  __int64 v12; // r14@1
  void *v13; // rbx@1
  __int64 v14; // rax@1
  __int64 v15; // r12@1
  int v16; // er13@1
  int v17; // eax@1
  bool v18; // r15@1
  void *v19; // rax@6
  __int64 v20; // rax@6
  __int64 v21; // rax@6
  __int64 v22; // rax@7
  void *v23; // rax@7
  void *v24; // rbx@7
  _QWORD *v26; // [sp+0h] [bp-30h]@1

  v5 = a5;
  v6 = a4;
  LODWORD(v7) = objc_retain(a3, a2);
  v8 = v7;
  v9 = *(&selRef_class + 8);
  v10 = objc_msgSend(self, *(&selRef_class + 8), v6, 0LL, 0LL, v5);
  LODWORD(v11) = objc_retainAutoreleasedReturnValue(v10);
  v12 = v11;
  v13 = objc_msgSend(self, v9, v8, 0LL, 0LL);
  objc_release(v8);
  LODWORD(v14) = objc_retainAutoreleasedReturnValue(v13);
  v15 = v14;
  v16 = SecItemDelete(v14);
  v17 = SecItemDelete(v12);
  v18 = 1;
  if ( v17 != -25300 && v16 && v16 != -25300 && v17 )
  {
    if ( v26 )
    {
      v19 = objc_msgSend(*(&classRef_NSNumber + 2), *(&selRef_class + 14), 2001LL);
      LODWORD(v20) = objc_retainAutoreleasedReturnValue(v19);
      LODWORD(v21) = objc_autorelease(v20);
      *v26 = v21;
    }
    LODWORD(v22) = FIRInstanceIDSharedLogger();
    LODWORD(v23) = objc_retainAutoreleasedReturnValue(v22);
    v24 = v23;
    v18 = 0;
    objc_msgSend(
      v23,
      *(&selRef_class + 19),
      &aFirinstanceidk[322],
      9001LL,
      &cfstr_CouldNotUpdate + 2,
      (unsigned int)v16);
    objc_release(v24);
  }
  objc_release(v15);
  objc_release(v12);
  return v18;
}
// 1268: using guessed type char *selRef_class;
// 13B0: using guessed type void *classRef_NSNumber;
// 1648: using guessed type __CFString cfstr_CouldNotUpdate;
// 7310: using guessed type int FIRInstanceIDSharedLogger(void);
// 7360: using guessed type int __fastcall SecItemDelete(_QWORD);
// 7408: using guessed type int __fastcall objc_autorelease(_QWORD);
// 7428: using guessed type int __fastcall objc_release(_QWORD);
// 7430: using guessed type int __fastcall objc_retain(_QWORD, _QWORD);
// 7440: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000CBE) ----------------------------------------------------
// FIRInstanceIDKeyPair - (bool)isValid
bool __cdecl -[FIRInstanceIDKeyPair isValid](struct FIRInstanceIDKeyPair *self, SEL a2)
{
  bool result; // al@2

  if ( self->_privateKey )
    result = self->_publicKey != 0LL;
  else
    result = 0;
  return result;
}

//----- (0000000000000CE5) ----------------------------------------------------
// FIRInstanceIDKeyPair - (struct __SecKey *)publicKey
struct __SecKey *__cdecl -[FIRInstanceIDKeyPair publicKey](struct FIRInstanceIDKeyPair *self, SEL a2)
{
  return self->_publicKey;
}

//----- (0000000000000CF6) ----------------------------------------------------
// FIRInstanceIDKeyPair - (struct __SecKey *)privateKey
struct __SecKey *__cdecl -[FIRInstanceIDKeyPair privateKey](struct FIRInstanceIDKeyPair *self, SEL a2)
{
  return self->_privateKey;
}

//----- (0000000000000D07) ----------------------------------------------------
// FIRInstanceIDKeyPair + (id)appIdentityWithKeyPair:(id) 
id __cdecl +[FIRInstanceIDKeyPair appIdentityWithKeyPair:](struct FIRInstanceIDKeyPair *self, SEL a2, id a3)
{
  void *v3; // rax@1
  void *v4; // r12@1
  void *v5; // rax@2
  __int64 v6; // rax@2
  __int64 v7; // ST00_8@2
  __int64 v8; // rax@2
  __int64 v9; // rax@2
  void *v10; // rax@2
  void *v11; // rbx@2
  void *v12; // ST08_8@2
  _BYTE *v13; // r13@2
  void *v14; // rax@2
  void *v15; // rax@2
  void *v16; // rbx@2
  void *v17; // rax@2
  __int64 v18; // rax@2
  __int64 v19; // r14@2
  __int64 v20; // rax@2
  __int64 v21; // rax@2
  __int64 v22; // r13@2
  __int64 v23; // ST00_8@2
  __int64 v24; // rax@3
  void *v25; // rax@3
  void *v26; // rbx@3
  id result; // rax@4
  char v28; // [sp+17h] [bp-29h]@2

  LODWORD(v3) = objc_retain(a3, a2);
  v4 = v3;
  if ( objc_msgSend(v3, *(&selRef_class + 20)) )
  {
    v5 = objc_msgSend(v4, *(&selRef_class + 21));
    LODWORD(v6) = objc_retainAutoreleasedReturnValue(v5);
    v7 = v6;
    LODWORD(v8) = FIRInstanceIDSHA1(v6);
    LODWORD(v9) = objc_retainAutoreleasedReturnValue(v8);
    LODWORD(v10) = objc_retainAutorelease(v9);
    v11 = v10;
    v12 = v10;
    v13 = objc_msgSend(v10, *(&selRef_class + 22), v7);
    v14 = objc_msgSend(*(&classRef_NSNumber + 5), *(&selRef_class + 23), v11);
    LODWORD(v15) = objc_retainAutoreleasedReturnValue(v14);
    v16 = v15;
    v28 = *v13 & 0xF | 0x70;
    objc_msgSend(v15, *(&selRef_class + 24), 0LL, 1LL);
    v17 = objc_msgSend(v16, *(&selRef_class + 25), 0LL, 8LL);
    LODWORD(v18) = objc_retainAutoreleasedReturnValue(v17);
    v19 = v18;
    LODWORD(v20) = FIRInstanceIDWebSafeBase64(v18);
    LODWORD(v21) = objc_retainAutoreleasedReturnValue(v20);
    v22 = v21;
    objc_release(v19);
    objc_release(v16);
    objc_release(v12);
    objc_release(v23);
  }
  else
  {
    LODWORD(v24) = FIRInstanceIDSharedLogger();
    LODWORD(v25) = objc_retainAutoreleasedReturnValue(v24);
    v26 = v25;
    v22 = 0LL;
    objc_msgSend(v25, *(&selRef_class + 19), &aFirinstanceidk[425], 9002LL, &cfstr_CouldNotUpdate + 3);
    objc_release(v26);
  }
  objc_release(v4);
  LODWORD(result) = objc_autoreleaseReturnValue(v22);
  return result;
}
// 1268: using guessed type char *selRef_class;
// 13B0: using guessed type void *classRef_NSNumber;
// 1648: using guessed type __CFString cfstr_CouldNotUpdate;
// 7308: using guessed type int __fastcall FIRInstanceIDSHA1(_QWORD);
// 7310: using guessed type int FIRInstanceIDSharedLogger(void);
// 7318: using guessed type int __fastcall FIRInstanceIDWebSafeBase64(_QWORD);
// 7410: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 7428: using guessed type int __fastcall objc_release(_QWORD);
// 7430: using guessed type int __fastcall objc_retain(_QWORD, _QWORD);
// 7438: using guessed type int __fastcall objc_retainAutorelease(_QWORD);
// 7440: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000E83) ----------------------------------------------------
// FIRInstanceIDKeyPair - (id)publicKeyData
id __cdecl -[FIRInstanceIDKeyPair publicKeyData](struct FIRInstanceIDKeyPair *self, SEL a2)
{
  return (id)self->_publicKeyData;
}

//----- (0000000000000E94) ----------------------------------------------------
// FIRInstanceIDKeyPair - (void)setPublicKeyData:(id) 
void __cdecl -[FIRInstanceIDKeyPair setPublicKeyData:](struct FIRInstanceIDKeyPair *self, SEL a2, id a3)
{
  objc_storeStrong(&self->_publicKeyData, a3);
}
// 7448: using guessed type int __fastcall objc_storeStrong(_QWORD, _QWORD);

//----- (0000000000000EA8) ----------------------------------------------------
// FIRInstanceIDKeyPair - (id)privateKeyData
id __cdecl -[FIRInstanceIDKeyPair privateKeyData](struct FIRInstanceIDKeyPair *self, SEL a2)
{
  return (id)self->_privateKeyData;
}

//----- (0000000000000EB9) ----------------------------------------------------
// FIRInstanceIDKeyPair - (void)setPrivateKeyData:(id) 
void __cdecl -[FIRInstanceIDKeyPair setPrivateKeyData:](struct FIRInstanceIDKeyPair *self, SEL a2, id a3)
{
  objc_storeStrong(&self->_privateKeyData, a3);
}
// 7448: using guessed type int __fastcall objc_storeStrong(_QWORD, _QWORD);

//----- (0000000000000ECD) ----------------------------------------------------
// FIRInstanceIDKeyPair - (void).cxx_destruct
void __cdecl -[FIRInstanceIDKeyPair .cxx_destruct](struct FIRInstanceIDKeyPair *self, SEL a2)
{
  objc_storeStrong(&self->_privateKeyData, 0LL);
  objc_storeStrong(&self->_publicKeyData, 0LL);
}
// 7448: using guessed type int __fastcall objc_storeStrong(_QWORD, _QWORD);

// ALL OK, 18 function(s) have been successfully decompiled
