/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2015 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

// __int64 __usercall -[FIRInstanceIDTokenStore init]@<rax>(__int64 a1@<rax>, void *a2@<rdi>);
id __cdecl +[FIRInstanceIDTokenStore defaultStore](struct FIRInstanceIDTokenStore_meta *self, SEL);
id __cdecl -[FIRInstanceIDTokenStore initWithKeychain:](struct FIRInstanceIDTokenStore *self, SEL, id);
id __cdecl -[FIRInstanceIDTokenStore tokenInfoWithAuthorizedEntity:scope:](struct FIRInstanceIDTokenStore *self, SEL, id, id);
id __cdecl -[FIRInstanceIDTokenStore cachedTokenInfos](struct FIRInstanceIDTokenStore *self, SEL);
id __cdecl +[FIRInstanceIDTokenStore tokenInfoFromKeychainItem:](struct FIRInstanceIDTokenStore *self, SEL, id);
bool __cdecl -[FIRInstanceIDTokenStore saveTokenInfo:](struct FIRInstanceIDTokenStore *self, SEL, id);
bool __cdecl -[FIRInstanceIDTokenStore removeTokenWithAuthorizedEntity:scope:error:](struct FIRInstanceIDTokenStore *self, SEL, id, id, id *);
bool __cdecl -[FIRInstanceIDTokenStore removeAllTokensWithError:](struct FIRInstanceIDTokenStore *self, SEL, id *);
id __cdecl -[FIRInstanceIDTokenStore keychain](struct FIRInstanceIDTokenStore *self, SEL);
void __cdecl -[FIRInstanceIDTokenStore setKeychain:](struct FIRInstanceIDTokenStore *self, SEL, id);
void __cdecl -[FIRInstanceIDTokenStore .cxx_destruct](struct FIRInstanceIDTokenStore *self, SEL);
// int __fastcall FIRInstanceIDSharedLogger(_QWORD); weak
// int __fastcall objc_autoreleaseReturnValue(_QWORD); weak
// int __fastcall objc_enumerationMutation(_QWORD); weak
// void *objc_msgSend(void *, const char *, ...); idb
// void *objc_msgSendSuper2(void *, const char *, ...); idb
// int __fastcall objc_retainAutoreleasedReturnValue(_QWORD); weak
// int __fastcall objc_storeStrong(_QWORD, _QWORD); weak

//-------------------------------------------------------------------------
// Data declarations

char aCom_google_iid[22] = "com.google.iid-tokens"; // weak
__CFString cfstr_Com_google_iid = { &__CFConstantStringClassReference, 1992LL, "com.google.iid-tokens", 21LL }; // weak
char *selRef_class = "class"; // weak
void *classRef_FIRInstanceIDAuthKeychain = &OBJC_CLASS___FIRInstanceIDAuthKeychain; // weak
void *classRef_FIRInstanceIDTokenStore_0 = &OBJC_CLASS___FIRInstanceIDTokenStore; // weak
// extern _UNKNOWN __stack_chk_guard; weak
// extern _UNKNOWN kFIRInstanceIDKeychainWildcardIdentifier; weak
// extern int (__fastcall *objc_release)(_QWORD); weak
// extern int (__fastcall *objc_retain)(_QWORD, _QWORD); weak


//----- (0000000000000000) ----------------------------------------------------
__int64 __usercall -[FIRInstanceIDTokenStore init]@<rax>(__int64 a1@<rax>, void *a2@<rdi>)
{
  objc_msgSend(a2, selRef_class, a1);
  objc_release(a2);
  return 0LL;
}
// 1510: using guessed type char *selRef_class;
// 67D8: using guessed type int (__fastcall *objc_release)(_QWORD);

//----- (0000000000000028) ----------------------------------------------------
// FIRInstanceIDTokenStore + (id)defaultStore
id __cdecl +[FIRInstanceIDTokenStore defaultStore](struct FIRInstanceIDTokenStore_meta *self, SEL a2)
{
  __int64 v2; // rax@0
  const char *v3; // r14@1
  void *v4; // rax@1
  void *v5; // rbx@1
  void *v6; // rax@1
  void *v7; // r14@1
  id result; // rax@1

  v3 = *(&selRef_class + 1);
  v4 = objc_msgSend(classRef_FIRInstanceIDAuthKeychain, *(&selRef_class + 1), v2);
  v5 = objc_msgSend(v4, *(&selRef_class + 2), &cfstr_Com_google_iid);
  v6 = objc_msgSend(*(&classRef_FIRInstanceIDAuthKeychain + 1), v3);
  v7 = objc_msgSend(v6, *(&selRef_class + 3), v5);
  objc_release(v5);
  LODWORD(result) = objc_autoreleaseReturnValue(v7);
  return result;
}
// 10A0: using guessed type __CFString cfstr_Com_google_iid;
// 1510: using guessed type char *selRef_class;
// 15F0: using guessed type void *classRef_FIRInstanceIDAuthKeychain;
// 67A0: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 67D8: using guessed type int (__fastcall *objc_release)(_QWORD);

//----- (000000000000009F) ----------------------------------------------------
// FIRInstanceIDTokenStore - (id)initWithKeychain:(id) 
id __cdecl -[FIRInstanceIDTokenStore initWithKeychain:](struct FIRInstanceIDTokenStore *self, SEL a2, id a3)
{
  id v3; // r15@1
  __int64 v4; // rax@1
  __int64 v5; // r14@1
  struct objc_object *v6; // rax@1
  struct objc_object *v7; // rbx@1
  struct FIRInstanceIDTokenStore *v9; // [sp+8h] [bp-28h]@1
  void *v10; // [sp+10h] [bp-20h]@1

  v3 = a3;
  LODWORD(v4) = objc_retain(a3, a2);
  v5 = v4;
  v9 = self;
  v10 = classRef_FIRInstanceIDTokenStore_0;
  v6 = (struct objc_object *)objc_msgSendSuper2(&v9, *(&selRef_class + 4));
  v7 = v6;
  if ( v6 )
    objc_storeStrong(&v6[1], v3);
  objc_release(v5);
  return v7;
}
// 1510: using guessed type char *selRef_class;
// 1670: using guessed type void *classRef_FIRInstanceIDTokenStore_0;
// 67D8: using guessed type int (__fastcall *objc_release)(_QWORD);
// 67E0: using guessed type int (__fastcall *objc_retain)(_QWORD, _QWORD);
// 67F0: using guessed type int __fastcall objc_storeStrong(_QWORD, _QWORD);

//----- (000000000000010D) ----------------------------------------------------
// FIRInstanceIDTokenStore - (id)tokenInfoWithAuthorizedEntity:(id) scope:(id) 
id __cdecl -[FIRInstanceIDTokenStore tokenInfoWithAuthorizedEntity:scope:](struct FIRInstanceIDTokenStore *self, SEL a2, id a3, id a4)
{
  id v4; // r14@1
  __int64 v5; // rax@1
  const char *v6; // r15@1
  __int64 v7; // rax@1
  __int64 v8; // r14@1
  const char *v9; // r12@1
  void *v10; // rax@1
  __int64 v11; // rax@1
  void *v12; // r15@1
  void *v13; // rax@1
  void *v14; // rax@1
  void *v15; // rax@1
  __int64 v16; // rax@1
  __int64 v17; // r12@1
  const char *v18; // rsi@1
  __int64 v19; // rbx@1
  void *v20; // r15@1
  __int64 v21; // rax@1
  __int64 v22; // rbx@1
  void *v23; // rax@1
  void *v24; // r15@1
  void *v25; // rax@2
  void *v26; // rax@2
  __int64 v27; // rax@2
  __int64 v28; // r14@2
  void *v29; // r13@2
  __int64 v30; // rax@6
  void *v31; // rax@6
  void *v32; // rbx@6
  void *v33; // rdi@6
  id result; // rax@7
  __int64 v35; // [sp+0h] [bp-50h]@1
  void *v36; // [sp+8h] [bp-48h]@1
  __int64 v37; // [sp+10h] [bp-40h]@1
  __int64 v38; // [sp+18h] [bp-38h]@1
  struct FIRInstanceIDTokenStore *v39; // [sp+20h] [bp-30h]@1

  v4 = a4;
  LODWORD(v5) = objc_retain(a3, a2);
  v37 = v5;
  v6 = *(&selRef_class + 5);
  LODWORD(v7) = objc_retain(v4, a2);
  v8 = v7;
  v9 = v6;
  v10 = objc_msgSend(self, v6);
  LODWORD(v11) = objc_retainAutoreleasedReturnValue(v10);
  v12 = (void *)v11;
  v38 = v11;
  v39 = self;
  v13 = objc_msgSend(self, v9);
  LODWORD(v14) = objc_retainAutoreleasedReturnValue(v13);
  v36 = v14;
  v15 = objc_msgSend(v14, *(&selRef_class + 6));
  LODWORD(v16) = objc_retainAutoreleasedReturnValue(v15);
  v17 = v16;
  v35 = 0LL;
  v18 = *(&selRef_class + 7);
  v19 = v37;
  v20 = objc_msgSend(v12, v18, v8, v37, v16, 0LL);
  objc_release(v8);
  objc_release(v19);
  LODWORD(v21) = objc_retainAutoreleasedReturnValue(v20);
  v22 = v21;
  LODWORD(v23) = objc_retain(v35, v18);
  v24 = v23;
  objc_release(v17);
  ((void (*)(void))objc_release)();
  ((void (*)(void))objc_release)();
  if ( v22 )
  {
    v25 = objc_msgSend(v39, selRef_class, v35);
    v26 = objc_msgSend(v25, *(&selRef_class + 10), v22, v35);
    LODWORD(v27) = objc_retainAutoreleasedReturnValue(v26);
    v28 = v27;
    v29 = v24;
  }
  else
  {
    v29 = v24;
    if ( v24 && objc_msgSend(v24, *(&selRef_class + 8), v35) != (void *)-25300 )
    {
      LODWORD(v30) = FIRInstanceIDSharedLogger(v24);
      LODWORD(v31) = objc_retainAutoreleasedReturnValue(v30);
      v32 = v31;
      v28 = 0LL;
      objc_msgSend(v31, *(&selRef_class + 9), &aCom_google_iid[22], 15000LL, &cfstr_Com_google_iid + 1, v24, v35);
      v33 = v32;
      v22 = 0LL;
      objc_release(v33);
    }
    else
    {
      v28 = 0LL;
    }
  }
  objc_release(v22);
  objc_release(v29);
  LODWORD(result) = objc_autoreleaseReturnValue(v28);
  return result;
}
// 10A0: using guessed type __CFString cfstr_Com_google_iid;
// 1510: using guessed type char *selRef_class;
// 6720: using guessed type int __fastcall FIRInstanceIDSharedLogger(_QWORD);
// 67A0: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 67D8: using guessed type int (__fastcall *objc_release)(_QWORD);
// 67E0: using guessed type int (__fastcall *objc_retain)(_QWORD, _QWORD);
// 67E8: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (00000000000002D3) ----------------------------------------------------
// FIRInstanceIDTokenStore - (id)cachedTokenInfos
id __cdecl -[FIRInstanceIDTokenStore cachedTokenInfos](struct FIRInstanceIDTokenStore *self, SEL a2)
{
  const char *v2; // r14@1
  void *v3; // rax@1
  __int64 v4; // rax@1
  __int64 v5; // r12@1
  __int64 v6; // r13@1
  void *v7; // rax@1
  void *v8; // rax@1
  void *v9; // rax@1
  __int64 v10; // rax@1
  __int64 v11; // r15@1
  __int64 v12; // rsi@1
  __int64 v13; // rax@1
  void *v14; // rax@1
  void *v15; // r13@1
  __int64 v16; // rax@1
  __int64 v17; // r14@1
  __int64 v18; // rax@2
  void *v19; // rax@2
  void *v20; // rbx@2
  void *v21; // rbx@3
  void *v22; // rax@3
  const char *v23; // rsi@3
  void *v24; // rax@3
  void *v25; // rax@3
  void *v26; // rax@3
  const char *v27; // rsi@3
  const char *v28; // r15@5
  unsigned __int64 v29; // r12@5
  __int64 v30; // rbx@8
  void *v31; // rax@8
  void *v32; // rax@8
  __int64 v33; // rax@8
  __int64 v34; // rbx@8
  void *v35; // rbx@12
  id result; // rax@12
  __int128 v37; // [sp+0h] [bp-130h]@3
  __int128 v38; // [sp+10h] [bp-120h]@3
  __int128 v39; // [sp+20h] [bp-110h]@3
  __int128 v40; // [sp+30h] [bp-100h]@3
  __int64 v41; // [sp+40h] [bp-F0h]@1
  struct FIRInstanceIDTokenStore *v42; // [sp+48h] [bp-E8h]@1
  __int64 v43; // [sp+50h] [bp-E0h]@4
  const char *v44; // [sp+58h] [bp-D8h]@5
  __int64 v45; // [sp+60h] [bp-D0h]@3
  void *v46; // [sp+68h] [bp-C8h]@3
  void *v47; // [sp+70h] [bp-C0h]@3
  void *v48; // [sp+78h] [bp-B8h]@1
  char v49; // [sp+80h] [bp-B0h]@3
  __int64 v50; // [sp+100h] [bp-30h]@1

  v50 = *__stack_chk_guard;
  v2 = *(&selRef_class + 5);
  v3 = objc_msgSend(self, *(&selRef_class + 5));
  LODWORD(v4) = objc_retainAutoreleasedReturnValue(v3);
  v5 = v4;
  v6 = *kFIRInstanceIDKeychainWildcardIdentifier;
  v42 = self;
  v7 = objc_msgSend(self, v2);
  LODWORD(v8) = objc_retainAutoreleasedReturnValue(v7);
  v48 = v8;
  v9 = objc_msgSend(v8, *(&selRef_class + 6));
  LODWORD(v10) = objc_retainAutoreleasedReturnValue(v9);
  v11 = v10;
  v41 = 0LL;
  v12 = (__int64)*(&selRef_class + 11);
  LODWORD(v13) = ((int (__fastcall *)(__int64, __int64, __int64, __int64, __int64, __int64 *))objc_msgSend)(
                   v5,
                   v12,
                   v6,
                   v6,
                   v10,
                   &v41);
  LODWORD(v14) = objc_retainAutoreleasedReturnValue(v13);
  v15 = v14;
  LODWORD(v16) = objc_retain(v41, v12);
  v17 = v16;
  objc_release(v11);
  objc_release(v48);
  objc_release(v5);
  if ( v17 )
  {
    LODWORD(v18) = FIRInstanceIDSharedLogger(v5);
    LODWORD(v19) = objc_retainAutoreleasedReturnValue(v18);
    v20 = v19;
    objc_msgSend(v19, *(&selRef_class + 12), &aCom_google_iid[128], 15014LL, &cfstr_Com_google_iid + 2, v17);
    objc_release(v20);
  }
  v45 = v17;
  v21 = *(&classRef_FIRInstanceIDAuthKeychain + 2);
  v22 = objc_msgSend(v15, *(&selRef_class + 13));
  v23 = *(&selRef_class + 14);
  v24 = objc_msgSend(v21, v23, v22);
  LODWORD(v25) = objc_retainAutoreleasedReturnValue(v24);
  v46 = v25;
  v40 = 0LL;
  v39 = 0LL;
  v38 = 0LL;
  v37 = 0LL;
  LODWORD(v26) = objc_retain(v15, v23);
  v27 = *(&selRef_class + 15);
  v47 = v26;
  v48 = objc_msgSend(v26, v27, &v37, &v49, 16LL, (_QWORD)v37);
  if ( v48 )
  {
    v43 = *(_QWORD *)v38;
    do
    {
      v28 = *(&selRef_class + 10);
      v44 = *(&selRef_class + 16);
      v29 = 0LL;
      do
      {
        if ( *(_QWORD *)v38 != v43 )
          objc_enumerationMutation(v47);
        v30 = *(_QWORD *)(*((_QWORD *)&v37 + 1) + 8 * v29);
        v31 = objc_msgSend(v42, selRef_class, (_QWORD)v37);
        v32 = objc_msgSend(v31, v28, v30, (_QWORD)v37);
        LODWORD(v33) = objc_retainAutoreleasedReturnValue(v32);
        v34 = v33;
        if ( v33 )
          objc_msgSend(v46, v44, v33, (_QWORD)v37);
        objc_release(v34);
        ++v29;
      }
      while ( v29 < (unsigned __int64)v48 );
      v48 = objc_msgSend(v47, *(&selRef_class + 15), &v37, &v49, 16LL, (_QWORD)v37);
    }
    while ( v48 );
  }
  v35 = v47;
  objc_release(v47);
  objc_release(v35);
  objc_release(v45);
  result = (id)*__stack_chk_guard;
  if ( *__stack_chk_guard == v50 )
    LODWORD(result) = objc_autoreleaseReturnValue(v46);
  return result;
}
// 10A0: using guessed type __CFString cfstr_Com_google_iid;
// 1510: using guessed type char *selRef_class;
// 15F0: using guessed type void *classRef_FIRInstanceIDAuthKeychain;
// 6720: using guessed type int __fastcall FIRInstanceIDSharedLogger(_QWORD);
// 67A0: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 67B8: using guessed type int __fastcall objc_enumerationMutation(_QWORD);
// 67D8: using guessed type int (__fastcall *objc_release)(_QWORD);
// 67E0: using guessed type int (__fastcall *objc_retain)(_QWORD, _QWORD);
// 67E8: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (00000000000005DB) ----------------------------------------------------
// FIRInstanceIDTokenStore + (id)tokenInfoFromKeychainItem:(id) 
id __cdecl +[FIRInstanceIDTokenStore tokenInfoFromKeychainItem:](struct FIRInstanceIDTokenStore *self, SEL a2, id a3)
{
  void *v3; // rax@1
  void *v4; // r12@1
  const char *v5; // r14@1
  void *v6; // rax@1
  __int64 v7; // rax@1
  __int64 v8; // rbx@1
  void *v9; // rbx@2
  void *v10; // rax@2
  __int64 v11; // rax@2
  __int64 v12; // r14@2
  void *v13; // rax@2
  __int64 v14; // rax@2
  __int64 v15; // rbx@2
  id result; // rax@4

  LODWORD(v3) = objc_retain(a3, a2);
  v4 = v3;
  v5 = *(&selRef_class + 17);
  v6 = objc_msgSend(v3, *(&selRef_class + 17));
  LODWORD(v7) = objc_retainAutoreleasedReturnValue(v6);
  v8 = v7;
  objc_release(v7);
  if ( v8 )
  {
    v9 = *(&classRef_FIRInstanceIDAuthKeychain + 3);
    v10 = objc_msgSend(v4, v5);
    LODWORD(v11) = objc_retainAutoreleasedReturnValue(v10);
    v12 = v11;
    v13 = objc_msgSend(v9, *(&selRef_class + 18), v11);
    LODWORD(v14) = objc_retainAutoreleasedReturnValue(v13);
    v15 = v14;
    objc_release(v12);
  }
  else
  {
    v15 = 0LL;
  }
  objc_release(v4);
  LODWORD(result) = objc_autoreleaseReturnValue(v15);
  return result;
}
// 1510: using guessed type char *selRef_class;
// 15F0: using guessed type void *classRef_FIRInstanceIDAuthKeychain;
// 67A0: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 67D8: using guessed type int (__fastcall *objc_release)(_QWORD);
// 67E0: using guessed type int (__fastcall *objc_retain)(_QWORD, _QWORD);
// 67E8: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000718) ----------------------------------------------------
// FIRInstanceIDTokenStore - (bool)saveTokenInfo:(id) 
bool __cdecl -[FIRInstanceIDTokenStore saveTokenInfo:](struct FIRInstanceIDTokenStore *self, SEL a2, id a3)
{
  void *v3; // rax@1
  void *v4; // r12@1
  void *v5; // rax@1
  __int64 v6; // rax@1
  __int64 v7; // rbx@1
  __int64 v8; // rax@1
  __int64 v9; // rax@1
  __int64 v10; // rbx@1
  __int64 v11; // rax@1
  void *v12; // rax@1
  void *v13; // r13@1
  __int64 v14; // rax@1
  __int64 v15; // rax@1
  __int64 v16; // rsi@1
  __int64 v17; // rax@1
  __int64 v18; // rax@1
  __int64 v19; // rax@1
  __int64 v20; // rax@1
  __int64 v21; // rax@1
  __int64 v22; // rax@1
  __int64 v23; // rbx@1
  const char *v24; // rsi@1
  __int64 v25; // r15@1
  __int64 v26; // r14@1
  __int64 v27; // rax@1
  __int64 v28; // r12@1
  __int64 v29; // rax@1
  void *v30; // rax@1
  __int64 v31; // rdx@1
  void *v32; // r13@1
  void *v33; // r15@3
  void *v34; // rax@4
  __int64 v35; // rax@4
  __int64 v36; // rbx@4
  void *v37; // rax@4
  __int64 v38; // rax@4
  __int64 v39; // r12@4
  __int64 v40; // rdi@4
  __int64 v41; // rbx@5
  __int64 v43; // [sp+0h] [bp-60h]@1
  __int64 v44; // [sp+8h] [bp-58h]@1
  __int64 v45; // [sp+10h] [bp-50h]@1
  void *v46; // [sp+18h] [bp-48h]@1
  __int64 v47; // [sp+20h] [bp-40h]@1
  __int64 v48; // [sp+28h] [bp-38h]@1
  char v49; // [sp+37h] [bp-29h]@1

  LODWORD(v3) = objc_retain(a3, a2);
  v4 = v3;
  v5 = objc_msgSend(*(&classRef_FIRInstanceIDAuthKeychain + 4), *(&selRef_class + 20));
  LODWORD(v6) = objc_retainAutoreleasedReturnValue(v5);
  v7 = v6;
  ((void (__fastcall *)(void *, _QWORD, __int64))objc_msgSend)(v4, *(&selRef_class + 21), v6);
  objc_release(v7);
  LODWORD(v8) = ((int (__fastcall *)(_QWORD, _QWORD, void *))objc_msgSend)(
                  *(&classRef_FIRInstanceIDAuthKeychain + 5),
                  *(&selRef_class + 22),
                  v4);
  LODWORD(v9) = objc_retainAutoreleasedReturnValue(v8);
  v47 = v9;
  v10 = (__int64)*(&selRef_class + 5);
  LODWORD(v11) = ((int (__fastcall *)(struct FIRInstanceIDTokenStore *, _QWORD))objc_msgSend)(
                   self,
                   *(&selRef_class + 5));
  LODWORD(v12) = objc_retainAutoreleasedReturnValue(v11);
  v13 = v12;
  LODWORD(v14) = ((int (__fastcall *)(void *, _QWORD))objc_msgSend)(v4, *(&selRef_class + 23));
  LODWORD(v15) = objc_retainAutoreleasedReturnValue(v14);
  v48 = v15;
  v16 = (__int64)*(&selRef_class + 24);
  v46 = v4;
  LODWORD(v17) = ((int (__fastcall *)(void *, __int64))objc_msgSend)(v4, v16);
  LODWORD(v18) = objc_retainAutoreleasedReturnValue(v17);
  v45 = v18;
  LODWORD(v19) = ((int (__fastcall *)(struct FIRInstanceIDTokenStore *, __int64))objc_msgSend)(self, v10);
  LODWORD(v20) = objc_retainAutoreleasedReturnValue(v19);
  v44 = v20;
  LODWORD(v21) = ((int (__fastcall *)(__int64, _QWORD))objc_msgSend)(v20, *(&selRef_class + 6));
  LODWORD(v22) = objc_retainAutoreleasedReturnValue(v21);
  v23 = v22;
  v43 = 0LL;
  v24 = *(&selRef_class + 25);
  v25 = v48;
  v26 = v45;
  v49 = (unsigned __int64)objc_msgSend(v13, v24, v47, v48, 0LL, v45, v22, &v43);
  LODWORD(v27) = objc_retain(v43, v24);
  v28 = v27;
  objc_release(v23);
  objc_release(v44);
  objc_release(v26);
  objc_release(v25);
  objc_release(v13);
  LODWORD(v29) = FIRInstanceIDSharedLogger(v13);
  LODWORD(v30) = objc_retainAutoreleasedReturnValue(v29);
  v32 = v30;
  if ( v28 && v49 != 1 )
  {
    objc_msgSend(v30, *(&selRef_class + 26), &aCom_google_iid[353], 15006LL, &cfstr_Com_google_iid + 4, v28, v43);
    objc_release(v32);
    v33 = v46;
  }
  else
  {
    v33 = v46;
    v34 = objc_msgSend(v46, *(&selRef_class + 24), v31, v43);
    LODWORD(v35) = objc_retainAutoreleasedReturnValue(v34);
    v36 = v35;
    v37 = objc_msgSend(v33, *(&selRef_class + 23), v43);
    LODWORD(v38) = objc_retainAutoreleasedReturnValue(v37);
    v48 = v28;
    v39 = v38;
    objc_msgSend(v32, *(&selRef_class + 9), &aCom_google_iid[353], 15007LL, &cfstr_Com_google_iid + 5, v36, v38);
    v40 = v39;
    v28 = v48;
    objc_release(v40);
    objc_release(v36);
    objc_release(v32);
  }
  v41 = v47;
  objc_release(v28);
  objc_release(v41);
  objc_release(v33);
  return v49;
}
// 10A0: using guessed type __CFString cfstr_Com_google_iid;
// 1510: using guessed type char *selRef_class;
// 15F0: using guessed type void *classRef_FIRInstanceIDAuthKeychain;
// 6720: using guessed type int __fastcall FIRInstanceIDSharedLogger(_QWORD);
// 67D8: using guessed type int (__fastcall *objc_release)(_QWORD);
// 67E0: using guessed type int (__fastcall *objc_retain)(_QWORD, _QWORD);
// 67E8: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (000000000000098C) ----------------------------------------------------
// FIRInstanceIDTokenStore - (bool)removeTokenWithAuthorizedEntity:(id) scope:(id) error:(id *) 
bool __cdecl -[FIRInstanceIDTokenStore removeTokenWithAuthorizedEntity:scope:error:](struct FIRInstanceIDTokenStore *self, SEL a2, id a3, id a4, id *a5)
{
  id v5; // r12@1
  __int64 v6; // rax@1
  __int64 v7; // r15@1
  __int64 v8; // rax@1
  __int64 v9; // r12@1
  void *v10; // rax@1
  void *v11; // rax@1
  void *v12; // r13@1
  void *v13; // rax@1
  __int64 v14; // rax@1
  __int64 v15; // r14@1
  __int64 v16; // rax@1
  __int64 v17; // rax@1
  __int64 v18; // rbx@1
  __int64 v19; // rax@1
  void *v20; // rax@1
  void *v21; // r14@1
  __int64 v22; // rbx@2
  bool v23; // r15@2
  __int64 v24; // rdi@2
  id *v26; // [sp+10h] [bp-40h]@1
  __int64 v27; // [sp+18h] [bp-38h]@1

  v26 = a5;
  v5 = a4;
  LODWORD(v6) = objc_retain(a3, a2);
  v7 = v6;
  LODWORD(v8) = objc_retain(v5, a2);
  v9 = v8;
  v10 = objc_msgSend(self, *(&selRef_class + 5));
  LODWORD(v11) = objc_retainAutoreleasedReturnValue(v10);
  v12 = v11;
  v13 = objc_msgSend(self, *(&selRef_class + 5));
  LODWORD(v14) = objc_retainAutoreleasedReturnValue(v13);
  v15 = v14;
  LODWORD(v16) = ((int (__fastcall *)(__int64, _QWORD))objc_msgSend)(v14, *(&selRef_class + 6));
  LODWORD(v17) = objc_retainAutoreleasedReturnValue(v16);
  v18 = v17;
  v27 = v7;
  LODWORD(v7) = (unsigned __int64)objc_msgSend(v12, *(&selRef_class + 27), v9, v7, v17, v26);
  objc_release(v18);
  objc_release(v15);
  objc_release(v12);
  LODWORD(v19) = FIRInstanceIDSharedLogger(v12);
  LODWORD(v20) = objc_retainAutoreleasedReturnValue(v19);
  v21 = v20;
  if ( (_BYTE)v7 )
  {
    v22 = v27;
    objc_msgSend(v20, *(&selRef_class + 9), &aCom_google_iid[500], 15009LL, &cfstr_Com_google_iid + 7, v27, v9);
    objc_release(v21);
    v23 = 1;
    v24 = v9;
  }
  else
  {
    v23 = 0;
    objc_msgSend(v20, *(&selRef_class + 26), &aCom_google_iid[500], 15008LL, &cfstr_Com_google_iid + 6, *v26);
    objc_release(v21);
    v22 = v27;
    v24 = v9;
  }
  objc_release(v24);
  objc_release(v22);
  return v23;
}
// 10A0: using guessed type __CFString cfstr_Com_google_iid;
// 1510: using guessed type char *selRef_class;
// 6720: using guessed type int __fastcall FIRInstanceIDSharedLogger(_QWORD);
// 67D8: using guessed type int (__fastcall *objc_release)(_QWORD);
// 67E0: using guessed type int (__fastcall *objc_retain)(_QWORD, _QWORD);
// 67E8: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000B07) ----------------------------------------------------
// FIRInstanceIDTokenStore - (bool)removeAllTokensWithError:(id *) 
bool __cdecl -[FIRInstanceIDTokenStore removeAllTokensWithError:](struct FIRInstanceIDTokenStore *self, SEL a2, id *a3)
{
  __int64 v3; // rax@0
  id *v4; // r14@1
  void *v5; // rax@1
  void *v6; // rax@1
  void *v7; // r15@1
  __int64 v8; // r13@1
  void *v9; // rax@1
  __int64 v10; // rax@1
  __int64 v11; // r12@1
  __int64 v12; // rax@1
  __int64 v13; // rax@1
  __int64 v14; // rbx@1
  __int64 v15; // rax@1
  void *v16; // rax@1
  void *v17; // rbx@1
  bool v18; // r14@2
  _QWORD *v20; // [sp+0h] [bp-30h]@1

  v4 = a3;
  v5 = objc_msgSend(self, *(&selRef_class + 5), v3);
  LODWORD(v6) = objc_retainAutoreleasedReturnValue(v5);
  v7 = v6;
  v8 = *kFIRInstanceIDKeychainWildcardIdentifier;
  v9 = objc_msgSend(self, *(&selRef_class + 5));
  LODWORD(v10) = objc_retainAutoreleasedReturnValue(v9);
  v11 = v10;
  LODWORD(v12) = ((int (__fastcall *)(__int64, _QWORD))objc_msgSend)(v10, *(&selRef_class + 6));
  LODWORD(v13) = objc_retainAutoreleasedReturnValue(v12);
  v14 = v13;
  LODWORD(v8) = (unsigned __int64)objc_msgSend(v7, *(&selRef_class + 27), v8, v8, v13, v4, v4);
  objc_release(v14);
  objc_release(v11);
  objc_release(v7);
  LODWORD(v15) = FIRInstanceIDSharedLogger(v7);
  LODWORD(v16) = objc_retainAutoreleasedReturnValue(v15);
  v17 = v16;
  if ( (_BYTE)v8 )
  {
    objc_msgSend(v16, *(&selRef_class + 9), &aCom_google_iid[689], 15013LL, &cfstr_Com_google_iid + 9);
    objc_release(v17);
    v18 = 1;
  }
  else
  {
    v18 = 0;
    objc_msgSend(v16, *(&selRef_class + 26), &aCom_google_iid[689], 15012LL, &cfstr_Com_google_iid + 8, *v20);
    objc_release(v17);
  }
  return v18;
}
// 10A0: using guessed type __CFString cfstr_Com_google_iid;
// 1510: using guessed type char *selRef_class;
// 6720: using guessed type int __fastcall FIRInstanceIDSharedLogger(_QWORD);
// 67D8: using guessed type int (__fastcall *objc_release)(_QWORD);
// 67E8: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000C41) ----------------------------------------------------
// FIRInstanceIDTokenStore - (id)keychain
id __cdecl -[FIRInstanceIDTokenStore keychain](struct FIRInstanceIDTokenStore *self, SEL a2)
{
  return (id)self->_keychain;
}

//----- (0000000000000C52) ----------------------------------------------------
// FIRInstanceIDTokenStore - (void)setKeychain:(id) 
void __cdecl -[FIRInstanceIDTokenStore setKeychain:](struct FIRInstanceIDTokenStore *self, SEL a2, id a3)
{
  objc_storeStrong(&self->_keychain, a3);
}
// 67F0: using guessed type int __fastcall objc_storeStrong(_QWORD, _QWORD);

//----- (0000000000000C66) ----------------------------------------------------
// FIRInstanceIDTokenStore - (void).cxx_destruct
void __cdecl -[FIRInstanceIDTokenStore .cxx_destruct](struct FIRInstanceIDTokenStore *self, SEL a2)
{
  objc_storeStrong(&self->_keychain, 0LL);
}
// 67F0: using guessed type int __fastcall objc_storeStrong(_QWORD, _QWORD);

// ALL OK, 12 function(s) have been successfully decompiled
