/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2015 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

_QWORD *__fastcall -[FIRInstanceIDKeyPairStore init](__int64 a1);
id __cdecl +[FIRInstanceIDKeyPairStore publicTagWithSubtype:](struct FIRInstanceIDKeyPairStore *self, SEL, id);
id __cdecl +[FIRInstanceIDKeyPairStore privateTagWithSubtype:](struct FIRInstanceIDKeyPairStore *self, SEL, id);
id __cdecl +[FIRInstanceIDKeyPairStore creationTimeKeyWithSubtype:](struct FIRInstanceIDKeyPairStore *self, SEL, id);
id __cdecl +[FIRInstanceIDKeyPairStore appIDKeyWithSubtype:](struct FIRInstanceIDKeyPairStore *self, SEL, id);
void __cdecl -[FIRInstanceIDKeyPairStore invalidateKeyPairsIfNeeded](struct FIRInstanceIDKeyPairStore *self, SEL);
bool __cdecl -[FIRInstanceIDKeyPairStore hasCachedKeyPairs](struct FIRInstanceIDKeyPairStore *self, SEL);
id __cdecl -[FIRInstanceIDKeyPairStore appIdentityWithError:](struct FIRInstanceIDKeyPairStore *self, SEL, id *);
id __cdecl -[FIRInstanceIDKeyPairStore loadKeyPairWithError:](struct FIRInstanceIDKeyPairStore *self, SEL, id *);
id __cdecl -[FIRInstanceIDKeyPairStore generateAndSaveKeyWithSubtype:creationTime:error:](struct FIRInstanceIDKeyPairStore *self, SEL, id, int64_t, id *);
id __cdecl -[FIRInstanceIDKeyPairStore validCachedKeyPairWithSubtype:error:](struct FIRInstanceIDKeyPairStore *self, SEL, id, id *);
id __cdecl -[FIRInstanceIDKeyPairStore cachedKeyPairWithSubtype:error:](struct FIRInstanceIDKeyPairStore *self, SEL, id, id *);
bool __cdecl -[FIRInstanceIDKeyPairStore deleteSavedKeyPairWithSubtype:error:](struct FIRInstanceIDKeyPairStore *self, SEL, id, id *);
bool __cdecl -[FIRInstanceIDKeyPairStore removeKeyPairCreationTimePlistWithError:](struct FIRInstanceIDKeyPairStore *self, SEL, id *);
id __cdecl +[FIRInstanceIDKeyPairStore keyStoreFileName](struct FIRInstanceIDKeyPairStore_meta *self, SEL);
id __cdecl -[FIRInstanceIDKeyPairStore delegate](struct FIRInstanceIDKeyPairStore *self, SEL);
void __cdecl -[FIRInstanceIDKeyPairStore setDelegate:](struct FIRInstanceIDKeyPairStore *self, SEL, id);
id __cdecl -[FIRInstanceIDKeyPairStore plist](struct FIRInstanceIDKeyPairStore *self, SEL);
void __cdecl -[FIRInstanceIDKeyPairStore setPlist:](struct FIRInstanceIDKeyPairStore *self, SEL, id);
id __cdecl -[FIRInstanceIDKeyPairStore keyPair](struct FIRInstanceIDKeyPairStore *self, SEL);
void __cdecl -[FIRInstanceIDKeyPairStore setKeyPair:](struct FIRInstanceIDKeyPairStore *self, SEL, id);
int __cdecl -[FIRInstanceIDKeyPairStore keychainEntitlementsErrorCount](struct FIRInstanceIDKeyPairStore *self, SEL);
void __cdecl -[FIRInstanceIDKeyPairStore setKeychainEntitlementsErrorCount:](struct FIRInstanceIDKeyPairStore *self, SEL, int);
void __cdecl -[FIRInstanceIDKeyPairStore .cxx_destruct](struct FIRInstanceIDKeyPairStore *self, SEL);
// int __fastcall FIRInstanceIDCurrentTimestampInSeconds(_QWORD); weak
// int __fastcall FIRInstanceIDSharedLogger(_QWORD); weak
// int __fastcall objc_autorelease(_QWORD); weak
// int __fastcall objc_autoreleaseReturnValue(_QWORD); weak
// int __fastcall objc_destroyWeak(_QWORD, _QWORD); weak
// int __fastcall objc_loadWeakRetained(_QWORD, _QWORD); weak
// void *objc_msgSend(void *, const char *, ...); idb
// void *objc_msgSendSuper2(void *, const char *, ...); idb
// int __fastcall objc_release(_QWORD); weak
// int __fastcall objc_retainAutorelease(_QWORD, _QWORD); weak
// int __fastcall objc_retainAutoreleasedReturnValue(_QWORD); weak
// int __fastcall objc_storeStrong(_QWORD, _QWORD); weak
// int __fastcall objc_storeWeak(_QWORD, _QWORD); weak
// int __fastcall objc_sync_enter(_QWORD); weak
// int __fastcall objc_sync_exit(_QWORD); weak

//-------------------------------------------------------------------------
// Data declarations

char aCom_google_iid[23] = "com.google.iid-keypair"; // weak
__CFString cfstr_Com_google_iid = { &__CFConstantStringClassReference, 1992LL, "com.google.iid-keypair", 22LL }; // weak
void *classRef_FIRInstanceIDKeyPairStore = &OBJC_CLASS___FIRInstanceIDKeyPairStore; // weak
char *selRef_init = "init"; // weak
void *classRef_FIRInstanceIDBackupExcludedPlist = &OBJC_CLASS___FIRInstanceIDBackupExcludedPlist; // weak
// extern _UNKNOWN kFIRInstanceIDApplicationSupportSubDirectory; weak
// extern _UNKNOWN kFIRInstanceIDSecMissingEntitlementErrorCode; weak
// extern int (__fastcall *objc_retain)(_QWORD, _QWORD); weak


//----- (0000000000000000) ----------------------------------------------------
_QWORD *__fastcall -[FIRInstanceIDKeyPairStore init](__int64 a1)
{
  _QWORD *v1; // rax@1
  _QWORD *v2; // rbx@1
  void *v3; // rax@2
  void *v4; // rax@2
  __int64 v5; // rax@2
  __int64 v6; // r14@2
  void *v7; // rax@2
  void *v8; // rax@2
  __int64 v9; // rdi@2
  __int64 v11; // [sp+8h] [bp-28h]@1
  void *v12; // [sp+10h] [bp-20h]@1

  v11 = a1;
  v12 = classRef_FIRInstanceIDKeyPairStore;
  v1 = objc_msgSendSuper2(&v11, selRef_init);
  v2 = v1;
  if ( v1 )
  {
    v3 = objc_msgSend(v1, *(&selRef_init + 1));
    v4 = objc_msgSend(v3, *(&selRef_init + 2));
    LODWORD(v5) = objc_retainAutoreleasedReturnValue(v4);
    v6 = v5;
    v7 = objc_msgSend(classRef_FIRInstanceIDBackupExcludedPlist, *(&selRef_init + 3));
    v8 = objc_msgSend(v7, *(&selRef_init + 4), v6, *kFIRInstanceIDApplicationSupportSubDirectory);
    v9 = v2[3];
    v2[3] = v8;
    objc_release(v9);
    objc_release(v6);
  }
  return v2;
}
// 1C10: using guessed type void *classRef_FIRInstanceIDKeyPairStore;
// 20F0: using guessed type char *selRef_init;
// 2268: using guessed type void *classRef_FIRInstanceIDBackupExcludedPlist;
// 9D40: using guessed type int __fastcall objc_release(_QWORD);
// 9D58: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (00000000000000BA) ----------------------------------------------------
// FIRInstanceIDKeyPairStore + (id)publicTagWithSubtype:(id) 
id __cdecl +[FIRInstanceIDKeyPairStore publicTagWithSubtype:](struct FIRInstanceIDKeyPairStore *self, SEL a2, id a3)
{
  __int64 v3; // rax@1
  __int64 v4; // rbx@1
  void *v5; // r14@1
  __int64 v6; // rax@1
  id result; // rax@1

  LODWORD(v3) = objc_retain(a3, a2);
  v4 = v3;
  v5 = objc_msgSend(
         *(&classRef_FIRInstanceIDBackupExcludedPlist + 1),
         *(&selRef_init + 5),
         &cfstr_Com_google_iid + 8,
         &cfstr_Com_google_iid + 3,
         v3,
         &cfstr_Com_google_iid + 4);
  objc_release(v4);
  LODWORD(v6) = objc_retainAutoreleasedReturnValue(v5);
  LODWORD(result) = objc_autoreleaseReturnValue(v6);
  return result;
}
// 1958: using guessed type __CFString cfstr_Com_google_iid;
// 20F0: using guessed type char *selRef_init;
// 2268: using guessed type void *classRef_FIRInstanceIDBackupExcludedPlist;
// 9D18: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 9D40: using guessed type int __fastcall objc_release(_QWORD);
// 9D48: using guessed type int (__fastcall *objc_retain)(_QWORD, _QWORD);
// 9D58: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (000000000000011B) ----------------------------------------------------
// FIRInstanceIDKeyPairStore + (id)privateTagWithSubtype:(id) 
id __cdecl +[FIRInstanceIDKeyPairStore privateTagWithSubtype:](struct FIRInstanceIDKeyPairStore *self, SEL a2, id a3)
{
  __int64 v3; // rax@1
  __int64 v4; // rbx@1
  void *v5; // r14@1
  __int64 v6; // rax@1
  id result; // rax@1

  LODWORD(v3) = objc_retain(a3, a2);
  v4 = v3;
  v5 = objc_msgSend(
         *(&classRef_FIRInstanceIDBackupExcludedPlist + 1),
         *(&selRef_init + 5),
         &cfstr_Com_google_iid + 8,
         &cfstr_Com_google_iid + 3,
         v3,
         &cfstr_Com_google_iid + 5);
  objc_release(v4);
  LODWORD(v6) = objc_retainAutoreleasedReturnValue(v5);
  LODWORD(result) = objc_autoreleaseReturnValue(v6);
  return result;
}
// 1958: using guessed type __CFString cfstr_Com_google_iid;
// 20F0: using guessed type char *selRef_init;
// 2268: using guessed type void *classRef_FIRInstanceIDBackupExcludedPlist;
// 9D18: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 9D40: using guessed type int __fastcall objc_release(_QWORD);
// 9D48: using guessed type int (__fastcall *objc_retain)(_QWORD, _QWORD);
// 9D58: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (000000000000017C) ----------------------------------------------------
// FIRInstanceIDKeyPairStore + (id)creationTimeKeyWithSubtype:(id) 
id __cdecl +[FIRInstanceIDKeyPairStore creationTimeKeyWithSubtype:](struct FIRInstanceIDKeyPairStore *self, SEL a2, id a3)
{
  return (id)objc_msgSend(
               *(&classRef_FIRInstanceIDBackupExcludedPlist + 1),
               *(&selRef_init + 5),
               &cfstr_Com_google_iid + 8,
               a3,
               &cfstr_Com_google_iid + 6,
               &cfstr_Com_google_iid + 1);
}
// 1958: using guessed type __CFString cfstr_Com_google_iid;
// 20F0: using guessed type char *selRef_init;
// 2268: using guessed type void *classRef_FIRInstanceIDBackupExcludedPlist;

//----- (00000000000001B3) ----------------------------------------------------
// FIRInstanceIDKeyPairStore + (id)appIDKeyWithSubtype:(id) 
id __cdecl +[FIRInstanceIDKeyPairStore appIDKeyWithSubtype:](struct FIRInstanceIDKeyPairStore *self, SEL a2, id a3)
{
  return (id)objc_msgSend(
               *(&classRef_FIRInstanceIDBackupExcludedPlist + 1),
               *(&selRef_init + 5),
               &cfstr_Com_google_iid + 8,
               a3,
               &cfstr_Com_google_iid + 6,
               &cfstr_Com_google_iid + 2);
}
// 1958: using guessed type __CFString cfstr_Com_google_iid;
// 20F0: using guessed type char *selRef_init;
// 2268: using guessed type void *classRef_FIRInstanceIDBackupExcludedPlist;

//----- (00000000000001EA) ----------------------------------------------------
// FIRInstanceIDKeyPairStore - (void)invalidateKeyPairsIfNeeded
void __cdecl -[FIRInstanceIDKeyPairStore invalidateKeyPairsIfNeeded](struct FIRInstanceIDKeyPairStore *self, SEL a2)
{
  __int64 v2; // rax@0
  void *v3; // rax@1
  void *v4; // rax@1
  void *v5; // rbx@1
  int v6; // er15@1
  __int64 v7; // [sp+0h] [bp-20h]@1

  v7 = v2;
  v3 = objc_msgSend(self, *(&selRef_init + 6), v2);
  LODWORD(v4) = objc_retainAutoreleasedReturnValue(v3);
  v5 = v4;
  v6 = (unsigned __int64)objc_msgSend(v4, *(&selRef_init + 7), v7);
  objc_release(v5);
  if ( !(_BYTE)v6 )
  {
    v7 = 0LL;
    objc_msgSend(self, *(&selRef_init + 8), &cfstr_Com_google_iid + 7, 0LL);
  }
}
// 1958: using guessed type __CFString cfstr_Com_google_iid;
// 20F0: using guessed type char *selRef_init;
// 9D40: using guessed type int __fastcall objc_release(_QWORD);
// 9D58: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (000000000000025E) ----------------------------------------------------
// FIRInstanceIDKeyPairStore - (bool)hasCachedKeyPairs
bool __cdecl -[FIRInstanceIDKeyPairStore hasCachedKeyPairs](struct FIRInstanceIDKeyPairStore *self, SEL a2)
{
  const char *v2; // rsi@1
  void *v3; // rax@1
  __int64 v4; // rax@1
  __int64 v5; // rbx@1
  __int64 v6; // rax@1
  __int64 v7; // r15@1
  bool v8; // r14@2
  __int64 v9; // rax@4
  void *v10; // rax@4
  void *v11; // rbx@4
  const char *v12; // rsi@5
  __int64 v13; // rdi@5
  __int64 v14; // rax@5
  __int64 v15; // rax@6
  void *v16; // rax@6
  void *v17; // rbx@6
  __int64 v19; // [sp+8h] [bp-28h]@1
  __int64 v20; // [sp+10h] [bp-20h]@5

  v19 = 0LL;
  v2 = *(&selRef_init + 9);
  v3 = objc_msgSend(self, v2, &cfstr_Com_google_iid + 7, &v19);
  LODWORD(v4) = objc_retainAutoreleasedReturnValue(v3);
  v5 = v4;
  LODWORD(v6) = objc_retain(v19, v2);
  v7 = v6;
  objc_release(v5);
  if ( v5 )
  {
    v8 = 1;
  }
  else
  {
    if ( v7 )
    {
      LODWORD(v9) = FIRInstanceIDSharedLogger(v5);
      LODWORD(v10) = objc_retainAutoreleasedReturnValue(v9);
      v11 = v10;
      objc_msgSend(v10, *(&selRef_init + 10), &aCom_google_iid[70], 10000LL, &cfstr_Com_google_iid + 9, v7);
      objc_release(v11);
    }
    objc_release(v7);
    v20 = 0LL;
    v12 = *(&selRef_init + 11);
    objc_msgSend(self, v12, &v20);
    v13 = v20;
    LODWORD(v14) = objc_retain(v20, v12);
    v7 = v14;
    if ( v14 )
    {
      LODWORD(v15) = FIRInstanceIDSharedLogger(v13);
      LODWORD(v16) = objc_retainAutoreleasedReturnValue(v15);
      v17 = v16;
      v8 = 0;
      objc_msgSend(v16, *(&selRef_init + 10), &aCom_google_iid[70], 10001LL, &cfstr_Com_google_iid + 10, v7);
      objc_release(v17);
    }
    else
    {
      v8 = 0;
      v7 = 0LL;
    }
  }
  objc_release(v7);
  return v8;
}
// 1958: using guessed type __CFString cfstr_Com_google_iid;
// 20F0: using guessed type char *selRef_init;
// 9C98: using guessed type int __fastcall FIRInstanceIDSharedLogger(_QWORD);
// 9D40: using guessed type int __fastcall objc_release(_QWORD);
// 9D48: using guessed type int (__fastcall *objc_retain)(_QWORD, _QWORD);
// 9D58: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (000000000000039E) ----------------------------------------------------
// FIRInstanceIDKeyPairStore - (id)appIdentityWithError:(id *) 
id __cdecl -[FIRInstanceIDKeyPairStore appIdentityWithError:](struct FIRInstanceIDKeyPairStore *self, SEL a2, id *a3)
{
  struct FIRInstanceIDKeyPairStore *v3; // r13@1
  void *v4; // rax@1
  void *v5; // rax@1
  __int64 v6; // rax@1
  __int64 v7; // rbx@1
  void *v8; // rax@1
  void *v9; // rax@1
  void *v10; // r12@1
  void *v11; // rax@1
  void *v12; // rax@1
  void *v13; // r14@1
  const char *v14; // rsi@1
  void *v15; // rax@1
  __int64 v16; // rax@1
  void (__fastcall *v17)(__int64); // rbx@1
  void *v18; // rdi@1
  __int64 v19; // r14@1
  void *v20; // rax@2
  void *v21; // r13@2
  __int64 v22; // r15@2
  void *v23; // rax@3
  void *v24; // rdi@3
  __int64 v25; // rax@3
  __int64 v26; // r14@3
  void *v27; // rax@6
  void *v28; // rax@6
  void *v29; // rax@6
  void *v30; // rax@8
  __int64 v31; // rax@8
  __int64 v32; // rax@8
  __int64 v33; // rax@9
  void *v34; // rax@9
  void *v35; // rbx@9
  id result; // rax@12
  _QWORD *v37; // [sp+0h] [bp-40h]@1
  __int64 v38; // [sp+10h] [bp-30h]@1

  v3 = self;
  v4 = objc_msgSend(self, *(&selRef_init + 1), a3);
  v5 = objc_msgSend(v4, *(&selRef_init + 12), &cfstr_Com_google_iid + 7);
  LODWORD(v6) = objc_retainAutoreleasedReturnValue(v5);
  v7 = v6;
  v8 = objc_msgSend(self, *(&selRef_init + 6));
  LODWORD(v9) = objc_retainAutoreleasedReturnValue(v8);
  v10 = v9;
  v11 = objc_msgSend(v9, *(&selRef_init + 13));
  LODWORD(v12) = objc_retainAutoreleasedReturnValue(v11);
  v13 = v12;
  v14 = *(&selRef_init + 14);
  v38 = v7;
  v15 = objc_msgSend(v12, v14, v7);
  LODWORD(v16) = objc_retainAutoreleasedReturnValue(v15);
  v17 = (void (__fastcall *)(__int64))objc_release;
  v18 = v13;
  v19 = v16;
  objc_release(v18);
  objc_release(v10);
  if ( !v19 )
  {
    v23 = objc_msgSend(v3, *(&selRef_init + 15), v37);
    v24 = v23;
    LODWORD(v25) = objc_retainAutoreleasedReturnValue(v23);
    v26 = v25;
    if ( v25 )
    {
      if ( v37 )
        *v37 = 0LL;
      v27 = objc_msgSend(*(&classRef_FIRInstanceIDBackupExcludedPlist + 2), *(&selRef_init + 17), v25);
      LODWORD(v28) = objc_retainAutoreleasedReturnValue(v27);
      v21 = v28;
      v29 = objc_msgSend(v28, *(&selRef_init + 18));
      if ( v37 )
      {
        v22 = v38;
        if ( !v29 )
        {
          v30 = objc_msgSend(*(&classRef_FIRInstanceIDBackupExcludedPlist + 3), *(&selRef_init + 19), 0LL);
          LODWORD(v31) = objc_retainAutoreleasedReturnValue(v30);
          LODWORD(v32) = objc_autorelease(v31);
          *v37 = v32;
        }
        goto LABEL_11;
      }
    }
    else
    {
      LODWORD(v33) = FIRInstanceIDSharedLogger(v24);
      LODWORD(v34) = objc_retainAutoreleasedReturnValue(v33);
      v35 = v34;
      v21 = 0LL;
      objc_msgSend(v34, *(&selRef_init + 16), &aCom_google_iid[196], 10009LL, &cfstr_Com_google_iid + 11, *v37);
      objc_release(v35);
    }
    v22 = v38;
LABEL_11:
    objc_release(v26);
    v17 = (void (__fastcall *)(__int64))objc_release;
    v19 = 0LL;
    goto LABEL_12;
  }
  LODWORD(v20) = objc_retain(v19, v14);
  v21 = v20;
  v22 = v38;
LABEL_12:
  v17(v19);
  v17(v22);
  LODWORD(result) = objc_autoreleaseReturnValue(v21);
  return result;
}
// 1958: using guessed type __CFString cfstr_Com_google_iid;
// 20F0: using guessed type char *selRef_init;
// 2268: using guessed type void *classRef_FIRInstanceIDBackupExcludedPlist;
// 9C98: using guessed type int __fastcall FIRInstanceIDSharedLogger(_QWORD);
// 9D10: using guessed type int __fastcall objc_autorelease(_QWORD);
// 9D18: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 9D40: using guessed type int __fastcall objc_release(_QWORD);
// 9D48: using guessed type int (__fastcall *objc_retain)(_QWORD, _QWORD);
// 9D58: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (000000000000057E) ----------------------------------------------------
// FIRInstanceIDKeyPairStore - (id)loadKeyPairWithError:(id *) 
id __cdecl -[FIRInstanceIDKeyPairStore loadKeyPairWithError:](struct FIRInstanceIDKeyPairStore *self, SEL a2, id *a3)
{
  __int64 v3; // rax@0
  __int64 v4; // ST00_8@1
  void **v5; // r15@1
  void *v6; // rax@1
  void *v7; // r13@1
  const char *v8; // r14@1
  void *v9; // rax@1
  void *v10; // rax@1
  void *v11; // rbx@1
  int v12; // er12@1
  void *v13; // rax@2
  __int64 v14; // rax@2
  __int64 v15; // rbx@2
  char v16; // r12@2
  const char *v17; // r12@3
  __int64 v18; // rax@4
  void *v19; // rax@4
  void *v20; // rbx@4
  void *v21; // rax@5
  __int64 v22; // rax@5
  __int64 v23; // rbx@5
  void *v24; // rax@6
  __int64 v25; // rax@6
  __int64 v26; // rbx@6
  int v27; // eax@8
  void *v28; // rax@9
  __int64 v29; // rax@9
  __int64 v30; // rdi@9
  __int64 v31; // rax@10
  void *v32; // rax@10
  __int64 v33; // rax@10
  void *v34; // rax@12
  __int64 v35; // rax@12
  id result; // rax@13

  v4 = v3;
  v5 = (void **)a3;
  LODWORD(v6) = objc_retain(self, a2);
  v7 = v6;
  objc_sync_enter(v6);
  v8 = *(&selRef_init + 20);
  v9 = objc_msgSend(v7, *(&selRef_init + 20), v4);
  LODWORD(v10) = objc_retainAutoreleasedReturnValue(v9);
  v11 = v10;
  v12 = (unsigned __int64)objc_msgSend(v10, *(&selRef_init + 21));
  objc_release(v11);
  if ( (_BYTE)v12 )
  {
    v13 = objc_msgSend(v7, v8);
    LODWORD(v14) = objc_retainAutoreleasedReturnValue(v13);
    v15 = v14;
    v16 = 0;
  }
  else
  {
    v17 = *(&selRef_init + 22);
    if ( (signed int)objc_msgSend(v7, *(&selRef_init + 22)) < 3 )
    {
      v21 = objc_msgSend(v7, v8);
      LODWORD(v22) = objc_retainAutoreleasedReturnValue(v21);
      v23 = v22;
      objc_release(v22);
      if ( !v23 )
      {
        v24 = objc_msgSend(v7, *(&selRef_init + 23), &cfstr_Com_google_iid + 7, v5);
        LODWORD(v25) = objc_retainAutoreleasedReturnValue(v24);
        v26 = v25;
        objc_msgSend(v7, *(&selRef_init + 24), v25);
        objc_release(v26);
      }
      if ( objc_msgSend(*v5, *(&selRef_init + 25)) == (void *)*kFIRInstanceIDSecMissingEntitlementErrorCode )
      {
        v27 = (unsigned __int64)objc_msgSend(v7, v17);
        objc_msgSend(v7, *(&selRef_init + 26), (unsigned int)(v27 + 1));
      }
      v28 = objc_msgSend(v7, v8);
      LODWORD(v29) = objc_retainAutoreleasedReturnValue(v28);
      v15 = v29;
      v30 = v29;
      objc_release(v29);
      v16 = 1;
      if ( !v15 )
      {
        LODWORD(v31) = FIRInstanceIDCurrentTimestampInSeconds(v30);
        v32 = objc_msgSend(v7, *(&selRef_init + 27), &cfstr_Com_google_iid + 7, v31, v5);
        LODWORD(v33) = objc_retainAutoreleasedReturnValue(v32);
        v15 = v33;
        objc_msgSend(v7, *(&selRef_init + 24), v33);
        objc_release(v15);
      }
    }
    else
    {
      LODWORD(v18) = FIRInstanceIDSharedLogger(v7);
      LODWORD(v19) = objc_retainAutoreleasedReturnValue(v18);
      v20 = v19;
      objc_msgSend(v19, *(&selRef_init + 10), &aCom_google_iid[300], 10002LL, &cfstr_Com_google_iid + 12);
      objc_release(v20);
      v15 = 0LL;
      v16 = 0;
    }
  }
  objc_sync_exit(v7);
  objc_release(v7);
  if ( v16 )
  {
    v34 = objc_msgSend(v7, v8);
    LODWORD(v35) = objc_retainAutoreleasedReturnValue(v34);
    v15 = v35;
  }
  LODWORD(result) = objc_autoreleaseReturnValue(v15);
  return result;
}
// 1958: using guessed type __CFString cfstr_Com_google_iid;
// 20F0: using guessed type char *selRef_init;
// 9C90: using guessed type int __fastcall FIRInstanceIDCurrentTimestampInSeconds(_QWORD);
// 9C98: using guessed type int __fastcall FIRInstanceIDSharedLogger(_QWORD);
// 9D18: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 9D40: using guessed type int __fastcall objc_release(_QWORD);
// 9D48: using guessed type int (__fastcall *objc_retain)(_QWORD, _QWORD);
// 9D58: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);
// 9D70: using guessed type int __fastcall objc_sync_enter(_QWORD);
// 9D78: using guessed type int __fastcall objc_sync_exit(_QWORD);

//----- (00000000000007CA) ----------------------------------------------------
// FIRInstanceIDKeyPairStore - (id)generateAndSaveKeyWithSubtype:(id) creationTime:(int64_t) error:(id *) 
id __cdecl -[FIRInstanceIDKeyPairStore generateAndSaveKeyWithSubtype:creationTime:error:](struct FIRInstanceIDKeyPairStore *self, SEL a2, id a3, int64_t a4, id *a5)
{
  __int64 v5; // rax@1
  __int64 v6; // r13@1
  const char *v7; // rbx@1
  void *v8; // rax@1
  void *v9; // rax@1
  __int64 v10; // rax@1
  __int64 v11; // r15@1
  void *v12; // rax@1
  void *v13; // rax@1
  __int64 v14; // rax@1
  void *v15; // rdi@1
  const char *v16; // rsi@1
  void *v17; // rax@1
  void *v18; // rax@1
  __int64 v19; // r15@1
  void *v20; // rdi@1
  char v21; // al@1
  void *v22; // rax@2
  void *v23; // rax@2
  const char *v24; // r12@2
  void *v25; // rax@2
  void *v26; // rax@2
  __int64 v27; // rax@2
  void *v28; // rax@2
  void *v29; // rax@2
  void *v30; // rax@2
  void *v31; // r13@2
  void *v32; // rax@2
  __int64 v33; // rax@2
  __int64 v34; // rbx@2
  __int64 v35; // r12@2
  __int64 v36; // r15@2
  void *v37; // rdi@2
  const char *v38; // rsi@2
  void *v39; // rax@2
  void *v40; // rax@2
  void *v41; // rbx@2
  const char *v42; // r12@2
  __int64 v43; // rax@4
  __int64 v44; // r14@4
  __int64 v45; // rax@7
  __int64 v46; // rax@7
  __int64 v47; // rbx@7
  __int64 v48; // rax@7
  __int64 v49; // rax@7
  __int64 v50; // r12@7
  void *v51; // rax@7
  void *v52; // r15@7
  __int64 v53; // rsi@7
  __int64 v54; // rax@7
  __int64 v55; // rax@9
  void *v56; // rax@9
  void *v57; // rbx@9
  __int64 v58; // r14@9
  __int64 v59; // r13@9
  void *v60; // rax@10
  void *v61; // rbx@10
  __int64 v62; // rax@11
  __int64 v63; // rax@11
  __int64 v64; // rbx@11
  __int64 v65; // rsi@11
  id *v66; // r12@11
  char v67; // r14@11
  __int64 v68; // rax@12
  void (__fastcall *v69)(void *); // rbx@12
  void *v70; // rdi@13
  const char *v71; // rsi@13
  __int64 v72; // rdi@13
  __int64 v73; // rax@13
  __int64 v74; // rbx@13
  __int64 v75; // rax@13
  void *v76; // rax@13
  __CFString *v77; // r9@14
  void *v78; // r12@16
  __int64 v79; // rdi@16
  id result; // rax@18
  __int64 v81; // [sp+0h] [bp-80h]@13
  __int64 v82; // [sp+8h] [bp-78h]@1
  void *v83; // [sp+10h] [bp-70h]@5
  __int64 v84; // [sp+18h] [bp-68h]@1
  struct FIRInstanceIDKeyPairStore *v85; // [sp+20h] [bp-60h]@1
  void *v86; // [sp+28h] [bp-58h]@2
  void *v87; // [sp+30h] [bp-50h]@2
  id *v88; // [sp+38h] [bp-48h]@1
  __int64 v89; // [sp+40h] [bp-40h]@1
  __int64 v90; // [sp+48h] [bp-38h]@1
  void *v91; // [sp+50h] [bp-30h]@2

  v88 = a5;
  v90 = a4;
  LODWORD(v5) = objc_retain(a3, a2);
  v6 = v5;
  v7 = *(&selRef_init + 1);
  v8 = objc_msgSend(self, *(&selRef_init + 1));
  v9 = objc_msgSend(v8, *(&selRef_init + 28), v6);
  LODWORD(v10) = objc_retainAutoreleasedReturnValue(v9);
  v11 = v10;
  v85 = self;
  v12 = objc_msgSend(self, v7);
  v13 = objc_msgSend(v12, *(&selRef_init + 29), v6);
  LODWORD(v14) = objc_retainAutoreleasedReturnValue(v13);
  v15 = *(&classRef_FIRInstanceIDBackupExcludedPlist + 2);
  v16 = *(&selRef_init + 30);
  v84 = v14;
  v89 = v11;
  v17 = objc_msgSend(v15, v16, v14, v11, v88);
  LODWORD(v18) = objc_retainAutoreleasedReturnValue(v17);
  v19 = (__int64)v18;
  v20 = v18;
  v21 = (unsigned __int64)objc_msgSend(v18, *(&selRef_init + 21));
  v82 = v6;
  if ( v21 )
  {
    v22 = objc_msgSend(*(&classRef_FIRInstanceIDBackupExcludedPlist + 4), *(&selRef_init + 31));
    LODWORD(v23) = objc_retainAutoreleasedReturnValue(v22);
    v91 = v23;
    v24 = *(&selRef_init + 1);
    v25 = objc_msgSend(v85, *(&selRef_init + 1));
    v26 = objc_msgSend(v25, *(&selRef_init + 32), v6);
    LODWORD(v27) = objc_retainAutoreleasedReturnValue(v26);
    v86 = (void *)v27;
    v28 = objc_msgSend(v85, v24);
    v29 = objc_msgSend(v28, *(&selRef_init + 12), v6);
    LODWORD(v30) = objc_retainAutoreleasedReturnValue(v29);
    v31 = v30;
    v32 = objc_msgSend(*(&classRef_FIRInstanceIDBackupExcludedPlist + 5), *(&selRef_init + 33), v90);
    LODWORD(v33) = objc_retainAutoreleasedReturnValue(v32);
    v34 = v33;
    v35 = v19;
    v36 = (__int64)*(&selRef_init + 34);
    objc_msgSend(v91, *(&selRef_init + 34), v33, v86);
    objc_release(v34);
    v37 = *(&classRef_FIRInstanceIDBackupExcludedPlist + 2);
    v38 = *(&selRef_init + 17);
    v90 = v35;
    v39 = objc_msgSend(v37, v38, v35);
    LODWORD(v40) = objc_retainAutoreleasedReturnValue(v39);
    v41 = v40;
    v42 = *(&selRef_init + 18);
    v87 = v31;
    if ( objc_msgSend(v31, v42) && objc_msgSend(v41, v42) )
    {
      LODWORD(v43) = ((int (__fastcall *)(void *, _QWORD))objc_msgSend)(v41, *(&selRef_init + 35));
      v44 = v43;
      ((void (__fastcall *)(void *, __int64, __int64, void *))objc_msgSend)(v91, v36, v43, v87);
      objc_release(v44);
    }
    v83 = v41;
    if ( v88 )
      *v88 = 0LL;
    LODWORD(v45) = ((int (__fastcall *)(struct FIRInstanceIDKeyPairStore *, _QWORD))objc_msgSend)(
                     v85,
                     *(&selRef_init + 6));
    LODWORD(v46) = objc_retainAutoreleasedReturnValue(v45);
    v47 = v46;
    LODWORD(v48) = ((int (__fastcall *)(__int64, _QWORD))objc_msgSend)(v46, *(&selRef_init + 13));
    LODWORD(v49) = objc_retainAutoreleasedReturnValue(v48);
    v50 = v49;
    LODWORD(v51) = ((int (__fastcall *)(__int64, _QWORD))objc_msgSend)(v49, *(&selRef_init + 36));
    v52 = v51;
    objc_release(v50);
    objc_release(v47);
    v53 = (__int64)*(&selRef_init + 37);
    LODWORD(v54) = ((int (__fastcall *)(void *, __int64))objc_msgSend)(v52, v53);
    if ( v54 )
    {
      objc_msgSend(v52, *(&selRef_init + 38), v91);
    }
    else
    {
      LODWORD(v60) = objc_retain(v91, v53);
      v61 = v60;
      objc_release(v52);
      v52 = v61;
    }
    LODWORD(v62) = ((int (__fastcall *)(struct FIRInstanceIDKeyPairStore *, _QWORD))objc_msgSend)(
                     v85,
                     *(&selRef_init + 6));
    LODWORD(v63) = objc_retainAutoreleasedReturnValue(v62);
    v64 = v63;
    v65 = (__int64)*(&selRef_init + 39);
    v66 = v88;
    v67 = ((int (__fastcall *)(__int64, __int64, void *, id *))objc_msgSend)(v63, v65, v52, v88);
    objc_release(v64);
    if ( v67 )
    {
      LODWORD(v68) = objc_retain(v90, v65);
      v58 = v68;
      v59 = v89;
      v69 = (void (__fastcall *)(void *))objc_release;
    }
    else
    {
      v70 = *(&classRef_FIRInstanceIDBackupExcludedPlist + 2);
      v81 = 0LL;
      v71 = *(&selRef_init + 40);
      v59 = v89;
      objc_msgSend(v70, v71, v84, v89, 0LL, v82, v83);
      v72 = v81;
      LODWORD(v73) = objc_retain(v81, v71);
      v74 = v73;
      LODWORD(v75) = FIRInstanceIDSharedLogger(v72);
      LODWORD(v76) = objc_retainAutoreleasedReturnValue(v75);
      if ( v66 )
        v77 = (__CFString *)*v66;
      else
        v77 = &cfstr_Com_google_iid + 7;
      v58 = 0LL;
      v78 = v76;
      objc_msgSend(v76, *(&selRef_init + 16), &aCom_google_iid[444], 10004LL, &cfstr_Com_google_iid + 14, v77, v81);
      v79 = v74;
      v69 = (void (__fastcall *)(void *))objc_release;
      objc_release(v79);
      objc_release(v78);
    }
    v69(v52);
    v69(v83);
    v69(v87);
    v69(v86);
    v69(v91);
    v19 = v90;
  }
  else
  {
    LODWORD(v55) = FIRInstanceIDSharedLogger(v20);
    LODWORD(v56) = objc_retainAutoreleasedReturnValue(v55);
    v57 = v56;
    v58 = 0LL;
    objc_msgSend(v56, *(&selRef_init + 16), &aCom_google_iid[444], 10003LL, &cfstr_Com_google_iid + 13);
    objc_release(v57);
    v59 = v89;
  }
  objc_release(v19);
  objc_release(v84);
  objc_release(v59);
  objc_release(v82);
  LODWORD(result) = objc_autoreleaseReturnValue(v58);
  return result;
}
// 1958: using guessed type __CFString cfstr_Com_google_iid;
// 20F0: using guessed type char *selRef_init;
// 2268: using guessed type void *classRef_FIRInstanceIDBackupExcludedPlist;
// 9C98: using guessed type int __fastcall FIRInstanceIDSharedLogger(_QWORD);
// 9D18: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 9D40: using guessed type int __fastcall objc_release(_QWORD);
// 9D48: using guessed type int (__fastcall *objc_retain)(_QWORD, _QWORD);
// 9D58: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000BFE) ----------------------------------------------------
// FIRInstanceIDKeyPairStore - (id)validCachedKeyPairWithSubtype:(id) error:(id *) 
id __cdecl -[FIRInstanceIDKeyPairStore validCachedKeyPairWithSubtype:error:](struct FIRInstanceIDKeyPairStore *self, SEL a2, id a3, id *a4)
{
  __int64 v4; // rax@1
  __int64 v5; // r14@1
  void *v6; // rax@1
  __int64 v7; // rax@1
  __int64 v8; // rbx@1
  __int64 v9; // rax@1
  __int64 v10; // rax@1
  __int64 v11; // r13@1
  __int64 v12; // rsi@1
  __int64 v13; // rax@1
  __int64 v14; // r12@1
  __int64 v15; // rax@1
  __int64 v16; // rax@1
  __int64 v17; // rsi@1
  __int64 v18; // rdi@1
  __int64 v19; // r13@1
  __int64 v20; // rax@1
  void (__fastcall *v21)(__int64); // r15@1
  __int64 v22; // rax@1
  __int64 v23; // rbx@1
  void *v24; // rax@2
  __int64 v25; // rax@2
  __int64 v26; // r14@2
  id *v27; // r15@3
  const char *v28; // rsi@3
  __int64 v29; // rdi@3
  __int64 v30; // rax@3
  __int64 v31; // r14@3
  __int64 v32; // rax@4
  void *v33; // rax@4
  void *v34; // rbx@4
  void *v35; // rax@5
  __int64 v36; // rax@5
  struct objc_object *v37; // rax@5
  __int64 v38; // rbx@6
  id result; // rax@6
  __int64 v40; // [sp+8h] [bp-48h]@3
  __int64 v41; // [sp+10h] [bp-40h]@1
  id *v42; // [sp+18h] [bp-38h]@1
  struct FIRInstanceIDKeyPairStore *v43; // [sp+20h] [bp-30h]@1

  v42 = a4;
  LODWORD(v4) = objc_retain(a3, a2);
  v5 = v4;
  v6 = objc_msgSend(self, *(&selRef_init + 6));
  LODWORD(v7) = objc_retainAutoreleasedReturnValue(v6);
  v8 = v7;
  LODWORD(v9) = ((int (__fastcall *)(__int64, _QWORD))objc_msgSend)(v7, *(&selRef_init + 13));
  LODWORD(v10) = objc_retainAutoreleasedReturnValue(v9);
  v11 = v10;
  objc_release(v8);
  v12 = (__int64)*(&selRef_init + 1);
  v43 = self;
  LODWORD(v13) = ((int (__fastcall *)(struct FIRInstanceIDKeyPairStore *, __int64))objc_msgSend)(self, v12);
  v14 = v5;
  LODWORD(v15) = ((int (__fastcall *)(__int64, _QWORD, __int64))objc_msgSend)(v13, *(&selRef_init + 32), v5);
  LODWORD(v16) = objc_retainAutoreleasedReturnValue(v15);
  v17 = (__int64)*(&selRef_init + 14);
  v41 = v11;
  v18 = v11;
  v19 = v16;
  LODWORD(v20) = ((int (__fastcall *)(__int64, __int64, __int64))objc_msgSend)(v18, v17, v16);
  v21 = (void (__fastcall *)(__int64))objc_release;
  LODWORD(v22) = objc_retainAutoreleasedReturnValue(v20);
  v23 = v22;
  objc_release(v22);
  if ( v23 )
  {
    v24 = objc_msgSend(v43, *(&selRef_init + 9), v5, v42);
    LODWORD(v25) = objc_retainAutoreleasedReturnValue(v24);
    v26 = v25;
  }
  else
  {
    v27 = v42;
    v40 = 0LL;
    v28 = *(&selRef_init + 8);
    objc_msgSend(v43, v28, v5, &v40);
    v29 = v40;
    LODWORD(v30) = objc_retain(v40, v28);
    v31 = v30;
    if ( v30 )
    {
      LODWORD(v32) = FIRInstanceIDSharedLogger(v29);
      LODWORD(v33) = objc_retainAutoreleasedReturnValue(v32);
      v34 = v33;
      objc_msgSend(v33, *(&selRef_init + 10), &aCom_google_iid[591], 10005LL, &cfstr_Com_google_iid + 15, v14, v31);
      objc_release(v34);
    }
    v35 = objc_msgSend(*(&classRef_FIRInstanceIDBackupExcludedPlist + 3), *(&selRef_init + 19), 2005LL);
    LODWORD(v36) = objc_retainAutoreleasedReturnValue(v35);
    LODWORD(v37) = objc_autorelease(v36);
    *v27 = v37;
    objc_release(v31);
    v26 = 0LL;
    v21 = (void (__fastcall *)(__int64))objc_release;
  }
  v38 = v41;
  v21(v19);
  v21(v38);
  v21(v14);
  LODWORD(result) = objc_autoreleaseReturnValue(v26);
  return result;
}
// 1958: using guessed type __CFString cfstr_Com_google_iid;
// 20F0: using guessed type char *selRef_init;
// 2268: using guessed type void *classRef_FIRInstanceIDBackupExcludedPlist;
// 9C98: using guessed type int __fastcall FIRInstanceIDSharedLogger(_QWORD);
// 9D10: using guessed type int __fastcall objc_autorelease(_QWORD);
// 9D18: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 9D40: using guessed type int __fastcall objc_release(_QWORD);
// 9D48: using guessed type int (__fastcall *objc_retain)(_QWORD, _QWORD);
// 9D58: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000DD3) ----------------------------------------------------
// FIRInstanceIDKeyPairStore - (id)cachedKeyPairWithSubtype:(id) error:(id *) 
id __cdecl -[FIRInstanceIDKeyPairStore cachedKeyPairWithSubtype:error:](struct FIRInstanceIDKeyPairStore *self, SEL a2, id a3, id *a4)
{
  id *v4; // ST00_8@1
  const char *v5; // r13@1
  __int64 v6; // rax@1
  __int64 v7; // rbx@1
  void *v8; // rax@1
  void *v9; // rax@1
  __int64 v10; // rax@1
  __int64 v11; // r15@1
  void *v12; // rax@1
  void *v13; // r12@1
  __int64 v14; // rax@1
  __int64 v15; // rbx@1
  __int64 v16; // ST00_8@1
  void *v17; // rax@1
  __int64 v18; // rax@1
  __int64 v19; // r14@1
  id result; // rax@1

  v4 = a4;
  v5 = *(&selRef_init + 1);
  LODWORD(v6) = objc_retain(a3, a2);
  v7 = v6;
  v8 = objc_msgSend(self, v5, v4);
  v9 = objc_msgSend(v8, *(&selRef_init + 28), v7);
  LODWORD(v10) = objc_retainAutoreleasedReturnValue(v9);
  v11 = v10;
  v12 = objc_msgSend(self, v5);
  v13 = objc_msgSend(v12, *(&selRef_init + 29), v7);
  objc_release(v7);
  LODWORD(v14) = objc_retainAutoreleasedReturnValue(v13);
  v15 = v14;
  v17 = objc_msgSend(*(&classRef_FIRInstanceIDBackupExcludedPlist + 2), *(&selRef_init + 41), v14, v11, v16);
  LODWORD(v18) = objc_retainAutoreleasedReturnValue(v17);
  v19 = v18;
  objc_release(v15);
  objc_release(v11);
  LODWORD(result) = objc_autoreleaseReturnValue(v19);
  return result;
}
// 20F0: using guessed type char *selRef_init;
// 2268: using guessed type void *classRef_FIRInstanceIDBackupExcludedPlist;
// 9D18: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 9D40: using guessed type int __fastcall objc_release(_QWORD);
// 9D48: using guessed type int (__fastcall *objc_retain)(_QWORD, _QWORD);
// 9D58: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000EA2) ----------------------------------------------------
// FIRInstanceIDKeyPairStore - (bool)deleteSavedKeyPairWithSubtype:(id) error:(id *) 
bool __cdecl -[FIRInstanceIDKeyPairStore deleteSavedKeyPairWithSubtype:error:](struct FIRInstanceIDKeyPairStore *self, SEL a2, id a3, id *a4)
{
  const char *v4; // rbx@1
  __int64 v5; // rax@1
  __int64 v6; // r13@1
  void *v7; // rax@1
  void *v8; // rax@1
  void *v9; // rbx@1
  void *v10; // rax@1
  void *v11; // rax@1
  const char *v12; // rbx@1
  void *v13; // rax@1
  void *v14; // rax@1
  __int64 v15; // rax@1
  void *v16; // rax@1
  void *v17; // rax@1
  __int64 v18; // rax@1
  void *v19; // rax@1
  void *v20; // rax@1
  __int64 v21; // rax@1
  __int64 v22; // r15@1
  void *v23; // r14@1
  void *v24; // rax@1
  void *v25; // rbx@1
  __int64 v26; // rax@1
  const char *v27; // rsi@1
  void *v28; // rax@1
  __int64 v29; // rax@1
  __int64 v30; // rbx@1
  __int64 v31; // rax@2
  __int64 v32; // rax@2
  __int64 v33; // r13@2
  __int64 v34; // r12@2
  __int64 v35; // rax@2
  __int64 v36; // rax@2
  __int64 v37; // rbx@2
  __int64 v38; // rsi@2
  char v39; // r14@2
  __int64 v40; // rax@2
  __int64 v41; // r12@2
  __int64 v42; // rax@3
  void *v43; // rax@3
  void *v44; // rbx@3
  void *v45; // rdi@7
  __int64 v46; // r13@7
  void *v47; // r12@7
  struct FIRInstanceIDKeyPairStore *v48; // rbx@8
  __int64 v49; // rax@8
  __int64 v50; // rax@8
  __int64 v51; // r14@8
  bool v52; // r14@8
  __int64 v53; // rax@9
  void *v54; // rax@9
  void *v55; // rbx@9
  __int64 v57; // [sp+8h] [bp-68h]@2
  __int64 v58; // [sp+10h] [bp-60h]@1
  id *v59; // [sp+18h] [bp-58h]@1
  __int64 v60; // [sp+20h] [bp-50h]@1
  void *v61; // [sp+28h] [bp-48h]@1
  __int64 v62; // [sp+30h] [bp-40h]@1
  __int64 v63; // [sp+38h] [bp-38h]@1
  struct FIRInstanceIDKeyPairStore *v64; // [sp+40h] [bp-30h]@1

  v59 = a4;
  v4 = *(&selRef_init + 6);
  LODWORD(v5) = objc_retain(a3, a2);
  v6 = v5;
  v7 = objc_msgSend(self, v4);
  LODWORD(v8) = objc_retainAutoreleasedReturnValue(v7);
  v9 = v8;
  v10 = objc_msgSend(v8, *(&selRef_init + 13));
  LODWORD(v11) = objc_retainAutoreleasedReturnValue(v10);
  v61 = v11;
  objc_release(v9);
  v12 = *(&selRef_init + 1);
  v13 = objc_msgSend(self, *(&selRef_init + 1));
  v14 = objc_msgSend(v13, *(&selRef_init + 28), v6);
  LODWORD(v15) = objc_retainAutoreleasedReturnValue(v14);
  v58 = v15;
  v16 = objc_msgSend(self, v12);
  v17 = objc_msgSend(v16, *(&selRef_init + 29), v6);
  LODWORD(v18) = objc_retainAutoreleasedReturnValue(v17);
  v60 = v18;
  v19 = objc_msgSend(self, v12);
  v20 = objc_msgSend(v19, *(&selRef_init + 32), v6);
  LODWORD(v21) = objc_retainAutoreleasedReturnValue(v20);
  v22 = v21;
  v64 = self;
  v23 = v61;
  v24 = objc_msgSend(self, v12);
  v25 = objc_msgSend(v24, *(&selRef_init + 12), v6);
  objc_release(v6);
  LODWORD(v26) = objc_retainAutoreleasedReturnValue(v25);
  v63 = v26;
  v27 = *(&selRef_init + 14);
  v62 = v22;
  v28 = objc_msgSend(v61, v27, v22);
  LODWORD(v29) = objc_retainAutoreleasedReturnValue(v28);
  v30 = v29;
  objc_release(v29);
  if ( v30 )
  {
    LODWORD(v31) = ((int (__fastcall *)(_QWORD, _QWORD, void *))objc_msgSend)(
                     *(&classRef_FIRInstanceIDBackupExcludedPlist + 4),
                     *(&selRef_init + 42),
                     v61);
    LODWORD(v32) = objc_retainAutoreleasedReturnValue(v31);
    v33 = v32;
    v34 = (__int64)*(&selRef_init + 43);
    ((void (__fastcall *)(__int64, _QWORD, __int64))objc_msgSend)(v32, *(&selRef_init + 43), v62);
    ((void (__fastcall *)(__int64, __int64, __int64))objc_msgSend)(v33, v34, v63);
    LODWORD(v35) = ((int (__fastcall *)(struct FIRInstanceIDKeyPairStore *, _QWORD))objc_msgSend)(
                     v64,
                     *(&selRef_init + 6));
    LODWORD(v36) = objc_retainAutoreleasedReturnValue(v35);
    v37 = v36;
    v57 = 0LL;
    v38 = (__int64)*(&selRef_init + 39);
    v39 = ((int (__fastcall *)(__int64, __int64, __int64, __int64 *))objc_msgSend)(v36, v38, v33, &v57);
    LODWORD(v40) = objc_retain(v57, v38);
    v41 = v40;
    objc_release(v37);
    if ( !v39 )
    {
      LODWORD(v42) = FIRInstanceIDSharedLogger(v37);
      LODWORD(v43) = objc_retainAutoreleasedReturnValue(v42);
      v44 = v43;
      objc_msgSend(v43, *(&selRef_init + 16), &aCom_google_iid[707], 10006LL, &cfstr_Com_google_iid + 16, v41);
      objc_release(v44);
    }
    objc_release(v41);
    objc_release(v33);
    v23 = v61;
  }
  if ( v59 )
    *v59 = 0LL;
  v45 = *(&classRef_FIRInstanceIDBackupExcludedPlist + 2);
  v46 = v58;
  v47 = v23;
  if ( (unsigned __int8)objc_msgSend(v45, *(&selRef_init + 40), v60, v58) )
  {
    v48 = v64;
    ((void (__fastcall *)(struct FIRInstanceIDKeyPairStore *, _QWORD, _QWORD))objc_msgSend)(
      v64,
      *(&selRef_init + 24),
      0LL);
    LODWORD(v49) = ((int (__fastcall *)(struct FIRInstanceIDKeyPairStore *, _QWORD))objc_msgSend)(
                     v48,
                     *(&selRef_init + 44));
    LODWORD(v50) = objc_retainAutoreleasedReturnValue(v49);
    v51 = v50;
    ((void (__fastcall *)(__int64, _QWORD, struct FIRInstanceIDKeyPairStore *))objc_msgSend)(
      v50,
      *(&selRef_init + 45),
      v48);
    objc_release(v51);
    v52 = 1;
  }
  else
  {
    LODWORD(v53) = FIRInstanceIDSharedLogger(v45);
    LODWORD(v54) = objc_retainAutoreleasedReturnValue(v53);
    v55 = v54;
    v52 = 0;
    objc_msgSend(v54, *(&selRef_init + 16), &aCom_google_iid[707], 10007LL, &cfstr_Com_google_iid + 17);
    objc_release(v55);
  }
  objc_release(v63);
  objc_release(v62);
  objc_release(v60);
  objc_release(v46);
  objc_release(v47);
  return v52;
}
// 1958: using guessed type __CFString cfstr_Com_google_iid;
// 20F0: using guessed type char *selRef_init;
// 2268: using guessed type void *classRef_FIRInstanceIDBackupExcludedPlist;
// 9C98: using guessed type int __fastcall FIRInstanceIDSharedLogger(_QWORD);
// 9D40: using guessed type int __fastcall objc_release(_QWORD);
// 9D48: using guessed type int (__fastcall *objc_retain)(_QWORD, _QWORD);
// 9D58: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (00000000000011D4) ----------------------------------------------------
// FIRInstanceIDKeyPairStore - (bool)removeKeyPairCreationTimePlistWithError:(id *) 
bool __cdecl -[FIRInstanceIDKeyPairStore removeKeyPairCreationTimePlistWithError:](struct FIRInstanceIDKeyPairStore *self, SEL a2, id *a3)
{
  __int64 v3; // rax@0
  id *v4; // r14@1
  void *v5; // rax@1
  void *v6; // rax@1
  void *v7; // rbx@1
  void *v8; // rdi@1
  bool v9; // bl@1
  __int64 v10; // rax@2
  void *v11; // rax@2
  void *v12; // r14@2

  v4 = a3;
  v5 = objc_msgSend(self, *(&selRef_init + 6), v3);
  LODWORD(v6) = objc_retainAutoreleasedReturnValue(v5);
  v7 = v6;
  LOBYTE(v4) = (unsigned __int64)objc_msgSend(v6, *(&selRef_init + 46), v4);
  v8 = v7;
  objc_release(v7);
  v9 = 1;
  if ( !(_BYTE)v4 )
  {
    LODWORD(v10) = FIRInstanceIDSharedLogger(v8);
    LODWORD(v11) = objc_retainAutoreleasedReturnValue(v10);
    v12 = v11;
    v9 = 0;
    objc_msgSend(v11, *(&selRef_init + 16), &aCom_google_iid[855], 10008LL, &cfstr_Com_google_iid + 18);
    objc_release(v12);
  }
  return v9;
}
// 1958: using guessed type __CFString cfstr_Com_google_iid;
// 20F0: using guessed type char *selRef_init;
// 9C98: using guessed type int __fastcall FIRInstanceIDSharedLogger(_QWORD);
// 9D40: using guessed type int __fastcall objc_release(_QWORD);
// 9D58: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (000000000000126D) ----------------------------------------------------
// FIRInstanceIDKeyPairStore + (id)keyStoreFileName
id __cdecl +[FIRInstanceIDKeyPairStore keyStoreFileName](struct FIRInstanceIDKeyPairStore_meta *self, SEL a2)
{
  objc_retainAutorelease(&cfstr_Com_google_iid, a2);
  return (id)&cfstr_Com_google_iid;
}
// 1958: using guessed type __CFString cfstr_Com_google_iid;
// 9D50: using guessed type int __fastcall objc_retainAutorelease(_QWORD, _QWORD);

//----- (000000000000128C) ----------------------------------------------------
// FIRInstanceIDKeyPairStore - (id)delegate
id __cdecl -[FIRInstanceIDKeyPairStore delegate](struct FIRInstanceIDKeyPairStore *self, SEL a2)
{
  __int64 v2; // rax@1
  id result; // rax@1

  LODWORD(v2) = objc_loadWeakRetained(&self->_delegate, a2);
  LODWORD(result) = objc_autoreleaseReturnValue(v2);
  return result;
}
// 9D18: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 9D28: using guessed type int __fastcall objc_loadWeakRetained(_QWORD, _QWORD);

//----- (00000000000012A5) ----------------------------------------------------
// FIRInstanceIDKeyPairStore - (void)setDelegate:(id) 
void __cdecl -[FIRInstanceIDKeyPairStore setDelegate:](struct FIRInstanceIDKeyPairStore *self, SEL a2, id a3)
{
  objc_storeWeak(&self->_delegate, a3);
}
// 9D68: using guessed type int __fastcall objc_storeWeak(_QWORD, _QWORD);

//----- (00000000000012B9) ----------------------------------------------------
// FIRInstanceIDKeyPairStore - (id)plist
id __cdecl -[FIRInstanceIDKeyPairStore plist](struct FIRInstanceIDKeyPairStore *self, SEL a2)
{
  return (id)self->_plist;
}

//----- (00000000000012CA) ----------------------------------------------------
// FIRInstanceIDKeyPairStore - (void)setPlist:(id) 
void __cdecl -[FIRInstanceIDKeyPairStore setPlist:](struct FIRInstanceIDKeyPairStore *self, SEL a2, id a3)
{
  objc_storeStrong(&self->_plist, a3);
}
// 9D60: using guessed type int __fastcall objc_storeStrong(_QWORD, _QWORD);

//----- (00000000000012DE) ----------------------------------------------------
// FIRInstanceIDKeyPairStore - (id)keyPair
id __cdecl -[FIRInstanceIDKeyPairStore keyPair](struct FIRInstanceIDKeyPairStore *self, SEL a2)
{
  return (id)self->_keyPair;
}

//----- (00000000000012EF) ----------------------------------------------------
// FIRInstanceIDKeyPairStore - (void)setKeyPair:(id) 
void __cdecl -[FIRInstanceIDKeyPairStore setKeyPair:](struct FIRInstanceIDKeyPairStore *self, SEL a2, id a3)
{
  objc_storeStrong(&self->_keyPair, a3);
}
// 9D60: using guessed type int __fastcall objc_storeStrong(_QWORD, _QWORD);

//----- (0000000000001303) ----------------------------------------------------
// FIRInstanceIDKeyPairStore - (int)keychainEntitlementsErrorCount
int __cdecl -[FIRInstanceIDKeyPairStore keychainEntitlementsErrorCount](struct FIRInstanceIDKeyPairStore *self, SEL a2)
{
  return self->_keychainEntitlementsErrorCount;
}

//----- (0000000000001313) ----------------------------------------------------
// FIRInstanceIDKeyPairStore - (void)setKeychainEntitlementsErrorCount:(int) 
void __cdecl -[FIRInstanceIDKeyPairStore setKeychainEntitlementsErrorCount:](struct FIRInstanceIDKeyPairStore *self, SEL a2, int a3)
{
  self->_keychainEntitlementsErrorCount = a3;
}

//----- (0000000000001323) ----------------------------------------------------
// FIRInstanceIDKeyPairStore - (void).cxx_destruct
void __cdecl -[FIRInstanceIDKeyPairStore .cxx_destruct](struct FIRInstanceIDKeyPairStore *self, SEL a2)
{
  objc_storeStrong(&self->_keyPair, 0LL);
  objc_storeStrong(&self->_plist, 0LL);
  objc_destroyWeak(&self->_delegate, 0LL);
}
// 9D20: using guessed type int __fastcall objc_destroyWeak(_QWORD, _QWORD);
// 9D60: using guessed type int __fastcall objc_storeStrong(_QWORD, _QWORD);

// ALL OK, 24 function(s) have been successfully decompiled
