/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2015 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int __fastcall +[FIRInstanceIDAuthKeychainItem keychainItemFromDictionary:](__int64 a1, __int64 a2, void *a3);
id __cdecl -[FIRInstanceIDAuthKeychainItem account](struct FIRInstanceIDAuthKeychainItem *self, SEL);
void __cdecl -[FIRInstanceIDAuthKeychainItem setAccount:](struct FIRInstanceIDAuthKeychainItem *self, SEL, id);
id __cdecl -[FIRInstanceIDAuthKeychainItem service](struct FIRInstanceIDAuthKeychainItem *self, SEL);
void __cdecl -[FIRInstanceIDAuthKeychainItem setService:](struct FIRInstanceIDAuthKeychainItem *self, SEL, id);
id __cdecl -[FIRInstanceIDAuthKeychainItem data](struct FIRInstanceIDAuthKeychainItem *self, SEL);
void __cdecl -[FIRInstanceIDAuthKeychainItem setData:](struct FIRInstanceIDAuthKeychainItem *self, SEL, id);
id __cdecl -[FIRInstanceIDAuthKeychainItem modificationDate](struct FIRInstanceIDAuthKeychainItem *self, SEL);
void __cdecl -[FIRInstanceIDAuthKeychainItem setModificationDate:](struct FIRInstanceIDAuthKeychainItem *self, SEL, id);
void __cdecl -[FIRInstanceIDAuthKeychainItem .cxx_destruct](struct FIRInstanceIDAuthKeychainItem *self, SEL);
id __cdecl -[FIRInstanceIDAuthKeychain initWithIdentifier:](struct FIRInstanceIDAuthKeychain *self, SEL, id);
id __cdecl +[FIRInstanceIDAuthKeychain keychainQueryForService:account:accessGroup:generic:](struct FIRInstanceIDAuthKeychain *self, SEL, id, id, id, id);
id __cdecl -[FIRInstanceIDAuthKeychain keychainQueryForService:account:accessGroup:](struct FIRInstanceIDAuthKeychain *self, SEL, id, id, id);
id __cdecl -[FIRInstanceIDAuthKeychain defaultAccessGroup](struct FIRInstanceIDAuthKeychain *self, SEL);
// int __usercall __47__FIRInstanceIDAuthKeychain_defaultAccessGroup__block_invoke@<eax>(__int64 a1@<rax>, __int64 a2@<rdi>);
int __fastcall __copy_helper_block_(__int64 a1, __int64 a2);
int __fastcall __destroy_helper_block_(__int64 a1);
id __cdecl -[FIRInstanceIDAuthKeychain itemsMatchingService:account:accessGroup:error:](struct FIRInstanceIDAuthKeychain *self, SEL, id, id, id, id *);
id __cdecl -[FIRInstanceIDAuthKeychain itemForService:account:accessGroup:error:](struct FIRInstanceIDAuthKeychain *self, SEL, id, id, id, id *);
bool __cdecl -[FIRInstanceIDAuthKeychain removeItemsMatchingService:account:accessGroup:error:](struct FIRInstanceIDAuthKeychain *self, SEL, id, id, id, id *);
bool __cdecl -[FIRInstanceIDAuthKeychain setData:forService:accessibility:account:accessGroup:error:](struct FIRInstanceIDAuthKeychain *self, SEL, id, id, void *, id, id, id *);
bool __cdecl -[FIRInstanceIDAuthKeychain removeAllItemsWithError:](struct FIRInstanceIDAuthKeychain *self, SEL, id *);
void __cdecl +[FIRInstanceIDAuthKeychain printKeychainItems](struct FIRInstanceIDAuthKeychain_meta *self, SEL);
id __cdecl -[FIRInstanceIDAuthKeychain generic](struct FIRInstanceIDAuthKeychain *self, SEL);
void __cdecl -[FIRInstanceIDAuthKeychain setGeneric:](struct FIRInstanceIDAuthKeychain *self, SEL, id);
id __cdecl -[FIRInstanceIDAuthKeychain identifier](struct FIRInstanceIDAuthKeychain *self, SEL);
void __cdecl -[FIRInstanceIDAuthKeychain setIdentifier:](struct FIRInstanceIDAuthKeychain *self, SEL, id);
void __cdecl -[FIRInstanceIDAuthKeychain .cxx_destruct](struct FIRInstanceIDAuthKeychain *self, SEL);
// int CFArrayGetCount(void); weak
// int CFRelease(void); weak
// int FIRInstanceIDSharedLogger(void); weak
// int __fastcall SecItemAdd(_QWORD, _QWORD); weak
// int __fastcall SecItemCopyMatching(_QWORD, _QWORD); weak
// int __fastcall SecItemDelete(_QWORD); weak
// int __fastcall dispatch_once(_QWORD, _QWORD); weak
// int __fastcall objc_autorelease(_QWORD); weak
// int __fastcall objc_autoreleaseReturnValue(_QWORD); weak
// int __fastcall objc_getProperty(_QWORD, _QWORD, _QWORD, _QWORD); weak
// void *objc_msgSend(void *, const char *, ...); idb
// void *objc_msgSendSuper2(void *, const char *, ...); idb
// int __fastcall objc_retainAutoreleaseReturnValue(_QWORD, _QWORD); weak
// int __fastcall objc_retainAutoreleasedReturnValue(_QWORD); weak
// int __fastcall objc_setProperty_nonatomic_copy(_QWORD, _QWORD, _QWORD, _QWORD); weak
// int __fastcall objc_storeStrong(_QWORD, _QWORD); weak

//-------------------------------------------------------------------------
// Data declarations

char asc_F35[2] = "*"; // weak
__CFString stru_10E8 = { &__CFConstantStringClassReference, 1992LL, "*", 1LL }; // weak
_UNKNOWN __block_descriptor_tmp; // weak
void *classRef_FIRInstanceIDAuthKeychainItem = &OBJC_CLASS___FIRInstanceIDAuthKeychainItem; // weak
char *selRef_alloc = "alloc"; // weak
void *classRef_FIRInstanceIDAuthKeychain = &OBJC_CLASS___FIRInstanceIDAuthKeychain; // weak
__int64 defaultAccessGroup_defaultGroup; // weak
__int64 defaultAccessGroup_onceToken; // weak
// extern void *_NSConcreteStackBlock[32];
// extern _UNKNOWN __stack_chk_guard; weak
// extern _UNKNOWN kCFBooleanFalse; weak
// extern _UNKNOWN kCFBooleanTrue; weak
// extern _UNKNOWN kSecAttrAccessGroup; weak
// extern _UNKNOWN kSecAttrAccessible; weak
// extern _UNKNOWN kSecAttrAccessibleAlwaysThisDeviceOnly; weak
// extern _UNKNOWN kSecAttrAccount; weak
// extern _UNKNOWN kSecAttrGeneric; weak
// extern _UNKNOWN kSecAttrModificationDate; weak
// extern _UNKNOWN kSecAttrService; weak
// extern _UNKNOWN kSecAttrSynchronizable; weak
// extern _UNKNOWN kSecClass; weak
// extern _UNKNOWN kSecClassGenericPassword; weak
// extern _UNKNOWN kSecMatchLimit; weak
// extern _UNKNOWN kSecMatchLimitAll; weak
// extern _UNKNOWN kSecReturnAttributes; weak
// extern _UNKNOWN kSecReturnData; weak
// extern _UNKNOWN kSecValueData; weak
// extern int (__fastcall *objc_release)(_QWORD); weak
// extern int (__fastcall *objc_retain)(_QWORD); weak


//----- (0000000000000000) ----------------------------------------------------
int __fastcall +[FIRInstanceIDAuthKeychainItem keychainItemFromDictionary:](__int64 a1, __int64 a2, void *a3)
{
  void *v3; // r13@1
  __int64 v4; // rax@1
  void *v5; // rax@1
  void *v6; // r14@1
  const char *v7; // r12@1
  void *v8; // rax@1
  __int64 v9; // rax@1
  __int64 v10; // rbx@1
  void *v11; // rax@1
  __int64 v12; // rax@1
  __int64 v13; // rbx@1
  void *v14; // rax@1
  __int64 v15; // rax@1
  __int64 v16; // rbx@1
  void *v17; // rbx@1
  __int64 v18; // ST00_8@1
  __int64 v19; // rax@1
  __int64 v20; // rbx@1

  v3 = a3;
  LODWORD(v4) = objc_retain(a3);
  v5 = objc_msgSend(classRef_FIRInstanceIDAuthKeychainItem, selRef_alloc, v4);
  v6 = objc_msgSend(v5, *(&selRef_alloc + 1));
  v7 = *(&selRef_alloc + 2);
  v8 = objc_msgSend(v3, *(&selRef_alloc + 2), *kSecAttrAccount);
  LODWORD(v9) = objc_retainAutoreleasedReturnValue(v8);
  v10 = v9;
  objc_msgSend(v6, *(&selRef_alloc + 3), v9);
  objc_release(v10);
  v11 = objc_msgSend(v3, v7, *kSecAttrService);
  LODWORD(v12) = objc_retainAutoreleasedReturnValue(v11);
  v13 = v12;
  objc_msgSend(v6, *(&selRef_alloc + 4), v12);
  objc_release(v13);
  v14 = objc_msgSend(v3, v7, *kSecValueData);
  LODWORD(v15) = objc_retainAutoreleasedReturnValue(v14);
  v16 = v15;
  objc_msgSend(v6, *(&selRef_alloc + 5), v15);
  objc_release(v16);
  v17 = objc_msgSend(v3, *(&selRef_alloc + 2), *kSecAttrModificationDate);
  objc_release(v18);
  LODWORD(v19) = objc_retainAutoreleasedReturnValue(v17);
  v20 = v19;
  objc_msgSend(v6, *(&selRef_alloc + 6), v19);
  objc_release(v20);
  return objc_autoreleaseReturnValue(v6);
}
// 1270: using guessed type void *classRef_FIRInstanceIDAuthKeychainItem;
// 1640: using guessed type char *selRef_alloc;
// 8918: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 8938: using guessed type int (__fastcall *objc_release)(_QWORD);
// 8940: using guessed type int (__fastcall *objc_retain)(_QWORD);
// 8950: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000154) ----------------------------------------------------
// FIRInstanceIDAuthKeychainItem - (id)account
id __cdecl -[FIRInstanceIDAuthKeychainItem account](struct FIRInstanceIDAuthKeychainItem *self, SEL a2)
{
  id result; // rax@1

  LODWORD(result) = objc_getProperty(self, a2, 8LL, 0LL);
  return result;
}
// 8920: using guessed type int __fastcall objc_getProperty(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000000167) ----------------------------------------------------
// FIRInstanceIDAuthKeychainItem - (void)setAccount:(id) 
void __cdecl -[FIRInstanceIDAuthKeychainItem setAccount:](struct FIRInstanceIDAuthKeychainItem *self, SEL a2, id a3)
{
  objc_setProperty_nonatomic_copy(self, a2, a3, 8LL);
}
// 8958: using guessed type int __fastcall objc_setProperty_nonatomic_copy(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000000178) ----------------------------------------------------
// FIRInstanceIDAuthKeychainItem - (id)service
id __cdecl -[FIRInstanceIDAuthKeychainItem service](struct FIRInstanceIDAuthKeychainItem *self, SEL a2)
{
  id result; // rax@1

  LODWORD(result) = objc_getProperty(self, a2, 16LL, 0LL);
  return result;
}
// 8920: using guessed type int __fastcall objc_getProperty(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (000000000000018B) ----------------------------------------------------
// FIRInstanceIDAuthKeychainItem - (void)setService:(id) 
void __cdecl -[FIRInstanceIDAuthKeychainItem setService:](struct FIRInstanceIDAuthKeychainItem *self, SEL a2, id a3)
{
  objc_setProperty_nonatomic_copy(self, a2, a3, 16LL);
}
// 8958: using guessed type int __fastcall objc_setProperty_nonatomic_copy(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (000000000000019C) ----------------------------------------------------
// FIRInstanceIDAuthKeychainItem - (id)data
id __cdecl -[FIRInstanceIDAuthKeychainItem data](struct FIRInstanceIDAuthKeychainItem *self, SEL a2)
{
  id result; // rax@1

  LODWORD(result) = objc_getProperty(self, a2, 24LL, 0LL);
  return result;
}
// 8920: using guessed type int __fastcall objc_getProperty(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (00000000000001AF) ----------------------------------------------------
// FIRInstanceIDAuthKeychainItem - (void)setData:(id) 
void __cdecl -[FIRInstanceIDAuthKeychainItem setData:](struct FIRInstanceIDAuthKeychainItem *self, SEL a2, id a3)
{
  objc_setProperty_nonatomic_copy(self, a2, a3, 24LL);
}
// 8958: using guessed type int __fastcall objc_setProperty_nonatomic_copy(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (00000000000001C0) ----------------------------------------------------
// FIRInstanceIDAuthKeychainItem - (id)modificationDate
id __cdecl -[FIRInstanceIDAuthKeychainItem modificationDate](struct FIRInstanceIDAuthKeychainItem *self, SEL a2)
{
  id result; // rax@1

  LODWORD(result) = objc_getProperty(self, a2, 32LL, 0LL);
  return result;
}
// 8920: using guessed type int __fastcall objc_getProperty(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (00000000000001D3) ----------------------------------------------------
// FIRInstanceIDAuthKeychainItem - (void)setModificationDate:(id) 
void __cdecl -[FIRInstanceIDAuthKeychainItem setModificationDate:](struct FIRInstanceIDAuthKeychainItem *self, SEL a2, id a3)
{
  objc_setProperty_nonatomic_copy(self, a2, a3, 32LL);
}
// 8958: using guessed type int __fastcall objc_setProperty_nonatomic_copy(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (00000000000001E4) ----------------------------------------------------
// FIRInstanceIDAuthKeychainItem - (void).cxx_destruct
void __cdecl -[FIRInstanceIDAuthKeychainItem .cxx_destruct](struct FIRInstanceIDAuthKeychainItem *self, SEL a2)
{
  objc_storeStrong(&self->_modificationDate, 0LL);
  objc_storeStrong(&self->_data, 0LL);
  objc_storeStrong(&self->_service, 0LL);
  objc_storeStrong(&self->_account, 0LL);
}
// 8960: using guessed type int __fastcall objc_storeStrong(_QWORD, _QWORD);

//----- (0000000000000237) ----------------------------------------------------
// FIRInstanceIDAuthKeychain - (id)initWithIdentifier:(id) 
id __cdecl -[FIRInstanceIDAuthKeychain initWithIdentifier:](struct FIRInstanceIDAuthKeychain *self, SEL a2, id a3)
{
  void *v3; // rax@1
  void *v4; // r14@1
  struct objc_object *v5; // rbx@1
  void *v6; // rax@2
  Class v7; // rdi@2
  struct FIRInstanceIDAuthKeychain *v9; // [sp+0h] [bp-20h]@1
  void *v10; // [sp+8h] [bp-18h]@1

  LODWORD(v3) = objc_retain(a3);
  v4 = v3;
  v9 = self;
  v10 = classRef_FIRInstanceIDAuthKeychain;
  v5 = (struct objc_object *)objc_msgSendSuper2(&v9, *(&selRef_alloc + 1), self, classRef_FIRInstanceIDAuthKeychain);
  if ( v5 )
  {
    v6 = objc_msgSend(v4, *(&selRef_alloc + 7), v9, v10);
    v7 = v5[1].isa;
    v5[1].isa = v6;
    objc_release(v7);
  }
  objc_release(v4);
  return v5;
}
// 1640: using guessed type char *selRef_alloc;
// 1D30: using guessed type void *classRef_FIRInstanceIDAuthKeychain;
// 8938: using guessed type int (__fastcall *objc_release)(_QWORD);
// 8940: using guessed type int (__fastcall *objc_retain)(_QWORD);

//----- (00000000000002B1) ----------------------------------------------------
// FIRInstanceIDAuthKeychain + (id)keychainQueryForService:(id) account:(id) accessGroup:(id) generic:(id) 
id __cdecl +[FIRInstanceIDAuthKeychain keychainQueryForService:account:accessGroup:generic:](struct FIRInstanceIDAuthKeychain *self, SEL a2, id a3, id a4, id a5, id a6)
{
  id v6; // r14@1
  id v7; // r15@1
  id v8; // r12@1
  __int64 v9; // rax@1
  __int64 v10; // ST00_8@1
  void *v11; // rax@1
  __int64 v12; // rax@1
  void *v13; // rax@1
  void *v14; // r13@1
  void *v15; // rax@1
  __int64 v16; // rax@1
  void *v17; // rax@1
  void *v18; // rax@1
  void *v19; // r12@1
  const char *v20; // r15@1
  id result; // rax@12
  void *v22; // [sp+0h] [bp-60h]@1
  __int64 v23; // [sp+8h] [bp-58h]@1
  __int64 v24; // [sp+10h] [bp-50h]@1
  void *v25; // [sp+18h] [bp-48h]@1
  __int64 v26; // [sp+20h] [bp-40h]@1
  __int64 v27; // [sp+28h] [bp-38h]@1
  __int64 v28; // [sp+30h] [bp-30h]@1

  v6 = a6;
  v7 = a5;
  v8 = a4;
  v28 = *__stack_chk_guard;
  LODWORD(v9) = objc_retain(a3);
  v10 = v9;
  LODWORD(v11) = objc_retain(v8);
  v25 = v11;
  LODWORD(v12) = objc_retain(v7);
  v23 = v12;
  LODWORD(v13) = objc_retain(v6);
  v14 = v13;
  v26 = *kSecClass;
  v27 = *kSecClassGenericPassword;
  v15 = objc_msgSend(*(&classRef_FIRInstanceIDAuthKeychainItem + 1), *(&selRef_alloc + 8), &v27, v10);
  LODWORD(v16) = objc_retainAutoreleasedReturnValue(v15);
  v24 = v16;
  v17 = objc_msgSend(*(&classRef_FIRInstanceIDAuthKeychainItem + 2), *(&selRef_alloc + 9), v16);
  LODWORD(v18) = objc_retainAutoreleasedReturnValue(v17);
  v19 = v18;
  v20 = *(&selRef_alloc + 10);
  if ( objc_msgSend(v14, *(&selRef_alloc + 10))
    && !(unsigned __int8)objc_msgSend(&stru_10E8, *(&selRef_alloc + 11), v14) )
  {
    objc_msgSend(v19, *(&selRef_alloc + 12), v14, *kSecAttrGeneric);
  }
  if ( objc_msgSend(v25, v20) && !(unsigned __int8)objc_msgSend(&stru_10E8, *(&selRef_alloc + 11), v25) )
    objc_msgSend(v19, *(&selRef_alloc + 12), v25, *kSecAttrAccount);
  if ( objc_msgSend(v22, v20) && !(unsigned __int8)objc_msgSend(&stru_10E8, *(&selRef_alloc + 11), v22) )
    objc_msgSend(v19, *(&selRef_alloc + 12), v22, *kSecAttrService);
  if ( v23 )
    objc_msgSend(v19, *(&selRef_alloc + 12), v23, *kSecAttrAccessGroup);
  objc_release(v24);
  objc_release(v14);
  objc_release(v23);
  objc_release(v25);
  objc_release(v22);
  result = (id)*__stack_chk_guard;
  if ( *__stack_chk_guard == v28 )
    LODWORD(result) = objc_autoreleaseReturnValue(v19);
  return result;
}
// 10E8: using guessed type __CFString stru_10E8;
// 1270: using guessed type void *classRef_FIRInstanceIDAuthKeychainItem;
// 1640: using guessed type char *selRef_alloc;
// 8918: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 8938: using guessed type int (__fastcall *objc_release)(_QWORD);
// 8940: using guessed type int (__fastcall *objc_retain)(_QWORD);
// 8950: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (00000000000004CD) ----------------------------------------------------
// FIRInstanceIDAuthKeychain - (id)keychainQueryForService:(id) account:(id) accessGroup:(id) 
id __cdecl -[FIRInstanceIDAuthKeychain keychainQueryForService:account:accessGroup:](struct FIRInstanceIDAuthKeychain *self, SEL a2, id a3, id a4, id a5)
{
  id v5; // r12@1
  id v6; // r15@1
  __int64 v7; // rax@1
  __int64 v8; // ST08_8@1
  __int64 v9; // rax@1
  __int64 v10; // r15@1
  const char *v11; // r13@1
  __int64 v12; // rax@1
  __int64 v13; // r12@1
  void *v14; // r13@1
  void *v15; // rax@1
  __int64 v16; // rax@1
  __int64 v17; // r14@1
  void *v18; // ST10_8@1
  __int64 v19; // rax@1
  __int64 v20; // rbx@1
  id result; // rax@1

  v5 = a5;
  v6 = a4;
  LODWORD(v7) = objc_retain(a3);
  v8 = v7;
  LODWORD(v9) = objc_retain(v6);
  v10 = v9;
  v11 = *(&selRef_alloc + 13);
  LODWORD(v12) = objc_retain(v5);
  v13 = v12;
  v14 = objc_msgSend(self, v11);
  v15 = objc_msgSend(self, *(&selRef_alloc + 14));
  LODWORD(v16) = objc_retainAutoreleasedReturnValue(v15);
  v17 = v16;
  v18 = objc_msgSend(v14, *(&selRef_alloc + 15), v8, v10, v13, v16);
  objc_release(v13);
  objc_release(v10);
  objc_release(v8);
  LODWORD(v19) = objc_retainAutoreleasedReturnValue(v18);
  v20 = v19;
  objc_release(v17);
  LODWORD(result) = objc_autoreleaseReturnValue(v20);
  return result;
}
// 1640: using guessed type char *selRef_alloc;
// 8918: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 8938: using guessed type int (__fastcall *objc_release)(_QWORD);
// 8940: using guessed type int (__fastcall *objc_retain)(_QWORD);
// 8950: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (00000000000005A4) ----------------------------------------------------
// FIRInstanceIDAuthKeychain - (id)defaultAccessGroup
id __cdecl -[FIRInstanceIDAuthKeychain defaultAccessGroup](struct FIRInstanceIDAuthKeychain *self, SEL a2)
{
  __int64 v2; // rax@1
  __int64 v3; // r14@1
  struct objc_object *v4; // rax@3
  struct objc_object *v5; // rbx@3
  void *v7; // [sp+8h] [bp-38h]@1
  int v8; // [sp+10h] [bp-30h]@1
  int v9; // [sp+14h] [bp-2Ch]@1
  int (__usercall *v10)@<eax>(__int64@<rax>, __int64@<rdi>); // [sp+18h] [bp-28h]@1
  void *v11; // [sp+20h] [bp-20h]@1
  __int64 v12; // [sp+28h] [bp-18h]@1

  v7 = _NSConcreteStackBlock[0];
  v8 = -1040187392;
  v9 = 0;
  v10 = __47__FIRInstanceIDAuthKeychain_defaultAccessGroup__block_invoke;
  v11 = &__block_descriptor_tmp;
  LODWORD(v2) = objc_retain(self);
  v3 = v2;
  v12 = v2;
  if ( defaultAccessGroup_onceToken != -1 )
  {
    a2 = &v7;
    dispatch_once(&defaultAccessGroup_onceToken, &v7);
    v3 = v12;
  }
  LODWORD(v4) = objc_retainAutoreleaseReturnValue(defaultAccessGroup_defaultGroup, a2);
  v5 = v4;
  objc_release(v3);
  return v5;
}
// 87D8: using guessed type __int64 defaultAccessGroup_defaultGroup;
// 87E0: using guessed type __int64 defaultAccessGroup_onceToken;
// 8880: using guessed type int __fastcall dispatch_once(_QWORD, _QWORD);
// 8938: using guessed type int (__fastcall *objc_release)(_QWORD);
// 8940: using guessed type int (__fastcall *objc_retain)(_QWORD);
// 8948: using guessed type int __fastcall objc_retainAutoreleaseReturnValue(_QWORD, _QWORD);

//----- (0000000000000632) ----------------------------------------------------
int __usercall __47__FIRInstanceIDAuthKeychain_defaultAccessGroup__block_invoke@<eax>(__int64 a1@<rax>, __int64 a2@<rdi>)
{
  void *v2; // rax@1
  void *v3; // rax@1
  void *v4; // r14@1
  const char *v5; // rbx@1
  int v6; // ebx@1
  __int64 v7; // rax@2
  void *v8; // rax@2
  void *v9; // r15@2
  __int64 v10; // rbx@3
  const char *v11; // r15@3
  void *v12; // rax@3
  void *v13; // r12@3
  void *v14; // rax@3
  void *v15; // rax@3
  void *v16; // rbx@3
  void *v17; // rax@3
  __int64 v18; // rdi@3
  __int64 v20; // [sp+0h] [bp-30h]@1

  v20 = a1;
  v2 = objc_msgSend(*(void **)(a2 + 32), *(&selRef_alloc + 16), &stru_10E8 + 2, &stru_10E8 + 3, 0LL, a1);
  LODWORD(v3) = objc_retainAutoreleasedReturnValue(v2);
  v4 = v3;
  v5 = *(&selRef_alloc + 12);
  objc_msgSend(v3, *(&selRef_alloc + 12), *kCFBooleanTrue, *kSecReturnAttributes, v20);
  objc_msgSend(v4, v5, *kCFBooleanFalse, *kSecAttrSynchronizable, v20);
  objc_msgSend(v4, v5, *kSecAttrAccessibleAlwaysThisDeviceOnly, *kSecAttrAccessible, v20);
  v20 = 0LL;
  SecItemDelete(v4);
  v6 = SecItemAdd(v4, &v20);
  if ( v6 )
  {
    LODWORD(v7) = FIRInstanceIDSharedLogger();
    LODWORD(v8) = objc_retainAutoreleasedReturnValue(v7);
    v9 = v8;
    objc_msgSend(v8, *(&selRef_alloc + 17), &asc_F35[186], 17000LL, &stru_10E8 + 4, (unsigned int)v6, v20);
    objc_release(v9);
  }
  else
  {
    v10 = *kSecAttrAccessGroup;
    v11 = *(&selRef_alloc + 2);
    LODWORD(v12) = objc_retain(v20);
    v13 = v12;
    v14 = objc_msgSend(v12, v11, v10, v20);
    LODWORD(v15) = objc_retainAutoreleasedReturnValue(v14);
    v16 = v15;
    v17 = objc_msgSend(v15, *(&selRef_alloc + 7), v20);
    v18 = defaultAccessGroup_defaultGroup;
    defaultAccessGroup_defaultGroup = (__int64)v17;
    objc_release(v18);
    objc_release(v13);
    SecItemDelete(v4);
    objc_release(v16);
  }
  if ( v20 )
    CFRelease();
  return objc_release(v4);
}
// 10E8: using guessed type __CFString stru_10E8;
// 1640: using guessed type char *selRef_alloc;
// 87D8: using guessed type __int64 defaultAccessGroup_defaultGroup;
// 87F8: using guessed type int CFRelease(void);
// 8800: using guessed type int FIRInstanceIDSharedLogger(void);
// 8840: using guessed type int __fastcall SecItemAdd(_QWORD, _QWORD);
// 8850: using guessed type int __fastcall SecItemDelete(_QWORD);
// 8938: using guessed type int (__fastcall *objc_release)(_QWORD);
// 8940: using guessed type int (__fastcall *objc_retain)(_QWORD);
// 8950: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (00000000000007CA) ----------------------------------------------------
int __fastcall __copy_helper_block_(__int64 a1, __int64 a2)
{
  return objc_retain(*(_QWORD *)(a2 + 32));
}
// 8940: using guessed type int (__fastcall *objc_retain)(_QWORD);

//----- (00000000000007D9) ----------------------------------------------------
int __fastcall __destroy_helper_block_(__int64 a1)
{
  return objc_release(*(_QWORD *)(a1 + 32));
}
// 8938: using guessed type int (__fastcall *objc_release)(_QWORD);

//----- (00000000000007E8) ----------------------------------------------------
// FIRInstanceIDAuthKeychain - (id)itemsMatchingService:(id) account:(id) accessGroup:(id) error:(id *) 
id __cdecl -[FIRInstanceIDAuthKeychain itemsMatchingService:account:accessGroup:error:](struct FIRInstanceIDAuthKeychain *self, SEL a2, id a3, id a4, id a5, id *a6)
{
  id v6; // r15@1
  id v7; // rbx@1
  void *v8; // rax@1
  void *v9; // r13@1
  void *v10; // rax@1
  void *v11; // r14@1
  __int64 v12; // rax@1
  __int64 v13; // r12@1
  void *v14; // rax@1
  void *v15; // rax@1
  const char *v16; // r15@1
  void *v17; // rax@1
  __int64 v18; // rdx@1
  signed int v19; // ecx@1
  void *v20; // rax@2
  void *v21; // r15@2
  void *v22; // rax@3
  void *v23; // rax@3
  void *v24; // r12@3
  __int64 v25; // rbx@3
  const char *v26; // r14@3
  int v27; // eax@3
  __int64 v28; // rax@4
  __int64 v29; // r15@4
  __int64 v30; // rbx@6
  void *v31; // rax@7
  __int64 v32; // rax@7
  __int64 v33; // r14@7
  void *v34; // rax@7
  __int64 v35; // rax@7
  __int64 v36; // r12@7
  void *v37; // rax@14
  __int64 v38; // rax@14
  struct objc_object *v39; // rax@14
  void *v40; // rbx@15
  __int64 v41; // rax@15
  void *v42; // rdi@15
  __int64 v43; // r14@15
  id result; // rax@16
  void *v45; // rax@17
  __int64 v46; // rax@17
  const char *v47; // [sp+8h] [bp-88h]@6
  const char *v48; // [sp+10h] [bp-80h]@6
  id *v49; // [sp+18h] [bp-78h]@1
  void *v50; // [sp+28h] [bp-68h]@4
  void *v51; // [sp+30h] [bp-60h]@4
  __int64 v52; // [sp+38h] [bp-58h]@3
  void *v53; // [sp+40h] [bp-50h]@3
  void *v54; // [sp+48h] [bp-48h]@1
  struct FIRInstanceIDAuthKeychain *v55; // [sp+50h] [bp-40h]@1
  int v56; // [sp+5Ch] [bp-34h]@4
  char v57; // [sp+60h] [bp-30h]@17

  v49 = a6;
  v6 = a5;
  v7 = a4;
  v55 = self;
  LODWORD(v8) = objc_retain(a3);
  v9 = v8;
  LODWORD(v10) = objc_retain(v7);
  v11 = v10;
  LODWORD(v12) = objc_retain(v6);
  v13 = v12;
  v14 = objc_msgSend(*(&classRef_FIRInstanceIDAuthKeychainItem + 3), *(&selRef_alloc + 18));
  LODWORD(v15) = objc_retainAutoreleasedReturnValue(v14);
  v54 = v15;
  v16 = *(&selRef_alloc + 10);
  v17 = objc_msgSend(v9, *(&selRef_alloc + 10));
  v19 = -1301;
  if ( v17 )
  {
    v20 = objc_msgSend(v11, v16, v18);
    v19 = -1301;
    v21 = v11;
    if ( v20 )
    {
      v53 = 0LL;
      v52 = v13;
      v22 = objc_msgSend(v55, *(&selRef_alloc + 16), v9, v11, v13);
      LODWORD(v23) = objc_retainAutoreleasedReturnValue(v22);
      v24 = v23;
      v25 = *kCFBooleanTrue;
      v26 = *(&selRef_alloc + 12);
      objc_msgSend(v23, *(&selRef_alloc + 12), *kCFBooleanTrue, *kSecReturnData);
      objc_msgSend(v24, v26, v25, *kSecReturnAttributes);
      objc_msgSend(v24, v26, *kSecMatchLimitAll, *kSecMatchLimit);
      v27 = SecItemCopyMatching(v24, &v53);
      if ( !v53 )
      {
        v45 = objc_msgSend(*(&classRef_FIRInstanceIDAuthKeychainItem + 4), *(&selRef_alloc + 19), &v57, 0LL);
        LODWORD(v46) = objc_retainAutoreleasedReturnValue(v45);
        v43 = v46;
        objc_release(v24);
        v42 = v54;
        v13 = v52;
        goto LABEL_16;
      }
      v56 = v27;
      v51 = v24;
      v50 = v21;
      LODWORD(v28) = CFArrayGetCount();
      v29 = v28;
      if ( v28 > 0 && !v56 )
      {
        v55 = (struct FIRInstanceIDAuthKeychain *)*(&selRef_alloc + 20);
        v47 = *(&selRef_alloc + 21);
        v48 = *(&selRef_alloc + 22);
        v30 = 0LL;
        do
        {
          v31 = objc_msgSend(v53, (const char *)v55, v30);
          LODWORD(v32) = objc_retainAutoreleasedReturnValue(v31);
          v33 = v32;
          v34 = objc_msgSend(classRef_FIRInstanceIDAuthKeychainItem, v47, v32);
          LODWORD(v35) = objc_retainAutoreleasedReturnValue(v34);
          v36 = v35;
          objc_msgSend(v54, v48, v35);
          objc_release(v36);
          objc_release(v33);
          ++v30;
        }
        while ( v29 != v30 );
      }
      if ( v53 )
        CFRelease();
      objc_release(v51);
      v21 = v50;
      v13 = v52;
      v19 = v56;
    }
  }
  else
  {
    v21 = v11;
  }
  if ( v49 && v19 )
  {
    v37 = objc_msgSend(*(&classRef_FIRInstanceIDAuthKeychainItem + 5), *(&selRef_alloc + 23), &stru_10E8 + 1, v19, 0LL);
    LODWORD(v38) = objc_retainAutoreleasedReturnValue(v37);
    LODWORD(v39) = objc_autorelease(v38);
    *v49 = v39;
  }
  v40 = v54;
  LODWORD(v41) = objc_retain(v54);
  v42 = v40;
  v43 = v41;
LABEL_16:
  objc_release(v42);
  objc_release(v13);
  objc_release(v21);
  objc_release(v9);
  LODWORD(result) = objc_autoreleaseReturnValue(v43);
  return result;
}
// 10E8: using guessed type __CFString stru_10E8;
// 1270: using guessed type void *classRef_FIRInstanceIDAuthKeychainItem;
// 1640: using guessed type char *selRef_alloc;
// 87F0: using guessed type int CFArrayGetCount(void);
// 87F8: using guessed type int CFRelease(void);
// 8848: using guessed type int __fastcall SecItemCopyMatching(_QWORD, _QWORD);
// 8910: using guessed type int __fastcall objc_autorelease(_QWORD);
// 8918: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 8938: using guessed type int (__fastcall *objc_release)(_QWORD);
// 8940: using guessed type int (__fastcall *objc_retain)(_QWORD);
// 8950: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000AE1) ----------------------------------------------------
// FIRInstanceIDAuthKeychain - (id)itemForService:(id) account:(id) accessGroup:(id) error:(id *) 
id __cdecl -[FIRInstanceIDAuthKeychain itemForService:account:accessGroup:error:](struct FIRInstanceIDAuthKeychain *self, SEL a2, id a3, id a4, id a5, id *a6)
{
  id *v6; // ST00_8@1
  id v7; // r15@1
  id v8; // r13@1
  __int64 v9; // rax@1
  __int64 v10; // r14@1
  __int64 v11; // rax@1
  __int64 v12; // rbx@1
  void *v13; // r15@1
  void *v14; // rax@1
  void *v15; // rbx@1
  void *v16; // rax@1
  __int64 v17; // rax@1
  __int64 v18; // r14@1
  id result; // rax@1

  v6 = a6;
  v7 = a5;
  v8 = a4;
  LODWORD(v9) = objc_retain(a3);
  v10 = v9;
  LODWORD(v11) = objc_retain(v8);
  v12 = v11;
  v13 = objc_msgSend(self, *(&selRef_alloc + 24), v10, v11, v7, v6, v6);
  objc_release(v12);
  objc_release(v10);
  LODWORD(v14) = objc_retainAutoreleasedReturnValue(v13);
  v15 = v14;
  v16 = objc_msgSend(v14, *(&selRef_alloc + 25));
  LODWORD(v17) = objc_retainAutoreleasedReturnValue(v16);
  v18 = v17;
  objc_release(v15);
  LODWORD(result) = objc_autoreleaseReturnValue(v18);
  return result;
}
// 1640: using guessed type char *selRef_alloc;
// 8918: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 8938: using guessed type int (__fastcall *objc_release)(_QWORD);
// 8940: using guessed type int (__fastcall *objc_retain)(_QWORD);
// 8950: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000B89) ----------------------------------------------------
// FIRInstanceIDAuthKeychain - (bool)removeItemsMatchingService:(id) account:(id) accessGroup:(id) error:(id *) 
bool __cdecl -[FIRInstanceIDAuthKeychain removeItemsMatchingService:account:accessGroup:error:](struct FIRInstanceIDAuthKeychain *self, SEL a2, id a3, id a4, id a5, id *a6)
{
  id v6; // r12@1
  id v7; // rbx@1
  void *v8; // rax@1
  void *v9; // r13@1
  void *v10; // rax@1
  void *v11; // rbx@1
  __int64 v12; // rax@1
  __int64 v13; // r14@1
  const char *v14; // r15@1
  int v15; // er12@1
  void *v16; // rax@3
  __int64 v17; // rax@3
  __int64 v18; // r15@3
  char v19; // r15@5
  void *v20; // rax@7
  __int64 v21; // rax@7
  struct objc_object *v22; // rax@7
  id *v24; // [sp+8h] [bp-38h]@1

  v24 = a6;
  v6 = a5;
  v7 = a4;
  LODWORD(v8) = objc_retain(a3);
  v9 = v8;
  LODWORD(v10) = objc_retain(v7);
  v11 = v10;
  LODWORD(v12) = objc_retain(v6);
  v13 = v12;
  v14 = *(&selRef_alloc + 10);
  v15 = -1301;
  if ( objc_msgSend(v9, *(&selRef_alloc + 10)) && objc_msgSend(v11, v14) )
  {
    v16 = objc_msgSend(self, *(&selRef_alloc + 16), v9, v11, v13);
    LODWORD(v17) = objc_retainAutoreleasedReturnValue(v16);
    v18 = v17;
    v15 = SecItemDelete(v17);
    objc_release(v18);
  }
  if ( v24 )
  {
    v19 = 1;
    if ( v15 == -25300 )
      goto LABEL_10;
    if ( !v15 )
    {
LABEL_9:
      v19 = v15 == 0;
      goto LABEL_10;
    }
    v20 = objc_msgSend(*(&classRef_FIRInstanceIDAuthKeychainItem + 5), *(&selRef_alloc + 23), &stru_10E8 + 1, v15, 0LL);
    LODWORD(v21) = objc_retainAutoreleasedReturnValue(v20);
    LODWORD(v22) = objc_autorelease(v21);
    *v24 = v22;
  }
  v19 = 1;
  if ( v15 != -25300 )
    goto LABEL_9;
LABEL_10:
  objc_release(v13);
  objc_release(v11);
  objc_release(v9);
  return v19;
}
// 10E8: using guessed type __CFString stru_10E8;
// 1270: using guessed type void *classRef_FIRInstanceIDAuthKeychainItem;
// 1640: using guessed type char *selRef_alloc;
// 8850: using guessed type int __fastcall SecItemDelete(_QWORD);
// 8910: using guessed type int __fastcall objc_autorelease(_QWORD);
// 8938: using guessed type int (__fastcall *objc_release)(_QWORD);
// 8940: using guessed type int (__fastcall *objc_retain)(_QWORD);
// 8950: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000CC3) ----------------------------------------------------
// FIRInstanceIDAuthKeychain - (bool)setData:(id) forService:(id) accessibility:(void *) account:(id) accessGroup:(id) error:(id *) 
bool __cdecl -[FIRInstanceIDAuthKeychain setData:forService:accessibility:account:accessGroup:error:](struct FIRInstanceIDAuthKeychain *self, SEL a2, id a3, id a4, void *a5, id a6, id a7, id *a8)
{
  id v8; // r15@1
  id v9; // r14@1
  void *v10; // rax@1
  void *v11; // rax@1
  void *v12; // r14@1
  void *v13; // rax@1
  void *v14; // r15@1
  __int64 v15; // rax@1
  __int64 v16; // rbx@1
  const char *v17; // r12@1
  int v18; // er13@1
  __int64 v19; // rax@4
  void *v20; // rax@4
  void *v21; // rbx@4
  const char *v22; // r12@4
  void *v23; // rdx@4
  __int64 v24; // rcx@4
  void *v25; // rax@9
  __int64 v26; // rax@9
  struct objc_object *v27; // rax@9
  void *v29; // [sp+10h] [bp-50h]@1
  __int64 v30; // [sp+18h] [bp-48h]@1
  void *v31; // [sp+28h] [bp-38h]@1

  v8 = a6;
  v29 = a5;
  v9 = a4;
  LODWORD(v10) = objc_retain(a3);
  v31 = v10;
  LODWORD(v11) = objc_retain(v9);
  v12 = v11;
  LODWORD(v13) = objc_retain(v8);
  v14 = v13;
  LODWORD(v15) = objc_retain(a7);
  v16 = v15;
  v17 = *(&selRef_alloc + 10);
  v18 = -1301;
  v30 = v15;
  if ( objc_msgSend(v12, *(&selRef_alloc + 10)) )
  {
    if ( objc_msgSend(v14, v17) )
    {
      objc_msgSend(self, *(&selRef_alloc + 26), v12, v14, v16, 0LL);
      if ( objc_msgSend(v31, v17) )
      {
        LODWORD(v19) = ((int (__fastcall *)(struct FIRInstanceIDAuthKeychain *, _QWORD, void *, void *, __int64))objc_msgSend)(
                         self,
                         *(&selRef_alloc + 16),
                         v12,
                         v14,
                         v30);
        LODWORD(v20) = objc_retainAutoreleasedReturnValue(v19);
        v21 = v20;
        v22 = *(&selRef_alloc + 12);
        ((void (__fastcall *)(void *, _QWORD, void *, _QWORD))objc_msgSend)(
          v20,
          *(&selRef_alloc + 12),
          v31,
          *kSecValueData);
        v23 = v29;
        v24 = *kSecAttrAccessible;
        if ( !v29 )
          v23 = (void *)*kSecAttrAccessibleAlwaysThisDeviceOnly;
        objc_msgSend(v21, v22, v23);
        v18 = SecItemAdd(v21, 0LL);
        objc_release(v21);
      }
    }
  }
  if ( a8 && v18 )
  {
    v25 = objc_msgSend(*(&classRef_FIRInstanceIDAuthKeychainItem + 5), *(&selRef_alloc + 23), &stru_10E8 + 1, v18, 0LL);
    LODWORD(v26) = objc_retainAutoreleasedReturnValue(v25);
    LODWORD(v27) = objc_autorelease(v26);
    *a8 = v27;
  }
  objc_release(v30);
  objc_release(v14);
  objc_release(v12);
  objc_release(v31);
  return v18 == 0;
}
// 10E8: using guessed type __CFString stru_10E8;
// 1270: using guessed type void *classRef_FIRInstanceIDAuthKeychainItem;
// 1640: using guessed type char *selRef_alloc;
// 8840: using guessed type int __fastcall SecItemAdd(_QWORD, _QWORD);
// 8910: using guessed type int __fastcall objc_autorelease(_QWORD);
// 8938: using guessed type int (__fastcall *objc_release)(_QWORD);
// 8940: using guessed type int (__fastcall *objc_retain)(_QWORD);
// 8950: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000E90) ----------------------------------------------------
// FIRInstanceIDAuthKeychain - (bool)removeAllItemsWithError:(id *) 
bool __cdecl -[FIRInstanceIDAuthKeychain removeAllItemsWithError:](struct FIRInstanceIDAuthKeychain *self, SEL a2, id *a3)
{
  return (unsigned __int64)objc_msgSend(self, *(&selRef_alloc + 26), &stru_10E8, &stru_10E8, 0LL);
}
// 10E8: using guessed type __CFString stru_10E8;
// 1640: using guessed type char *selRef_alloc;

//----- (0000000000000EB5) ----------------------------------------------------
// FIRInstanceIDAuthKeychain + (void)printKeychainItems
void __cdecl +[FIRInstanceIDAuthKeychain printKeychainItems](struct FIRInstanceIDAuthKeychain_meta *self, SEL a2)
{
  ;
}

//----- (0000000000000EBB) ----------------------------------------------------
// FIRInstanceIDAuthKeychain - (id)generic
id __cdecl -[FIRInstanceIDAuthKeychain generic](struct FIRInstanceIDAuthKeychain *self, SEL a2)
{
  return (id)self->_generic;
}

//----- (0000000000000ECC) ----------------------------------------------------
// FIRInstanceIDAuthKeychain - (void)setGeneric:(id) 
void __cdecl -[FIRInstanceIDAuthKeychain setGeneric:](struct FIRInstanceIDAuthKeychain *self, SEL a2, id a3)
{
  objc_storeStrong(&self->_generic, a3);
}
// 8960: using guessed type int __fastcall objc_storeStrong(_QWORD, _QWORD);

//----- (0000000000000EE0) ----------------------------------------------------
// FIRInstanceIDAuthKeychain - (id)identifier
id __cdecl -[FIRInstanceIDAuthKeychain identifier](struct FIRInstanceIDAuthKeychain *self, SEL a2)
{
  id result; // rax@1

  LODWORD(result) = objc_getProperty(self, a2, 16LL, 0LL);
  return result;
}
// 8920: using guessed type int __fastcall objc_getProperty(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000000EF3) ----------------------------------------------------
// FIRInstanceIDAuthKeychain - (void)setIdentifier:(id) 
void __cdecl -[FIRInstanceIDAuthKeychain setIdentifier:](struct FIRInstanceIDAuthKeychain *self, SEL a2, id a3)
{
  objc_setProperty_nonatomic_copy(self, a2, a3, 16LL);
}
// 8958: using guessed type int __fastcall objc_setProperty_nonatomic_copy(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000000F04) ----------------------------------------------------
// FIRInstanceIDAuthKeychain - (void).cxx_destruct
void __cdecl -[FIRInstanceIDAuthKeychain .cxx_destruct](struct FIRInstanceIDAuthKeychain *self, SEL a2)
{
  objc_storeStrong(&self->_identifier, 0LL);
  objc_storeStrong(&self->_generic, 0LL);
}
// 8960: using guessed type int __fastcall objc_storeStrong(_QWORD, _QWORD);

// ALL OK, 28 function(s) have been successfully decompiled
