/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2015 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

// void *__usercall -[FIRInstanceIDStore initWithDelegate:]@<rax>(__int64 a1@<rax>, __int64 a2@<rdx>, void *a3@<rdi>);
id __cdecl -[FIRInstanceIDStore initWithCheckinStore:tokenStore:delegate:](struct FIRInstanceIDStore *self, SEL, id, id, id);
bool __cdecl +[FIRInstanceIDStore hasApplicationSupportSubDirectory:](struct FIRInstanceIDStore *self, SEL, id);
id __cdecl +[FIRInstanceIDStore pathForApplicationSupportSubDirectory:](struct FIRInstanceIDStore *self, SEL, id);
bool __cdecl +[FIRInstanceIDStore createApplicationSupportSubDirectory:](struct FIRInstanceIDStore *self, SEL, id);
bool __cdecl +[FIRInstanceIDStore removeApplicationSupportSubDirectory:error:](struct FIRInstanceIDStore *self, SEL, id, id *);
void __cdecl -[FIRInstanceIDStore resetCredentialsIfNeeded](struct FIRInstanceIDStore *self, SEL);
void __cdecl -[FIRInstanceIDStore saveLibraryVersion](struct FIRInstanceIDStore *self, SEL);
id __cdecl -[FIRInstanceIDStore currentSavedLibraryVersion](struct FIRInstanceIDStore *self, SEL);
bool __cdecl -[FIRInstanceIDStore hasSavedLibraryVersion](struct FIRInstanceIDStore *self, SEL);
id __cdecl -[FIRInstanceIDStore tokenInfoWithAuthorizedEntity:scope:](struct FIRInstanceIDStore *self, SEL, id, id);
id __cdecl -[FIRInstanceIDStore cachedTokenInfos](struct FIRInstanceIDStore *self, SEL);
bool __cdecl -[FIRInstanceIDStore saveTokenInfo:](struct FIRInstanceIDStore *self, SEL, id);
void __cdecl -[FIRInstanceIDStore removeCachedTokenWithAuthorizedEntity:scope:](struct FIRInstanceIDStore *self, SEL, id, id);
bool __cdecl -[FIRInstanceIDStore removeAllCachedTokensWithError:](struct FIRInstanceIDStore *self, SEL, id *);
bool __cdecl -[FIRInstanceIDStore saveCheckinPreferences:error:](struct FIRInstanceIDStore *self, SEL, id, id *);
id __cdecl -[FIRInstanceIDStore cachedCheckinPreferences](struct FIRInstanceIDStore *self, SEL);
bool __cdecl -[FIRInstanceIDStore removeCheckinPreferences:](struct FIRInstanceIDStore *self, SEL, id *);
id __cdecl -[FIRInstanceIDStore delegate](struct FIRInstanceIDStore *self, SEL);
id __cdecl -[FIRInstanceIDStore checkinStore](struct FIRInstanceIDStore *self, SEL);
void __cdecl -[FIRInstanceIDStore setCheckinStore:](struct FIRInstanceIDStore *self, SEL, id);
id __cdecl -[FIRInstanceIDStore tokenStore](struct FIRInstanceIDStore *self, SEL);
void __cdecl -[FIRInstanceIDStore setTokenStore:](struct FIRInstanceIDStore *self, SEL, id);
void __cdecl -[FIRInstanceIDStore .cxx_destruct](struct FIRInstanceIDStore *self, SEL);
// int __fastcall FIRInstanceIDCurrentLibraryVersion(_QWORD, _QWORD); weak
// int __fastcall FIRInstanceIDSharedLogger(_QWORD); weak
// int __fastcall NSSearchPathForDirectoriesInDomains(_QWORD, _QWORD, _QWORD); weak
// int __fastcall objc_autoreleaseReturnValue(_QWORD); weak
// int __fastcall objc_destroyWeak(_QWORD, _QWORD); weak
// int __fastcall objc_loadWeakRetained(_QWORD, _QWORD); weak
// void *objc_msgSend(void *, const char *, ...); idb
// void *objc_msgSendSuper2(void *, const char *, ...); idb
// int __fastcall objc_release(_QWORD); weak
// int __fastcall objc_retainAutoreleasedReturnValue(_QWORD); weak
// int __fastcall objc_storeStrong(_QWORD, _QWORD); weak
// int __fastcall objc_storeWeak(_QWORD, _QWORD); weak

//-------------------------------------------------------------------------
// Data declarations

char aGCheckin[10] = "g-checkin"; // weak
__CFString cfstr_GCheckin = { &__CFConstantStringClassReference, 1992LL, "g-checkin", 9LL }; // weak
void *classRef_FIRInstanceIDCheckinStore = &OBJC_CLASS___FIRInstanceIDCheckinStore; // weak
char *selRef_alloc = "alloc"; // weak
void *classRef_FIRInstanceIDStore = &OBJC_CLASS___FIRInstanceIDStore; // weak
// extern _UNKNOWN __stack_chk_guard; weak
// extern _UNKNOWN kFIRInstanceIDApplicationSupportSubDirectory; weak
// extern int (__fastcall *objc_retain)(_QWORD); weak


//----- (0000000000000000) ----------------------------------------------------
void *__usercall -[FIRInstanceIDStore initWithDelegate:]@<rax>(__int64 a1@<rax>, __int64 a2@<rdx>, void *a3@<rdi>)
{
  __int64 v3; // ST00_8@1
  __int64 v4; // rax@1
  __int64 v5; // r15@1
  void *v6; // rax@1
  void *v7; // r12@1
  void *v8; // rax@1
  __int64 v9; // rax@1
  __int64 v10; // rbx@1
  void *v11; // r14@1

  v3 = a1;
  LODWORD(v4) = objc_retain(a2);
  v5 = v4;
  v6 = objc_msgSend(classRef_FIRInstanceIDCheckinStore, selRef_alloc, v3);
  v7 = objc_msgSend(v6, *(&selRef_alloc + 1), &cfstr_GCheckin, *kFIRInstanceIDApplicationSupportSubDirectory);
  v8 = objc_msgSend(*(&classRef_FIRInstanceIDCheckinStore + 1), *(&selRef_alloc + 2));
  LODWORD(v9) = objc_retainAutoreleasedReturnValue(v8);
  v10 = v9;
  v11 = objc_msgSend(a3, *(&selRef_alloc + 3), v7, v9, v5);
  objc_release(v5);
  objc_release(v10);
  objc_release(v7);
  return v11;
}
// 11E8: using guessed type __CFString cfstr_GCheckin;
// 1328: using guessed type void *classRef_FIRInstanceIDCheckinStore;
// 1848: using guessed type char *selRef_alloc;
// 8178: using guessed type int __fastcall objc_release(_QWORD);
// 8180: using guessed type int (__fastcall *objc_retain)(_QWORD);
// 8188: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (00000000000000BC) ----------------------------------------------------
// FIRInstanceIDStore - (id)initWithCheckinStore:(id) tokenStore:(id) delegate:(id) 
id __cdecl -[FIRInstanceIDStore initWithCheckinStore:tokenStore:delegate:](struct FIRInstanceIDStore *self, SEL a2, id a3, id a4, id a5)
{
  id v5; // r12@1
  id v6; // r13@1
  id v7; // r14@1
  __int64 v8; // rax@1
  __int64 v9; // rax@1
  __int64 v10; // rax@1
  __int64 v11; // r12@1
  char *v12; // rax@1
  char *v13; // rbx@1
  struct FIRInstanceIDStore *v15; // [sp+8h] [bp-48h]@1
  void *v16; // [sp+10h] [bp-40h]@1
  __int64 v17; // [sp+18h] [bp-38h]@1
  __int64 v18; // [sp+20h] [bp-30h]@1

  v5 = a5;
  v6 = a4;
  v7 = a3;
  LODWORD(v8) = objc_retain(a3);
  v17 = v8;
  LODWORD(v9) = objc_retain(v6);
  v18 = v9;
  LODWORD(v10) = objc_retain(v5);
  v11 = v10;
  v15 = self;
  v16 = classRef_FIRInstanceIDStore;
  v12 = (char *)objc_msgSendSuper2(&v15, *(&selRef_alloc + 4));
  v13 = v12;
  if ( v12 )
  {
    objc_storeStrong(v12 + 16, v7);
    objc_storeStrong(v13 + 24, v6);
    objc_storeWeak(v13 + 8, v11);
    objc_msgSend(v13, *(&selRef_alloc + 5));
    objc_msgSend(v13, *(&selRef_alloc + 6));
  }
  objc_release(v11);
  objc_release(v18);
  objc_release(v17);
  return (id)v13;
}
// 1848: using guessed type char *selRef_alloc;
// 19D0: using guessed type void *classRef_FIRInstanceIDStore;
// 8178: using guessed type int __fastcall objc_release(_QWORD);
// 8180: using guessed type int (__fastcall *objc_retain)(_QWORD);
// 8190: using guessed type int __fastcall objc_storeStrong(_QWORD, _QWORD);
// 8198: using guessed type int __fastcall objc_storeWeak(_QWORD, _QWORD);

//----- (00000000000001A4) ----------------------------------------------------
// FIRInstanceIDStore + (bool)hasApplicationSupportSubDirectory:(id) 
bool __cdecl +[FIRInstanceIDStore hasApplicationSupportSubDirectory:](struct FIRInstanceIDStore *self, SEL a2, id a3)
{
  __int64 v3; // rax@0
  void *v4; // rax@1
  __int64 v5; // rax@1
  __int64 v6; // r14@1
  void *v7; // rax@1
  void *v8; // rax@1
  void *v9; // r12@1
  int v10; // ebx@1
  __int64 v12; // [sp-6h] [bp-30h]@1

  v12 = v3;
  v4 = objc_msgSend(self, *(&selRef_alloc + 7), a3, v3);
  LODWORD(v5) = objc_retainAutoreleasedReturnValue(v4);
  v6 = v5;
  v7 = objc_msgSend(*(&classRef_FIRInstanceIDCheckinStore + 2), *(&selRef_alloc + 8), v12);
  LODWORD(v8) = objc_retainAutoreleasedReturnValue(v7);
  v9 = v8;
  v10 = (unsigned __int64)objc_msgSend(v8, *(&selRef_alloc + 9), v6, (char *)&v12 + 7, v12);
  objc_release(v9);
  LOBYTE(v10) = (BYTE7(v12) != 0) & v10;
  objc_release(v6);
  return v10;
}
// 1328: using guessed type void *classRef_FIRInstanceIDCheckinStore;
// 1848: using guessed type char *selRef_alloc;
// 8178: using guessed type int __fastcall objc_release(_QWORD);
// 8188: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (000000000000022D) ----------------------------------------------------
// FIRInstanceIDStore + (id)pathForApplicationSupportSubDirectory:(id) 
id __cdecl +[FIRInstanceIDStore pathForApplicationSupportSubDirectory:](struct FIRInstanceIDStore *self, SEL a2, id a3)
{
  __int64 v3; // rax@1
  __int64 v4; // r15@1
  __int64 v5; // rax@1
  void *v6; // rax@1
  void *v7; // ST08_8@1
  void *v8; // rax@1
  __int64 v9; // rax@1
  __int64 v10; // r12@1
  void *v11; // rax@1
  __int64 v12; // rax@1
  __int64 v13; // rbx@1
  void *v14; // r13@1
  __int64 v15; // rax@1
  __int64 v16; // r15@1
  id result; // rax@1
  __int64 v18; // [sp+10h] [bp-40h]@1
  __int64 v19; // [sp+18h] [bp-38h]@1
  __int64 v20; // [sp+20h] [bp-30h]@1

  v20 = *__stack_chk_guard;
  LODWORD(v3) = objc_retain(a3);
  v4 = v3;
  LODWORD(v5) = NSSearchPathForDirectoriesInDomains(14LL, 1LL, 1LL);
  LODWORD(v6) = objc_retainAutoreleasedReturnValue(v5);
  v7 = v6;
  v8 = objc_msgSend(v6, *(&selRef_alloc + 10));
  LODWORD(v9) = objc_retainAutoreleasedReturnValue(v8);
  v10 = v9;
  v18 = v9;
  v19 = v4;
  v11 = objc_msgSend(*(&classRef_FIRInstanceIDCheckinStore + 3), *(&selRef_alloc + 11), &v18);
  LODWORD(v12) = objc_retainAutoreleasedReturnValue(v11);
  v13 = v12;
  v14 = objc_msgSend(*(&classRef_FIRInstanceIDCheckinStore + 4), *(&selRef_alloc + 12), v12);
  objc_release(v4);
  LODWORD(v15) = objc_retainAutoreleasedReturnValue(v14);
  v16 = v15;
  objc_release(v13);
  objc_release(v10);
  objc_release(v7);
  result = (id)*__stack_chk_guard;
  if ( *__stack_chk_guard == v20 )
    LODWORD(result) = objc_autoreleaseReturnValue(v16);
  return result;
}
// 1328: using guessed type void *classRef_FIRInstanceIDCheckinStore;
// 1848: using guessed type char *selRef_alloc;
// 80E0: using guessed type int __fastcall NSSearchPathForDirectoriesInDomains(_QWORD, _QWORD, _QWORD);
// 8150: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 8178: using guessed type int __fastcall objc_release(_QWORD);
// 8180: using guessed type int (__fastcall *objc_retain)(_QWORD);
// 8188: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000330) ----------------------------------------------------
// FIRInstanceIDStore + (bool)createApplicationSupportSubDirectory:(id) 
bool __cdecl +[FIRInstanceIDStore createApplicationSupportSubDirectory:](struct FIRInstanceIDStore *self, SEL a2, id a3)
{
  void *v3; // rax@1
  __int64 v4; // rax@1
  __int64 v5; // r14@1
  const char *v6; // r15@1
  void *v7; // rax@1
  void *v8; // rax@1
  void *v9; // rbx@1
  int v10; // er12@1
  void *v11; // rdi@1
  bool v12; // bl@2
  __int64 v13; // rax@3
  void *v14; // rax@3
  void *v15; // r15@3
  void *v16; // rax@4
  void *v17; // rax@4
  void *v18; // rbx@4
  __int64 v19; // rax@4
  __int64 v20; // r15@4
  __int64 v21; // rax@5
  void *v22; // rax@5
  void *v23; // r12@5
  __int64 v25; // [sp+8h] [bp-38h]@4
  char v26; // [sp+17h] [bp-29h]@1

  v3 = objc_msgSend(self, *(&selRef_alloc + 7), a3);
  LODWORD(v4) = objc_retainAutoreleasedReturnValue(v3);
  v5 = v4;
  v6 = *(&selRef_alloc + 8);
  v7 = objc_msgSend(*(&classRef_FIRInstanceIDCheckinStore + 2), *(&selRef_alloc + 8));
  LODWORD(v8) = objc_retainAutoreleasedReturnValue(v7);
  v9 = v8;
  v10 = (unsigned __int64)objc_msgSend(v8, *(&selRef_alloc + 9), v5, &v26);
  v11 = v9;
  objc_release(v9);
  if ( (_BYTE)v10 )
  {
    v12 = 1;
    if ( !v26 )
    {
      LODWORD(v13) = FIRInstanceIDSharedLogger(v11);
      LODWORD(v14) = objc_retainAutoreleasedReturnValue(v13);
      v15 = v14;
      v12 = 0;
      objc_msgSend(v14, *(&selRef_alloc + 14), &aGCheckin[32], 13001LL, &cfstr_GCheckin + 3, v5);
      objc_release(v15);
    }
  }
  else
  {
    v16 = objc_msgSend(*(&classRef_FIRInstanceIDCheckinStore + 2), v6);
    LODWORD(v17) = objc_retainAutoreleasedReturnValue(v16);
    v18 = v17;
    v25 = 0LL;
    objc_msgSend(v17, *(&selRef_alloc + 13), v5, 1LL, 0LL, &v25);
    LODWORD(v19) = objc_retain(v25);
    v20 = v19;
    objc_release(v18);
    if ( v20 )
    {
      LODWORD(v21) = FIRInstanceIDSharedLogger(v18);
      LODWORD(v22) = objc_retainAutoreleasedReturnValue(v21);
      v23 = v22;
      v12 = 0;
      objc_msgSend(v22, *(&selRef_alloc + 14), &aGCheckin[32], 13000LL, &cfstr_GCheckin + 2, v5, v20);
      objc_release(v23);
      objc_release(v20);
    }
    else
    {
      objc_release(0LL);
      v12 = 1;
    }
  }
  objc_release(v5);
  return v12;
}
// 11E8: using guessed type __CFString cfstr_GCheckin;
// 1328: using guessed type void *classRef_FIRInstanceIDCheckinStore;
// 1848: using guessed type char *selRef_alloc;
// 80D8: using guessed type int __fastcall FIRInstanceIDSharedLogger(_QWORD);
// 8178: using guessed type int __fastcall objc_release(_QWORD);
// 8180: using guessed type int (__fastcall *objc_retain)(_QWORD);
// 8188: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (00000000000004C5) ----------------------------------------------------
// FIRInstanceIDStore + (bool)removeApplicationSupportSubDirectory:(id) error:(id *) 
bool __cdecl +[FIRInstanceIDStore removeApplicationSupportSubDirectory:error:](struct FIRInstanceIDStore *self, SEL a2, id a3, id *a4)
{
  __int64 v4; // rax@1
  __int64 v5; // r13@1
  int v6; // er15@1
  void *v7; // rax@2
  __int64 v8; // rax@2
  __int64 v9; // r12@2
  void *v10; // rax@2
  void *v11; // rax@2
  void *v12; // rbx@2
  char v13; // r14@2
  void *v14; // rax@3
  void *v15; // rax@3
  void *v16; // rbx@3
  char v18; // [sp+17h] [bp-29h]@2

  LODWORD(v4) = objc_retain(a3);
  v5 = v4;
  LOBYTE(v6) = 1;
  if ( (unsigned __int8)objc_msgSend(self, *(&selRef_alloc + 15), v4) )
  {
    v7 = objc_msgSend(self, *(&selRef_alloc + 7), v5);
    LODWORD(v8) = objc_retainAutoreleasedReturnValue(v7);
    v9 = v8;
    v10 = objc_msgSend(*(&classRef_FIRInstanceIDCheckinStore + 2), *(&selRef_alloc + 8));
    LODWORD(v11) = objc_retainAutoreleasedReturnValue(v10);
    v12 = v11;
    v13 = (unsigned __int64)objc_msgSend(v11, *(&selRef_alloc + 9), v9, &v18);
    objc_release(v12);
    if ( v13 )
    {
      v14 = objc_msgSend(*(&classRef_FIRInstanceIDCheckinStore + 2), *(&selRef_alloc + 8));
      LODWORD(v15) = objc_retainAutoreleasedReturnValue(v14);
      v16 = v15;
      v6 = (unsigned __int64)objc_msgSend(v15, *(&selRef_alloc + 16), v9);
      objc_release(v16);
      objc_release(v9);
    }
    else
    {
      objc_release(v9);
    }
  }
  objc_release(v5);
  return v6;
}
// 1328: using guessed type void *classRef_FIRInstanceIDCheckinStore;
// 1848: using guessed type char *selRef_alloc;
// 8178: using guessed type int __fastcall objc_release(_QWORD);
// 8180: using guessed type int (__fastcall *objc_retain)(_QWORD);
// 8188: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (00000000000005E3) ----------------------------------------------------
// FIRInstanceIDStore - (void)resetCredentialsIfNeeded
void __cdecl -[FIRInstanceIDStore resetCredentialsIfNeeded](struct FIRInstanceIDStore *self, SEL a2)
{
  const char *v2; // r15@2
  void *(*v3)(void *, const char *, ...); // r12@2
  void *v4; // rax@2
  void *v5; // rax@2
  void *v6; // rbx@2
  int v7; // er14@2
  void *v8; // rbx@3
  void *v9; // rax@4
  void *v10; // rax@4
  void *v11; // rbx@4
  void *v12; // rax@4
  __int64 v13; // rax@4
  void *v14; // rax@4
  void *v15; // rax@4
  void *v16; // rbx@4
  int v17; // er14@4
  __int64 v18; // rax@4
  __int64 v19; // r15@4
  __int64 v20; // rax@4
  void *v21; // rax@4
  void *v22; // r12@4
  void *v23; // rax@8
  void *v24; // rax@8
  void *v25; // r14@8
  const char *v26; // r15@8
  void *v27; // rax@8
  void *v28; // rax@9
  void *v29; // rax@9
  void *v30; // rbx@9
  bool v31; // r15@9
  __int64 v32; // rax@11
  void *v33; // rax@11
  void *v34; // rbx@11
  const char *v35; // rsi@11
  char *v36; // rdx@11
  void *v37; // rax@12
  void *v38; // rax@12
  void *v39; // r15@12
  __int64 v40; // rbx@12
  __int64 v41; // [sp+8h] [bp-38h]@4
  void *v42; // [sp+10h] [bp-30h]@4

  if ( !(unsigned __int8)objc_msgSend(self, *(&selRef_alloc + 17)) )
  {
    v2 = *(&selRef_alloc + 18);
    v3 = objc_msgSend;
    v4 = objc_msgSend(self, *(&selRef_alloc + 18));
    LODWORD(v5) = objc_retainAutoreleasedReturnValue(v4);
    v6 = v5;
    v7 = (unsigned __int64)objc_msgSend(v5, *(&selRef_alloc + 19));
    objc_release(v6);
    if ( (_BYTE)v7 )
    {
      v8 = 0LL;
    }
    else
    {
      v9 = objc_msgSend(self, v2);
      LODWORD(v10) = objc_retainAutoreleasedReturnValue(v9);
      v11 = v10;
      v12 = objc_msgSend(v10, *(&selRef_alloc + 20));
      LODWORD(v13) = objc_retainAutoreleasedReturnValue(v12);
      v42 = (void *)v13;
      objc_release(v11);
      v14 = objc_msgSend(self, v2);
      LODWORD(v15) = objc_retainAutoreleasedReturnValue(v14);
      v16 = v15;
      v41 = 0LL;
      v17 = (unsigned __int64)objc_msgSend(v15, *(&selRef_alloc + 21), &v41);
      LODWORD(v18) = objc_retain(v41);
      v19 = v18;
      objc_release(v16);
      LODWORD(v20) = FIRInstanceIDSharedLogger(v16);
      LODWORD(v21) = objc_retainAutoreleasedReturnValue(v20);
      v22 = v21;
      if ( (_BYTE)v17 )
        objc_msgSend(v21, *(&selRef_alloc + 22), &aGCheckin[168], 13002LL, &cfstr_GCheckin + 4);
      else
        objc_msgSend(v21, *(&selRef_alloc + 14), &aGCheckin[168], 13003LL, &cfstr_GCheckin + 5, v19);
      objc_release(v19);
      objc_release(v22);
      v3 = objc_msgSend;
      v8 = v42;
    }
    v23 = v3(v8, *(&selRef_alloc + 23));
    LODWORD(v24) = objc_retainAutoreleasedReturnValue(v23);
    v25 = v24;
    v26 = *(&selRef_alloc + 24);
    v27 = v3(v24, *(&selRef_alloc + 24));
    v42 = v8;
    if ( v27 )
    {
      v28 = v3(v8, *(&selRef_alloc + 25));
      LODWORD(v29) = objc_retainAutoreleasedReturnValue(v28);
      v30 = v29;
      v31 = v3(v29, v26) != 0LL;
      objc_release(v30);
    }
    else
    {
      v31 = 0;
    }
    objc_release(v25);
    LODWORD(v32) = FIRInstanceIDSharedLogger(v25);
    LODWORD(v33) = objc_retainAutoreleasedReturnValue(v32);
    v34 = v33;
    v35 = *(&selRef_alloc + 22);
    v36 = &aGCheckin[168];
    if ( v31 )
    {
      v3(v33, v35, v36, 13006LL, &cfstr_GCheckin + 6);
      objc_release(v34);
      v37 = v3(self, *(&selRef_alloc + 26));
      LODWORD(v38) = objc_retainAutoreleasedReturnValue(v37);
      v39 = v38;
      v40 = (__int64)v42;
      v3(v38, *(&selRef_alloc + 27), self, v42);
      objc_release(v39);
    }
    else
    {
      objc_msgSend(v33, v35, v36, 13009LL, &cfstr_GCheckin + 7);
      objc_release(v34);
      v40 = (__int64)v42;
    }
    objc_release(v40);
  }
}
// 11E8: using guessed type __CFString cfstr_GCheckin;
// 1848: using guessed type char *selRef_alloc;
// 80D8: using guessed type int __fastcall FIRInstanceIDSharedLogger(_QWORD);
// 8178: using guessed type int __fastcall objc_release(_QWORD);
// 8180: using guessed type int (__fastcall *objc_retain)(_QWORD);
// 8188: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000873) ----------------------------------------------------
// FIRInstanceIDStore - (void)saveLibraryVersion
void __cdecl -[FIRInstanceIDStore saveLibraryVersion](struct FIRInstanceIDStore *self, SEL a2)
{
  __int64 v2; // rax@1
  __int64 v3; // rax@1
  __int64 v4; // r14@1
  void *v5; // rax@1
  void *v6; // rax@1
  void *v7; // rbx@1
  __int64 v8; // rax@1
  void *v9; // rax@1
  void *v10; // rbx@1

  LODWORD(v2) = FIRInstanceIDCurrentLibraryVersion(self, a2);
  LODWORD(v3) = objc_retainAutoreleasedReturnValue(v2);
  v4 = v3;
  v5 = objc_msgSend(*(&classRef_FIRInstanceIDCheckinStore + 5), *(&selRef_alloc + 28));
  LODWORD(v6) = objc_retainAutoreleasedReturnValue(v5);
  v7 = v6;
  objc_msgSend(v6, *(&selRef_alloc + 29), v4, &cfstr_GCheckin + 1);
  objc_release(v7);
  LODWORD(v8) = FIRInstanceIDSharedLogger(v7);
  LODWORD(v9) = objc_retainAutoreleasedReturnValue(v8);
  v10 = v9;
  objc_msgSend(v9, *(&selRef_alloc + 30), &aGCheckin[475], 13010LL, &cfstr_GCheckin + 8, v4);
  objc_release(v10);
  objc_release(v4);
}
// 11E8: using guessed type __CFString cfstr_GCheckin;
// 1328: using guessed type void *classRef_FIRInstanceIDCheckinStore;
// 1848: using guessed type char *selRef_alloc;
// 80D0: using guessed type int __fastcall FIRInstanceIDCurrentLibraryVersion(_QWORD, _QWORD);
// 80D8: using guessed type int __fastcall FIRInstanceIDSharedLogger(_QWORD);
// 8178: using guessed type int __fastcall objc_release(_QWORD);
// 8188: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000920) ----------------------------------------------------
// FIRInstanceIDStore - (id)currentSavedLibraryVersion
id __cdecl -[FIRInstanceIDStore currentSavedLibraryVersion](struct FIRInstanceIDStore *self, SEL a2)
{
  void *v2; // rax@1
  void *v3; // rax@1
  void *v4; // rbx@1
  void *v5; // rax@1
  __int64 v6; // rax@1
  __int64 v7; // r14@1
  id result; // rax@1

  v2 = objc_msgSend(*(&classRef_FIRInstanceIDCheckinStore + 5), *(&selRef_alloc + 28));
  LODWORD(v3) = objc_retainAutoreleasedReturnValue(v2);
  v4 = v3;
  v5 = objc_msgSend(v3, *(&selRef_alloc + 31), &cfstr_GCheckin + 1);
  LODWORD(v6) = objc_retainAutoreleasedReturnValue(v5);
  v7 = v6;
  objc_release(v4);
  LODWORD(result) = objc_autoreleaseReturnValue(v7);
  return result;
}
// 11E8: using guessed type __CFString cfstr_GCheckin;
// 1328: using guessed type void *classRef_FIRInstanceIDCheckinStore;
// 1848: using guessed type char *selRef_alloc;
// 8150: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 8178: using guessed type int __fastcall objc_release(_QWORD);
// 8188: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (000000000000097E) ----------------------------------------------------
// FIRInstanceIDStore - (bool)hasSavedLibraryVersion
bool __cdecl -[FIRInstanceIDStore hasSavedLibraryVersion](struct FIRInstanceIDStore *self, SEL a2)
{
  __int64 v2; // rax@0
  void *v3; // rax@1
  void *v4; // rax@1
  void *v5; // rbx@1
  void *v6; // rax@1
  __int64 v7; // rax@1
  bool v8; // r14@1

  v3 = objc_msgSend(*(&classRef_FIRInstanceIDCheckinStore + 5), *(&selRef_alloc + 28), v2);
  LODWORD(v4) = objc_retainAutoreleasedReturnValue(v3);
  v5 = v4;
  v6 = objc_msgSend(v4, *(&selRef_alloc + 31), &cfstr_GCheckin + 1);
  LODWORD(v7) = objc_retainAutoreleasedReturnValue(v6);
  v8 = v7 != 0;
  objc_release(v7);
  objc_release(v5);
  return v8;
}
// 11E8: using guessed type __CFString cfstr_GCheckin;
// 1328: using guessed type void *classRef_FIRInstanceIDCheckinStore;
// 1848: using guessed type char *selRef_alloc;
// 8178: using guessed type int __fastcall objc_release(_QWORD);
// 8188: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (00000000000009EF) ----------------------------------------------------
// FIRInstanceIDStore - (id)tokenInfoWithAuthorizedEntity:(id) scope:(id) 
id __cdecl -[FIRInstanceIDStore tokenInfoWithAuthorizedEntity:scope:](struct FIRInstanceIDStore *self, SEL a2, id a3, id a4)
{
  __int64 v4; // rax@0
  __int64 v5; // ST00_8@1
  id v6; // rbx@1
  void *v7; // rax@1
  void *v8; // r12@1
  void *v9; // rax@1
  void *v10; // r14@1
  const char *v11; // rbx@1
  void *v12; // rax@3
  void *v13; // rax@3
  void *v14; // r15@3
  void *v15; // rax@3
  __int64 v16; // rax@3
  __int64 v17; // r13@3
  id result; // rax@5

  v5 = v4;
  v6 = a4;
  LODWORD(v7) = objc_retain(a3);
  v8 = v7;
  LODWORD(v9) = objc_retain(v6);
  v10 = v9;
  v11 = *(&selRef_alloc + 24);
  if ( objc_msgSend(v8, *(&selRef_alloc + 24), v5) && objc_msgSend(v10, v11) )
  {
    v12 = objc_msgSend(self, *(&selRef_alloc + 32));
    LODWORD(v13) = objc_retainAutoreleasedReturnValue(v12);
    v14 = v13;
    v15 = objc_msgSend(v13, *(&selRef_alloc + 33), v8, v10);
    LODWORD(v16) = objc_retainAutoreleasedReturnValue(v15);
    v17 = v16;
    objc_release(v14);
  }
  else
  {
    v17 = 0LL;
  }
  objc_release(v10);
  objc_release(v8);
  LODWORD(result) = objc_autoreleaseReturnValue(v17);
  return result;
}
// 1848: using guessed type char *selRef_alloc;
// 8150: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 8178: using guessed type int __fastcall objc_release(_QWORD);
// 8180: using guessed type int (__fastcall *objc_retain)(_QWORD);
// 8188: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000AB5) ----------------------------------------------------
// FIRInstanceIDStore - (id)cachedTokenInfos
id __cdecl -[FIRInstanceIDStore cachedTokenInfos](struct FIRInstanceIDStore *self, SEL a2)
{
  void *v2; // rax@1
  void *v3; // rax@1
  void *v4; // rbx@1
  void *v5; // rax@1
  __int64 v6; // rax@1
  __int64 v7; // r14@1
  id result; // rax@1

  v2 = objc_msgSend(self, *(&selRef_alloc + 32));
  LODWORD(v3) = objc_retainAutoreleasedReturnValue(v2);
  v4 = v3;
  v5 = objc_msgSend(v3, *(&selRef_alloc + 34));
  LODWORD(v6) = objc_retainAutoreleasedReturnValue(v5);
  v7 = v6;
  objc_release(v4);
  LODWORD(result) = objc_autoreleaseReturnValue(v7);
  return result;
}
// 1848: using guessed type char *selRef_alloc;
// 8150: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 8178: using guessed type int __fastcall objc_release(_QWORD);
// 8188: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000B05) ----------------------------------------------------
// FIRInstanceIDStore - (bool)saveTokenInfo:(id) 
bool __cdecl -[FIRInstanceIDStore saveTokenInfo:](struct FIRInstanceIDStore *self, SEL a2, id a3)
{
  __int64 v3; // rax@0
  __int64 v4; // ST00_8@1
  const char *v5; // r14@1
  __int64 v6; // rax@1
  __int64 v7; // r12@1
  void *v8; // rax@1
  void *v9; // rax@1
  void *v10; // rbx@1

  v4 = v3;
  v5 = *(&selRef_alloc + 32);
  LODWORD(v6) = objc_retain(a3);
  v7 = v6;
  v8 = objc_msgSend(self, v5, v4);
  LODWORD(v9) = objc_retainAutoreleasedReturnValue(v8);
  v10 = v9;
  LODWORD(v5) = (unsigned __int64)objc_msgSend(v9, *(&selRef_alloc + 35), v7);
  objc_release(v7);
  objc_release(v10);
  return (char)v5;
}
// 1848: using guessed type char *selRef_alloc;
// 8178: using guessed type int __fastcall objc_release(_QWORD);
// 8180: using guessed type int (__fastcall *objc_retain)(_QWORD);
// 8188: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000B7C) ----------------------------------------------------
// FIRInstanceIDStore - (void)removeCachedTokenWithAuthorizedEntity:(id) scope:(id) 
void __cdecl -[FIRInstanceIDStore removeCachedTokenWithAuthorizedEntity:scope:](struct FIRInstanceIDStore *self, SEL a2, id a3, id a4)
{
  id v4; // rbx@1
  struct FIRInstanceIDStore *v5; // r15@1
  void *v6; // rax@1
  void *v7; // r12@1
  void *v8; // rax@1
  void *v9; // r14@1
  const char *v10; // rbx@1
  void *v11; // rdi@1
  void *v12; // rax@3
  void *v13; // rax@3
  void *v14; // rbx@3
  __int64 v15; // rax@4
  void *v16; // rax@4
  __int64 v17; // [sp+10h] [bp-30h]@3

  v4 = a4;
  v5 = self;
  LODWORD(v6) = objc_retain(a3);
  v7 = v6;
  LODWORD(v8) = objc_retain(v4);
  v9 = v8;
  v10 = *(&selRef_alloc + 24);
  v11 = v7;
  if ( objc_msgSend(v7, *(&selRef_alloc + 24)) && (v11 = v9, objc_msgSend(v9, v10)) )
  {
    v12 = objc_msgSend(v5, *(&selRef_alloc + 32));
    LODWORD(v13) = objc_retainAutoreleasedReturnValue(v12);
    v14 = v13;
    v17 = 0LL;
    objc_msgSend(v13, *(&selRef_alloc + 36), v7, v9);
  }
  else
  {
    LODWORD(v15) = FIRInstanceIDSharedLogger(v11);
    LODWORD(v16) = objc_retainAutoreleasedReturnValue(v15);
    v14 = v16;
    objc_msgSend(v16, *(&selRef_alloc + 14), &aGCheckin[546], 13012LL, &cfstr_GCheckin + 9, v7, v9);
  }
  objc_release(v14);
  objc_release(v9);
  objc_release(v7);
}
// 11E8: using guessed type __CFString cfstr_GCheckin;
// 1848: using guessed type char *selRef_alloc;
// 80D8: using guessed type int __fastcall FIRInstanceIDSharedLogger(_QWORD);
// 8178: using guessed type int __fastcall objc_release(_QWORD);
// 8180: using guessed type int (__fastcall *objc_retain)(_QWORD);
// 8188: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000C79) ----------------------------------------------------
// FIRInstanceIDStore - (bool)removeAllCachedTokensWithError:(id *) 
bool __cdecl -[FIRInstanceIDStore removeAllCachedTokensWithError:](struct FIRInstanceIDStore *self, SEL a2, id *a3)
{
  __int64 v3; // rax@0
  id *v4; // r14@1
  void *v5; // rax@1
  void *v6; // rax@1
  void *v7; // rbx@1

  v4 = a3;
  v5 = objc_msgSend(self, *(&selRef_alloc + 32), v3);
  LODWORD(v6) = objc_retainAutoreleasedReturnValue(v5);
  v7 = v6;
  LODWORD(v4) = (unsigned __int64)objc_msgSend(v6, *(&selRef_alloc + 37), v4);
  objc_release(v7);
  return (char)v4;
}
// 1848: using guessed type char *selRef_alloc;
// 8178: using guessed type int __fastcall objc_release(_QWORD);
// 8188: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000CCC) ----------------------------------------------------
// FIRInstanceIDStore - (bool)saveCheckinPreferences:(id) error:(id *) 
bool __cdecl -[FIRInstanceIDStore saveCheckinPreferences:error:](struct FIRInstanceIDStore *self, SEL a2, id a3, id *a4)
{
  __int64 v4; // rax@0
  __int64 v5; // ST00_8@1
  id *v6; // r14@1
  const char *v7; // rbx@1
  __int64 v8; // rax@1
  __int64 v9; // r13@1
  void *v10; // rax@1
  void *v11; // rax@1
  void *v12; // rbx@1

  v5 = v4;
  v6 = a4;
  v7 = *(&selRef_alloc + 18);
  LODWORD(v8) = objc_retain(a3);
  v9 = v8;
  v10 = objc_msgSend(self, v7, v5);
  LODWORD(v11) = objc_retainAutoreleasedReturnValue(v10);
  v12 = v11;
  LODWORD(v6) = (unsigned __int64)objc_msgSend(v11, *(&selRef_alloc + 38), v9, v6);
  objc_release(v9);
  objc_release(v12);
  return (char)v6;
}
// 1848: using guessed type char *selRef_alloc;
// 8178: using guessed type int __fastcall objc_release(_QWORD);
// 8180: using guessed type int (__fastcall *objc_retain)(_QWORD);
// 8188: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000D49) ----------------------------------------------------
// FIRInstanceIDStore - (id)cachedCheckinPreferences
id __cdecl -[FIRInstanceIDStore cachedCheckinPreferences](struct FIRInstanceIDStore *self, SEL a2)
{
  void *v2; // rax@1
  void *v3; // rax@1
  void *v4; // rbx@1
  void *v5; // rax@1
  __int64 v6; // rax@1
  __int64 v7; // r14@1
  id result; // rax@1

  v2 = objc_msgSend(self, *(&selRef_alloc + 18));
  LODWORD(v3) = objc_retainAutoreleasedReturnValue(v2);
  v4 = v3;
  v5 = objc_msgSend(v3, *(&selRef_alloc + 20));
  LODWORD(v6) = objc_retainAutoreleasedReturnValue(v5);
  v7 = v6;
  objc_release(v4);
  LODWORD(result) = objc_autoreleaseReturnValue(v7);
  return result;
}
// 1848: using guessed type char *selRef_alloc;
// 8150: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 8178: using guessed type int __fastcall objc_release(_QWORD);
// 8188: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000D99) ----------------------------------------------------
// FIRInstanceIDStore - (bool)removeCheckinPreferences:(id *) 
bool __cdecl -[FIRInstanceIDStore removeCheckinPreferences:](struct FIRInstanceIDStore *self, SEL a2, id *a3)
{
  __int64 v3; // rax@0
  id *v4; // r14@1
  void *v5; // rax@1
  void *v6; // rax@1
  void *v7; // rbx@1

  v4 = a3;
  v5 = objc_msgSend(self, *(&selRef_alloc + 18), v3);
  LODWORD(v6) = objc_retainAutoreleasedReturnValue(v5);
  v7 = v6;
  LODWORD(v4) = (unsigned __int64)objc_msgSend(v6, *(&selRef_alloc + 21), v4);
  objc_release(v7);
  return (char)v4;
}
// 1848: using guessed type char *selRef_alloc;
// 8178: using guessed type int __fastcall objc_release(_QWORD);
// 8188: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000DEC) ----------------------------------------------------
// FIRInstanceIDStore - (id)delegate
id __cdecl -[FIRInstanceIDStore delegate](struct FIRInstanceIDStore *self, SEL a2)
{
  __int64 v2; // rax@1
  id result; // rax@1

  LODWORD(v2) = objc_loadWeakRetained(&self->_delegate, a2);
  LODWORD(result) = objc_autoreleaseReturnValue(v2);
  return result;
}
// 8150: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// 8160: using guessed type int __fastcall objc_loadWeakRetained(_QWORD, _QWORD);

//----- (0000000000000E05) ----------------------------------------------------
// FIRInstanceIDStore - (id)checkinStore
id __cdecl -[FIRInstanceIDStore checkinStore](struct FIRInstanceIDStore *self, SEL a2)
{
  return (id)self->_checkinStore;
}

//----- (0000000000000E16) ----------------------------------------------------
// FIRInstanceIDStore - (void)setCheckinStore:(id) 
void __cdecl -[FIRInstanceIDStore setCheckinStore:](struct FIRInstanceIDStore *self, SEL a2, id a3)
{
  objc_storeStrong(&self->_checkinStore, a3);
}
// 8190: using guessed type int __fastcall objc_storeStrong(_QWORD, _QWORD);

//----- (0000000000000E2A) ----------------------------------------------------
// FIRInstanceIDStore - (id)tokenStore
id __cdecl -[FIRInstanceIDStore tokenStore](struct FIRInstanceIDStore *self, SEL a2)
{
  return (id)self->_tokenStore;
}

//----- (0000000000000E3B) ----------------------------------------------------
// FIRInstanceIDStore - (void)setTokenStore:(id) 
void __cdecl -[FIRInstanceIDStore setTokenStore:](struct FIRInstanceIDStore *self, SEL a2, id a3)
{
  objc_storeStrong(&self->_tokenStore, a3);
}
// 8190: using guessed type int __fastcall objc_storeStrong(_QWORD, _QWORD);

//----- (0000000000000E4F) ----------------------------------------------------
// FIRInstanceIDStore - (void).cxx_destruct
void __cdecl -[FIRInstanceIDStore .cxx_destruct](struct FIRInstanceIDStore *self, SEL a2)
{
  objc_storeStrong(&self->_tokenStore, 0LL);
  objc_storeStrong(&self->_checkinStore, 0LL);
  objc_destroyWeak(&self->_delegate, 0LL);
}
// 8158: using guessed type int __fastcall objc_destroyWeak(_QWORD, _QWORD);
// 8190: using guessed type int __fastcall objc_storeStrong(_QWORD, _QWORD);

// ALL OK, 24 function(s) have been successfully decompiled
