/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2015 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int +[FIRInstanceIDTokenOperation sharedURLSession]();
// int __usercall __47__FIRInstanceIDTokenOperation_sharedURLSession__block_invoke@<eax>(__int64 a1@<rax>);
id __cdecl -[FIRInstanceIDTokenOperation initWithAction:forAuthorizedEntity:scope:options:checkinPreferences:keyPair:](struct FIRInstanceIDTokenOperation *self, SEL, int64_t, id, id, id, id, id);
void __cdecl -[FIRInstanceIDTokenOperation dealloc](struct FIRInstanceIDTokenOperation *self, SEL);
void __cdecl -[FIRInstanceIDTokenOperation addCompletionHandler:](struct FIRInstanceIDTokenOperation *self, SEL, id);
bool __cdecl -[FIRInstanceIDTokenOperation isAsynchronous](struct FIRInstanceIDTokenOperation *self, SEL);
bool __cdecl -[FIRInstanceIDTokenOperation isExecuting](struct FIRInstanceIDTokenOperation *self, SEL);
void __cdecl -[FIRInstanceIDTokenOperation setExecuting:](struct FIRInstanceIDTokenOperation *self, SEL, bool);
bool __cdecl -[FIRInstanceIDTokenOperation isFinished](struct FIRInstanceIDTokenOperation *self, SEL);
void __cdecl -[FIRInstanceIDTokenOperation setFinished:](struct FIRInstanceIDTokenOperation *self, SEL, bool);
void __cdecl -[FIRInstanceIDTokenOperation start](struct FIRInstanceIDTokenOperation *self, SEL);
void __cdecl -[FIRInstanceIDTokenOperation finishWithResult:token:error:](struct FIRInstanceIDTokenOperation *self, SEL, int64_t, id, id);
void __cdecl -[FIRInstanceIDTokenOperation cancel](struct FIRInstanceIDTokenOperation *self, SEL);
void __cdecl -[FIRInstanceIDTokenOperation performTokenOperation](struct FIRInstanceIDTokenOperation *self, SEL);
id __cdecl +[FIRInstanceIDTokenOperation requestWithAuthHeader:](struct FIRInstanceIDTokenOperation *self, SEL, id);
id __cdecl +[FIRInstanceIDTokenOperation standardQueryItemsWithDeviceID:scope:requestID:](struct FIRInstanceIDTokenOperation *self, SEL, id, id, uint64_t);
id __cdecl -[FIRInstanceIDTokenOperation queryItemsWithKeyPair:](struct FIRInstanceIDTokenOperation *self, SEL, id);
uint64_t __cdecl +[FIRInstanceIDTokenOperation nextRequestID](struct FIRInstanceIDTokenOperation_meta *self, SEL);
id __cdecl +[FIRInstanceIDTokenOperation HTTPAuthHeaderFromCheckin:](struct FIRInstanceIDTokenOperation *self, SEL, id);
int64_t __cdecl -[FIRInstanceIDTokenOperation action](struct FIRInstanceIDTokenOperation *self, SEL);
id __cdecl -[FIRInstanceIDTokenOperation authorizedEntity](struct FIRInstanceIDTokenOperation *self, SEL);
id __cdecl -[FIRInstanceIDTokenOperation scope](struct FIRInstanceIDTokenOperation *self, SEL);
id __cdecl -[FIRInstanceIDTokenOperation options](struct FIRInstanceIDTokenOperation *self, SEL);
id __cdecl -[FIRInstanceIDTokenOperation checkinPreferences](struct FIRInstanceIDTokenOperation *self, SEL);
void __cdecl -[FIRInstanceIDTokenOperation setCheckinPreferences:](struct FIRInstanceIDTokenOperation *self, SEL, id);
id __cdecl -[FIRInstanceIDTokenOperation keyPair](struct FIRInstanceIDTokenOperation *self, SEL);
void __cdecl -[FIRInstanceIDTokenOperation setKeyPair:](struct FIRInstanceIDTokenOperation *self, SEL, id);
int64_t __cdecl -[FIRInstanceIDTokenOperation result](struct FIRInstanceIDTokenOperation *self, SEL);
uint64_t __cdecl -[FIRInstanceIDTokenOperation requestID](struct FIRInstanceIDTokenOperation *self, SEL);
void __cdecl -[FIRInstanceIDTokenOperation setRequestID:](struct FIRInstanceIDTokenOperation *self, SEL, uint64_t);
id __cdecl -[FIRInstanceIDTokenOperation dataTask](struct FIRInstanceIDTokenOperation *self, SEL);
void __cdecl -[FIRInstanceIDTokenOperation setDataTask:](struct FIRInstanceIDTokenOperation *self, SEL, id);
id __cdecl -[FIRInstanceIDTokenOperation completionHandlers](struct FIRInstanceIDTokenOperation *self, SEL);
id __cdecl -[FIRInstanceIDTokenOperation testBlock](struct FIRInstanceIDTokenOperation *self, SEL);
void __cdecl -[FIRInstanceIDTokenOperation setTestBlock:](struct FIRInstanceIDTokenOperation *self, SEL, id);
void __cdecl -[FIRInstanceIDTokenOperation .cxx_destruct](struct FIRInstanceIDTokenOperation *self, SEL);
// int __fastcall FIRInstanceIDAppIdentifier(_QWORD); weak
// int __fastcall FIRInstanceIDConcatenateStrings(_QWORD, _QWORD, _QWORD); weak
// int __fastcall FIRInstanceIDCurrentAppVersion(_QWORD); weak
// int __fastcall FIRInstanceIDCurrentGCMVersion(_QWORD); weak
// int __fastcall FIRInstanceIDOperatingSystemVersion(_QWORD); weak
// int __fastcall FIRInstanceIDRegisterServer(_QWORD); weak
// int __fastcall FIRInstanceIDSecKeyBase64Encoding(_QWORD); weak
// int __fastcall FIRInstanceIDSharedLogger(_QWORD); weak
// int __fastcall FIRInstanceIDSignParams(_QWORD, _QWORD); weak
// int __fastcall FIRInstanceIDVerifyData(_QWORD, _QWORD, _QWORD); weak
// int __fastcall dispatch_once(_QWORD, _QWORD); weak
// int __fastcall objc_autoreleaseReturnValue(_QWORD); weak
// int __fastcall objc_enumerationMutation(_QWORD); weak
// int __fastcall objc_getProperty(_QWORD, _QWORD, _QWORD, _QWORD); weak
// void *objc_msgSend(void *, const char *, ...); idb
// void *objc_msgSendSuper2(void *, const char *, ...); idb
// int __fastcall objc_release(_QWORD); weak
// int __fastcall objc_retain(_QWORD, _QWORD, _QWORD); weak
// int __fastcall objc_retainAutoreleaseReturnValue(_QWORD); weak
// int __fastcall objc_retainAutoreleasedReturnValue(_QWORD); weak
// int __fastcall objc_retainBlock(_QWORD); weak
// int __fastcall objc_setProperty_atomic(_QWORD, _QWORD, _QWORD, _QWORD); weak
// int __fastcall objc_setProperty_nonatomic_copy(_QWORD, _QWORD, _QWORD, _QWORD); weak
// int __fastcall objc_storeStrong(_QWORD, _QWORD); weak
// int __fastcall objc_sync_enter(_QWORD, _QWORD); weak
// int objc_sync_exit(void); weak

//-------------------------------------------------------------------------
// Data declarations

char aAppid[6] = "appid"; // weak
__CFString cfstr_Appid = { &__CFConstantStringClassReference, 1992LL, "appid", 5LL }; // weak
void *classRef_NSURLSessionConfiguration = &OBJC_CLASS___NSURLSessionConfiguration; // weak
char *selRef_defaultSessionConfiguration = "defaultSessionConfiguration"; // weak
void *__block_literal_global = &_NSConcreteGlobalBlock; // weak
void *classRef_FIRInstanceIDTokenOperation = &OBJC_CLASS___FIRInstanceIDTokenOperation; // weak
__int64 sharedURLSession_tokenOperationSharedSession; // weak
__int64 sharedURLSession_onceToken; // weak
__int64 currentRequestID; // weak
// extern _UNKNOWN __stack_chk_guard; weak


//----- (0000000000000000) ----------------------------------------------------
int +[FIRInstanceIDTokenOperation sharedURLSession]()
{
  if ( sharedURLSession_onceToken != -1 )
    dispatch_once(&sharedURLSession_onceToken, &__block_literal_global);
  return objc_retainAutoreleaseReturnValue(sharedURLSession_tokenOperationSharedSession);
}
// 1D70: using guessed type void *__block_literal_global;
// AC68: using guessed type __int64 sharedURLSession_tokenOperationSharedSession;
// AC70: using guessed type __int64 sharedURLSession_onceToken;
// AD58: using guessed type int __fastcall dispatch_once(_QWORD, _QWORD);
// AD98: using guessed type int __fastcall objc_retainAutoreleaseReturnValue(_QWORD);

//----- (0000000000000030) ----------------------------------------------------
int __usercall __47__FIRInstanceIDTokenOperation_sharedURLSession__block_invoke@<eax>(__int64 a1@<rax>)
{
  void *v1; // rax@1
  void *v2; // rax@1
  void *v3; // rbx@1
  void *v4; // rax@1
  __int64 v5; // rax@1
  __int64 v6; // rdi@1

  v1 = objc_msgSend(classRef_NSURLSessionConfiguration, selRef_defaultSessionConfiguration, a1);
  LODWORD(v2) = objc_retainAutoreleasedReturnValue(v1);
  v3 = v2;
  objc_msgSend(v2, *(&selRef_defaultSessionConfiguration + 1), COERCE_DOUBLE(4633641066610819072LL));
  v4 = objc_msgSend(*(&classRef_NSURLSessionConfiguration + 1), *(&selRef_defaultSessionConfiguration + 2), v3);
  LODWORD(v5) = objc_retainAutoreleasedReturnValue(v4);
  v6 = sharedURLSession_tokenOperationSharedSession;
  sharedURLSession_tokenOperationSharedSession = v5;
  objc_release(v6);
  objc_msgSend(
    (void *)sharedURLSession_tokenOperationSharedSession,
    *(&selRef_defaultSessionConfiguration + 3),
    &cfstr_Appid + 6);
  return objc_release(v3);
}
// 1418: using guessed type __CFString cfstr_Appid;
// 1698: using guessed type void *classRef_NSURLSessionConfiguration;
// 1C00: using guessed type char *selRef_defaultSessionConfiguration;
// AC68: using guessed type __int64 sharedURLSession_tokenOperationSharedSession;
// AD88: using guessed type int __fastcall objc_release(_QWORD);
// ADA0: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (00000000000000D0) ----------------------------------------------------
// FIRInstanceIDTokenOperation - (id)initWithAction:(int64_t) forAuthorizedEntity:(id) scope:(id) options:(id) checkinPreferences:(id) keyPair:(id) 
id __cdecl -[FIRInstanceIDTokenOperation initWithAction:forAuthorizedEntity:scope:options:checkinPreferences:keyPair:](struct FIRInstanceIDTokenOperation *self, SEL a2, int64_t a3, id a4, id a5, id a6, id a7, id a8)
{
  id v8; // r13@1
  id v9; // r14@1
  void *v10; // rax@1
  __int64 v11; // rdx@1
  void *v12; // rax@1
  __int64 v13; // rdx@1
  void *v14; // rax@1
  void *v15; // r13@1
  __int64 v16; // rdx@1
  __int64 v17; // rax@1
  __int64 v18; // r15@1
  __int64 v19; // rdx@1
  __int64 v20; // rax@1
  _QWORD *v21; // rbx@1
  const char *v22; // r12@2
  void *v23; // rax@2
  __int64 v24; // rdi@2
  void *v25; // rax@2
  __int64 v26; // rdi@2
  void *v27; // rax@2
  __int64 v28; // rdi@2
  void *v29; // rax@2
  __int64 v30; // rax@2
  __int64 v31; // rdi@2
  struct FIRInstanceIDTokenOperation *v33; // [sp+8h] [bp-58h]@1
  void *v34; // [sp+10h] [bp-50h]@1
  __int64 v35; // [sp+18h] [bp-48h]@1
  __int64 v36; // [sp+20h] [bp-40h]@2
  void *v37; // [sp+28h] [bp-38h]@1
  void *v38; // [sp+30h] [bp-30h]@1

  v8 = a6;
  v9 = a5;
  LODWORD(v10) = objc_retain(a4, a2, a3);
  v37 = v10;
  LODWORD(v12) = objc_retain(v9, a2, v11);
  v38 = v12;
  LODWORD(v14) = objc_retain(v8, a2, v13);
  v15 = v14;
  LODWORD(v17) = objc_retain(a7, a2, v16);
  v18 = v17;
  LODWORD(v20) = objc_retain(a8, a2, v19);
  v35 = v20;
  v33 = self;
  v34 = classRef_FIRInstanceIDTokenOperation;
  v21 = objc_msgSendSuper2(&v33, *(&selRef_defaultSessionConfiguration + 4));
  if ( v21 )
  {
    v22 = *(&selRef_defaultSessionConfiguration + 5);
    v36 = v18;
    v23 = objc_msgSend(v37, v22);
    v24 = v21[5];
    v21[5] = v23;
    objc_release(v24);
    v25 = objc_msgSend(v38, v22);
    v26 = v21[6];
    v21[6] = v25;
    objc_release(v26);
    v27 = objc_msgSend(v15, v22);
    v28 = v21[7];
    v21[7] = v27;
    objc_release(v28);
    objc_storeStrong(v21 + 8, a7);
    objc_storeStrong(v21 + 9, a8);
    v29 = objc_msgSend(*(&classRef_NSURLSessionConfiguration + 2), *(&selRef_defaultSessionConfiguration + 6));
    v18 = v36;
    LODWORD(v30) = objc_retainAutoreleasedReturnValue(v29);
    v31 = v21[13];
    v21[13] = v30;
    objc_release(v31);
    *((_BYTE *)v21 + 25) = 0;
    *((_BYTE *)v21 + 24) = 0;
  }
  objc_release(v35);
  objc_release(v18);
  objc_release(v15);
  objc_release(v38);
  objc_release(v37);
  return (id)v21;
}
// 1698: using guessed type void *classRef_NSURLSessionConfiguration;
// 1C00: using guessed type char *selRef_defaultSessionConfiguration;
// 1DE0: using guessed type void *classRef_FIRInstanceIDTokenOperation;
// AD88: using guessed type int __fastcall objc_release(_QWORD);
// AD90: using guessed type int __fastcall objc_retain(_QWORD, _QWORD, _QWORD);
// ADA0: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);
// ADC0: using guessed type int __fastcall objc_storeStrong(_QWORD, _QWORD);

//----- (000000000000025C) ----------------------------------------------------
// FIRInstanceIDTokenOperation - (void)dealloc
void __cdecl -[FIRInstanceIDTokenOperation dealloc](struct FIRInstanceIDTokenOperation *self, SEL a2)
{
  struct FIRInstanceIDTokenOperation *v2; // rbx@1
  id v3; // rdi@1
  struct NSString *v4; // rdi@1
  struct NSString *v5; // rdi@1
  struct NSDictionary *v6; // rdi@1
  struct FIRInstanceIDCheckinPreferences *v7; // rdi@1
  struct FIRInstanceIDKeyPair *v8; // rdi@1
  struct NSMutableArray *v9; // rdi@1
  struct FIRInstanceIDTokenOperation *v10; // [sp+0h] [bp-30h]@1
  void *v11; // [sp+8h] [bp-28h]@1

  v2 = self;
  v3 = self->_testBlock;
  v2->_testBlock = 0LL;
  objc_release(v3);
  v4 = v2->_authorizedEntity;
  v2->_authorizedEntity = 0LL;
  objc_release(v4);
  v5 = v2->_scope;
  v2->_scope = 0LL;
  objc_release(v5);
  v6 = v2->_options;
  v2->_options = 0LL;
  objc_release(v6);
  v7 = v2->_checkinPreferences;
  v2->_checkinPreferences = 0LL;
  objc_release(v7);
  v8 = v2->_keyPair;
  v2->_keyPair = 0LL;
  objc_release(v8);
  objc_msgSend((void *)v2->_completionHandlers, *(&selRef_defaultSessionConfiguration + 7));
  v9 = v2->_completionHandlers;
  v2->_completionHandlers = 0LL;
  objc_release(v9);
  v10 = v2;
  v11 = classRef_FIRInstanceIDTokenOperation;
  objc_msgSendSuper2(&v10, *(&selRef_defaultSessionConfiguration + 8), v2, classRef_FIRInstanceIDTokenOperation);
}
// 1C00: using guessed type char *selRef_defaultSessionConfiguration;
// 1DE0: using guessed type void *classRef_FIRInstanceIDTokenOperation;
// AD88: using guessed type int __fastcall objc_release(_QWORD);

//----- (0000000000000332) ----------------------------------------------------
// FIRInstanceIDTokenOperation - (void)addCompletionHandler:(id) 
void __cdecl -[FIRInstanceIDTokenOperation addCompletionHandler:](struct FIRInstanceIDTokenOperation *self, SEL a2, id a3)
{
  __int64 v3; // rax@0
  __int64 v4; // ST00_8@1
  id v5; // rbx@1
  const char *v6; // r15@1
  __int64 v7; // rax@1
  __int64 v8; // r12@1
  void *v9; // rax@1
  void *v10; // rax@1
  void *v11; // r14@1
  __int64 v12; // rax@1
  __int64 v13; // rbx@1

  v4 = v3;
  v5 = a3;
  v6 = *(&selRef_defaultSessionConfiguration + 9);
  LODWORD(v7) = objc_retain(a3, a2, a3);
  v8 = v7;
  v9 = objc_msgSend(self, v6, v4);
  LODWORD(v10) = objc_retainAutoreleasedReturnValue(v9);
  v11 = v10;
  LODWORD(v12) = objc_retainBlock(v5);
  v13 = v12;
  objc_release(v8);
  objc_msgSend(v11, *(&selRef_defaultSessionConfiguration + 10), v13);
  objc_release(v13);
  objc_release(v11);
}
// 1C00: using guessed type char *selRef_defaultSessionConfiguration;
// AD88: using guessed type int __fastcall objc_release(_QWORD);
// AD90: using guessed type int __fastcall objc_retain(_QWORD, _QWORD, _QWORD);
// ADA0: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);
// ADA8: using guessed type int __fastcall objc_retainBlock(_QWORD);

//----- (00000000000003B8) ----------------------------------------------------
// FIRInstanceIDTokenOperation - (bool)isAsynchronous
bool __cdecl -[FIRInstanceIDTokenOperation isAsynchronous](struct FIRInstanceIDTokenOperation *self, SEL a2)
{
  return 1;
}

//----- (00000000000003C0) ----------------------------------------------------
// FIRInstanceIDTokenOperation - (bool)isExecuting
bool __cdecl -[FIRInstanceIDTokenOperation isExecuting](struct FIRInstanceIDTokenOperation *self, SEL a2)
{
  return self->_isExecuting;
}

//----- (00000000000003D0) ----------------------------------------------------
// FIRInstanceIDTokenOperation - (void)setExecuting:(bool) 
void __cdecl -[FIRInstanceIDTokenOperation setExecuting:](struct FIRInstanceIDTokenOperation *self, SEL a2, bool a3)
{
  bool v3; // r14@1

  v3 = a3;
  objc_msgSend(self, *(&selRef_defaultSessionConfiguration + 11), &cfstr_Appid + 7);
  self->_isExecuting = v3;
  objc_msgSend(self, *(&selRef_defaultSessionConfiguration + 12), &cfstr_Appid + 7);
}
// 1418: using guessed type __CFString cfstr_Appid;
// 1C00: using guessed type char *selRef_defaultSessionConfiguration;

//----- (0000000000000421) ----------------------------------------------------
// FIRInstanceIDTokenOperation - (bool)isFinished
bool __cdecl -[FIRInstanceIDTokenOperation isFinished](struct FIRInstanceIDTokenOperation *self, SEL a2)
{
  return self->_isFinished;
}

//----- (0000000000000431) ----------------------------------------------------
// FIRInstanceIDTokenOperation - (void)setFinished:(bool) 
void __cdecl -[FIRInstanceIDTokenOperation setFinished:](struct FIRInstanceIDTokenOperation *self, SEL a2, bool a3)
{
  bool v3; // r14@1

  v3 = a3;
  objc_msgSend(self, *(&selRef_defaultSessionConfiguration + 11), &cfstr_Appid + 8);
  self->_isFinished = v3;
  objc_msgSend(self, *(&selRef_defaultSessionConfiguration + 12), &cfstr_Appid + 8);
}
// 1418: using guessed type __CFString cfstr_Appid;
// 1C00: using guessed type char *selRef_defaultSessionConfiguration;

//----- (0000000000000482) ----------------------------------------------------
// FIRInstanceIDTokenOperation - (void)start
void __cdecl -[FIRInstanceIDTokenOperation start](struct FIRInstanceIDTokenOperation *self, SEL a2)
{
  void *v2; // rax@3
  void *v3; // rax@3
  void *v4; // rbx@3
  int v5; // er15@3
  __int64 v6; // rax@5
  __int64 v7; // rax@5
  __int64 v8; // rbx@5

  if ( (unsigned __int8)objc_msgSend(self, *(&selRef_defaultSessionConfiguration + 13)) )
  {
    objc_msgSend(self, *(&selRef_defaultSessionConfiguration + 14), 2LL, 0LL, 0LL);
  }
  else
  {
    v2 = objc_msgSend(self, *(&selRef_defaultSessionConfiguration + 15));
    LODWORD(v3) = objc_retainAutoreleasedReturnValue(v2);
    v4 = v3;
    v5 = (unsigned __int64)objc_msgSend(v3, *(&selRef_defaultSessionConfiguration + 16));
    objc_release(v4);
    if ( (_BYTE)v5 )
    {
      ((void (__fastcall *)(struct FIRInstanceIDTokenOperation *, _QWORD, signed __int64))objc_msgSend)(
        self,
        *(&selRef_defaultSessionConfiguration + 18),
        1LL);
      ((void (__fastcall *)(struct FIRInstanceIDTokenOperation *, _QWORD))objc_msgSend)(
        self,
        *(&selRef_defaultSessionConfiguration + 19));
    }
    else
    {
      LODWORD(v6) = ((int (__fastcall *)(_QWORD, _QWORD, signed __int64))objc_msgSend)(
                      *(&classRef_NSURLSessionConfiguration + 3),
                      *(&selRef_defaultSessionConfiguration + 17),
                      6LL);
      LODWORD(v7) = objc_retainAutoreleasedReturnValue(v6);
      v8 = v7;
      ((void (__fastcall *)(struct FIRInstanceIDTokenOperation *, _QWORD, signed __int64, _QWORD, __int64))objc_msgSend)(
        self,
        *(&selRef_defaultSessionConfiguration + 14),
        1LL,
        0LL,
        v7);
      objc_release(v8);
    }
  }
}
// 1698: using guessed type void *classRef_NSURLSessionConfiguration;
// 1C00: using guessed type char *selRef_defaultSessionConfiguration;
// AD88: using guessed type int __fastcall objc_release(_QWORD);
// ADA0: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000575) ----------------------------------------------------
// FIRInstanceIDTokenOperation - (void)finishWithResult:(int64_t) token:(id) error:(id) 
void __cdecl -[FIRInstanceIDTokenOperation finishWithResult:token:error:](struct FIRInstanceIDTokenOperation *self, SEL a2, int64_t a3, id a4, id a5)
{
  id v5; // r14@1
  int64_t v6; // rbx@1
  __int64 v7; // rax@1
  __int64 v8; // rdx@1
  __int64 v9; // rax@1
  __int64 v10; // r12@1
  const char *v11; // rsi@2
  void *v12; // rax@2
  void *v13; // rax@2
  const char *v14; // rsi@2
  void *v15; // r14@2
  __int64 v16; // r13@3
  unsigned __int64 v17; // r15@4
  struct FIRInstanceIDTokenOperation *v18; // rbx@9
  __int64 v19; // rax@10
  __int128 v20; // [sp+0h] [bp-110h]@2
  __int128 v21; // [sp+10h] [bp-100h]@2
  __int128 v22; // [sp+20h] [bp-F0h]@2
  __int128 v23; // [sp+30h] [bp-E0h]@2
  struct FIRInstanceIDTokenOperation *v24; // [sp+48h] [bp-C8h]@2
  __int64 v25; // [sp+50h] [bp-C0h]@1
  void *v26; // [sp+58h] [bp-B8h]@2
  char v27; // [sp+60h] [bp-B0h]@2
  __int64 v28; // [sp+E0h] [bp-30h]@1

  v5 = a5;
  v6 = a3;
  v28 = *__stack_chk_guard;
  LODWORD(v7) = objc_retain(a4, a2, a3);
  v25 = v7;
  LODWORD(v9) = objc_retain(v5, a2, v8);
  v10 = v9;
  if ( !(unsigned __int8)objc_msgSend(self, *(&selRef_defaultSessionConfiguration + 20)) )
  {
    objc_msgSend(self, *(&selRef_defaultSessionConfiguration + 21), 0LL);
    self->_result = v6;
    v23 = 0LL;
    v22 = 0LL;
    v21 = 0LL;
    v20 = 0LL;
    v11 = *(&selRef_defaultSessionConfiguration + 9);
    v24 = self;
    v12 = objc_msgSend(self, v11, 0LL, 0LL);
    LODWORD(v13) = objc_retainAutoreleasedReturnValue(v12);
    v14 = *(&selRef_defaultSessionConfiguration + 22);
    v26 = v13;
    v15 = objc_msgSend(v13, v14, &v20, &v27, 16LL, (_QWORD)v20);
    if ( v15 )
    {
      v16 = *(_QWORD *)v21;
      do
      {
        v17 = 0LL;
        do
        {
          if ( *(_QWORD *)v21 != v16 )
            objc_enumerationMutation(v26);
          (*(void (__fastcall **)(_QWORD, int64_t, __int64, __int64))(*(_QWORD *)(*((_QWORD *)&v20 + 1) + 8 * v17) + 16LL))(
            *(_QWORD *)(*((_QWORD *)&v20 + 1) + 8 * v17),
            v6,
            v25,
            v10);
          ++v17;
        }
        while ( v17 < (unsigned __int64)v15 );
        v15 = objc_msgSend(v26, *(&selRef_defaultSessionConfiguration + 22), &v20, &v27, 16LL, (_QWORD)v20);
      }
      while ( v15 );
    }
    objc_release(v26);
    v18 = v24;
    objc_msgSend(v24, *(&selRef_defaultSessionConfiguration + 18), 0LL, (_QWORD)v20);
    objc_msgSend(v18, *(&selRef_defaultSessionConfiguration + 23), 1LL, (_QWORD)v20);
  }
  objc_release(v10);
  objc_release(v25);
  v19 = *__stack_chk_guard;
}
// 1C00: using guessed type char *selRef_defaultSessionConfiguration;
// AD68: using guessed type int __fastcall objc_enumerationMutation(_QWORD);
// AD88: using guessed type int __fastcall objc_release(_QWORD);
// AD90: using guessed type int __fastcall objc_retain(_QWORD, _QWORD, _QWORD);
// ADA0: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000753) ----------------------------------------------------
// FIRInstanceIDTokenOperation - (void)cancel
void __cdecl -[FIRInstanceIDTokenOperation cancel](struct FIRInstanceIDTokenOperation *self, SEL a2)
{
  const char *v2; // r14@1
  void *v3; // rax@1
  void *v4; // rax@1
  void *v5; // rbx@1
  struct FIRInstanceIDTokenOperation *v6; // [sp+0h] [bp-30h]@1
  void *v7; // [sp+8h] [bp-28h]@1

  v6 = self;
  v7 = classRef_FIRInstanceIDTokenOperation;
  v2 = *(&selRef_defaultSessionConfiguration + 24);
  objc_msgSendSuper2(&v6, *(&selRef_defaultSessionConfiguration + 24), self, classRef_FIRInstanceIDTokenOperation);
  v3 = objc_msgSend(self, *(&selRef_defaultSessionConfiguration + 25), v6, v7);
  LODWORD(v4) = objc_retainAutoreleasedReturnValue(v3);
  v5 = v4;
  objc_msgSend(v4, v2, v6, v7);
  objc_release(v5);
  objc_msgSend(self, *(&selRef_defaultSessionConfiguration + 14), 2LL, 0LL, 0LL, v6, v7);
}
// 1C00: using guessed type char *selRef_defaultSessionConfiguration;
// 1DE0: using guessed type void *classRef_FIRInstanceIDTokenOperation;
// AD88: using guessed type int __fastcall objc_release(_QWORD);
// ADA0: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (00000000000007DB) ----------------------------------------------------
// FIRInstanceIDTokenOperation - (void)performTokenOperation
void __cdecl -[FIRInstanceIDTokenOperation performTokenOperation](struct FIRInstanceIDTokenOperation *self, SEL a2)
{
  ;
}

//----- (00000000000007E1) ----------------------------------------------------
// FIRInstanceIDTokenOperation + (id)requestWithAuthHeader:(id) 
id __cdecl +[FIRInstanceIDTokenOperation requestWithAuthHeader:](struct FIRInstanceIDTokenOperation *self, SEL a2, id a3)
{
  __int64 v3; // rax@0
  __int64 v4; // ST00_8@1
  void *v5; // r14@1
  id v6; // rdi@1
  __int64 v7; // rax@1
  __int64 v8; // r15@1
  __int64 v9; // rax@1
  __int64 v10; // rax@1
  __int64 v11; // rbx@1
  void *v12; // rax@1
  __int64 v13; // rax@1
  __int64 v14; // r14@1
  void *v15; // rax@1
  void *v16; // rax@1
  void *v17; // r13@1
  __int64 v18; // rax@1
  __int64 v19; // rax@1
  __int64 v20; // rbx@1
  id result; // rax@1

  v4 = v3;
  v5 = *(&classRef_NSURLSessionConfiguration + 4);
  v6 = a3;
  LODWORD(v7) = objc_retain(a3, a2, a3);
  v8 = v7;
  LODWORD(v9) = FIRInstanceIDRegisterServer(v6);
  LODWORD(v10) = objc_retainAutoreleasedReturnValue(v9);
  v11 = v10;
  v12 = objc_msgSend(v5, *(&selRef_defaultSessionConfiguration + 26), v10, v4);
  LODWORD(v13) = objc_retainAutoreleasedReturnValue(v12);
  v14 = v13;
  objc_release(v11);
  v15 = objc_msgSend(*(&classRef_NSURLSessionConfiguration + 5), *(&selRef_defaultSessionConfiguration + 27), v14);
  LODWORD(v16) = objc_retainAutoreleasedReturnValue(v15);
  v17 = v16;
  objc_msgSend(v16, *(&selRef_defaultSessionConfiguration + 28), v8, &cfstr_Appid + 9);
  objc_release(v8);
  LODWORD(v18) = FIRInstanceIDAppIdentifier(v8);
  LODWORD(v19) = objc_retainAutoreleasedReturnValue(v18);
  v20 = v19;
  objc_msgSend(v17, *(&selRef_defaultSessionConfiguration + 28), v19, &cfstr_Appid + 10);
  objc_release(v20);
  objc_msgSend(v17, *(&selRef_defaultSessionConfiguration + 29), &cfstr_Appid + 11);
  objc_release(v14);
  LODWORD(result) = objc_autoreleaseReturnValue(v17);
  return result;
}
// 1418: using guessed type __CFString cfstr_Appid;
// 1698: using guessed type void *classRef_NSURLSessionConfiguration;
// 1C00: using guessed type char *selRef_defaultSessionConfiguration;
// AC80: using guessed type int __fastcall FIRInstanceIDAppIdentifier(_QWORD);
// ACA8: using guessed type int __fastcall FIRInstanceIDRegisterServer(_QWORD);
// AD60: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// AD88: using guessed type int __fastcall objc_release(_QWORD);
// AD90: using guessed type int __fastcall objc_retain(_QWORD, _QWORD, _QWORD);
// ADA0: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (00000000000008E0) ----------------------------------------------------
// FIRInstanceIDTokenOperation + (id)standardQueryItemsWithDeviceID:(id) scope:(id) requestID:(uint64_t) 
id __cdecl +[FIRInstanceIDTokenOperation standardQueryItemsWithDeviceID:scope:requestID:](struct FIRInstanceIDTokenOperation *self, SEL a2, id a3, id a4, uint64_t a5)
{
  id v5; // rbx@1
  __int64 v6; // rax@1
  __int64 v7; // r15@1
  __int64 v8; // rdx@1
  __int64 v9; // rax@1
  __int64 v10; // r12@1
  void *v11; // rax@1
  void *v12; // rdi@1
  void *v13; // rax@1
  void *v14; // r13@1
  __int64 v15; // rax@1
  __int64 v16; // rax@1
  void *v17; // rax@1
  __int64 v18; // rax@1
  __int64 v19; // rbx@1
  void *v20; // rax@2
  __int64 v21; // rax@2
  __int64 v22; // rbx@2
  const char *v23; // r15@3
  void *v24; // rax@4
  __int64 v25; // rax@4
  __int64 v26; // rbx@4
  void *v27; // rax@5
  __int64 v28; // rax@5
  void *v29; // rax@5
  __int64 v30; // rax@5
  __int64 v31; // rbx@5
  __int64 v32; // rax@5
  __int64 v33; // rax@5
  void *v34; // rax@5
  __int64 v35; // rax@5
  __int64 v36; // rbx@5
  const char *v37; // r12@5
  __int64 v38; // rax@5
  __int64 v39; // rax@5
  void *v40; // rax@5
  __int64 v41; // rax@5
  __int64 v42; // rbx@5
  void *v43; // rax@5
  __int64 v44; // rax@5
  void *v45; // r12@5
  __int64 v46; // r13@5
  void *v47; // rax@5
  __int64 v48; // rax@5
  __int64 v49; // rbx@5
  __int64 v50; // rax@5
  void *v51; // rax@5
  void *v52; // r12@5
  void *v53; // rax@6
  __int64 v54; // rax@6
  __int64 v55; // rbx@6
  id result; // rax@7
  __int64 v57; // [sp+0h] [bp-60h]@3
  __int64 v58; // [sp+0h] [bp-60h]@5
  __int64 v59; // [sp+8h] [bp-58h]@5
  __int64 v60; // [sp+10h] [bp-50h]@1
  __int64 v61; // [sp+18h] [bp-48h]@5
  __int64 v62; // [sp+20h] [bp-40h]@5
  __int64 v63; // [sp+28h] [bp-38h]@5
  uint64_t v64; // [sp+30h] [bp-30h]@1
  void *v65; // [sp+30h] [bp-30h]@5

  v64 = a5;
  v5 = a4;
  LODWORD(v6) = objc_retain(a3, a2, a3);
  v7 = v6;
  LODWORD(v9) = objc_retain(v5, a2, v8);
  v10 = v9;
  v11 = objc_msgSend(*(&classRef_NSURLSessionConfiguration + 2), *(&selRef_defaultSessionConfiguration + 30), 8LL);
  v12 = v11;
  LODWORD(v13) = objc_retainAutoreleasedReturnValue(v11);
  v14 = v13;
  LODWORD(v15) = FIRInstanceIDOperatingSystemVersion(v12);
  LODWORD(v16) = objc_retainAutoreleasedReturnValue(v15);
  v60 = v16;
  v17 = objc_msgSend(
          *(&classRef_NSURLSessionConfiguration + 6),
          *(&selRef_defaultSessionConfiguration + 31),
          &cfstr_Appid + 12,
          v16);
  LODWORD(v18) = objc_retainAutoreleasedReturnValue(v17);
  v19 = v18;
  objc_msgSend(v14, *(&selRef_defaultSessionConfiguration + 10), v18);
  objc_release(v19);
  if ( v7 )
  {
    v20 = objc_msgSend(
            *(&classRef_NSURLSessionConfiguration + 6),
            *(&selRef_defaultSessionConfiguration + 31),
            &cfstr_Appid + 13,
            v7);
    LODWORD(v21) = objc_retainAutoreleasedReturnValue(v20);
    v22 = v21;
    objc_msgSend(v14, *(&selRef_defaultSessionConfiguration + 10), v21);
    objc_release(v22);
  }
  v57 = v7;
  v23 = *(&selRef_defaultSessionConfiguration + 31);
  if ( v10 )
  {
    v24 = objc_msgSend(
            *(&classRef_NSURLSessionConfiguration + 6),
            *(&selRef_defaultSessionConfiguration + 31),
            &cfstr_Appid + 4,
            v10,
            v57);
    LODWORD(v25) = objc_retainAutoreleasedReturnValue(v24);
    v26 = v25;
    objc_msgSend(v14, *(&selRef_defaultSessionConfiguration + 10), v25);
    objc_release(v26);
  }
  v59 = v10;
  v27 = objc_msgSend(
          *(&classRef_NSURLSessionConfiguration + 7),
          *(&selRef_defaultSessionConfiguration + 32),
          &cfstr_Appid + 14,
          2LL,
          v57);
  LODWORD(v28) = objc_retainAutoreleasedReturnValue(v27);
  v61 = v28;
  v29 = objc_msgSend(*(&classRef_NSURLSessionConfiguration + 6), v23, &cfstr_Appid + 15, v28);
  LODWORD(v30) = objc_retainAutoreleasedReturnValue(v29);
  v31 = v30;
  objc_msgSend(v14, *(&selRef_defaultSessionConfiguration + 10), v30);
  objc_release(v31);
  LODWORD(v32) = FIRInstanceIDAppIdentifier(v31);
  LODWORD(v33) = objc_retainAutoreleasedReturnValue(v32);
  v62 = v33;
  v34 = objc_msgSend(*(&classRef_NSURLSessionConfiguration + 6), v23, &cfstr_Appid + 10, v33);
  LODWORD(v35) = objc_retainAutoreleasedReturnValue(v34);
  v36 = v35;
  v37 = *(&selRef_defaultSessionConfiguration + 10);
  objc_msgSend(v14, *(&selRef_defaultSessionConfiguration + 10), v35);
  objc_release(v36);
  LODWORD(v38) = FIRInstanceIDCurrentAppVersion(v36);
  LODWORD(v39) = objc_retainAutoreleasedReturnValue(v38);
  v63 = v39;
  v40 = objc_msgSend(
          *(&classRef_NSURLSessionConfiguration + 6),
          *(&selRef_defaultSessionConfiguration + 31),
          &cfstr_Appid + 16,
          v39);
  LODWORD(v41) = objc_retainAutoreleasedReturnValue(v40);
  v42 = v41;
  objc_msgSend(v14, v37, v41);
  objc_release(v42);
  v43 = objc_msgSend(
          *(&classRef_NSURLSessionConfiguration + 7),
          *(&selRef_defaultSessionConfiguration + 32),
          &cfstr_Appid + 17,
          v64);
  LODWORD(v44) = objc_retainAutoreleasedReturnValue(v43);
  v45 = v14;
  v46 = v44;
  v47 = objc_msgSend(
          *(&classRef_NSURLSessionConfiguration + 6),
          *(&selRef_defaultSessionConfiguration + 31),
          &cfstr_Appid + 3,
          v44);
  LODWORD(v48) = objc_retainAutoreleasedReturnValue(v47);
  v49 = v48;
  v65 = v45;
  objc_msgSend(v45, *(&selRef_defaultSessionConfiguration + 10), v48);
  objc_release(v49);
  LODWORD(v50) = FIRInstanceIDCurrentGCMVersion(v49);
  LODWORD(v51) = objc_retainAutoreleasedReturnValue(v50);
  v52 = v51;
  if ( objc_msgSend(v51, *(&selRef_defaultSessionConfiguration + 33)) )
  {
    v53 = objc_msgSend(
            *(&classRef_NSURLSessionConfiguration + 6),
            *(&selRef_defaultSessionConfiguration + 31),
            &cfstr_Appid + 5,
            v52);
    LODWORD(v54) = objc_retainAutoreleasedReturnValue(v53);
    v55 = v54;
    objc_msgSend(v65, *(&selRef_defaultSessionConfiguration + 10), v54);
    objc_release(v55);
  }
  objc_release(v52);
  objc_release(v46);
  objc_release(v63);
  objc_release(v62);
  objc_release(v61);
  objc_release(v60);
  objc_release(v59);
  objc_release(v58);
  LODWORD(result) = objc_autoreleaseReturnValue(v65);
  return result;
}
// 1418: using guessed type __CFString cfstr_Appid;
// 1698: using guessed type void *classRef_NSURLSessionConfiguration;
// 1C00: using guessed type char *selRef_defaultSessionConfiguration;
// AC80: using guessed type int __fastcall FIRInstanceIDAppIdentifier(_QWORD);
// AC90: using guessed type int __fastcall FIRInstanceIDCurrentAppVersion(_QWORD);
// AC98: using guessed type int __fastcall FIRInstanceIDCurrentGCMVersion(_QWORD);
// ACA0: using guessed type int __fastcall FIRInstanceIDOperatingSystemVersion(_QWORD);
// AD60: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// AD88: using guessed type int __fastcall objc_release(_QWORD);
// AD90: using guessed type int __fastcall objc_retain(_QWORD, _QWORD, _QWORD);
// ADA0: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000C3C) ----------------------------------------------------
// FIRInstanceIDTokenOperation - (id)queryItemsWithKeyPair:(id) 
id __cdecl -[FIRInstanceIDTokenOperation queryItemsWithKeyPair:](struct FIRInstanceIDTokenOperation *self, SEL a2, id a3)
{
  void *v3; // rax@1
  void *v4; // r15@1
  void *v5; // rax@1
  void *v6; // rax@1
  void *v7; // r13@1
  void *v8; // rax@1
  __int64 v9; // rax@1
  void *v10; // rax@1
  __int64 v11; // rax@1
  __int64 v12; // rbx@1
  void *v13; // rax@1
  __int64 v14; // rax@1
  __int64 v15; // rbx@1
  __int64 v16; // rax@1
  __int64 v17; // rax@1
  __int64 v18; // r12@1
  void *v19; // rax@1
  __int64 v20; // rax@1
  __int64 v21; // rbx@1
  __int64 v22; // rax@1
  __int64 v23; // rax@1
  __int64 v24; // rbx@1
  __int64 v25; // rax@1
  __int64 v26; // rax@1
  __int64 v27; // r13@1
  void *v28; // rax@1
  __int64 v29; // rax@1
  __int64 v30; // rdi@1
  __int64 v31; // rax@1
  __int64 v32; // r15@1
  void *v33; // rax@2
  void *v34; // rax@2
  void *v35; // rbx@2
  __int64 v36; // rax@3
  void *v37; // rax@3
  void *v38; // rax@4
  id result; // rax@4
  void *v40; // [sp+18h] [bp-38h]@1
  void *v41; // [sp+20h] [bp-30h]@1

  LODWORD(v3) = objc_retain(a3, a2, a3);
  v4 = v3;
  v5 = objc_msgSend(*(&classRef_NSURLSessionConfiguration + 2), *(&selRef_defaultSessionConfiguration + 30), 3LL);
  LODWORD(v6) = objc_retainAutoreleasedReturnValue(v5);
  v7 = v6;
  v40 = v4;
  v8 = objc_msgSend(*(&classRef_NSURLSessionConfiguration + 8), *(&selRef_defaultSessionConfiguration + 34), v4);
  LODWORD(v9) = objc_retainAutoreleasedReturnValue(v8);
  v10 = objc_msgSend(
          *(&classRef_NSURLSessionConfiguration + 6),
          *(&selRef_defaultSessionConfiguration + 31),
          &cfstr_Appid,
          v9);
  LODWORD(v11) = objc_retainAutoreleasedReturnValue(v10);
  v12 = v11;
  objc_msgSend(v7, *(&selRef_defaultSessionConfiguration + 10), v11);
  objc_release(v12);
  v13 = objc_msgSend(v4, *(&selRef_defaultSessionConfiguration + 35));
  LODWORD(v14) = objc_retainAutoreleasedReturnValue(v13);
  v15 = v14;
  LODWORD(v16) = FIRInstanceIDSecKeyBase64Encoding(v14);
  LODWORD(v17) = objc_retainAutoreleasedReturnValue(v16);
  v18 = v17;
  objc_release(v15);
  v19 = objc_msgSend(
          *(&classRef_NSURLSessionConfiguration + 6),
          *(&selRef_defaultSessionConfiguration + 31),
          &cfstr_Appid + 1,
          v18);
  LODWORD(v20) = objc_retainAutoreleasedReturnValue(v19);
  v21 = v20;
  v41 = v7;
  objc_msgSend(v7, *(&selRef_defaultSessionConfiguration + 10), v20);
  objc_release(v21);
  LODWORD(v22) = FIRInstanceIDAppIdentifier(v21);
  LODWORD(v23) = objc_retainAutoreleasedReturnValue(v22);
  v24 = v23;
  LODWORD(v25) = FIRInstanceIDConcatenateStrings(v23, v18, 0LL);
  LODWORD(v26) = objc_retainAutoreleasedReturnValue(v25);
  v27 = v26;
  objc_release(v24);
  v28 = objc_msgSend(v4, *(&selRef_defaultSessionConfiguration + 36));
  LODWORD(v29) = FIRInstanceIDSignParams(v28, v27);
  v30 = v29;
  LODWORD(v31) = objc_retainAutoreleasedReturnValue(v29);
  v32 = v31;
  if ( v31 )
  {
    v33 = objc_msgSend(
            *(&classRef_NSURLSessionConfiguration + 6),
            *(&selRef_defaultSessionConfiguration + 31),
            &cfstr_Appid + 2,
            v31);
    LODWORD(v34) = objc_retainAutoreleasedReturnValue(v33);
    v35 = v34;
    objc_msgSend(v41, *(&selRef_defaultSessionConfiguration + 10), v34);
  }
  else
  {
    LODWORD(v36) = FIRInstanceIDSharedLogger(v30);
    LODWORD(v37) = objc_retainAutoreleasedReturnValue(v36);
    v35 = v37;
    objc_msgSend(v37, *(&selRef_defaultSessionConfiguration + 37), &aAppid[155], 19000LL, &cfstr_Appid + 18, v27);
  }
  objc_release(v35);
  v38 = objc_msgSend(v40, *(&selRef_defaultSessionConfiguration + 38));
  FIRInstanceIDVerifyData(v38, v27, v32);
  objc_release(v32);
  objc_release(v27);
  objc_release(v18);
  ((void (*)(void))objc_release)();
  objc_release(v40);
  LODWORD(result) = objc_autoreleaseReturnValue(v41);
  return result;
}
// 1418: using guessed type __CFString cfstr_Appid;
// 1698: using guessed type void *classRef_NSURLSessionConfiguration;
// 1C00: using guessed type char *selRef_defaultSessionConfiguration;
// AC80: using guessed type int __fastcall FIRInstanceIDAppIdentifier(_QWORD);
// AC88: using guessed type int __fastcall FIRInstanceIDConcatenateStrings(_QWORD, _QWORD, _QWORD);
// ACB0: using guessed type int __fastcall FIRInstanceIDSecKeyBase64Encoding(_QWORD);
// ACB8: using guessed type int __fastcall FIRInstanceIDSharedLogger(_QWORD);
// ACC0: using guessed type int __fastcall FIRInstanceIDSignParams(_QWORD, _QWORD);
// ACC8: using guessed type int __fastcall FIRInstanceIDVerifyData(_QWORD, _QWORD, _QWORD);
// AD60: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// AD88: using guessed type int __fastcall objc_release(_QWORD);
// AD90: using guessed type int __fastcall objc_retain(_QWORD, _QWORD, _QWORD);
// ADA0: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000E8F) ----------------------------------------------------
// FIRInstanceIDTokenOperation + (uint64_t)nextRequestID
uint64_t __cdecl +[FIRInstanceIDTokenOperation nextRequestID](struct FIRInstanceIDTokenOperation_meta *self, SEL a2)
{
  uint64_t v2; // rbx@1

  objc_sync_enter(self, a2);
  v2 = ++currentRequestID;
  objc_sync_exit();
  return v2;
}
// AC78: using guessed type __int64 currentRequestID;
// ADC8: using guessed type int __fastcall objc_sync_enter(_QWORD, _QWORD);
// ADD0: using guessed type int objc_sync_exit(void);

//----- (0000000000000EBF) ----------------------------------------------------
// FIRInstanceIDTokenOperation + (id)HTTPAuthHeaderFromCheckin:(id) 
id __cdecl +[FIRInstanceIDTokenOperation HTTPAuthHeaderFromCheckin:](struct FIRInstanceIDTokenOperation *self, SEL a2, id a3)
{
  __int64 v3; // rax@0
  __int64 v4; // ST00_8@1
  id v5; // rbx@1
  const char *v6; // r14@1
  __int64 v7; // rax@1
  __int64 v8; // r15@1
  void *v9; // rax@1
  __int64 v10; // rax@1
  __int64 v11; // r14@1
  void *v12; // rbx@1
  __int64 v13; // rax@1
  __int64 v14; // rbx@1
  void *v15; // rax@1
  __int64 v16; // rax@1
  __int64 v17; // r15@1
  id result; // rax@1

  v4 = v3;
  v5 = a3;
  v6 = *(&selRef_defaultSessionConfiguration + 39);
  LODWORD(v7) = objc_retain(a3, a2, a3);
  v8 = v7;
  v9 = objc_msgSend(v5, v6, v4);
  LODWORD(v10) = objc_retainAutoreleasedReturnValue(v9);
  v11 = v10;
  v12 = objc_msgSend(v5, *(&selRef_defaultSessionConfiguration + 40));
  objc_release(v8);
  LODWORD(v13) = objc_retainAutoreleasedReturnValue(v12);
  v14 = v13;
  v15 = objc_msgSend(
          *(&classRef_NSURLSessionConfiguration + 7),
          *(&selRef_defaultSessionConfiguration + 32),
          &cfstr_Appid + 19,
          v11,
          v13);
  LODWORD(v16) = objc_retainAutoreleasedReturnValue(v15);
  v17 = v16;
  objc_release(v14);
  objc_release(v11);
  LODWORD(result) = objc_autoreleaseReturnValue(v17);
  return result;
}
// 1418: using guessed type __CFString cfstr_Appid;
// 1698: using guessed type void *classRef_NSURLSessionConfiguration;
// 1C00: using guessed type char *selRef_defaultSessionConfiguration;
// AD60: using guessed type int __fastcall objc_autoreleaseReturnValue(_QWORD);
// AD88: using guessed type int __fastcall objc_release(_QWORD);
// AD90: using guessed type int __fastcall objc_retain(_QWORD, _QWORD, _QWORD);
// ADA0: using guessed type int __fastcall objc_retainAutoreleasedReturnValue(_QWORD);

//----- (0000000000000F73) ----------------------------------------------------
// FIRInstanceIDTokenOperation - (int64_t)action
int64_t __cdecl -[FIRInstanceIDTokenOperation action](struct FIRInstanceIDTokenOperation *self, SEL a2)
{
  return self->_action;
}

//----- (0000000000000F84) ----------------------------------------------------
// FIRInstanceIDTokenOperation - (id)authorizedEntity
id __cdecl -[FIRInstanceIDTokenOperation authorizedEntity](struct FIRInstanceIDTokenOperation *self, SEL a2)
{
  return (id)self->_authorizedEntity;
}

//----- (0000000000000F95) ----------------------------------------------------
// FIRInstanceIDTokenOperation - (id)scope
id __cdecl -[FIRInstanceIDTokenOperation scope](struct FIRInstanceIDTokenOperation *self, SEL a2)
{
  return (id)self->_scope;
}

//----- (0000000000000FA6) ----------------------------------------------------
// FIRInstanceIDTokenOperation - (id)options
id __cdecl -[FIRInstanceIDTokenOperation options](struct FIRInstanceIDTokenOperation *self, SEL a2)
{
  return (id)self->_options;
}

//----- (0000000000000FB7) ----------------------------------------------------
// FIRInstanceIDTokenOperation - (id)checkinPreferences
id __cdecl -[FIRInstanceIDTokenOperation checkinPreferences](struct FIRInstanceIDTokenOperation *self, SEL a2)
{
  return (id)self->_checkinPreferences;
}

//----- (0000000000000FC8) ----------------------------------------------------
// FIRInstanceIDTokenOperation - (void)setCheckinPreferences:(id) 
void __cdecl -[FIRInstanceIDTokenOperation setCheckinPreferences:](struct FIRInstanceIDTokenOperation *self, SEL a2, id a3)
{
  objc_storeStrong(&self->_checkinPreferences, a3);
}
// ADC0: using guessed type int __fastcall objc_storeStrong(_QWORD, _QWORD);

//----- (0000000000000FDC) ----------------------------------------------------
// FIRInstanceIDTokenOperation - (id)keyPair
id __cdecl -[FIRInstanceIDTokenOperation keyPair](struct FIRInstanceIDTokenOperation *self, SEL a2)
{
  return (id)self->_keyPair;
}

//----- (0000000000000FED) ----------------------------------------------------
// FIRInstanceIDTokenOperation - (void)setKeyPair:(id) 
void __cdecl -[FIRInstanceIDTokenOperation setKeyPair:](struct FIRInstanceIDTokenOperation *self, SEL a2, id a3)
{
  objc_storeStrong(&self->_keyPair, a3);
}
// ADC0: using guessed type int __fastcall objc_storeStrong(_QWORD, _QWORD);

//----- (0000000000001001) ----------------------------------------------------
// FIRInstanceIDTokenOperation - (int64_t)result
int64_t __cdecl -[FIRInstanceIDTokenOperation result](struct FIRInstanceIDTokenOperation *self, SEL a2)
{
  return self->_result;
}

//----- (0000000000001012) ----------------------------------------------------
// FIRInstanceIDTokenOperation - (uint64_t)requestID
uint64_t __cdecl -[FIRInstanceIDTokenOperation requestID](struct FIRInstanceIDTokenOperation *self, SEL a2)
{
  return self->_requestID;
}

//----- (0000000000001023) ----------------------------------------------------
// FIRInstanceIDTokenOperation - (void)setRequestID:(uint64_t) 
void __cdecl -[FIRInstanceIDTokenOperation setRequestID:](struct FIRInstanceIDTokenOperation *self, SEL a2, uint64_t a3)
{
  self->_requestID = a3;
}

//----- (0000000000001034) ----------------------------------------------------
// FIRInstanceIDTokenOperation - (id)dataTask
id __cdecl -[FIRInstanceIDTokenOperation dataTask](struct FIRInstanceIDTokenOperation *self, SEL a2)
{
  id result; // rax@1

  LODWORD(result) = objc_getProperty(self, a2, 96LL, 1LL);
  return result;
}
// AD70: using guessed type int __fastcall objc_getProperty(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (000000000000104A) ----------------------------------------------------
// FIRInstanceIDTokenOperation - (void)setDataTask:(id) 
void __cdecl -[FIRInstanceIDTokenOperation setDataTask:](struct FIRInstanceIDTokenOperation *self, SEL a2, id a3)
{
  objc_setProperty_atomic(self, a2, a3, 96LL);
}
// ADB0: using guessed type int __fastcall objc_setProperty_atomic(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (000000000000105B) ----------------------------------------------------
// FIRInstanceIDTokenOperation - (id)completionHandlers
id __cdecl -[FIRInstanceIDTokenOperation completionHandlers](struct FIRInstanceIDTokenOperation *self, SEL a2)
{
  id result; // rax@1

  LODWORD(result) = objc_getProperty(self, a2, 104LL, 1LL);
  return result;
}
// AD70: using guessed type int __fastcall objc_getProperty(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000001071) ----------------------------------------------------
// FIRInstanceIDTokenOperation - (id)testBlock
id __cdecl -[FIRInstanceIDTokenOperation testBlock](struct FIRInstanceIDTokenOperation *self, SEL a2)
{
  id result; // rax@1

  LODWORD(result) = objc_getProperty(self, a2, 112LL, 0LL);
  return result;
}
// AD70: using guessed type int __fastcall objc_getProperty(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000001084) ----------------------------------------------------
// FIRInstanceIDTokenOperation - (void)setTestBlock:(id) 
void __cdecl -[FIRInstanceIDTokenOperation setTestBlock:](struct FIRInstanceIDTokenOperation *self, SEL a2, id a3)
{
  objc_setProperty_nonatomic_copy(self, a2, a3, 112LL);
}
// ADB8: using guessed type int __fastcall objc_setProperty_nonatomic_copy(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000001095) ----------------------------------------------------
// FIRInstanceIDTokenOperation - (void).cxx_destruct
void __cdecl -[FIRInstanceIDTokenOperation .cxx_destruct](struct FIRInstanceIDTokenOperation *self, SEL a2)
{
  objc_storeStrong(&self->_testBlock, 0LL);
  objc_storeStrong(&self->_completionHandlers, 0LL);
  objc_storeStrong(&self->_dataTask, 0LL);
  objc_storeStrong(&self->_keyPair, 0LL);
  objc_storeStrong(&self->_checkinPreferences, 0LL);
  objc_storeStrong(&self->_options, 0LL);
  objc_storeStrong(&self->_scope, 0LL);
  objc_storeStrong(&self->_authorizedEntity, 0LL);
}
// ADC0: using guessed type int __fastcall objc_storeStrong(_QWORD, _QWORD);

// ALL OK, 36 function(s) have been successfully decompiled
